config/crd/kustomization.yaml, config/crd/patches/label_in_awsclustercontrolleridentities.yaml, config/crd/patches/label_in_awsclusterroleidentities.yaml, config/crd/patches/label_in_awsclusterstaticidentities.yaml
/kind feature
added kustomize patch to add label of `clusterctl.cluster.x-k8s.io/move-hierarchy` to CRDs of global identity resources like AWSClusterControllerIdentity, AWSClusterRoleIdentity, AWSClusterStaticIdentity.
Fixes #2533 
**Checklist**:
```release-note
None
```
=> Kustomize patch added for move-hierarchy label

Makefile
Signed-off-by: Scott Lowe <scott.lowe@scottlowe.org>
/kind feature
This PR adds ARM64 builds of `clusterawsadm` for both Linux and Darwin (macOS).
Fixes #
**Checklist**:
```release-note
clusterawsadm ARM64 builds for both Linux and macOS are now available
```
=> Add Linux and Darwin ARM64 builds of clusterawsadm

exp/api/v1alpha4/awsmanagedmachinepool_webhook.go
/kind bug
Fixes # https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2543
**Checklist**:
```release-note
None
```
=> add 64 length for awsmanagedmachinepool iam role

Makefile, test/e2e/shared/resource.go, test/e2e/shared/suite.go, test/e2e/suites/unmanaged/unmanaged_CAPI_quick_test.go, test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
/kind bug
The new PR blocking test was failing due regex problem. This PR fixes that.
Fixes #
**Checklist**:
```release-note
NONE
```
=> Makefile fix for pr blocking e2e test

pkg/cloud/services/securitygroup/securitygroups.go, pkg/cloud/services/securitygroup/securitygroups_test.go
/kind bug
We were deleting SGs looking at `Status`, which also includes overridden SGs.
Instead, during SG deletion, this PR only deletes the ones that have `sigs.k8s.io/cluster-api-provider-aws/cluster/name: owned` tag.
Also, allows overriding SGs partially. Before all default SGs must have been overridden or seeing this error:
`"msg"="failed to reconcile security groups" "error"="security group overrides have been provided for some but not all roles - missing security group for role bastion" "cluster"="tagleme" "name"="tagleme" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" `
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will …
=> Do not delete overriden security groups

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml, controlplane/eks/api/v1alpha4/awsmanagedcontrolplane_webhook.go, controlplane/eks/api/v1alpha4/awsmanagedcontrolplane_webhook_test.go, pkg/cloud/services/eks/cluster.go, pkg/cloud/services/eks/cluster_test.go, pkg/internal/cmp/slice.go, pkg/internal/cmp/slice_test.go, tilt-provider.json
/kind feature
Enables to add encryption config in update path if it was nil at the time of cluster creation. It also disallows any modifications in further update if the config was already defined at the time of creation
Fixes #2452
**Checklist**:
```release-note
* Add encryption-config in update if missed in cluster creation
* Add webhook validation checks for encryption-config
Action required
Controllers policy updated with missing IAM permissions required to enable EKS encryption, if you are planning to enable EKS encryption then you will need to update your controllers policy by running `clusterawsadm bootstrap iam create-cloudformation-stack` again.
```
=> Update EKS clusters to enable encryption

pkg/cloud/services/network/routetables.go, pkg/cloud/services/network/subnets.go
/kind bug
Due to a recent change to remove slices of pointers the subnet reconcilation logic was not correctly saving the subnet ID of the newly created subnets to the AWSCluster/AWSmanagedControlPlane. This then cause the routetable reconcilation to fail because of the missing subnet ids:
```bash
[manager] E0709 13:25:30.608802       8 routetables.go:131]  "msg"="trying to associate route table" "error"="failed to associate route table \"rtb-07d2c36ff9ab81afc\" to subnet \"\": MissingParameter: The request must contain the parameter SubnetId or GatewayId\n\tstatus code: 400, request id: f3fc1704-18cd-436e-9036-a32963045218"  "subnet_id"=""
``` 
**Which issue(s) this PR …
=> fix: ensure updates to subnet are persisted to the scope

api/v1alpha4/awscluster_webhook.go, api/v1alpha4/awscluster_webhook_test.go, pkg/cloud/services/network/network.go, pkg/cloud/services/network/vpc.go, pkg/cloud/services/network/vpc_test.go
/kind bug
1) Remove wait logic that wait until vpc is created. Instead returns early if `vpc.id` is set but AWS resource could not be retrieved.
2) Don't allow `spec.vpc.id` modifications in the webhook. This may cause problems such as if an unmanaged VPC is used and the VPC ID is nulled, then we create a new managed VPC but do not handle the ELB logic afterwards.
3) Create VPC and patch the ID immediately.
4) Also, instead of allowing not providing VPC ids in DescribeVPCs logic, modified it to describe only the VPC when the id is set in the spec.
Reopening @sedefsavas's PR rebased on top of …
=> Cleanup ReconcileVPC() and set id early in reconciliation.

bootstrap/eks/controllers/eksconfig_controller.go, bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go, bootstrap/eks/controllers/suite_test.go
/kind bug
Whenever the `EKSConfig` `.spec.kubeletExtraArgs` field is updated, the eksconfig controller will reconcile the resulting userdata `Secret` and refresh its `.data.value` field value. Otherwise the `Secret` needs to be manually deleted to trigger a LaunchTemplate update.
I'm also improving the unit tests. Currently, since `cluster.Status.InfrastructureReady == false` all tests end [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/bootstrap/eks/controllers/eksconfig_controller.go#L171). With my changes, the `Secret` is effectively created and checked after reconciliation, thus ensuring the entire reconciliation loop was run.
Fixes …
=> fix: reconcile Secret when userdata changes

api/v1alpha3/awscluster_webhook.go, api/v1alpha3/awscluster_webhook_test.go, pkg/cloud/services/network/network.go, pkg/cloud/services/network/vpc.go, pkg/cloud/services/network/vpc_test.go
Cherry pick of #2587 on release-0.6.
#2587: Cleanup ReconcileVPC() and set id early in reconciliation.
=> Automated cherry pick of #2587: Cleanup ReconcileVPC() and set id early in reconciliation.

bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
Moves the check for the value of the modified secret into the
Eventually, since the new secret value is eventually consistent.
Fixes #
**Checklist**:
```release-note
NONE
```
/assign @richardcase
=> eksconfig_controller_reconciler_test: Eventually test for updated secret

controlplane/eks/main.go, go.mod, go.sum, main.go
Adds webhook health check that will be considered for controller deployment readiness.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2602
**Checklist**:
```release-note
NONE
```
=> Add webhook health check

pkg/cloud/services/network/natgateways.go
/kind cleanup
Added parallelization during NAT gateway deletion
Fixes #2263 
**Checklist**:
```release-note
NAT gateways are now deleted in parallel, which should reduce cluster deletion time by >50% for multi-AZ clusters
```
=> Parallelise NAT gateway deletion

bootstrap/eks/config/manager/manager.yaml, config/manager/manager.yaml, controlplane/eks/config/manager/manager.yaml
/kind bug
Fixes #2361
**Checklist**:
```release-note
Cluster API Provider AWS will now be preferentially pinned to control plane nodes. This is especially helpful when running self-managed management clusters in AWS as for EC2-based control planes, the control plane EC2 instances have the controlplane.cluster-api.sigs.k8s.io IAM role which has sufficient permissions for CAPA to run.
Action Required: Please ensure your control plane nodes have sufficient resources to run Cluster API Provider AWS.
```
=> bug: make sure that controllers run on controll plane nodes

controllers/awsmachine_controller.go, controllers/awsmachine_controller_test.go
/kind bug
Update finalizer addition logic for AWSMachine. If we apply AWS workload cluster yaml with invalid credentials, then AWSMachine object is created and stuck because of invalid credentials. Once we try to delete that yaml, AWSMachine object stuck. So adding finalizer in AWSMachine only after first successful AWS read operation.
Fixes #2270 
With this change AWSMachine object is deleted in case of invalid credentials, same needs to be done for AWSCluster. WIP because AWSCluster finalizer updation requires a bit of …
=> Finalizers added after first read operation on AWS in AWSMachines

config/manager/manager.yaml, controlplane/eks/config/manager/manager.yaml
/kind bug
Missed a few manager configs in #2625, so updated the nodeaffinity definitions in the missed deployments.
Fixes #2624 
**Checklist**:
```release-note
NONE
```
=> fix: changed the node affinity for the manager deployments

controlplane/eks/main.go, main.go
We see `http: TLS handshake error from 127.0.0.1:50396: EOF` errors since we added webhook health check.
The reason of this is yet to determined but in the meantime, this PR reverts changes of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2603
Fixes #
**Checklist**:
```release-note
NONE
```
=> Remove webhook health check

pkg/cloud/services/network/vpc.go
/kind bug
The logic to retry when vpc is not found, already exists, but does not work as intended due to a minor bug.
This PR adds a fix to identify vpc 'NotFound' error and retry fetching vpc, instead of recreating an already existing vpc.
Fixes #2658 
**Checklist**:
```release-note
Retry EC2::DescribeVpcAttribute when VPCs is temporarily not found instead of creating a duplicate
```
=> Retry fetching managed vpc attributes when vpc is 'NotFound'

cmd/clusterawsadm/cloudformation/bootstrap/cloud_provider_integration_control_plane.go, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
This PR removes all the duplicate `elasticloadbalancing:AddTags` entries from the policies that `clusterawsadm` generates.
Signed-off-by: Rayan Das <rayandas91@gmail.com>
/kind bug
Fixes #2683 
**Checklist**:
```
Removed elasticloadbalancing:AddTags duplicate entries.
```
=> Remove elasticloadbalancing:AddTags duplicate entries.

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml, cmd/clusterawsadm/cloudformation/bootstrap/iam.go, cmd/clusterawsadm/cloudformation/bootstrap/template.go
/kind bug
This PR works around the AWS character limit for managed policies. In the e2e tests the `AWSIAMManagedPolicyControllers` policy is currently very close to the AWS limit, which means that the next time a feature adds a few lines to this policy, the CloudFormation template would error out (I've already hit this limit while working on #2271, hence this issue + PR). More info and repro instructions in #2642.
Fixes #2642
**Checklist**:
```release-note
Move EKS-related resources from …
```
=> Separate EKS-related IAM resources

controlplane/eks/config/rbac/role.yaml, controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
/kind bug
Adds a missing permission for aws cluster controller identity to the managed control plane.
Fixes #
**Checklist**:
```release-note
Add missing RBAC permission for AWSClusterControllerIdentities for managed control plane controller
```
=> fix: missing identity permission for the managed control plane

main.go
This change adds a ready and health check on the webhook server.
Release note:
Signed-off-by: Geetika Batra <geetika.b@vmware.com>
Fixes #
**Checklist**:
```release-note
Add readiness and health checks to webhook server
```
=> Wait for webhook readiness and healthy 

pkg/cloud/services/network/routetables.go, pkg/cloud/services/network/routetables_test.go
/kind bug
Fixes a panic when there are extra routes with non-CIDR destinations (IPv6 CIDR, Prefix List) present in the managed routing table.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: N/A
**Special notes for your reviewer**: N/A
**Checklist**:
```release-note
BUGFIX: Fixes a panic when there are extra routes with non-CIDR destinations (IPv6 CIDR, Prefix List) present in the managed routing table.
```
=> [cloud/network] Fix panic on RouteTables reconcile.

test/e2e/data/infrastructure-aws/cluster-template-external-cloud-provider.yaml, test/e2e/data/infrastructure-aws/external-cloud-provider/aws-ccm-external.yaml
/kind bug
Follow up of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2647
Added node affinity rules for external cloud provider as well.
Fixes #
**Checklist**:
```release-note
NONE
```
=> fix: node affinity rules in external CCM CRDs

test/e2e/data/infrastructure-aws/cluster-template-external-cloud-provider.yaml, test/e2e/data/infrastructure-aws/external-cloud-provider/aws-ccm-external.yaml
/kind bug
Fix for failing e2e test in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2722
**Checklist**:
```release-note
NONE
```
=> fix: node affinity rules indentation in external CCM CRDs

docs/book/src/topics/external-cloud-provider-with-ebs-csi-driver.md
This PR gives the direction on using external cloud provider and EBS CSI driver with the AWS workloads. It's a follow up of issue [#1475](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1475)
**Checklist**:
```release-note
Add documentation for using external cloud provider and CSI driver add-on
```
=> Add doc for using external cloud provider with CSI driver

docs/book/src/SUMMARY_PREFIX.md
/kind bug
The doc which was added for [using external cloud provider with EBS CSI driver](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2718) was not added to `SUMMARY_PREFIX.md`, which is added in this PR
**Checklist**:
```release-note
NONE
```
=> fix: add the doc for using external CCM with CSI driver to summary_prefix.md

pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go
/kind bug
findSubnet function's logic is incorrect when subnet ID is specified in AWSMachine's spec. The logic should find a subnet regardless of a failureDomain setting. Current logic returns a subnet ID from a spec when failureDomain is not defined, which may not match any subnets provided in AWSCluster.
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2732
**Checklist**:
```release-note
Fix findSubnet function's logic when subnet ID is specified. It will find a matching subnet regardless of a …
```
=> Fix findSubnet function's logic when subnet ID is specified

api/v1alpha4/tags.go, pkg/cloud/services/network/subnets.go, pkg/cloud/services/network/subnets_test.go, pkg/cloud/tags/tags.go
/kind feature
Support writing AWS cloud provider tags on pre-existing infrastructure
Fixes # https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2584
**Checklist**:
**Release note:**
```release-note
Support adding AWS cloud provider tags to pre-existing infrastructure
`kubernetes.io/cluster/<name> = shared` and `kubernetes.io/role/elb = 1` for public subnets
`kubernetes.io/cluster/<name> = shared` and`kubernetes.io/role/internal-elb = 1` for private subnets
```
=> Add AWS cloud provider tags to pre-existing infrastructure

CONTRIBUTING.md
Updated the contributing guide to reference the developer guide so that people know how to setup their development environment.
Relates To #2752 
**Checklist**:
```release-note
NONE
```
=> docs: update to contributing to reference developer guide in book

api/v1alpha3/awscluster_types.go, api/v1alpha3/types.go, api/v1alpha4/awscluster_types.go, api/v1alpha4/awscluster_webhook.go, api/v1alpha4/types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
/kind bug
According to AWS documentation, the scheme is lowercase. If the field is
explicitly set to Internet-facing, CAPA fails to recognize the ELB it
has created, because the ELB's scheme is lowercase, i.e.,
internet-facing.
Fixes #2534
Ordinarily, changing the accepted value is a breaking API change. However, cluster create _always fails_ with the current value ( `Internet-facing`), therefore we can assume that no one is using the current value.
I added this PR to the agenda for our next meeting.
**Checklist**:
**Release …
=> :bug: Rename the ELB scheme from Internet-facing to internet-facing

test/e2e/shared/common.go
/kind bug
This PR fixes the timeout errors in the conformance tests because log collection takes longer time than expected.
Fixes #2746 
**Checklist**:
```release-note
NONE
```
=> Fix the timeout for conformance test due to prolonged log collection

test/e2e/data/e2e_conf.yaml, test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
The upgrade path from v1alpha3 to v1alpha4 has to be tested in E2E, hence this PR.
Fixes #2388 
**Checklist**:
```release-note
Add v1alpha3 to v1alpha4 upgrade test
```
=> Add v1alpha3 to v1alpha4 upgrade e2e test

test/e2e/data/e2e_conf.yaml, test/e2e/suites/unmanaged/unmanaged_functional_test.go
/kind flake
The control plane node wait interval is set to 10m in e2e conf, but sometimes the control plane takes more than 10m to come up. This issue has been majorly seen in multitenancy test, but it can fail for other tests as well(as it's not specific to multitenancy). This PR updates the wait interval for control plane to fix the flaky tests in testgrid.
Fixes #2763 
**Checklist**:
```release-note
None
```
=> Fix timeout due to delay in bringing up control plane in e2e tests

api/v1alpha4/awsclustertemplate_webhook.go
/kind bug
Fixes a typo in an error message.
Fixes #
This could be considered a breaking API change, since users that parse the error string may depend on the typo
**Checklist**:
```release-note
Fixes typo in AWSCluster validation webhook error. Changes error from "AWSClusterTemaplate.Spec is immutable" to "AWSClusterTemplate.Spec is immutable" 
```
=> :bug: fix typo in AWSCluster validation hook error

api/v1alpha3/conversion.go
/kind cleanup
The removed code, introduced in #2556, became unnecessary when
equivalent code was added to the restoreInstance() function in #2468.
This code handles a subset of the cases that restoreInstances() does;
namely, when both the restored and dst pointers are non-nil. The
conversion tests fail if the restoreInstance() call is removed, but this
code is left.  They pass if this code is removed.
Fixes #
**Checklist**:
```release-note
NONE
```
=> chore: Remove unnecessary conversion code

Dockerfile, Makefile, hack/tools/Makefile
/kind bug
There is some network issues in downloading the start.sh and restart.sh scripts in dockerfile, which is causing e2e test runs to fail. This PR fetches those scripts outside the dockerfile to fix the issue.
Fixes #
**Checklist**:
```release-note
None
```
=> Download the e2e restart scripts outside the dockerfile

tilt-provider.json
/kind feature
Update tilt-provider.json to add CAPA label in Tilt UX. This grouping feature is supported in tilt version >= v0.22.2.
See [cluster-api issue](https://github.com/kubernetes-sigs/cluster-api/pull/5217) for grouping resources in Tilt.
Fixes #
```release-note
Add CAPA label in Tilt
```
=> Update tilt-provider.json to add CAPA label in Tilt

api/v1alpha3/conversion.go, exp/api/v1alpha3/conversion.go
/kind cleanup
Previously, the functions were reassigning the destination pointer, which had no effect outside the function scope, because pointers are passed by value.
(The bug had no effect on the conversion tests, but that appears to be a happy accident.)
Fixes #
Another approach is to return errors if either the `dst` pointer is nil. However, the caller _wants_ to end up with a non-nil `dst`, and that's only possible if the caller initializes it. Likewise, the caller does not need to call the function if `restored` is nil, so …
=> Ensure destination pointer is non-nil before calling restore functions

pkg/cloud/services/eks/nodegroup.go
/kind bug
When bastion is enabled for an EKS cluster, this PR ensures SSH access via bastion, to the worker nodes/instances associated with the NodeGroup. 
Currently, when bastion is enabled and SSH key is configured in a ManagedMachinePool, SSH access fails when attempted from the bastion node using the private IP of the worker node.
This is because worker node security-group(sg) "eks-remoteAccess-" has an inbound rule with "-node-eks-additional" sg as source, which in turn has an inbound rule with "-bastion" sg as source.  But adding a security group as a source does not add rules from the source security group.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
=> bug: Add bastion-sg to managedMachinePool remoteAccess source-sgs when bastion is enabled

test/helpers/envtest.go
/kind bug
Usually, but not always, a resource has both a mutating and validating webhook. If one type of webhook is not defined for some resource. The nil dereference happens here: https://github.com/kubernetes-sigs/controller-runtime/blob/v0.9.7/pkg/envtest/webhook.go#L438.
Fixes #
**Checklist**:
```release-note
NONE
```
=> bug: If one type of webhook is not defined, testenv.Build hits a nil dereference

hack/boilerplate/boilerplate.py
/kind cleanup
Go 1.17 introduces a new format for build constrants, see the following:
https://golang.org/doc/go1.17
https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md
And files formatted using `go fmt` will be changed to use the new
format. For example in our e2e test files:
```go
//go:build e2e
// +build e2e
```
This change updates the header verification to strip out the new build
constraint tag.
Fixes #
**Checklist**:
```release-note
NONE
```
=> chore: updated header verify to support go 1.17 build contraints

api/v1alpha4/types_test.go, pkg/cloud/services/securitygroup/securitygroups.go, pkg/cloud/services/securitygroup/securitygroups_test.go
/kind bug
Fix `ingressRulesFromSDKType` function.
Changed the logic to generate separate Ingress rules for userIdGroupPairs and IPRanges from EC2 IpPermission API Response.
An IngressRule cannot have SourceSecurityGroupIDs and CidrBlocks at the same time and combining them into a single IngressRule was the cause of the reported bug.
Fixes # https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2795
There are three commits in this PR, which I plan to keep separate.
* The first commit refactors duplicate codes.
* The …
=> Fix reconciliation of AWS ingress rules of same port

api/v1alpha3/awscluster_conversion.go, api/v1alpha3/awsidentity_conversion.go, api/v1alpha3/awsmachine_conversion.go, api/v1alpha4/awscluster_conversion.go, api/v1alpha4/awsidentity_conversion.go, api/v1alpha4/awsmachine_conversion.go, cmd/clusterawsadm/ami/helper.go, cmd/clusterawsadm/cloudformation/bootstrap/iam.go, cmd/clusterawsadm/cloudformation/bootstrap/template_test.go, cmd/clusterawsadm/configreader/configreader.go, exp/api/v1alpha4/conversion_test.go, hack/tools/tools.go, test/e2e/shared/aws.go, test/e2e/shared/exec.go, test/e2e/shared/resource.go, test/e2e/shared/suite.go, test/e2e/shared/temp.go, test/e2e/shared/template.go, test/e2e/suites/managed/cluster.go, test/e2e/suites/unmanaged/helpers_test.go, test/helpers/envtest.go, util/system/util.go, util/system/util_test.go
/kind cleanup
The ioutil package has already been deprecated in golang 1.16, please see [go1.16#ioutil](https://golang.org/doc/go1.16#ioutil). So we need to replace all the ioutil with os and io.
Fixes #
**Checklist**:
```release-note
Replace ioutil deprecated package with os/io for golang 1.16
```
=> Replace ioutil with os/io packages

docs/book/src/topics/machinepools.md
This PR fixes the broken hyperlinked URL for word [Flavor](https://cluster-api.sigs.k8s.io/clusterctl/commands/config-cluster.html#flavors) across [Machine Pools](https://cluster-api-aws.sigs.k8s.io/topics/machinepools.html) page.
Fixes #2863
**Checklist**:
```release-note
NONE
```
=> Correct URL for Flavor(s) in Machine Pool topic

test/e2e/data/e2e_conf.yaml
/kind flake
This PR increases the timeout interval for wait-job creation in e2e config which is causing GPU tests to be flaky.
Fixes #2905 
**Checklist**:
```release-note
None
```
=> [e2e] Fix GPU test cuda vector pod creation timeout

.gitignore, pkg/cloud/services/eks/addons.go, pkg/eks/addons/plan.go, pkg/eks/addons/plan_test.go, pkg/eks/addons/procedures.go, test/e2e/data/e2e_eks_conf.yaml, test/e2e/data/eks/cluster-template-eks-control-plane-only-withaddon.yaml, test/e2e/suites/managed/addon.go, test/e2e/suites/managed/addon_helpers.go, test/e2e/suites/managed/eks_test.go
/kind bug
When the EKS addons functionality was added to CAPA there was only 1
addon available (vpc) and so it was never tested with multiple addons.
Now there are multiple addons there are issues.
The unit and e2e tests only tested 1 addons. On investigation the issue
was caused by implicit memory aliasing in a loop. This change fixes the
loop and also expands the unit and e2e tests to include multiple eks
addons
Fixes #2911 
**Checklist**:
```release-note
Fixes an issue with using multiple EKS addons.
```
=> fix: multiple addons not being reconciled

Makefile, hack/tools/Makefile
/kind bug
This PR updates the Makefile to remove the condition checks for GINKGO_SKIP for e2e tests such that CAPI tests are not skipped in testgrid.
It also fixes the unzip issue in mac OS while running e2e tests locally. Related to #2674 
Fixes #
**Checklist**:
```release-note
None
```
=> Remove GINKGO_SKIP conditions from Makefile to enable the e2e tests for CAPI

hack/tools/Makefile
/kind bug
This PR updates the unzip command in Makefile such that session manager plugin installation is not asked everytime e2e test runs in macOS
Fixes #2674
**Checklist**:
```release-note
None
```
=> Fix unzip command while running e2e tests locally

test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
Enable v1alpha4 to v1beta1 upgrade test
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2788
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2833
**Checklist**:
```release-note
Enable v1alpha3/v1alpha4 to v1beta1 upgrade e2e test 
```
=> Enable v1alpha3/v1alpha4 to v1beta1 upgrade test

pkg/cloud/services/ssm/secret.go
/kind bug
Removes the data type to make ssm work with govcloud.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2636
**Checklist**:
```release-note
Fix for supporting SecureString as a parameter type in SSM on GovCloud
```
=> Fix ssm parameter

Dockerfile
/kind bug
This PR updates CAPA manager container to use non root numeric user
Fixes #2222 
**Checklist**:
```release-note
Use non root numeric user for CAPA containers
```
=> Use non root numeric user for CAPA containers

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
/kind bug
This PR adds 3 missing permissions/actions for EKS cluster management, related to OIDC provider association/configuration. Without these, EKS reconciliation fails directly after cluster creation.
Fixes #
**Checklist**:
```release-note
Add missing permissions for EKS OIDC provider configuration
```
=> Add missing permissions for EKS OIDC provider configuration

.gitignore, pkg/cloud/services/eks/addons.go, pkg/eks/addons/plan.go, pkg/eks/addons/plan_test.go, pkg/eks/addons/procedures.go, test/e2e/data/e2e_eks_conf.yaml, test/e2e/data/eks/cluster-template-eks-control-plane-only-withaddon.yaml, test/e2e/suites/managed/addon.go, test/e2e/suites/managed/addon_helpers.go, test/e2e/suites/managed/eks_test.go
/kind bug
When the EKS addons functionality was added to CAPA there was only 1
addon available (vpc) and so it was never tested with multiple addons.
Now there are multiple addons there are issues.
The unit and e2e tests only tested 1 addons. On investigation the issue
was caused by implicit memory aliasing in a loop. This change fixes the
loop and also expands the unit and e2e tests to include multiple eks
addons
Backport of #2914 
Relates #2911 
**Checklist**:
```release-note
Fixes an issue with using multiple …
```
=> [backport 0.7] Fixes an issue with using multiple EKS addons.

controllers/awsmachine_controller.go, pkg/cloud/services/ec2/errors.go, pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go
/kind bug
If providerID is set for an `AWSMachine`, we should never create a new instance for it again. Because the new instance id does not propagate to `Machine.status.nodeRef`.
This PR has some reorg for better readability. The main change is to return error (instead of nil instance and nil error), when the instance could not be found in `InstanceIfExists()`.
Partially fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2915, more investigation needed.
```release-note
Do not create a new instance if AWSMachine already has ProviderID field set.
```
=> Return error if providerID is set and instance cannot be found

test/e2e/data/e2e_conf.yaml, test/e2e/data/e2e_eks_conf.yaml
Downgrade K8s version to the latest kind node 1.22.2
```release-note
NONE
```
=> Bump cluster-api in e2e tests + fix K8s version

test/e2e/data/e2e_conf.yaml
clusterctl v1alpha3 upgrade spec on main is failing with the following message. See [failing test](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e/1461346822172708864)
```
[6] • Failure [847.960 seconds]
[6] [unmanaged] [Cluster API Framework]
[6] /home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/suites/unmanaged/unmanaged_CAPI_test.go:34
[6]   Clusterctl Upgrade Spec [from v1alpha3]
[6]   /home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/suites/unmanaged/unmanaged_CAPI_test.go:155
[6]     Should create a management cluster and then upgrade all the providers [It]
[6]     /home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.0.1-0.2021 …
```
=> Downgrade k8s version for clusterctl upgrade spec

templates/cluster-template-eks-fargate.yaml
/kind bug
There is a string literal in a template for the cluster name. This will render an invalid kubeyaml doc for kind: AWSFargateProfile.
Fixes #2983 
**Checklist**:
```release-note
fix: Replace string literal in template for AWSFargateProfile.
```
=> fix: replace string literal in AWSFargateProfile

test/e2e/data/e2e_conf.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/topology/cluster-template.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/topology/clusterclass-quick-start.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/topology/kustomization.yaml, test/e2e/data/shared/v1beta1/metadata.yaml, test/e2e/suites/unmanaged/unmanaged_CAPI_quick_test_cluster_class.go
Signed-off-by: Stefan Büringer buringerst@vmware.com
This PR adds a ClusterClass quickstart e2e test.
Improves ClusterClass<=>CAPA test coverage
Fixes #2939
**Checklist**:
```release-note
NONE
```
=> Add ClusterClass quickstart e2e test

go.mod
/kind cleanup
This PR deletes version locking comment for v1beta1 in go.mod since v1beta1 will span multiple minor releases.
Fixes #
**Checklist**:
```release-note
```
=> Version locking comment cleanup from go.mod

controllers/awscluster_controller.go
/kind cleanup
A minor cleanup. Noticed that reconcileNormal and reconcileDelete in awscluster_controller don't follow the standard pattern of being a method of a reconciler, hence refactoring.
Make AWSCluster reconcileNormal(Delete) as reconciler functions
Fixes #
**Checklist**:
```release-note
NONE
```
=> Make AWSCluster reconcileNormal(Delete) as reconciler methods

pkg/cloud/scope/managedcontrolplane.go, pkg/cloud/services/eks/cluster.go, pkg/internal/cidr/cidr.go, pkg/internal/cidr/cidr_test.go
/kind feature
If an IPv4 CIDR is specified in `ClusterNetwork.Services.CIDRBlocks` then we will use this for configuring the ipv4 services cidr when creating the eks cluster.
Fixes #2891 
**Checklist**:
```release-note
Allow configuring services cidr when creating an EKS cluster.
```
=> feat: expose eks service network configuration.

test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
/kind cleanup
Updated ClusterUpgradeConformanceSpec in unmanaged suite to skip conformance test for now to reduce testing time.
Also, removed `KCP Upgrade Spec - Single Control Plane Cluster` test as the test case is covered by the `ClusterUpgradeConformanceSpec`
Fixes #
This is a part of #2993. 
[KCP Upgrade Spec - HA Control Plane Cluster using Scale-In](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/test/e2e/suites/unmanaged/unmanaged_CAPI_test.go#L65) will be replaced with ClusterUpgradeConformanceSpec …
=> Update ClusterUpgradeConformanceSpec to skip conformance test

pkg/cloud/services/ec2/instances.go
/kind bug
This PR fixes the issue of AWSMachine controller trying to update an immutable field, `spec.rootVolume.deviceName`, and getting an webhook error while trying to update it.
```
"error"="admission webhook \"validation.awsmachine.infrastructure.cluster.x-k8s.io\" denied the request: AWSMachine.infrastructure.cluster.x-k8s.io \"mgmt-control-plane-cvc28\" is invalid: spec: Forbidden: cannot be modified"
```
This was caused by rootVolumes of AWSMachine and an instance sharing the same pointer.
Fixes #3000 
**Checklist**: …
=> Fix AWSMachine controller trying to update rootVolume device name

api/v1beta1/awscluster_webhook.go, api/v1beta1/awscluster_webhook_test.go
/kind bug
Prior to commit 2cd2f4900e77a3f8de5a67f8740a44c7e2493117, the name was
immutable, unless it was nil, in which case it could be updated. Now,
the name must be immutable, even if it is nil, since the default name is
generated at runtime and not written to the AWSCluster resource.
This change should have been included as part of #3004.
Fixes #3003
**Checklist**:
```release-note
NONE
```
=> fix: api/v1beta1: Make AWSCluster ControlPlaneLoadBalancer name immutable

test/e2e/shared/defaults.go
e2e tests are failing due to hitting ec2 quota when it is set to 32.
Testing if this will fix
Fixes #
**Checklist**:
```release-note
NONE
```
=> Increase ec2 quota to 128

test/e2e/data/e2e_conf.yaml
Tests started frequently failing due to timeout, don't know the root cause but to unblock our PRs increasing timeouts.
Fixes #
**Checklist**:
```release-note
```
=> Increase e2e test timeouts

controllers/awscluster_controller.go, pkg/cloud/interfaces.go, pkg/cloud/scope/cluster.go, pkg/cloud/scope/fargate.go, pkg/cloud/scope/managedcontrolplane.go, pkg/cloud/scope/managednodegroup.go, pkg/cloud/services/network/network.go, util/conditions/helper.go
/kind bug
Sets error severities to warning when cluster has not initialized yet.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3017
**Checklist**:
```release-note
Fix for setting conditions to error severity only when errors are non-transients.
```
=> Set condition severities to warning if control plane not initialized

controlplane/eks/controllers/awsmanagedcontrolplane_controller.go, pkg/cloud/services/securitygroup/securitygroups.go
/kind bug
This PR enables EKS bastion security group only when bastion is enabled in the AWSManagedControlPlane.
Fixes #3026 
**Checklist**:
```release-note
EKS: disable bastion SG when bastion is disabled
```
=> EKS: disable bastion sg when bastion is disabled

cmd/clusterawsadm/cloudformation/bootstrap/template_test.go
/kind cleanup
Previously, the tests in template_test.go were structured in a way that we couldn't run/debug an individual test case.
This PR refactors the tests to enable an individual run and also improve the test output. It will make debugging easier when tests fail.
BEFORE
```
=== RUN   Test_RenderCloudformation
--- PASS: Test_RenderCloudformation (0.07s)
```
AFTER
```
=== RUN   Test_RenderCloudformation
=== RUN   Test_RenderCloudformation/default
=== RUN   Test_RenderCloudformation/with_ssm_secret_backend
=== RUN   Test_RenderCloudformation/with_all_secret_backends
=== RUN   Test_RenderCloudformation/customsuffix
=== RUN   Test_RenderCloudformation/with_bootstrap_user
=== RUN …
```
=> Refactor template_test.go to enable an individual run for each test case

bootstrap/eks/api/v1alpha3/conversion.go, bootstrap/eks/api/v1alpha3/webhook_suite_test.go, bootstrap/eks/api/v1alpha4/conversion.go, bootstrap/eks/api/v1alpha4/webhook_suite_test.go
EKS API conversion tests were silently exiting with panic due to an incorrect webhook config path.
This PR enables the tests and fixed failing conversion tests in v1alpha3 and v1alpha4.
Fixes #3023
**Checklist**:
```release-note
Make EKS conversion tests run and fix failing conversions
```
=> Make EKS conversion tests run and fix failing conversion tests

controlplane/eks/api/v1alpha3/conversion.go
/kind bug
The `AWSManagedControlPlane` object conversion from `v1alpha3` to
`v1beta1` were not considering new fields in status and spec. The bug
is covered by tests, but these are failing silently at the moment as
**Checklist**:
```release-note
Bugfix in  `AWSManagedControlPlane` object conversion from v1alpha3 to v1beta1. Some fields in Status and Spec were not being considered during conversion
```
=> Fix AWSManagedControlPlane conversion

api/v1alpha3/webhook_suite_test.go, api/v1beta1/suite_test.go, bootstrap/eks/api/v1alpha3/webhook_suite_test.go, bootstrap/eks/api/v1alpha4/webhook_suite_test.go, bootstrap/eks/controllers/suite_test.go, controllers/suite_test.go, controlplane/eks/api/v1alpha3/webhook_suite_test.go, controlplane/eks/api/v1alpha4/webhook_suite_test.go, controlplane/eks/api/v1beta1/suite_test.go, exp/api/v1alpha3/webhook_suite_test.go, exp/controlleridentitycreator/suite_test.go, exp/controllers/suite_test.go, exp/instancestate/suite_test.go
[go#34129]: https://github.com/golang/go/issues/34129
/kind bug
/kind cleanup
As described in [go#34129], `os.Exit()` in the way we have in multiple
tests in this project make panics to fail silently. That was first
Since go 1.15 the `os.Exit(code)` calls are not required, therefore,
let's make panics visible and just run `m.Run()`.
Fixes #3032
**Checklist**:
```release-note
Refactor TestMain functions across the project to stop using os.Exit swallowing errors
```
=> Remove os.Exit calls from TestMain

docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md
The example of how to add extra policies to nodes and the control plane use a capitalised name of `extraPolicyAttachments`. This field is just ignored this way and since this field is ignored when null, the exported config (`clusterawsadm bootstrap iam show-config`) does not have these fields.
Fixes #
**Checklist**:
```release-note
NONE
```
=> docs: fix extra policies field name

controlplane/eks/api/v1beta1/awsmanagedcontrolplane_webhook.go, pkg/cloud/services/eks/cluster.go, pkg/cloud/services/eks/cluster_test.go, pkg/internal/cmp/slice.go, pkg/internal/cmp/slice_test.go
/kind bug
This PR addresses a couple of issues that are preventing EKS-managed clusters from fully reconciling when encryption is enabled:
- Update EncryptionConfig.Provider comparison to dereference pointers and compare KeyARN
- Fix a couple of other equality comparisons that were flipped (checking true vs false)
- Add assertions to TestCompareSlices (`g.Expect(...)` vs `g.Expect(...).To(...)`)
Fixes #2908 
This PR does not address the refactor work [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2540), …
=> Fix EKS encryption config value comparisons

api/v1alpha3/webhook_suite_test.go, api/v1alpha4/suite_test.go, bootstrap/eks/api/v1alpha3/webhook_suite_test.go, bootstrap/eks/controllers/suite_test.go, controllers/suite_test.go, controlplane/eks/api/v1alpha3/webhook_suite_test.go, controlplane/eks/api/v1alpha4/suite_test.go, exp/api/v1alpha3/webhook_suite_test.go, exp/controlleridentitycreator/suite_test.go, exp/controllers/suite_test.go, exp/instancestate/suite_test.go
[go#34129]: https://github.com/golang/go/issues/34129
/kind bug
/kind cleanup
As described in [go#34129], `os.Exit()` in the way we have in multiple
tests in this project make panics to fail silently. That was first
Since go 1.15 the `os.Exit(code)` calls are not required, therefore,
let's make panics visible and just run `m.Run()`.
Fixes #3032
**Checklist**:
```release-note
Refactor TestMain functions across the project to stop using os.Exit swallowing errors
```
=> [backport 0.7] Remove os.Exit calls from TestMain

api/v1alpha3/suite_test.go, controllers/suite_test.go, controlplane/eks/api/v1alpha3/suite_test.go, exp/controlleridentitycreator/suite_test.go, exp/controllers/suite_test.go
[go#34129]: https://github.com/golang/go/issues/34129
/kind bug
/kind cleanup
As described in [go#34129], `os.Exit()` in the way we have in multiple
tests in this project make panics to fail silently. That was first
Since go 1.15 the `os.Exit(code)` calls are not required, therefore,
let's make panics visible and just run `m.Run()`.
Fixes #3032
**Checklist**:
```release-note
Refactor TestMain functions across the project to stop using os.Exit swallowing errors
```
=> [backport 0.6] Remove os.Exit calls from TestMain

test/e2e/data/e2e_conf.yaml, test/e2e/data/e2e_eks_conf.yaml
/kind bug
`clusterctl init` fails with the error below when CAPA version is set > v1.0:
```
[1]   [91mfailed to run clusterctl init
[1]   Unexpected error:
[1]       <*errors.withStack | 0xc000c14e40>: {
[1]           error: <*errors.withMessage | 0xc000498e60>{
[1]               cause: <*errors.withStack | 0xc000c14e10>{
[1]                   error: <*errors.withMessage | 0xc000498e40>{
[1]                       cause: <*errors.withStack | 0xc000c14de0>{
[1]                           error: <*errors.withMessage | 0xc000498e20>{
[1]                               cause: <*errors.withStack | 0xc000c14db0>{
[1]                                   error: <*errors.withMessage | 0xc000498e00>{
[1]                                       cause: …
```
=> Fix e2e config CAPA version

exp/api/v1beta1/awsfargateprofile_webhook.go, exp/api/v1beta1/awsfargateprofile_webhook_test.go
/kind bug
This PR allows updating AWSFargateProfile roleName when the existing roleName is empty. This resolves the error from the fargate webhook validation.
Fixes #3051 
**Checklist**:
- [x ] squashed commits
```release-note
[EKS] Fix to allow updating roleName in fargate, if not already configured
```
=> EKS: allow updating roleName in fargate, if not already configured

cmd/clusterawsadm/controller/helper.go
/kind bug
`clusterawsadm` was disregarding the KubeConfig context passed via arguments.
Fixes #
**Checklist**:
```release-note
Fix for using kubeconfig context in clusterawsadm.
```
=> Fix kube-context usage in clusterawsadm

test/e2e/data/e2e_conf.yaml, test/e2e/data/e2e_eks_conf.yaml
Updating cluster api to v1.1.0-beta.1 in EKS e2e tests to match CAPA modules.
Fixes #
**Checklist**:
```release-note
NONE
```
=> Update cluster-api to v1.1.0-beta.1 in EKS e2e tests

test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
/kind cleanup
A follow up of #3001. 
Add HA control plane cluster upgrade test, which replaces the recently deprecated KCP Upgrade spec for HA control plane cluster in CAPI.
Fixes #
This is a part of #2993.
**Checklist**:
```release-note
Add HA control plane cluster upgrade e2e test
```
=> Add HA control plane cluster upgrade e2e test

.golangci.yml, api/v1beta1/awscluster_webhook_test.go, controllers/awsmachine_controller_test.go, exp/controllers/awsmachinepool_controller_test.go, pkg/cloud/scope/session_test.go, pkg/cloud/services/elb/loadbalancer_test.go
/kind cleanup
thelper detects golang test helpers without t.Helper() call and checks the consistency of test helpers
See https://github.com/kulti/thelper for more information.
Fixes #
Part of #3077 
**Checklist**:
```release-note
Enable thelper golang linter 
```
=> Enable thelper golang linter

.golangci.yml, cmd/clusterawsadm/cmd/ami/ami.go, cmd/clusterawsadm/cmd/ami/common/common.go, cmd/clusterawsadm/cmd/ami/common/copy.go, cmd/clusterawsadm/cmd/ami/common/encryptedcopy.go, cmd/clusterawsadm/cmd/ami/list/list.go, pkg/hash/base36.go
/kind cleanup
Enabled two more linters
* predeclared linter finds code that shadows one of Go's predeclared identifiers.
* unused linter checks Go code for unused constants, variables, functions and types
Fixes #3077 
Will keep two commits separately as one is for `unused` linter and another is for `predeclared` linter.
**Checklist**:
```release-note
Enable predeclared and unused golang linters
```
=> Enable predeclared and unused golang linters

pkg/cloud/services/ec2/bastion.go, pkg/cloud/services/ec2/bastion_test.go
/kind bug
This PR updates bastion instance in `AWSCluster` status upon its deletion.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3089
**Checklist**:
```release-note
NONE
```
=> Update bastion status after deleting it

pkg/cloud/scope/managednodegroup.go, pkg/cloud/services/eks/nodegroup.go, pkg/cloud/services/eks/tags.go, test/e2e/suites/managed/helpers.go, test/e2e/suites/managed/machine_pool.go
/kind feature
There is an [open issue](https://github.com/aws/containers-roadmap/issues/1541) on EKS where EKS doesn’t support tagging the underlying ASGs, however it’s quite important for many organizations for compliance, cost. This PR adds such support in CAPA, where user can specify an optional `AdditionalAsgTags` field in `AWSManagedMachinePool` and the node group controller will reconcile the underlying ASG tags.
Fixes #2881
**Checklist**:
```release-note
Support tagging EKS node group's underlying ASG
```
=> EKS: Support tagging node group's underlying ASG

docs/book/src/topics/eks/encryption.md, pkg/cloud/services/eks/cluster.go
/kind bug
The logic for when to update the EKS encryption had issues. This
refactors the logic to be more explicit.
Also updated the docs to say that the KMS key ARN needs to be used and
not the alias ARN.
Fixes #3092 
**Checklist**:
```release-note
Update to EKS encryption logic to stop it reporting a chnage when one hasn't occured.
```
=> fix: eks encryption logic fix

README.md
Follow up to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3104 which fixes the mentions, which is not a supported thing in Markdown, to be proper links. :)
```release-note
Fix the list of contributors in the README to be links instead of @ mentions.
```
=> Fix markdown mentions to proper links

cmd/clusterawsadm/ami/helper.go, cmd/clusterawsadm/ami/helper_test.go, cmd/clusterawsadm/ami/list.go, docs/book/src/topics/images/built-amis.md, hack/tools/go.mod, hack/tools/go.sum
/kind bug
This PR helps in publishing AMI images for last 4 Kubernetes releases in [book](https://cluster-api-aws.sigs.k8s.io/topics/images/built-amis.html).
Fixes #3061 
To find out all Patch versions for a given kubernetes release, we are taking all versions from vx.x.0 to vx.x.latest_stable_patch. And during finding images I am ignoring those patches for which image is not found
**Checklist**:
```release-note
Publish CAPA AMI images for last 4 k8s releases in CAPA book. 
```
=> Fix AMI publishing failure for patch versions in book

Makefile
Add lint-fix to Makefile target.
When a linter supports `--fix` option, running `make lint-fix` will fix linter errors. 
Fixes #
```release-note
NONE
```
=> Add lint-fix to Makefile target

pkg/cloud/services/ec2/bastion.go, pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/network/gateways.go, pkg/cloud/services/network/natgateways.go, pkg/cloud/services/network/routetables.go, pkg/cloud/services/network/subnets.go, pkg/cloud/services/network/vpc.go, pkg/cloud/services/securitygroup/securitygroups.go
/kind cleanup
Make logging for creating/deleting AWS resources consistent. See #3143 for a detailed description.
Fixes #3143 
Added missing logs, formatted some logs and moved unimportant logs to level 2.
**Checklist**:
```release-note
Make logging for AWS resources creation/deletion consistent
```
=> Make logging for creating/deleting AWS resources consistent

.gitignore
/kind bug
We are using `go mod vendor` for our internal builds and the current `.gitignore` excludes `sigs.k8s.io/cluster-api/util/kubeconfig` package from the vendor directory which breaks the build. I added `!kubeconfig/` to make it not ignore kubeconfig package and still ignore kubeconfig when it's a file.
Fixes #
**Checklist**:
```release-note
Don't ignore vendored kubeconfig package in git.
```
=> Don't ignore kubeconfig directory in git

pkg/cloud/services/autoscaling/autoscalinggroup.go, pkg/cloud/services/autoscaling/autoscalinggroup_test.go
/area testing
This PR increases the unit tests coverage for `pkg/cloud/services/autoscaling` package.
Coverage increased from 13.7% to 94.2%
Part of #2910
Please add missing test scenarios [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2910) for tracking.
**Checklist**:
```release-note
Add unit tests for `pkg/cloud/services/autoscaling` package
```
=> Added unit test for pkg/cloud/services/autoscaling package

Makefile, hack/utils.sh, hack/verify-shellcheck.sh
`/kind feature`
* Added `verify-shellcheck` make target and its dependencies `hack/utils.sh`, `hack/verify-shellcheck.sh`
Fixes #3175
**Checklist**:
```release-note
Added `verify-shellcheck` make target
```
=> Added `verify-shellcheck` make target

pkg/cloud/services/network/subnets.go, pkg/cloud/services/network/subnets_test.go
Currently create tag from Service,scope.Name().
That returns CAPI cluster name.
But, when using EKS cluster, we need KubernetesClusterName() in actual.
/kind bug
While user use AWSCluster, ClusterScoper.Name() and ClusterScoper.KubernetesClusterName() are always returns same value.
But when using AWSManagedControlePlane, correct cluster name for subnet tag is returned from ClusterScoper.KubernetesClusterName().
Fixes #2918 
**Checklist**:
```release-note
fix a bug that EKS cluster fails to assign loadBalancer to …
```
=> create right tag for LoadBalancers

api/v1beta1/awscluster_webhook.go, api/v1beta1/awscluster_webhook_test.go, api/v1beta1/awsmachine_webhook.go, api/v1beta1/awsmachine_webhook_test.go, api/v1beta1/tags.go, api/v1beta1/tags_test.go, controlplane/eks/api/v1beta1/awsmanagedcontrolplane_webhook.go, controlplane/eks/api/v1beta1/awsmanagedcontrolplane_webhook_test.go, exp/api/v1beta1/awsfargateprofile_webhook.go, exp/api/v1beta1/awsfargateprofile_webhook_test.go, exp/api/v1beta1/awsmachinepool_webhook.go, exp/api/v1beta1/awsmachinepool_webhook_test.go, exp/api/v1beta1/awsmanagedmachinepool_webhook.go, exp/api/v1beta1/awsmanagedmachinepool_webhook_test.go
/kind bug
As described in https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3102, tags keys currently can be empty or do not
respect other AWS rules for tagging, resulting in errors during
resources provisioning.
This commit adds validation to the tags in the webhook, for all the
resource where `additionalTags` is present, during creation and update.
Validation is done in the webhook instead of OpenAPI schema due to
limitations in the current `additionalTags` field type, as better
described in #3102.
Part of #3102
**Checklist**:
```release-note
additionalTags are now validated to comply with AWS API requirements
```
=> Validate additionalTags

hack/utils.sh
/kind cleanup
Recently merged https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3178 brought capd helper functions from CAPI that are not needed in CAPA. Cleaning up.
Fixes #
**Checklist**:
```release-note
NONE
```
=> Remove unused capd helper functions

cmd/clusterawsadm/ami/helper.go, cmd/clusterawsadm/cmd/ami/common/copy.go, cmd/clusterawsadm/cmd/ami/common/encryptedcopy.go, cmd/clusterawsadm/cmd/ami/list/list.go, docs/book/src/topics/images/built-amis.md
To automatically list pre-built `flatcar-stable` in the book, added it to supported OS list.
Also, images can be listed with clusterawsadm.
`clusterawsadm ami list --kubernetes-version=1.23.3 --os=flatcar-stable`
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3107
**Checklist**:
```release-note
Add flatcar-stable os to supported OS list, will publish reference AMIs with each new K8s release.
```
=> Add flatcar-stable to supported OS list for clusterawsadm

test/e2e/data/e2e_conf.yaml
/kind feature
To make #2271 CI pass, as current Flatcar AMIs for 1.23.0 are built
using older image-builder version which we are not compatible with.
Signed-off-by: Mateusz Gozdek <mgozdek@microsoft.com>
```release-note
NONE
```
=> test/e2e/data/e2e_conf.yaml: bump k8s version to v1.23.3

Makefile, common.mk
/kind feature
A nicer Makefile help output:
```
➜  cluster-api-provider-aws git:(group_makefile) ✗ make
Usage:
make <target>
Testing
test                                      Run tests
generate-test-flavors                     Generate test template flavors
test-conformance                          Run clusterctl based conformance test on workload cluster (requires Docker).
test-cover                                Run tests with code coverage and code generate  reports
Binaries
binaries                                  Builds and installs all binaries
manager-aws-infrastructure                Build manager binary.
clusterawsadm                             Build clusterawsadm binary.
Linting
lint …
```
=> Group Makefile targets

exp/controlleridentitycreator/awscontrolleridentity_controller.go, exp/controllers/awsmanagedmachinepool_controller.go, pkg/cloud/services/instancestate/rule_test.go, test/e2e/shared/resource.go
/kind feature
We skip AWSMCP reconciliation when the owning Cluster or the AWSMCP itself is paused (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/controlplane/eks/controllers/awsmanagedcontrolplane_controller.go#L137). We should add the same logic for AWSMMP.
Fixes #3155
**Checklist**:
```release-note
Skip AWSMMP reconciliation if the owning Cluster or AWSMMP itself is paused
```
=> Skip AWSMMP reconciliation if the owning Cluster or AWSMMP itself is paused

README.md
This PR adds `go report` badges in CAPA project.
Fixes #3209 
Now we can see following badges in CAPA repo.
**Checklist**:
```release-note
Added go report badge in CAPA
```
=> Added  go report badge

controllers/awscluster_controller_test.go, controllers/awscluster_controller_unit_test.go
/kind flake
/area testing
This PR adds the unit tests for AWSCluster controller. It also resolves the flaky tests in AWSCluster controller which were failing due to the delay in creation of AWSCluster. This has been fixed by adding retries to fetch `AWSCluster` object using gomega `Eventually` which will wait for the cluster creation before proceeding for the tests. 
Coverage of `controllers` package increased from 42.5% to 59.7%
Fixes #3204
Part of #2910 
**Checklist**:
```release-note
Add unit tests for AWSCluster controller
```
=> Add unit tests for AWSCluster controller

test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
/kind cleanup
Refactored cluster upgrade tests:
1. Use 0 workers for KCP upgrade tests
2. Add test for upgrading KCP with scale in rollout
3. Add [K8s-Upgrade] so that we can run all upgrades with Ginkgo-focus.
Related to #2993 and #3087
**Checklist**:
```release-note
NONE
```
=> Refactor cluster upgrade tests

docs/book/src/topics/reference/versions.md
Update EOL dates and release versioning docs.
Fixes #
**Checklist**:
```release-note
NONE
```
=> Update version support documentation

test/e2e/shared/aws.go
/kind feature
Add some basic CRUD functions for VPCs, subnets, NatGW, IGW, route tables, routes and peering connections to be used by the e2e test suite for building out infrastructure prior to test.
Fixes #3235 
**Checklist**:
```release-note
Added AWS EC2 Service functions for use by e2e tests.
```
=> Added functions for building infra in AWS

test/e2e/shared/aws.go
/kind feature
Add
- security group functions for e2e tests
- list functions for VPC subnets, route tables and route tables associated to certain subnets
- relevant CCM tags to subnets
Adds 11 functions for managing security groups, 5 additional List functions and adds the appropriate tags to the subnets based on type.
Fixes #3250
**Checklist**:
```release-note
Adds additional AWS infrastructure functions for E2E testing of security groups.
```
=> Add SecurityGroup functions, List functions, subnet tags

docs/book/src/topics/multitenancy.md, exp/controlleridentitycreator/awscontrolleridentity_controller_test.go
/kind cleanup
Fixed incorrect info on multitenancy doc
- Remove apiVersion from sourceidentityRef as there is no apiVersion field.
- Remove a paragraph mentioning capa-eks-control-plane-system namespace, which is not used anymore with EKS feature graduation.
Also, fixed test name and description of awscontrolleridentity controller
Fixes #
**Checklist**:
```release-note
NONE
```
=> Update multitenancy doc

tilt-provider.json
/kind cleanup
CAPI's Tiltfile is not using manager_name while loading providers anymore. Cleaning up the unused field.
See [slack](https://kubernetes.slack.com/archives/C8TSNPY4T/p1646076234442319) for more information.
Fixes #
**Checklist**:
```release-note
NONE
```
=> Remove manager_name from tilt-provider.json

pkg/cloud/scope/cluster.go, pkg/cloud/scope/elb.go, pkg/cloud/services/elb/loadbalancer.go
/kind feature
Since ELB is created only when it's not found, this PR blocks the ELB creation in the scenario where if user deletes ELB post the cluster has been provisioned. The reason to do this is if ELB is created again after the cluster has been provisioned, then CAPA will create new ELB with new DNS endpoint which won't work.
As `AWSClusterSpec.ControlPlaneEndpoint` becomes immutable after cluster is provisioned, we are relying on the validity of this endpoint to know the status of provisioning of the cluster to check whether ELB has to be created or not. If this endpoint is valid and ELB is not found, then we inform the user that AWSCluster is in failed state and unrecoverable. …
=> Block ELB re-creation after the cluster has been provisioned

api/v1alpha3/awscluster_conversion.go, api/v1alpha3/zz_generated.conversion.go, api/v1alpha4/awscluster_conversion.go, api/v1alpha4/zz_generated.conversion.go, api/v1beta1/awscluster_types.go, api/v1beta1/awscluster_webhook.go, api/v1beta1/awscluster_webhook_test.go, api/v1beta1/network_types.go, api/v1beta1/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml, pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/elb/loadbalancer_test.go, test/e2e/data/infrastructure-aws/kustomize_sources/limit-az/kustomization.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/limit-az/patches/elb-health-check-protocol.yaml
/kind bug
This PR adds support for providing the custom protocol for Classic ELB health checks so as to support different ciphers.
Fixes #1657 
**Checklist**:
```release-note
Add support for custom protocol for ELB health checks
```
=> Add support for custom protocol for ELB health checks

pkg/cloud/scope/managedcontrolplane.go
/kind bug
While reviewing https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3157 and doing more investigation, I found that ClusterSecurityGroupsReadyCondition is not part of managedcontrolplane's patchObject function's owned conditions.
Fixes #2180
**Checklist**:
```release-note
NONE
```
=> Add ClusterSecurityGroupsReadyCondition to managedcontrolplane's patchObject

Makefile, test/e2e/data/e2e_eks_conf.yaml, test/e2e/shared/identity.go, test/e2e/shared/suite.go, test/e2e/suites/managed/cluster.go, test/e2e/suites/managed/eks_test.go, test/e2e/suites/managed/upgrade_test.go
Enable EKS upgrade test, updated k8s version to EKS supported versions and setup AWSClusterStaticIdentity in a central location for use by multiple tests.
Fixes #3228 
**Checklist**:
```release-note
NONE
```
=> Enable EKS upgrade test

Makefile, hack/tools/go.mod, hack/tools/go.sum, hack/tools/tools.go, scripts/ci-apidiff.sh
Signed-off-by: Meghana Jangi <mjangi@vmware.com>
Adds a Make target that takes a diff on API changes.
Fixes #3169 
**Checklist**:
```release-note
Add apidiff Make target
```
=> Adding apidiff target to the Makefile

test/e2e/data/e2e_conf.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/external-infrastructure/kustomization.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/external-infrastructure/patches/external-infrastructure.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/external-securitygroups/kustomization.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/external-securitygroups/patches/external-securitygroups.yaml, test/e2e/shared/aws.go, test/e2e/suites/unmanaged/helpers_test.go, test/e2e/suites/unmanaged/unmanaged_functional_test.go
Initial Sec Groups E2E test and refactor AWS infrastructure functions
/kind feature
Adds an E2E test for validating CAPA with managed VPC, subnets and security groups
Fixes #
**Checklist**:
```release-note
Adds an E2E test for validating CAPA with managed VPC, subnets and security groups
```
=> Functioning Sec Groups E2E test and refactor AWS infrastructure functions

Makefile, scripts/ci-apidiff.sh
Signed-off-by: Meghana Jangi <mjangi@vmware.com>
Apidiff prow job is failing, target is not using PULL_BASE_SHA.
Fixes #3272 
Fixes #3169 
**Checklist**:
```release-note
NONE
```
=> fix: Apidiff prow job is failing

docs/book/src/SUMMARY_PREFIX.md, docs/book/src/topics/spot-instances.md
This PR adds the documentation for usage of spot instances in CAPA for AWS Machines.
Fixes #3246 
**Checklist**:
```release-note
Added documentation for usage of spot instances for AWS Machines.
```
=> docs: Added documentation for usage of spot instances

exp/api/v1beta1/awsmachinepool_webhook.go, pkg/cloud/scope/machinepool.go, pkg/cloud/services/autoscaling/autoscalinggroup.go, pkg/cloud/services/autoscaling/autoscalinggroup_test.go, pkg/cloud/services/autoscaling/service.go
/kind feature
Currently we are doing lookup by subnet IDs only. But with this PR we enable
```
if subnet id is there, do a lookup using that
if filter is there, do a lookup using that
If both are given then it will throw a validation error as per comment on AWSResourceReference
```
Fixes #3254 
Fixes #2609 
Part of #2087 
**Checklist**:
```release-note
Added subnet IDs lookup by AWSMachinePool Spec Subnets.Filters in case IDs not provided
```
=> Added subnet IDs lookup by AWSMachinePool Spec Subnets.Filters

test/e2e/suites/unmanaged/unmanaged_functional_test.go
/kind bug
Changes assertion for DetachInternetGateway function in the managed security group E2E test to Eventually. Provides timeout to avoid test failure due to longer running operations in AWS.
Fixes #3283 
**Checklist**:
```release-note
Provides timeout for DetachInternetGateway function in managed security group E2E test.
```
=> Change assertion for DetachInternetGateway to Eventually

pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go
/kind feature
This basically unifies the code used to find subnets with filters and subnets
by ID. This is done by handling the ID case as a simple filter instead of
looking into the cluster network spec.
The reason is that explicitely specified subnets are not necessarely part
of the cluster network spec. For example, it might be desired to run a
EKS control plane inside 3 specific subnets (so they are part of the
network spec) while running workers in different subnets from the same
VPC.
A side effect of this change is that we don't have to check for the correct
failure domain and/or public/private subnets anymore as this is implicitely
handled by the criterias.
**Which issue(s) this PR fixes** *(optional, in `fixes …
=> Query AWS to find subnets with explicitely specified subnet IDs

docs/book/src/SUMMARY_PREFIX.md, docs/book/src/topics/bring-your-own-aws-infrastructure.md
This PR adds the documentation for briefly explaining about externally managed clusters(not EKS-managed clusters) and how to use it.
Fixes #2412 
**Checklist**:
```release-note
Added documentation for usage of externally managed clusters.
```
=> Documentation for usage of externally managed clusters

test/e2e/data/e2e_conf.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/internal-elb/kustomization.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/internal-elb/patches/internal-elb.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/kustomization.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/patches/management.yaml, test/e2e/shared/aws.go, test/e2e/suites/unmanaged/unmanaged_functional_test.go
/kind feature
Creates an E2E test for creating clusters in peered VPCs and creating a workload cluster using an internal ELB.
Fixes #3249
**Checklist**:
```release-note
Adds an E2E test that validates clusters in peered VPCs and cluster creation using an internal ELB.
```
=> Adds an E2E test for using peered VPCs and an internal ELB

docs/book/src/topics/accessing-ec2-instances.md, pkg/cloud/services/ec2/ami.go, pkg/cloud/services/ec2/bastion.go, pkg/cloud/services/ec2/bastion_test.go
/kind feature
Currently, default AMIs used for bastion are hardcoded. This PR enables to lookup the latest images published by Ubuntu.
Fixes #3108 
**Checklist**:
```release-note
- Added latest AMI lookup for bastion host and removed hardcoded AMIs.
- Added unit tests for bastion.go
```
=> Removed hardcoding for AMIs in bastion host and added latest AMI lookup

docs/book/src/development/conventions.md
As part of https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2910, we have added few integration and unit tests in controllers. We have separated two files *_unit_test.go specifically for unit tests and *_test.go for integration tests.
This PR makes clear distinction between the two files and  convention of how to differentiate integration vs unit tests.
Fixes #3288 
**Checklist**:
```release-note
Updated the test conventions used for CAPA controllers.
```
=> docs: Developer guideline to write unit/integration tests in CAPA repo

exp/api/v1beta1/awsmachinepool_webhook_test.go
/kind test
This PR add the webhook unit test for AWSMachinePool create and update operation. This PR covers test cases for [this](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3255/files) PR.
Fixes #
**Checklist**:
```release-note
Added test cases for AWSMachinePool webhook
```
=> Added AWSMachinepool webhook create and update test

docs/book/src/development/development.md, hack/ensure-kind.sh, hack/tools/go.mod, hack/tools/go.sum, scripts/ci-e2e-eks.sh, scripts/ci-e2e.sh
/area release
This updates to make use of latest kind v0.12.0 version 
Fixes #
**Checklist**:
```release-note
Upgrade to use latest Kind version v0.12.0
```
=> Upgrade to use latest Kind version v0.12.0

test/e2e/data/infrastructure-aws/kustomize_sources/internal-elb/kustomization.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/internal-elb/patches/az-select.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/kustomization.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/patches/az-select.yaml, test/e2e/suites/unmanaged/unmanaged_functional_test.go
/kind bug
Specifies the availability zone the subnets will be created in(us-west-2a) and forces CAPA to place instances in those same AZs.
Fixes #3310
**Checklist**:
```release-note
Add specific availability zone to peered VPC and  ELB E2E test
```
=> Add specific AZ to peered VPC and  ELB test

test/e2e/data/infrastructure-aws/kustomize_sources/nested-multitenancy/kustomization.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/nested-multitenancy/patches/bastion-enabled.yaml, test/e2e/suites/unmanaged/helpers_test.go, test/e2e/suites/unmanaged/unmanaged_functional_test.go
/area testing
Since we don't have any existing E2E tests to check if bastion host is up and running when enabled, this PR adds this check in existing multitenancy test(as it's faster as compared to other functional tests). This would also give assurity that bastion default AMI lookup is functioning properly.
Follow up for #3298 
**Checklist**:
```release-note
Added E2E test to check if bastion host is running when enabled.
```
=> [E2E] Test to check if bastion host is running when enabled

pkg/cloud/services/eks/addons.go
/kind bug
k8s upstream plans to drop ObjectMeta.ClusterName field as it has always been force cleared by the API server.
See kubernetes/kubernetes#108717.
Searched CAPA codebase and there is only one occasion where `ObjectMeta.ClusterName` is used.
Fixes #3321 
**Checklist**:
```release-note
Remove .metadata.clusterName usage
```
=> Remove .metadata.clusterName usage

exp/controllers/awsmachinepool_controller.go, exp/controllers/awsmachinepool_controller_test.go
/kind bug
`machinePoolScope.MachinePool.Spec.Replicas` and `existingASG.DesiredCapacity` are both pointers.
The previous condition compared memory addresses instead of integer values.
I'm not sure if the check for `existingASG.DesiredCapacity == nil` is needed (i.e. can it happen at all?) but I played a bit on the safe side here. The check could still fail overall if `machinePoolScope.MachinePool.Spec.Replicas` is nil, but I guess that should never happen. Or does it?
**Checklist**:
```release-note
fixes logic for determining if an AutoScalingGroup needs updates
```
=> fix: asgNeedsUpdates invalid condition (pointers)

controllers/awscluster_controller_test.go, controllers/awscluster_controller_unit_test.go, controllers/awsmachine_controller.go, controllers/awsmachine_controller_test.go, controllers/awsmachine_controller_unit_test.go, controllers/helpers_test.go, docs/book/src/SUMMARY_PREFIX.md, pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/interfaces.go, pkg/cloud/services/mock_services/elb_interface_mock.go
/area testing
This PR adds integration tests for AWSMachine controllers. Scenarios covered are:
- Should successfully reconcile control plane machine creation
- Should successfully reconcile control plane machine deletion
- Should fail reconciling control-plane machine creation while attaching load balancer
- Should fail reconciling control-plane machine deletion while terminating instance
Part of #2910 
**Checklist**:
```release-note
Added integration tests for AWSMachine controller
```
=> Add integration tests for AWSMachine controller

go.mod, pkg/record/recorder.go, test/helpers/external/cluster.go
/kind bug
This PR fixes below lint error in open PRs possibly caused by the version bump of golangci-lint(since strings.Title() is deprecated from Go 1.18).
> SA1019: strings.Title is deprecated: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead. (staticcheck)
**Checklist**:
```release-note
None
```
=> Fix lint errors due to golangci-lint bump

docs/book/src/topics/multitenancy.md
This PR updates documentation around multi-tenancy, and provides a working yaml sample of cross account provisioning.
```release-note
Documentation update for multi-tenancy
This update provides:
- clarity on how `identityRef` directs which cluster CAPA deploys into
- updates on examples
- working / apply-able yaml example
```
=> update multi-tenacy docs

hack/tools/go.mod, hack/tools/go.sum, hack/tools/tools.go
/kind bug
This PR fixes the netlify deployment issue. Since `blang/semver` dependency is missing which comes as part of import `sigs.k8s.io/cluster-api/hack/tools/mdbook/releaselink`, the target  `make -C docs/book build` fails. This PR adds back the above import to fix missing go.mod and go.sum entries.
Fixes #
**Checklist**:
**Release Note**:
```release-note
None
```
=> netlify: fix missing go.sum entry for blang/semver

controllers/awscluster_controller_test.go, controllers/helpers_test.go
/area testing
/kind flake
This PR fixes flaky integration test in AWSCluster controller. The sorting of tags by keys are in place in the test, this PR is just making it a bit more generic.
Fixes #3352 
**Checklist**:
**Release Notes**:
```release-note
None
```
=>  Fix flaky integration test

test/e2e/data/infrastructure-aws/kustomize_sources/internal-elb/patches/az-select.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/internal-elb/patches/internal-elb.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/patches/az-select.yaml, test/e2e/shared/common.go, test/e2e/suites/unmanaged/unmanaged_functional_test.go
/kind feature
This PR does the following:
- Modifies the internal ELB E2E test to only utilize the private subnet created in the AWSCluster resource. 
- Adds the us-west-2a AZ to the failure domain of the machine deployments created for both clusters. 
- Adds functions to dump spec and machine resources using the management cluster proxy.
- Adds logic to the E2E test to respect the skip cleanup logic
Fixes #3353
**Checklist**:
```release-note
Modifies Internal ELB E2E test to only utilize private subnet, E2E function …
```
=> Modify internal ELB test to only use private subnet

Makefile, scripts/ci-test.sh
/kind cleanup
Test logs are mainly useful either when developing/debugging tests or
when the tests are failing. If some test fails, Go will automatically
print the outputs from this tests.
Printing all test logs all the time makes it much difficult to find
which test is actually failing and which output belongs to it, so I
suggest we don't use -v by default.
Similar change has been made in CAPI a while ago:
https://github.com/kubernetes-sigs/cluster-api/pull/4187
Signed-off-by: Mateusz Gozdek <mgozdek@microsoft.com>
```
NONE
```
=> Makefile: don't log verbose from tests by default

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml, pkg/cloud/services/network/network.go, test/e2e/data/eks/cluster-template-eks-control-plane-only-withaddon.yaml
/kind bug
This PR fixes following:
- Order of disassociation of secondary CIDR post subnet deletion, otherwise the CIDR wont get deleted if subnet is still in use.
- Adds ec2:AssociateVpcCidrBlock and ec2:DisassociateVpcCidrBlock permissions to EKS controller policy.
Fixes #3277 
Fixes #3273 
**Checklist**:
```release-note
- Disassociate secondary CIDR after subnets are deleted.
- Adds ec2:AssociateVpcCidrBlock and ec2:DisassociateVpcCidrBlock permissions to EKS controller policy.
```
=> Disassociate secondary CIDR after subnets are deleted

pkg/cloud/services/autoscaling/autoscalinggroup.go, pkg/cloud/services/ec2/instances.go, test/e2e/data/e2e_conf.yaml, test/e2e/data/e2e_eks_conf.yaml, test/e2e/shared/services.go, test/e2e/suites/managed/eks_test.go, test/e2e/suites/managed/machine_deployment.go, test/e2e/suites/managed/machine_pool.go, test/e2e/suites/unmanaged/helpers_test.go, test/e2e/suites/unmanaged/unmanaged_functional_test.go
/kind bug
This PR creates  a failing test for #3329  as well as extending the existing test for non managed clusters to ensure the LB for service is actually backed by instances.
Fixes #
**Checklist**:
```release-note
changes AWSCloudProvider tag for ec2 instances to be KubernetesClusterName() instead of ClusterName() to support load balancer services for EKS clusters 
```
=> :bug: fixes services for EKS clusters 

Makefile
/kind bug 
It looks like we removed the `$(RELEASE_NOTES)` target with this pull request in favor of Github Release Notes from this commit https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/7ee7ca5c96433c0bb5ad8eefb36e17f44b31fcfc
the release target looks like it is still using that, so `make release` will fail when trying to do the missing target.
Fixes #
**Checklist**:
=> fix: removes unused release notes target

test/e2e/suites/unmanaged/unmanaged_functional_test.go
Both tests failed few times, after making sure resources are cleaned up when the tests fail, we can enable these.
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3371
Boskos already have cleanup logic for most if not all resources created here, but need to do the cleanup ourselves as well to make sure.
Fixes #
**Checklist**:
=> Disable external infra tests

Makefile
Signed-off-by: Meghana Jangi <mjangi@vmware.com>
This PR will limit the apidiff test to run only if there are changes made in the directory api/ and exp/api/
Fixes #3282 
**Checklist**:
=> Apidiff test runs only if there are changes in api/ or exp/api/

Makefile
/kind bug
Fix setup-envtest to be only needed and installed if the respective target (test, test-verbose, test-cover) is called.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3386#
**Checklist**:
=> Only setup setup-envtest when the test target is called

go.mod, go.sum, pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go, pkg/cloud/services/s3/mock_s3iface/s3api_mock.go
/area release
This PR bumps AWS SDK Go to v1.43.28 and AWS IAM Authenticator to v0.5.7 and resolves the generated files errors. 
Fixes #3392 
**Checklist**:
=> Bump AWS SDK Go and AWS IAM Authenticator

Makefile, hack/releasechangelog.sh
/kind bug
Removed getopts logic from the release notes script. The variables set in the Makefile that calls this script are passed to the script. getops was not working properly, values were being overriden by Makefile because same variables names were being used in the script.
Fixes #
**Checklist**:
=> Fix for release log creation script

controllers/awsmachine_controller.go, controllers/awsmachine_controller_unit_test.go
/kind bug
Addresses an issue where setting `InsecureSkipSecretsManager` option on CloudInit on an AWSMachine will cause errors when attempting to reconcile deletes later on. Open to discussion on whether adding e2e tests that cover this is necessary/in-scope :)
Fixes #3394
**Checklist**:
=> Only attempt to delete bootstrap data secret if InsecureSkipSecretsManager isn't set

docs/book/src/topics/multitenancy.md
=> Add role assumption trust policy example to book

test/e2e/suites/conformance/conformance_test.go, test/e2e/suites/managed/eks_test.go, test/e2e/suites/managed/upgrade_test.go, test/e2e/suites/unmanaged/unmanaged_functional_test.go
/kind feature
Test templates were not reflecting tests that they were for. This PR updates the cluster names in templates to include the spec name.
Fixes #3424
I replaced all instances of cluster name being set via `fmt.Sprintf("cluster-%s", util.RandomString(6))` with `fmt.Sprintf("cluster-%s-%s", specName, util.RandomString(6))`. Hopefully, I got them all and didn't go overboard 😃 
**Checklist**:
=> Updates e2e test cluster names to include spec name

api/v1alpha4/conversion.go, api/v1beta1/awsmachine_webhook.go, api/v1beta1/types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml, controllers/awsmachine_controller_unit_test.go, controllers/awsmachine_security_groups.go, exp/api/v1alpha3/conversion.go, exp/api/v1alpha3/conversion_test.go, exp/api/v1alpha4/conversion_test.go, exp/api/v1beta1/awsmachinepool_webhook.go, exp/api/v1beta1/awsmachinepool_webhook_test.go, pkg/cloud/services/autoscaling/autoscalinggroup_test.go, pkg/cloud/services/ec2/ami.go, pkg/cloud/services/ec2/helper_test.go, pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go, pkg/cloud/services/ec2/launchtemplate.go, pkg/cloud/services/ec2/launchtemplate_test.go, pkg/cloud/services/interfaces.go, pkg/cloud/services/mock_services/ec2_interface_mock.go
/kind bug
This PR does following:
- Remove unused conversion functions in APIs.
- Deprecate `ARN` field from `AWSResourceReference`.
- Add lookup for `AdditionalSecurityGroups` with filters.
- Refactored code for `GetAdditionalSecurityGroupIDs` so as to use common function in `AWSMachine` controller and `launchtemplate.go`.
Fixes #2087 
Subset [PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3255/) that handles the same for Subnet fields in AWSMachinePool
**Checklist**:
```release-note
- …
```
=> Added lookup for fields of type AWSResourcesReference

api/v1beta1/tags.go, api/v1beta1/tags_test.go
/kind feature
This PR validates the tags created for resources
1. Added code for checking max number of user tags which can be created for a resource [50 user tags can be created]
2. Added code for checking characters which can be used in user tags created for a resource [letters, numbers, spaces and the following characters: _ . : / = + - @]
Fixes # https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1746
**Checklist**:
=> Validate Tags created for the resources

test/e2e/suites/unmanaged/unmanaged_functional_test.go
There is an issue caused by [PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3425) which increases the cluster name in below tests:
- Ignition tests which requires s3 bucket name to be within 63 characters limit.
- External infrastructure tests where spec name is coming up as empty which violates RFC 1123 while creating cluster.
This PR keeps the naming of clusters within range such that it satisfies all validations in above tests.
**Checklist**:
=> [E2E] Fix failing tests because of change in cluster names

test/e2e/data/eks/cluster-template-eks-control-plane-only-withaddon.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/nested-multitenancy/kustomization.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/nested-multitenancy/patches/bastion-enabled.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/nested-multitenancy/patches/subnet-with-filters.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/kustomization.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/patches/additional-security-group.yaml, test/e2e/suites/unmanaged/unmanaged_functional_test.go
/area testing
This PR adds the E2E tests for usage of filters in AWSResourceReference type fields. It also adds comments to tests/manifests for the tests that are combined/overloaded with other existing tests.
Fixes #3348 
**Checklist**:
=> [E2E] Added tests for using filters in AWSResourceReference type fields

test/e2e/data/cni/calico_eks.yaml, test/e2e/data/e2e_conf.yaml, test/e2e/data/e2e_eks_conf.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/external-cloud-provider/aws-ebs-csi-external.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/external-csi/aws-ebs-csi-external.yaml, test/e2e/suites/unmanaged/unmanaged_functional_test.go
Directing the test traffic to registry.k8s.io for the the following effort: [google groups thread](https://groups.google.com/a/kubernetes.io/g/dev/c/DYZYNQ_A6_c/m/e6VVt1U_AAAJ?utm_medium=email&utm_source=footer)
cc @dims 
Fixes #
**Checklist**:
=> Use registry.k8s.io registry in CI jobs

pkg/cloud/scope/awsnode.go, pkg/cloud/scope/iamauth.go, pkg/cloud/scope/network.go, pkg/cloud/scope/sg.go, pkg/cloud/services/awsnode/service.go, pkg/cloud/services/iamauth/service.go, pkg/cloud/services/network/service.go, pkg/cloud/services/network/subnets_test.go, pkg/cloud/services/securitygroup/service.go
/kind cleanup
Half of the scope interfaces are in `scope` package to avoid cyclic imports.
This PR moves all scope interfaces to that package for having all interfaces in the same package.
Fixes #
**Checklist**:
=> Scope cleanup

Makefile, docs/book/src/crd/index.md
/kind bug
This fixes the wrong behavior where running `make generate` after an api change wont regenerate the CRD definitions. 
Fixes #3336 
1. `make clean`
2. change the [API definition](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/exp/api/v1beta1/awsmanagedmachinepool_types.go)
3. `make generate`
4. change the [API definition](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/exp/api/v1beta1/awsmanagedmachinepool_types.go) again
5. `make generate`
**Checklist**:
```release-note
```
=> :bug: ./build/generate-go-apis to run on api change

Makefile
/kind cleanup
So the target is idempotent and it does not print to stderr on CI.
Example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/3344/pull-cluster-api-provider-aws-verify/1518490957455036416#1:build-log.txt%3A16
=> Makefile: use 'rm -f' for verify-boilerplate

Makefile, docs/book/src/crd/index.md
/kind bug
What this PR does / why we need it:
Reverts kubernetes-sigs/cluster-api-provider-aws#3344 because of `make generate` out of date error.
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #
Checklist:
=> Revert ":bug: ./build/generate-go-apis to run on api change"

cmd/clusterawsadm/ami/helper.go
/kind bug
Importing `sigs.k8s.io/cluster-api/test/framework/kubernetesversions` package inside `cmd/clusterawsadm/ami/helper.go` causes a version error while installing the `sigs.k8s.io/cluster-api-provider-aws/cmd/clusterawsadm/ami` package.
```logtalk
❯ go get sigs.k8s.io/cluster-api-provider-aws/cmd/clusterawsadm/ami
go get: sigs.k8s.io/cluster-api@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```
This PR duplicates the functions required from `sigs.k8s.io/cluster-api/test/framework/kubernetesversions` within `cmd/clusterawsadm/ami/helper.go`.
cc - @sedefsavas  …
=> Remove CAPI test package import in `clusterawsadm`

test/e2e/data/infrastructure-aws/kustomize_sources/gpu/gpu-operator-components.yaml
NVIDIA has updated and rotated the signing keys used by the apt, dnf/yum, and zypper package managers beginning April 27, 2022. This caused our GPU tests to fail as GPU operator was not able to fetch the drivers from the NVIDIA repo because of GPG keys mismatch.
This PR updates the `imagePullPolicy` for driver to `Always` in `cluster-policy` such that GPU Operator always pulls the updated images and we wont get the GPG key mismatch errors, as mentioned in the [workaround](https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/) provided by NVIDIA.
As part of this PR, we have also updated the NVIDIA driver version to `510.47.03` as previous version was pretty old and was not able …
=> [E2E] Fix failing GPU test due to update in the CUDA Linux GPG Repository Key

test/e2e/shared/aws.go
/kind bug
The flaky e2e infrastructure test stems from a lack of AllocationId field on the ElasticIP field of the AWSInfrastructure struct
This change adds a retry and timeout for obtaining the allocation ID for the elastic IP. Additionally, AWSInfrastructure's CreateNatGateway function is made conditional based on setting that allocation ID.
Fixes #3455
**Checklist**:
=> Add timeout to AllocateAddress

cmd/clusterawsadm/ami/list.go, cmd/clusterawsadm/cmd/ami/list/list.go
/kind feature
Currently there’s no way to pass a custom owner ID for listing AMIs using `clusterawsadm ami list [...]` command, but there’s already an implementation for doing the same which is only limited by the lack of a flag to pass a custom owner ID instead of having to use the one owned by Heptio that’s hard-coded within the source at `pkg/cloud/services/ec2/ami.go -> DefaultMachineAMIOwnerID`.
This PR adds an additional `--owner-id` flag that can be used to list CAPA AMIs _(following the `capa-ami-{{.BaseOS}}-{{.K8sVersion}}` naming format)_ on accounts other than the hard-coded one.
cc - @sedefsavas  …
=> Added `owner-id` flag for `clusterawsadm ami list`

test/e2e/data/infrastructure-aws/kustomize_sources/topology/cluster-template.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/topology/clusterclass-quick-start.yaml, test/e2e/shared/defaults.go, test/e2e/suites/unmanaged/unmanaged_CAPI_quick_clusterclass_test.go, test/e2e/suites/unmanaged/unmanaged_functional_clusterclass_test.go
/kind feature
Add ssm test based on ClusterClass
Part of #3346 
Started the effort to combine ClusterClasses. This test refactored and added more capabilities to the existing ClusterClass.
**Checklist**:
=> Add ssm test based on ClusterClass

controllers/awscluster_controller.go
Reverts https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3482 due to failing e2e tests: 
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e/1532032209207169024
Fixes #
**Checklist**:
=> Revert "Create bastion security group only when bastion is enabled"

cmd/clusterawsadm/ami/helper.go, cmd/clusterawsadm/cmd/ami/list/list.go
/kind bug
The current behaviour treats absence of AMIs in the `clusterawsadm ami list ...` query as an error. This should instead be treated as normal, while notifying the user that the account does not contain any such AMI.
cc - @sedefsavas 
Fixes #
**Checklist**:
=> Updated `clusterawsadm ami list` nil AMI output

docs/book/src/topics/troubleshooting.md
This adds the steps to recover a management cluster that has lost it's load balancer.
=> adding steps to recover cluster

docs/book/src/SUMMARY_PREFIX.md, docs/book/src/topics/using-iam-roles-in-mgmt-cluster.md
This PR adds documentation for usage of IAM roles in management cluster instead of using AWS credentials with which the management cluster was created.
Fixes #3130 
**Checklist**:
```release-note
Added doc for using IAM roles instead of AWS credentials while deploying mgmt cluster
```
=> docs: Using IAM roles instead of AWS credentials in management cluster

docs/book/src/topics/spot-instances.md
Add an example how to use spot instances with a EKS managed node group backed by AWSManagedMachinePool.
Fixes #2523 
**Checklist**:
=> Add EKS AWSManagedMachinePool example to spot instances doc

Makefile
_Description has been updated to summarise discussion and eventual changes._
The `apidiff` target runs 2 commands (piped) in an `if` which swallows
the exit code, meaning it never fails.
What we want:
- exit 1 when `git diff` fails
- exit 0 when `grep` fails
- call `go-apidiff` when `git diff` and `grep` succeeds
- exit 1 when `go-apidiff` fails
This is honestly a complete pain to do in a Makefile.
One option was to move bits into another `.sh` script (not the
`scripts/ci-apidiff.sh` one as that would make the target pointless).
Another option was to fork the `go-apidiff` command so that we can make
it only run on the `api/` dir, since that is all we care about. While that option
is the easiest to run, we don't want to have to maintain another
thing.
So, if we can live with a little …
=> fix: Fail apidiff make target when git fails

config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml, controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_types.go, controlplane/eks/api/v1alpha4/awsmanagedcontrolplane_types.go, controlplane/eks/api/v1beta1/awsmanagedcontrolplane_types.go, controlplane/eks/api/v1beta1/awsmanagedcontrolplane_webhook.go, controlplane/eks/api/v1beta1/awsmanagedcontrolplane_webhook_test.go, docs/book/src/topics/eks/pod-networking.md
/kind feature
cilium has an eni mode that requires a secondary cidr block on the vpc but does not use the vpc cni.
I looked for e2e tests but I didn't see anything specific related to this functionality. If I missed it please point me in the right direction and I'd be happy to update the code.
**Checklist**:
=> Allow disabling vpc cni when setting secondary cidr block

docs/book/src/topics/full-multitenancy-implementation.md
Updates the docs to ensure manager cluster from the Multitenancy setup guide is able to assume the role into the managed account and successfully create a cluster. Also updates a link to return to a previous section which was broken.
Fixes #3554
N/A
**Checklist**:
=> update docs to refect cluster namespace used

Makefile, docs/book/src/development/e2e.md, docs/book/src/topics/reference/jobs.md
/kind bug
After [the changes in Ginkgo variable names](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3501), e2e tests' focus regex is not working. My guess is we need to do some changes in line with the naming changes in test-infra too to make it work.
In the meantime, reverting the changes.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3559
**Checklist**:
=> Revert "Streamline Ginkgo variables" #3501

test/e2e/data/kubetest/conformance.yaml
After [Ginkgo v1 to v2 migration](https://github.com/kubernetes/kubernetes/pull/109111) in the Kubernetes repo (thanks to @CecileRobertMichon for tracking this down), conformance tests started failing with timeout. 
([slack thread for details](https://kubernetes.slack.com/archives/CEX9HENG7/p1657578307470649))
This PR increases the timeout due to this change:
`ACTION REQUIRED: When running test/e2e via the Ginkgo CLI, the v2 CLI must be used and `-timeout=24h` (or some other, suitable value) must be passed because the default timeout was reduced from 24h to 1h.`
Fixes # …
=> Increase conformance test timeout

controllers/awscluster_controller.go, controllers/awscluster_controller_unit_test.go
For EC2 clusters, create the bastion security group only if the bastion is enabled. #3028 introduced this feature for EKS clusters.
This repeats the original PR (#3482), which was merged before I added unit tests, and unfortunately had a bug in the implementation. That PR was reverted in #3495.
Special thanks to @pydctw for finding the cause of the bug, and suggesting a fix! :bow: 
The first commit of this PR is the original fix, with the bug. The second commit adds a _failing_  test that confirms the implementation bug , and the final commit fixes the bug. I want to squash the commits before merging.
/kind feature
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
=> feat: Create bastion security group only when bastion is enabled

Makefile, test/e2e/data/kubetest/conformance-ci.yaml
After https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3586 is in, non-ci conformance tests started failing:
(https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e-conformance/1547086357950631936)
The reason for this is only K8s >= 1.25 is using ginkgo v2, so we need to use ginkgo v1 flags until we bump all conformance test versions to >= 1.25.
As a follow up to this PR, I will create a test-infra PR to pass the new conformance-ci.yaml to be used in CI conformance test.
Fixes # …
=> Use ginkgo.timeout for only ci conformance tests

Makefile, test/e2e/data/kubetest/conformance-ginkgo-v2.yaml, test/e2e/suites/conformance/conformance_test.go
As a follow up to https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3592, instead of passing the ci conformance config via prow config, adding a check for Kubernetes version to use CI conformance config only if Kubernetes version is >=1.25.0.
Fixes #
**Checklist**:
=> Use ginkgo v2 conformance config for Kubernetes >= 1.25

pkg/cloud/services/eks/cluster.go
/kind bug
During this [3573](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3573) we changed the owner tag name. That made owner lookup fail on the next run here:
```go
tagKey := infrav1.ClusterAWSCloudProviderTagKey(s.scope.Name())
```
Because the key no longer was used with `Name()` this check returned a `nil` value. This PR fixes that.
Unfortunately, I don't know the code enough to ascertain if the "fix" introduced in that PR actually has more ramifications. This is the only one I could find for now that seems to be related to that change.
This …
=> Fix the owner checking of a cluster

pkg/cloud/services/awsnode/cni.go, pkg/cloud/services/awsnode/cni_test.go
/kind bug
Adds deduplication and only update the DaemonSet if there is a need for an update.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3567
**Checklist**:
=> Add deduplication handling and only update if there is a need for it

cmd/clusterawsadm/cloudformation/bootstrap/csi.go
/kind bug
During CloudFormation creation, when EnableCSIPolicy is set to true, clusterawsadm was creating the policy for it but not attaching it to control plane role. 
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3527
**Checklist**:
=> [clusterawsadm] Fix attaching CSI policy to control plane IAM role

docs/book/src/topics/machinepools.md, test/e2e/data/e2e_eks_conf.yaml, test/e2e/data/eks/cluster-template-eks-machinepool-only.yaml, test/e2e/suites/managed/README.md, test/e2e/suites/managed/eks_test.go, test/e2e/suites/managed/helpers.go, test/e2e/suites/managed/machine_pool.go
/kind feature
EKS e2e do not test AWSMachinePool flavor. This is an important flavor to support so added e2e test.
Fixes #2865 
**Checklist**:
=> Add AWSMachinePool test to eks e2e test

test/e2e/suites/managed/aws_node_env.go
/kind bug
This PR fixes the aws-node-env checker to use the right context for accessing the Kubernetes client. The `e2eCtx` it was using is declared in a test file.
This check is part of the normal e2e_eks test, so I'm wondering how this ever passed / worked recently.
**Checklist**:
=> Fix aws-node-env checker to use the correct input and context

docs/book/src/topics/eks/addons.md, docs/book/src/topics/multitenancy.md
Fix broken links under [EKS Addons](https://cluster-api-aws.sigs.k8s.io/topics/eks/addons.html) and [Multi-tenancy](https://cluster-api-aws.sigs.k8s.io/topics/multitenancy.html) which leads to `Document not found (404)`
This should help new users who are following the EKS guide to not be confused with broken links.
Fixes #3614
**Checklist**:
=> Correct broken links for EKS addons and multitenancy

controlplane/eks/controllers/awsmanagedcontrolplane_controller.go, controlplane/eks/controllers/awsmanagedcontrolplane_controller_unit_test.go, controlplane/eks/controllers/helpers_test.go
/kind bug
For EKS clusters, #3028 enabled the bastion security group only when the bastion is enabled. However, the implementation introduced a bug: every reconcile appends to a package-level variable!
Fixes #
I'd like to add a pair of unit tests, but haven't done that yet.
**Checklist**:
=> fix: Do not change default security groups during EKS control plane reconcile

test/e2e/data/e2e_eks_conf.yaml
We no longer need to use a nightly build, so pinning e2e EKS CAPI version to 1.1.5.
Fixes #
**Checklist**:
=> Modify e2e EKS config to use cluster api v1.1.5

Makefile
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>
/kind bug
- Fix apidiff target
Fixes #
**Checklist**:
=> Fix apidiff target

Makefile
/kind cleanup
Adds windows amd64 and arm64 binaries to the releases for clusterawsadm.
```
~\kube\cluster-api-provider-aws [main] > .\out\clusterawsadm-windows-amd64.exe version
clusterawsadm version: &version.Info{Major:"", Minor:"", GitVersion:"", GitCommit:"", GitTreeState:"", BuildDate:"", GoVersion:"go1.17.3", AwsSdkVersion:"v1.43.29", Compiler:"gc", Platform:"windows/amd64"}
```
As far as i can tell right now everything works fine and I browsed the code for common windows pitfalls like filepath joining etc. and looks like it will be fine.
Fixes #
**Special …
=> add binary releases for windows

main.go
/kind cleanup
While reviewing #3633, I noticed that we had set up reconcilers and webhooks based on feature flags in `main` itself, although we put some code in a separate `enableGates` function.  I also noticed that we had two identical conditional blocks to setup EKS-only reconcilers and webhooks, respectively.
To make the setup code easier to follow, I grouped it by feature flag, because that seems like the most useful grouping. (This means we interleave the setup of reconcilers and webhooks; I think this is safe, but hope to get feedback).
I also moved the EKS-only setup into a separate function.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close …
=> refactor: Group setup by feature flag

test/e2e/data/infrastructure-aws/kustomize_sources/gpu/clusterpolicy-crd.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/gpu/gpu-operator-components.yaml
This PR updates the GPU operator version to v1.11.1 so as to fix the failing GPU tests.  Operator deprecated use of some of cuda base images in the init containers because of which the tests were failing.
Fixes #3660 
Original issue https://github.com/NVIDIA/gpu-operator/issues/388
Since we are maintaining manifests, we need to port the cluster policy CRD and gpu operator resources from NVIDIA gpu-operator [repo](https://github.com/NVIDIA/gpu-operator/blob/release-1.11/bundle/manif …
=> [E2E] Bump NVIDIA GPU operator version in GPU tests

test/e2e/data/e2e_conf.yaml, test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-topology.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/topology/cluster-template.yaml, test/e2e/data/infrastructure-aws/kustomize_sources/topology/clusterclass-ci-default.yaml
/kind cleanup
Following up comment from https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3491
Rename quick-start ClusterClass to ci-default to decouple the ClusterClass name from a test name.
Fixes #
**Checklist**:
=> Rename quick-start ClusterClass to ci-default

test/e2e/data/infrastructure-aws/kustomize_sources/machine-pool/spot-instance-machine-pool.yaml
This PR corrects the minimum desired size of spot instances MachinePool, in accordance to https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3253#issuecomment-1050792767
Fixes #
**Checklist**:
=> [E2E] fix min desired value of MachinePool nodes for spot instance MachinePool test manifest

pkg/cloud/scope/machine_test.go, pkg/cloud/services/autoscaling/autoscalinggroup_test.go, pkg/cloud/services/ec2/ami_test.go, pkg/cloud/services/ec2/bastion_test.go, pkg/cloud/services/ec2/launchtemplate_test.go, pkg/cloud/services/eks/cluster_test.go, pkg/cloud/services/elb/loadbalancer_test.go, pkg/cloud/services/iamauth/crd_test.go, pkg/cloud/services/s3/s3_test.go, pkg/cloud/services/secretsmanager/secret_test.go, pkg/cloud/services/ssm/secret_test.go, pkg/cloud/tags/tags_test.go
/kind cleanup
Makes the specs inside the cloud/service/network package conformant to one type of naming convention
Part of #3198
**Checklist**:
=>  refactor: Makes specs for cloud package conformant to a standard naming convention

pkg/cloud/services/awsnode/cni.go, pkg/cloud/services/awsnode/cni_test.go
/kind bug
We apply environment property changes to aws-node. These changes are only applied to the loop variable, but the actual update doesn't update them correctly.
When I change the values, the update doesn't do anything.
Before:
- create node
```
Environment:
ADDITIONAL_ENI_TAGS:                    {}
AWS_VPC_CNI_NODE_PORT_SUPPORT:          true
AWS_VPC_ENI_MTU:                        9001
AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER:     false
AWS_VPC_K8S_CNI_EXTERNALSNAT:           false
AWS_VPC_K8S_CNI_LOGLEVEL:               DEBUG
AWS_VPC_K8S_CNI_LOG_FILE:               /host/var/log/aws-routed-eni/ipamd.log
AWS_VPC_K8S_CNI_RANDOMIZESNAT:          prng
AWS_VPC_K8S_CNI_VETHPREFIX:             eni …
```
=> Fix the update logic for aws-node daemonset environment properties

Makefile, config/rbac/role.yaml
As part of a previous change we lost the rbac generation done via
controller-gen. This mean that any changes to the `// +kubebuilder:rbac`
comments where not being picked up.
This change adds rbac generation back in.
Fixes #
**Checklist**:
=> chore: adding rbac generation back in

templates/cluster-template-eks-machinepool.yaml
We added AWSMachinePool test to eks e2e test recently: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3607.
This PR adds the template to be published.
Fixes #2029 
**Checklist**:
=> Add eks machinepool flavor template

pkg/cloud/services/awsnode/cni.go
/kind bug
Seems weird when we delete the CNI we delete the daemon set then immediately run a Get on the daemon set and return a missing cni error. I think when this was written it was forgotten to `return nil` after s.deleteCNI is called.
Fixes #
**Checklist**:
=> adding a return nil after deleting cni

config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml, controlplane/eks/api/v1beta1/awsmanagedcontrolplane_types.go, controlplane/eks/api/v1beta1/awsmanagedcontrolplane_webhook.go, controlplane/eks/api/v1beta1/awsmanagedcontrolplane_webhook_test.go
/kind bug
Removes the normalisation we perform for the version given to the AWSManagedControlPlane object. EKS requires a major.minor version format and we did that by truncating any given version and having a regex validation for the version being major.minor.
This, however, lead to us editing the spec and causing diff in applied / existing configs.
This PR attempts to remove this normalisation and relax the regex, so existing configurations don't break ( normally they would break, because we no longer truncate a given version ).
However, everywhere internally where we DO use the version for various things like creating a cluster, it should already be normalised.
**Which issue(s) this PR fixes** *(optional, in `fixes …
=> Relax the AWSManagedControlPlane version regex and remove normalising the version

api/v1beta1/tags.go, api/v1beta1/tags_test.go
/kind bug
Fixes #3701 
- Fixes incorrect regex of invaliding aws tags with spaces
- Introduces test case to check for it
**Checklist**:
- [ x] squashed commits
- [x ] includes documentation
- [x ] adds unit tests
- [ x] adds or updates e2e tests
=> fix validation for aws tags with spaces

controllers/awsmachine_controller_unit_test.go, test/helpers/envtest.go
/kind support
Changed the testenv creation so that it explicitly adds the CRDs from
CAPI. This has been copied for CAPZ :) By making this change it caused
some tests to fail as the `Machine` definitions weren't valid and so
these have been updated.
Relates #3683 
**Checklist**:
=> refactor: add capi crds to testenv

docs/book/src/topics/multitenancy.md
Small fix for the usage of `secretRef` for `v1beta1` in the multi-tenancy topic. It was using the old format.
/kind bug
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3717
**Checklist**:
=> Fix multitenancy topic for secretRef syntax

cmd/clusterawsadm/cloudformation/bootstrap/cloud_provider_integration_control_plane.go, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
/kind bug
Adds the missing "elasticloadbalancing:DeregisterTargets" action permission to the control plane role policy document.
Fixes #3486
=> Add elasticloadbalancing:DeregisterTargets to control plane role policy

controllers/awsmachine_controller.go, docs/book/src/topics/ignition-support.md, go.mod, go.sum
/kind cleanup
The flatcar-linux GitHub organization is being renamed to "flatcar". This PR updates all references accordingly.
Upstream issue: https://github.com/flatcar-linux/Flatcar/issues/836
I'm opening this PR in advance to allow quick merging once the rename occurs. I'll mark it as on hold in the meantime.
None
**Special notes for your reviewer**: None
**Checklist**:
=> Update references following Flatcar GitHub org rename

pkg/cloud/services/eks/config.go
/kind bug
`client.authentication.k8s.io/v1alpha1` has been removed in Kubernetes v1.24 see https://github.com/aws/aws-cli/issues/6920. EKS will soon support v1.24, to prepare for that we should use a version that will be supported. This also breaks anyone that uses `kubectl` >=1.24, so others may already be seeing this issue.
The oldest version that EKS supports is v1.20 https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html where `v1beta1` [was already available](https://github.com/kubernetes/kubernetes/tree/release-1.20/staging/src/k8s.io/client-go/pkg/apis/clientauthentication) ([and is still available even in 1.26](https://github.com/kubernetes/kubernetes/tree/v1.26.0-alpha.1/staging/src/k8s.io/clie …
=> fix: use v1beta1 version in EKS user kubeconfig

pkg/cloud/services/autoscaling/autoscalinggroup.go, pkg/cloud/services/autoscaling/autoscalinggroup_test.go
/kind bug
This PR adds the conversion of ASG instance AZ from SDK API to CAPA APIs because in `providerIDList` in [awsmachinepool_controller](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/d52c10c272153d008c200ea05b7c200a5d19d62d/exp/controllers/awsmachinepool_controller.go#L299) somehow the `ec2.AvailabilityZone` was coming empty. When observed ASG code [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/autoscaling/autoscalinggroup.go#L85), we missed AZ conversion while converting `v.Instance` to `i.Instance`(AZ being mandatory field in EC2 Instance API in `aws-sdk-go`), thus fixing below issues. …
=> Add ASG Instance AZ SDK API to CAPA API conversion

pkg/cloud/converters/eks.go, pkg/cloud/services/eks/identity_provider.go, pkg/eks/identityprovider/plan.go, pkg/eks/identityprovider/plan_test.go, pkg/eks/identityprovider/procedures.go, pkg/eks/identityprovider/types.go, pkg/eks/identityprovider/types_test.go
/kind bug
Normalizes OIDC configs into string values for easier comparison for reconciliation.
Fixes #3734 
I have a test running with a debugger right now which will prove this fixed the issue so this is just ready for review and ill post screenshots of it being fixed when I have them.
**Checklist**:
=> normalize oidc configs to string values for comparison

CONTRIBUTING.md, OWNERS, OWNERS_ALIASES, README.md
/hold
/kind support
Make the following changes to maintainers & reviewers:
- @Skarlso moves to maintainer from reviewer
- @Ankitasw moves to maintainer from reviewer
- @AverageMarcus moves to reviewer
**Let me or @sedefsavas know if you want to become a reviewer**
This change will be on hold for approximately 1 week before its merged.
Fixes #
**Checklist**:
=> PROPOSAL: Maintainers and reviewer changes

go.mod, go.sum, pkg/cloud/scope/managedcontrolplane.go, pkg/cloud/services/awsnode/cni.go
/kind bug
Adds additional logic to removing vpc-cni pre-installed resources when you set disableVPCCNI to true. Previous logic only deleted the `aws-node` DaemonSet when in reality there are ServiceAccounts, ClusterRole, ClusterRoleBinding and a CRD.
New logic deletes the SA/CR/CRB but leaves the CRD and any CRs. This is important because some people manage the VPC CNI via the helm chart and with these pieces around the chart fails to install citing the SA/CR/CRB already existing. Additionally... if you choose to disable vpc-cni through capa and install via helm, capa would continually smash it out of existing during reconciliation so added a check for managed-by: Helm
**Which issue(s) this PR fixes** *(optional, in …
=> deleting additional vpc cni resources when disabled

pkg/cloud/services/eks/cluster.go
/kind bug
After https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3573, the AWS tag on a EKS cluster was changed. This was a good change to make everything more consistent, but it broke upgrading EKS clusters that were created with CAPA < v1.5.0.
In this PR, both the new and the previous tag formats will be checked and only fail if both are nil.
I also took the opportunity to clean up the error message, here is what it looked like before. It wasn't very clear what it was looking for and printed a nil error.
```
- lastTransitionTime: "2022-09-22T10:01:30Z"
message: 'checking owner of default_e2e-eks-upgrade-test-3618755-control-plane
is e2e-eks-upgrade-test-3618755: %!!(MISSING)w(<nil>)'
```
**Which …
=> fix: wrong EKS tag when upgrading older clusters

pkg/cloud/services/eks/cluster.go
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3783.
The automated cherry-pick [failed](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3783#issuecomment-1284493507).
=> [release-1.5] fix: wrong EKS tag when upgrading older clusters

controlplane/eks/controllers/awsmanagedcontrolplane_controller.go, test/e2e/data/e2e_eks_conf.yaml
/kind bug
The EventBridge feature for importing ec2 events is not supported for EKS in the AWS managed control planes controller. The logic to reconcile the events and create any roles/policies needed is missing.
Slack context: https://kubernetes.slack.com/archives/CD6U2V71N/p1663962497725469
**Checklist**:
=> Add EventBridge ec2 event reconciliation and rule creation to eks managed control planes

test/e2e/shared/aws.go
/kind bug
Does not explicitly error when a IAM role deletion fails in `deleteResourcesInCloudFormation` e2e logic. All of the other error handling in `deleteResourcesInCloudFormation` is suppressed, it's unclear why this error was checked and no others.
Fixes #3794
**Checklist**:
=> Skip deleting 'control-plane.cluster-api-provider-aws.sigs.k8s.io' if it does not exist in the e2e setup

OWNERS_ALIASES, README.md
Signed-off-by: Richard Case <richard.case@suse.com>
/kind feature
This change will move to Daniel from review to maintainer. Daniel has been a long term user and contributor to CAPA. He provides thoughtful and insightful reviews. 
Holding for lazy consensus until after the office hours on 31st October 2022
/hold
=> PROPOSAL: move Daniel to maintainer

Makefile
This PR unifies the make target for generating test flavors for tests with and without using ClusterClass, as it was not much of a value-add to separate both, as both are used in almost all the tests.
Fixes #
**Checklist**:
=> [E2E] Fix test flavor generation make targets

controllers/awsmachine_controller_unit_test.go, controllers/awsmachine_security_groups.go, pkg/cloud/services/ec2/instances_test.go, pkg/cloud/services/ec2/launchtemplate.go
/kind feature
Current behavior for additional security groups especially when using filters is somewhat cumbersome and mysterious. If a filter has no potential matches, it will silently blackhole *all* additional security groups due to returning up an error which is eventually silently dropped. Additionally, a choice was made to only return the first match from a specified filter. It would be nice to be able to instead match all security groups returned by a filter so that tags can be used to implicitly add security groups to AWSMachines in a more dynamic way. Finally, in the current setup, it is considered an error to have a filter match that returns no results... this forces the requirement that all security groups …
=> Allow multiple security group filter matches

api/v1beta2/awsmachine_webhook.go, api/v1beta2/awsmachine_webhook_test.go, api/v1beta2/awsmachinetemplate_webhook.go, api/v1beta2/awsmachinetemplate_webhook_test.go, exp/api/v1beta2/awsmachinepool_webhook.go, exp/api/v1beta2/awsmachinepool_webhook_test.go
/kind bug
`clusterctl move` currently fails if trying to move an `AWSMachinePool` that have it's `rootVolume` already populated.
Fixes #3624
From what I can tell, the RootVolume device name is actually retrieved from the AMI image and the value in the `Spec` isn't used (only populated after creating).
See: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/7440d3ed110540432a7aed1ea165aaea79157a9c/pkg/cloud/services/ec2/instances.go#L926-L942
**Checklist**:
=> fix: remove check for root volume device name on create

docs/book/src/topics/eks/pod-networking.md, pkg/cloud/services/awsnode/cni.go, pkg/cloud/services/awsnode/cni_test.go
/kind bug
when adding vpc cni env it [forced envvars](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/awsnode/cni.go#L165-L172) for `aws-node` but we now know due to a [bug](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3677) were never being applied. This PR drops them entirely and pushes all the onus for VPC CNI Environment Variables to the user and makes CAPA less opinionated since these env vars are being added/dropped/deprecated constantly.
In addition, this Fixes #3678 because we aren't looping/assigning the env a second time and the dedupe [code above](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/awsnode/cni.go#L71-L75) is already fixing the daemonset …
=> rework vpc cni envvar logic to drop the forced keys

cmd/clusterawsadm/ami/helper.go, cmd/clusterawsadm/ami/helper_test.go, pkg/cloud/services/ec2/ami.go, pkg/cloud/services/ec2/ami_test.go
/kind bug
The old AMIs were generated with following pattern: `capa-ami-amazon-2-1.25.2-00-1664536077`. From the recent releases, the new AMIs are getting generated as `capa-ami-amazon-2-v1.25.3-1665727783`(observe prefix v to the k8s version)). Because of this mismatch, the newly generated AMIs are not getting published in S3, as the AMIs are filtered based on the convention `capa-ami-{{.BaseOS}}-{{.K8sVersion}}`.
This PR fixes the AMI naming format from `capa-ami-{{.BaseOS}}-{{.K8sVersion}}` to `capa-ami-{{.BaseOS}}-{{.K8sVersion}}-*`, such that all the new AMIs are also published to the S3 amis.json.
[Ref](https://kubernetes.slack.com/archives/C01E0Q35A8J/p1666969997721009) slack thread.
**Which issue(s) this PR …
=> Change naming format of AMIs while searching for AMIs

cmd/clusterawsadm/ami/helper.go, cmd/clusterawsadm/ami/helper_test.go, pkg/cloud/services/ec2/ami.go, pkg/cloud/services/ec2/ami_test.go
Reverts kubernetes-sigs/cluster-api-provider-aws#3790
=> Revert "Change naming format of AMIs while searching for AMIs"

config/rbac/role.yaml, docs/book/src/crd/index.md, docs/book/src/topics/machinepools.md, exp/controllers/awsmachinepool_controller.go, exp/controllers/awsmachinepool_controller_test.go, pkg/cloud/scope/machinepool.go, pkg/cloud/services/autoscaling/autoscalinggroup_test.go, pkg/cloud/services/ec2/helper_test.go
/kind feature
As a cluster operator, I can mark a MachinePool with the annotation `cluster.x-k8s.io/replicas-managed-by-autoscaler` to indicate it should not enforce the `MachinePool.replicas` field but instead reconcile it to match the ASGs desiredCapacity field. This allows me to use an external autoscaler which does not come into conflict with the MachinePool reconciliation loop. 
Fixes #2022
The annotation is the same as in kubernetes-sigs/cluster-api-provider-azure#2444.
Unfortunately, I did not yet manage to make the added …
=> allow annotation on MachinePool to set externally managed

pkg/cloud/services/eks/nodegroup.go
/kind bug
Due to provider ID matching logic changes in core CAPI, ProviderIdList need to be populated correctly.
Fix for unmanaged machine pools is https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3743 and this PR does the same for managed machine pools.
Fixes #
**Checklist**:
=> [release-1.5] Fix ProviderIDList in managed machinepool

templates/cluster-template-machinepool.yaml
Production ready example and more reliability when running capi controlplanes
Fixes #3814 
**Checklist**:
=> Added machinehealthcheck to cluster-template-machinepool

config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml, exp/api/v1beta1/types.go
/kind cleanup
I noticed a small typo in the spelling of "percentage" in the struct tag for ``UpdateConfig.MaxUnavailablePercentage`.  
**Checklist**:
=> Fix typo in AWSManagedMachinePool UpdateConfig

pkg/cloud/awserrors/errors.go, pkg/cloud/services/network/vpc.go
deletion fails for aws cluster with vpc limit exceeded
Issue: In case cluster creation didn't go through due to the VPC limit being exceeded, the VPC ID will be nil and during deletion of the such cluster, the AWS client will give the error.
```
│ E0907 09:53:16.390472       1 network.go:89] controller/awscluster "msg"="non-fatal: VPC ID is missing, " "error"=null "cluster"="am-cluster-123-4" "name"="am-cluster-123-4" "namespace"="am-cluster-123-4" "reco │
│ nciler group"="infrastructure.cluster.x-k8s.io" "reconciler 
```
Fix: Check the error code during VPC deletion and skip it if the error code is "MissingParameter"
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
=> Deletion fails for aws cluster with vpc limit exceeded

config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml, exp/api/v1beta1/types.go
/kind cleanup
The change in #3467 should have been made to v1beta2, but was made to v1beta1 by mistake.
Thanks to @pydctw for spotting the mistake!
Fixes #
**Checklist**:
=> Revert "Merge pull request #3467 from phoban01/fix-awsmachinepool-spec typo"

config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml, controlplane/eks/api/v1beta2/types.go, docs/book/src/topics/eks/addons.md, pkg/cloud/services/eks/addons.go
/kind feature
After the IPv6 discussion there was this comment from Richard: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3513#discussion_r917737084
There is no scenario in which you wouldn't want to overwrite, so we set it up as default behaviour.
**Checklist**:
=> Make overwrite the default behaviour for conflict resolution in addons

pkg/cloud/services/network/routetables.go, pkg/cloud/services/network/routetables_test.go, pkg/cloud/services/network/subnets.go
/kind feature
Add CCM tag to routing tables.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3532
**Checklist**:
=> Add CCM tag to routing tables

config/rbac/serviceaccount.yaml
I ran into an issue using the published manifests because there was an envsubst directive that is only compatible with a specific distribution of envsubst (github.com/drone/envsubst). I found [context in an old PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2100/files#r534228348). This PR restores an explanatory comment that got lost in a subsequent change.
=> docs: restore comment describing specific envsubst usage

test/e2e/shared/aws.go
Removes CCM tags from unmanaged Subnets in e2e helper functions and test https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2715.
This PR https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3251 modified the e2e functions to tag unmanaged Subnets, instead the e2e tests should rely on CAPA to do the correct tagging.
@dlipovetsky and I noticed this while looking at https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3481
**Checklist**:
=> e2e: remove Subnet CCM tags

api/v1beta2/tags.go
/kind cleanup
This PR cleans up the `Equals` func from `Tags` as it is deprecated and not used anywhere.
Fixes Part of #2355 
**Checklist**:
=> Remove Equals() from v1beta2 Tags API

pkg/cloud/scope/managedcontrolplane.go, pkg/cloud/scope/sg.go, pkg/cloud/services/securitygroup/securitygroups.go, pkg/cloud/services/securitygroup/securitygroups_test.go
The wording "overridden" is misleading. In every case where the wording is used to reference a security group, the security group is being overridden. Instead, it is the security group provided as an override.
/kind cleanup
The wording "overridden" is misleading. In every case where the wording is used to reference a security group, the security group is being overridden. Instead, it is the security group provided as an override.
Fixes #
**Checklist**:
=> fix: Replace misleading wording used for security group overrides

api/v1beta1/awsmachine_conversion.go, api/v1beta1/conversion.go, api/v1beta1/conversion_test.go, api/v1beta1/zz_generated.conversion.go, api/v1beta2/awsmachine_webhook.go, api/v1beta2/types.go, api/v1beta2/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml, exp/api/v1beta2/awsmachinepool_webhook.go, go.mod, pkg/logger/logger.go
/kind cleanup
We deprecated ARN field from AWSResourceReference in this [PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3257) and decided to remove it once v1beta2 API changes are in. This PR removes that field.
Fixes Part of #2355 
**Checklist**:
=> Remove ARN field from AWSResourceReference

test/e2e/suites/managed/eks_ipv6_test.go
/kind bug
Adding a check that ensures that the pod list isn't empty. The for loop after it wouldn't error if there would be no pods.
Fixes #
**Checklist**:
=> [E2E] Add check that the pod list is not empty.

cmd/clusterawsadm/ami/helper.go, pkg/cloud/services/ec2/ami.go, pkg/cloud/services/ec2/ami_test.go, pkg/cloud/services/ec2/instances_test.go
/kind bug
The old AMIs were generated with following pattern: capa-ami-amazon-2-1.25.2-00-1664536077. From the recent releases, the new AMIs are getting generated as capa-ami-amazon-2-v1.25.3-1665727783(observe prefix v to the k8s version)). Because of this mismatch, the newly generated AMIs are not getting published in S3.
This PR fixes the generation of AMI names such that it respects both the above formats, such that all the new AMIs are also published to the S3 amis.json.
[Ref](https://kubernetes.slack.com/archives/C01E0Q35A8J/p1666969997721009) slack thread.
Changes in image-builder that is now appending AMIs with k8s semver: https://github.com/kubernetes-sigs/image-builder/commit/05eff6b6dcc75e158b51c26d5628ecf4de34 …
=>  Change AMI name generation based on new format in image-builder

test/e2e/data/e2e_conf.yaml, test/e2e/data/e2e_eks_conf.yaml, test/e2e/shared/aws.go
This PR upgrades the conformance tests k8s version to 1.24.4 so as to pick up the corrected AMIs with containerd version 1.6.6, which fixes failing conformance tests.
This PR also increases the control plane wait timeout such that conformance test passes.
Fixes https://github.com/kubernetes/kubernetes/issues/113449
**Checklist**:
=> [E2E] Use k8s version 1.24.4 in conformance test and increase control plane wait timeout for conformance and EKS tests

controllers/awsmachine_security_groups.go, controllers/awsmachine_tags.go, pkg/cloud/services/ec2/launchtemplate.go
/kind bug
Valid annotation keys have two segments: an optional prefix and name, separated by a slash (/). 
In this commit, we fix the ones that include two slashes that couldn't be parsed as valid structs.
Fixes #3863
**Checklist**:
=> Fix lastAppliedTags annotations naming

docs/book/src/development/development.md, docs/book/src/development/tilt-setup.md
Signed-off-by: rjsadow <richard.j.sadowski@gmail.com>
This PR merges in changes to make the Developer Guide and Development with Tilt documentation more accurate and clear to follow. It updates several minor issues and assumptions made in the live version. 
Fixes #3876 
**Checklist**:
=> docs: updated Developer Guide with changes to make it more accurate

test/e2e/data/e2e_eks_conf.yaml, test/e2e/suites/managed/cluster.go
/kind flake
/kind support
Increased the eks e2e timeout for cluster creation. Also added logging to time the wait for sucessful creations.
Fixes #
**Checklist**:
=> test: increased cluster creation timeout for eks e2e

test/e2e/data/e2e_conf.yaml, test/e2e/data/e2e_eks_conf.yaml, test/e2e/data/shared/v1beta2_provider/metadata.yaml, test/e2e/suites/managed/cluster.go, test/e2e/suites/managed/helpers.go, test/e2e/suites/managed/upgrade_test.go
/area testing
/kind support
This PR updates the CAPA version used to v2.0.x. It also updates k8s versions used in the tests to v1.24.4.
For EKS upgrade tests, the upgrade path is updated from 1.22.4 to 1.24.4
Fixes #3879 
**Checklist**:
=> [E2E] Update CAPA version in tests

exp/controllers/awsmachinepool_controller.go, exp/controllers/awsmachinepool_controller_test.go
/kind bug
The suspend flow in the create ASG process is failing because during the ASG creation, we never return the actual ASG. That's because the CreateAutoscalingGroup flow is not returning an ASG so we reconcile it.
I just removed the suspend during creation, the update flow should still suspend or unsuspend anything that is different.
I'll try adding some more tests to this part of the code.
Fixes #
**Checklist**:
=> Remove suspend process flow from create ASG

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
/kind bug
AWSServiceRoleForAmazonEKSForFargate role generation doesn't obey partition settings.
It failed to create on aws-cn and maybe would fail on aws-us-gov partition.
Fixes #
**Checklist**:
=> fix AWSServiceRoleForAmazonEKSForFargate failed to create on non-aws partitions

test/e2e/shared/aws.go, test/e2e/shared/resource.go, test/e2e/shared/suite.go
Signed-off-by: Richard Case <richard.case@outlook.com>
/kind support
This adds saving of the original quotas from AWS.
Fixes #
**Checklist**:
=> test: save original aws resource quotas as returned by API

test/e2e/shared/defaults.go
This PR increases service quota for VPC to 25, as current quota is not sufficient for running E2E tests.
Fixes #
**Checklist**:
=> [E2E] Increase service quota for VPC

config/rbac/role.yaml, controllers/awscluster_controller.go, exp/controlleridentitycreator/awscontrolleridentity_controller.go, pkg/logger/logger.go
/kind bug
This PR adds back RBAC for controller identities which was deleted mistakenly in #3907 
Fixes #
**Checklist**:
=> Add back RBAC for controller identities

.github/workflows/scan.yml, hack/verify-container-images.sh
It allows to scan the controller manager image locally
This script is referring hack/verify-container-images.sh from cluster-api
Fixes #3894
=> Verify container images

api/v1beta2/network_types.go
/kind bug
A simple fix of the `String` function receiver, which should be a value receiver instead of a pointer to kick in.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3942
**Checklist**:
=> Fix String function receiver for IngressRule which resulted in an unreadable log output

controllers/awsmachine_controller_test.go, pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go
**What type of PR is this?** /kind feature
**What this PR does / why we need it**: While and after creation of ec2 instances, the network interfaces attached to those ec2 instances didn't have any tags. This PR adds the similar tags of the ec2 instance to the attached network interface.
Fixes #3839 
**Checklist**:
=> Adding tags to AWS Network Interfaces

Makefile
/kind flake
/kind support
Sometimes EKS E2E tests takes more than 3 hrs to complete test runs. This PR increases the E2E tests timeout in Ginkgo args to accommodate the above requirement.
Fixes #
**Checklist**:
=> [E2E] Increase test timeout in Ginkgo args

exp/controllers/awsmachinepool_controller.go, exp/controllers/awsmachinepool_controller_test.go, pkg/cloud/services/autoscaling/autoscalinggroup.go, pkg/cloud/services/interfaces.go, pkg/cloud/services/mock_services/autoscaling_interface_mock.go
/kind feature
After aws machine pool deployed, CAPA creates asg with subnets （[code](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/c59945258adfcf08b7a2ddd4c5190c0456db9fb4/pkg/cloud/services/autoscaling/autoscalinggroup.go#L157)）. The subnets are either from AWSMachinePoolSpec.Subnets, or derived from AWSMachinePoolSpec.AvailabilityZones, or MachinePool.Spec.FailureDomains, or ControlplaneSubnets.FilterPrivate().
User is possible to update the subnets or AvailabilityZones defined in AWSMachinePool. CAPA should update asg accordingly.
Fixes #3315 …
=> Update ASG if subnet changes

.github/workflows/scan.yml, Makefile, hack/verify-container-images.sh
1. update scan workflow action
2. update verify-container-images script
3. add `make verify-container-images` tool
This is a follow up PR of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3921.
A test result by temporarily add
```
push:
branches: [ action ]
```
to scan.yaml: https://github.com/wyike/cluster-api-provider-aws/actions/runs/3828313468/jobs/6513758507 
Fixes #3894
=> Update scan action

controllers/awscluster_controller.go, pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/elb/loadbalancer_test.go
/kind bug
The LoadBalancerReadyCondition is sometimes explicitly patched and other times it only updates the awsCluster object. Furthermore the condition won't be patched by the patch helper in the AWSClusterReconciler, because it's not in the `patch.WithOwnedConditions` list. This change puts the condition in the list and also updates the condition reason to `Deleted` when the LB is not found. Without setting the condition in that case, the reconciler will set condition to `Deleting` and it will never go back to `Deleted`.
Fixes #3870
**Special notes for your …
=> Update LoadBalancerReadyCondition on deletion

pkg/cloud/converters/tags.go, pkg/cloud/services/eks/oidc.go, pkg/cloud/services/eks/oidc_test.go
**What type of PR is this?** /kind feature
**What this PR does / why we need it**: Currently while creating an EKS cluster, its respective OIDC provider gets created and reconciled. However it didn't have the same tags as of the cluster. This PR adds the code for the OIDC provider to also have same tags as of cluster.
Fixes #
**Checklist**:
Proof of OIDC getting tagged:
=> Adding tags to OIDC providers

pkg/cloud/services/autoscaling/autoscalinggroup.go, pkg/cloud/services/autoscaling/autoscalinggroup_test.go
/kind bug
Currently if when using subnet filters with an AWSMachinePool no subnets are found to match the code will fallback to using any matching the AZs specified on the CR. This is unexpected and in contrast to how AWSMachine is handled in the same situation. 
This PR causes an error to be raised if the filters provided result in no subnets matching.
Fixes #3977
**Checklist**:
=> Fail creation of machine pool if no subnets matching filters found

pkg/cloud/services/s3/s3_test.go
Signed-off-by: Marcus Noble <github@marcusnoble.co.uk>
/kind bug
Linting currently fails on any backported PRs due to the use of `io/ioutil` 
Fixes #
See failing test on this PR: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3988/
**Checklist**:
=> [Release-1.5] Removed io/ioutil import

controllers/awscluster_controller.go, pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/elb/loadbalancer_test.go
The LoadBalancerReadyCondition is sometimes explicitly patched and other times it only updates the awsCluster object. Furthermore the condition won't be patched by the patch helper in the AWSClusterReconciler, because it's not in the `patch.WithOwnedConditions` list. This change puts the condition in the list and also updates the condition reason to `Deleted` when the LB is not found. Without setting the condition in that case, the reconciler will set condition to `Deleting` and it will never go back to `Deleted`.
Co-authored-by: Jose Armesto <github@armesto.net>
/kind bug
This is #3871, but for the release-1.5. The original PR could not be backported due to conflicts.
**Checklist**:
=> Apply #3871 "Update LoadBalancerReadyCondition on deletion" to release-1.5

Makefile, hack/releasechangelog.sh
/kind refactor
The [releasechangelog.sh](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/hack/releasechangelog.sh) script now uses arguments instead of relying on the right variables being set out side the script.
Fixes #3405
The `PREVIOUS_VERSION` arg is not set in the `Makefile`, as of now it ends up being parsed as `-o`. I need help in order to get the previous version and pass it or set a default value, but I don't think it's doable cause of the call to gh api.
**Checklist**:
=> Introduce args in releasechangelog script

test/e2e/shared/aws.go
/kind bug
This will help a lot in figuring out test failures such as these: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-eks-e2e/1617752246580154368
The cloudFormation stack failed but we have no idea why because we don't have any output of it.
Fixes #4001
**Checklist**:
=> Fix AWS CloudFormation dump after failed suit when there is no bootstrap cluster

test/e2e/shared/aws.go, test/e2e/shared/suite.go
/kind bug
Re-order how the bootstrapping logic is set up and when during test cluster creation so the AWS session is available in the after suite to dump the CloudFormation stack.
Fixes #
**Checklist**:
=> Reorder the bootstrapping logic so AWSSession is available in afterSuite

test/e2e/data/e2e_conf.yaml, test/e2e/data/e2e_eks_conf.yaml, test/e2e/suites/gc_managed/gc_managed_test.go
=> Fixes for gc related tests

pkg/cloud/services/elb/loadbalancer.go
/kind bug
In the case of a BYO load balancer, CAPA does not discover what AZs the LoadBalancer is a part of automatically. A downstream consequence is that control plane nodes are unable to target multiple AZs for placement, leading to all nodes being placed in a single AZ. Instead, CAPA should always be able to determine the AZs in which a load balancer is available and select the proper AZs accordingly.
Fixes #3980
**Checklist**:
=> fix(#3980): save the API ELB AZ to NetworkStatus

test/helpers/envtest.go
/kind feature
Nasty [allow/deny firewall popup dialogs](https://dev4devs.com/2020/07/20/how-to-run-go-tests-without-the-mac-os-firewall-popup-how-to-solve-it-to-run-the-tests-in-the-travis/) appear whenever the test binaries are rebuilt and started by `go test`. That is because they listen on all interfaces (basically `0.0.0.0` + `::`). The tests however work fine (on my machine™️) if only listening on `localhost`, which avoids popups and increases security because the servers cannot be accessed on the Wi-Fi, for example.
n/a …
=> Run tests on localhost to increase security and avoid macOS firewall popup dialogs

Makefile
- Fail if the specified Kubernetes version binaries cannot be found. Otherwise the test starts and tries to use system-installed binaries by mistake, which it typically wouldn't find. The actual download error is then hidden at the beginning of the test output.
- Bump envtest to Kubernetes 1.24 because then it will work for [kubebuilder on Apple M1 as of this comment](https://github.com/kubernetes-sigs/kubebuilder/issues/2664#issuecomment-1183351948). With this, I found that the `--arch amd64` workaround isn't needed anymore (I'm on Apple M1 and it's working), so I removed the OS/arch distinction.
- Use latest envtest commit because the Makefile used a version from 2021 …
=> Fix `make test` for Apple M1 (darwin-arm64), fail if kubebuilder assets cannot be found

pkg/cloud/services/network/vpc.go, pkg/cloud/services/network/vpc_test.go
/kind bug
Ensure tags on managed VPCs. If `AdditionalTags` change, they should be applied to the VPC.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4031
**Checklist**:
=> Ensure tags on managed VPCs

api/v1beta2/awscluster_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml, controllers/awsmachine_controller.go, controllers/awsmachine_controller_unit_test.go
/kind bug
If outdated CRD versions (in my case: v2.0.2) were used against a newer controller (`main` branch), the `AWSCluster` object could be stored without a default value for `AWSCluster.Spec.ControlPlaneLoadBalancer.LoadBalancerType`. The machine controller handles that incorrectly: it tries to register instances with a v2 LB, but should default to a classic LB.
The previous fix attempt is in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4029, but since we found the root cause, I'd like to suggest _this_ PR's solution instead since `awsCluster.Default()` is an undesired workaround.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will …
=> Ensure empty `loadBalancerType` field value is handled correctly

api/v1beta2/tags.go, pkg/cloud/services/network/subnets.go, pkg/cloud/services/network/subnets_test.go
/kind bug
Prevents CAPA from overwriting any user-provided `Name` tags.
Fixes #3989
**Checklist**:
=> Allow user to specify the Name tag value for AWS tags

test/e2e/shared/aws.go
/area testing
This PR fixes the role deletion in CF stack which leaves behind the roles and conflicts while creation of the stack, thus causing failures in E2E tests quiet frequently.
Fixes #
**Checklist**:
=> [E2E] Fix CF role deletion flake

config/rbac/role.yaml, controlplane/eks/controllers/awsmanagedcontrolplane_controller.go, pkg/cloud/services/iamauth/reconcile.go, pkg/cloud/services/iamauth/reconcile_test.go, pkg/cloud/services/iamauth/service.go, pkg/cloud/services/iamauth/suite_test.go
/kind bug 
Fixes 
Previously users who specified a unique IAM instance profile for an MachineDeployment or MachinePool were unable to use a non default iam role name, because it was previously hard coded. This PR intends to fix that by querying the associated MachineDeployments and MachinePools querying the infrastructure refs of each and getting the instance profile for them. 
We then pass these roles lists to ReconcileIAMAuthenticator and query the ARN for them and set the mapping that way. 
Fixes the issue described here #3926 as well as the one described here …
=> fix: use instance profiles of machine pools and machine deployments for mapping roles 

.github/PULL_REQUEST_TEMPLATE.md
This adds the release note section back into the PR template. This is in reparation in switching back to using  the k8s release notes generation so that we don't miss any important notices/actions that we need to highlight to users.
Fixes #
**Checklist**:
=> chore: adding release notes section to PR template

config/rbac/role.yaml, controllers/awsmachine_controller_unit_test.go, controlplane/eks/controllers/awsmanagedcontrolplane_controller.go, pkg/cloud/services/iamauth/reconcile.go, pkg/cloud/services/iamauth/reconcile_test.go, pkg/cloud/services/iamauth/service.go, pkg/cloud/services/iamauth/suite_test.go, test/e2e/shared/aws.go, test/e2e/shared/template.go, test/helpers/envtest.go
chore: refactor getting roles to be inline with PR review
test: adds an integration test to test getting roles logic
Also backports the following commit to 1.5 https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/e0fc4de3bc5f4008b214a8cab6c72a5fe51c6960#diff-6ff1d74b482f5f7e1c2727b17204096fe4bf243e8b7bbb0099b5701b7d3f77b1L53-L54
/kind bug 
backports https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4011
Fixes #
**Checklist**:
=> fix: use instance profiles of nodepools and machine deployments for mapping roles

controllers/awscluster_controller.go, controllers/awsmachine_controller.go, controlplane/eks/controllers/awsmanagedcontrolplane_controller.go, exp/controllers/awsfargatepool_controller.go, exp/controllers/awsmachinepool_controller.go, exp/controllers/awsmanagedmachinepool_controller.go, pkg/cloud/scope/cluster.go
/kind bug
**What this PR does / why we need it**: 
- The AWSCluster reconciler has an additional defer which included a patch in it which is ignoring the existing existing Close happening in a defer about 10 lines further down. During reconciliation you'll get a double Patch call and the only difference in the two was the list of conditions. I merged the conditions and deleted the unneeded Patch.
- All finalizers are being added by `controllerutil.AddFinalizer` which returns a bool if the finalizer was actually added to the object. It will return true on the first reconciliation and the patch will be called and false from then on, wrapping the AddFinalizer call with an if and gating the Patch will avoid the patch logic when it's obviously not necessary. …
=> cleaning up unnecessary object patches

docs/book/src/topics/multitenancy.md
The YAML provided within the example is missing a space, this makes it invalid if a user wishes to place it into a file and apply it without editing the manifest directly.
```bash
kubectl apply -f default-controller-identity.yaml
error: error validating "default-controller-identity.yaml": error validating data: ValidationError(AWSClusterControllerIdentity.spec): invalid type for io.x-k8s.cluster.infrastructure.v1beta1.AWSClusterControllerIdentity.spec: got "string", expected "map"; if you choose to ignore these errors, turn validation off with --validate=false
```
**Checklist**:
```release-note
NONE
```
=> fix: invalid yaml in multi-tenancy example

controllers/awscluster_controller_test.go, controllers/awsmachine_controller.go, controllers/awsmachine_controller_test.go, controllers/awsmachine_controller_unit_test.go, pkg/cloud/services/ec2/bastion_test.go, pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go
/kind bug
The existing AWSMachine reconciliation loop blocks on terminating an ec2 instance and waits for it to confirm the termination with AWS, as well as blocking on ec2 instance creation and waits up to one minute, for no discernible reason I could detect. This PR removes the blocking behavior, proceeding with reconciliation immediately after the AWS sdk confirms success on the API call. 
As a result, this change greatly speeds up large machine deployment rollouts. Previously, very large Machine Deployments (> 100 machines) would take several hours for the machine sets to provision new nodes and tear down machines. This was mostly a result of the reconciliation blocking for each instance creation and delete, and …
=> Modify AWSMachine reconciliation behavior to terminate and create instances without blocking

api/v1beta2/awsmachine_webhook.go, api/v1beta2/awsmachinetemplate_webhook.go
Update AWSMachine webhook validate logic on update to be consistent with validation on creation.
/kind bug
* Adds the missing validation of the security groups `onUpdate` for the AWSMachine webhook. 
* Fixes the bug identified in #3105, which was introduced in #2468, where the wrong volume was compared in one of the validation non-root volumes in the AWSMachine webhook validation.
* Changes the AWSMachineTemplate  webhook `onCreate` validation to be consistent with the AWSMachine `onCreate` validation.
Fixes #3109 & #3105
* Split …
=> Update AWSMachine webhook validate logic on update to be consistent

docs/book/src/topics/eks/pod-networking.md, pkg/cloud/services/awsnode/cni.go, pkg/cloud/services/awsnode/cni_test.go, pkg/internal/cidr/cidr_test.go
/kind bug
This is quite the logic puzzle so apologies in advance and try and bear with me. I found a situation when trying to configure the VPC/CNI you are unable to generate ENIConfigs for secondary subnets for the pods. CAPA is making the assumption that if you want a secondary subnet you are using SecondaryCIDRBlock. 
This is the core logic
* ENIConfig creation is gated behind a not nil SecondaryCIDRBlock
* ENIConfig creation only creates ENIConfigs for subnets tagged `sigs.k8s.io/cluster-api-provider-aws/association=secondary`
* subnet creation is gated behind a VPC ID being not present
The only scenario you can get ENIConfigs for an unmanaged VPC is by setting the VPC ID, setting SecondaryCIDRBlock (which is …
=> Allow for Self-Managed VPC with a Secondary Subnet for Pods

go.mod, go.sum, pkg/cloud/services/autoscaling/mock_autoscalingiface/autoscalingapi_mock.go, pkg/cloud/services/eks/mock_eksiface/eksapi_mock.go, test/mocks/aws_ec2api_mock.go
/area release
This PR bumps aws-iam-authenticator to v0.6.5
Fixes #4128 
**Checklist**:
```release-note
Bump aws-iam-authenticator to v0.6.5
```
=> chore: Bump aws-iam-authenticator from 0.6.4 to 0.6.5

api/v1beta2/awsmachinetemplate_webhook.go, api/v1beta2/awsmachinetemplate_webhook_test.go, config/webhook/manifests.yaml
/kind bug
Enables the AWSMachineTemplate validating webhook. Unclear why it was not previously configured.
~~The CloudInit behavior was removed, as it was copied from the v1alpha4 resources in [c09f55f8f2249d9fde6d7878a6595bf1c4672ff2](https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/c09f55f8f2249d9fde6d7878a6595bf1c4672ff2#diff-d85ef380a29a05566d8f529b89c7746d5ce4b257400061fe52be4a9ef0647668R65-R68) and kept being dragged forward, but the comment indicates it was only needed for one resource version upgrade, so I _think_ it's no longer necessary.~~ …
=> Add missing configuration to enable the awsmachinetemplate validating webhook

controlplane/eks/controllers/awsmanagedcontrolplane_controller.go, main.go
/kind bug
Provider infrastructure is not ready when AWS Managed Control Plane is reconciled for the first time and the cluster creation get stuck for 15 minutes until the reconciliation is forced.
**Checklist**:
**Release Notes**:
```
Fix AWSManagedControlPlane reconciliation
```
=> Fix awsmanagedcontrolplane doesn’t get reconciled

exp/controllers/awsmanagedmachinepool_controller.go, pkg/cloud/scope/managednodegroup.go, pkg/cloud/services/eks/eks.go, pkg/cloud/services/eks/nodegroup.go
/kind bug
The `AWSManagedMachinePool` controller should respect the annotation for externally managed autoscaler.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4134
**Checklist**:
```release-note
The `AWSManagedMachinePool` controller should respect the annotation for the externally managed autoscaler.
```
=> Allow external autoscaler for EKS managed node groups

api/v1beta2/defaults.go, api/v1beta2/types.go, controllers/awsmachine_controller.go, controllers/awsmachine_controller_unit_test.go, test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/addons/csi/data/aws-ebs-csi-external.yaml
/kind bug
Fixes `InstanceMetadataOptions` defaults not being set for AWSMachines
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4037#discussion_r1129064749
**Checklist**:
```release-note
Fix InstanceMetadataOptions defaults not being set for AWSMachines
```
=> Fix InstanceMetadataOptions defaults

test/e2e/data/cni/calico.yaml
Update Calico to v3.24.1. May be related to failures in #4173 
/kind cleanup
```release-note
NONE
```
=> Update Calico to v3.24.1

pkg/cloud/services/autoscaling/autoscalinggroup.go, pkg/cloud/services/autoscaling/autoscalinggroup_test.go
/kind bug
Now if we don't define replicas value in MachinePool spec, it is [defaulted](https://github.com/kubernetes-sigs/cluster-api/blob/main/exp/api/v1beta1/machinepool_webhook.go#L54-L56) to 1 by the webhook. Unfortunately, if minimum size of AWSMachinePool is greater than that, ASG creation fails with 400 error from AWS.
To prevent this, we ensure that the desired number of replicas for ASG is set only if MachinePool replicas is between min and max size of the AWSMachinePool, otherwise we return an error.
For clusters with externally managed replicas we can ignore this problem and do not set desired replicas during ASG creation at all. In this case MachinePool replicas value will be defaulted to AWSMachinePool …
=> Set ASG DesiredCapacity value only if MachinePool replicas is between min and max size of the AWSMachinePool

pkg/cloud/scope/session.go
/kind bug
AWS sessions need to be removed from cache in case of faulty retrieval from credentials providers. Otherwise a defective session can survive a delete of a cluster and recreate with same name but new credentials. 
Steps to reproduce:
1. Create credentials for AWS account 
2. Create a cluster with name XYZ using multi-tenancy for these AWS credentials
3. Delete this cluster with name XYZ
4. Create new credentials for AWS account 
5. Create a cluster with same name XYZ using multi-tenancy for these new AWS credentials
Result: Due to the two-layered caching approach in `sessionForClusterWithRegion()`(`pkg/cloud/scope/session.go:108`) the session created using the credentials from step #1 is able to survive and …
=> Fix session surviving cluster purge and recreate through cache

test/e2e/data/e2e_conf.yaml
/kind bug
This PR disables eventbridge feature(as its done in main branch as well) as E2E tests in CI are failing continuously. Will keep this disabled till the root cause is found out.
Fixes #
**Checklist**:
```release-note
NONE
```
=> [release-1.5] [E2E] Disable EventBridge in the tests

bootstrap/eks/controllers/eksconfig_controller.go, bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go, bootstrap/eks/controllers/eksconfig_controller_test.go
/kind bug
Fixes EKSConfig reconciliation handling for non-Machine kind owner resources, such as MachinePools. Previously EKSConfig reconciliation stopped after the secret was created. However, the secret may need to be updated if the LaunchTemplate changes.
Additional logging and error handling improvements included alongside.
Fixes #3848
**Checklist**:
```release-note
Fixed EKSConfig reconciliation handling for non-Machine kind owner resources, such as MachinePools.
```
=> Reconcile EKSConfig correctly for MachinePool and other Owner kinds

config/rbac/role.yaml, docs/book/src/crd/index.md, docs/book/src/topics/machinepools.md, exp/controllers/awsmachinepool_controller.go, exp/controllers/awsmachinepool_controller_test.go, pkg/cloud/scope/machinepool.go, pkg/cloud/services/autoscaling/autoscalinggroup_test.go, pkg/cloud/services/ec2/helper_test.go
chore: Backport allow annotation on MachinePool to set externally managed to release-1.5 https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3683
/kind feature
Fixes #3918
**Checklist**:
```release-note
allow annotation on MachinePool to set externally managed 
```
=> chore: Backport allow annotation on MachinePool to set externally managed to release-1.5

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
/kind support
- Add required permission to CloudFormation to support AlternativeGCStrategy
Fixes #4161 
**Checklist**:
```release-note
Action required: if you plan to use the alternative GC strategy you will need to update your IAM permissions by running **clusterawsadm bootstrap iam create-cloudformation-stack** again.
```
=> Add required permission to CloudFormation to support AlternativeGCStrategy

config/manager/manager.yaml
/kind feature
This does not really change the configuration, it just makes it explicit and enforce the defaults, except for the seccompPolicy which changes from Unconfined to RuntimeDefault. Syscalls filtered by RuntimeDefault policy are 95% namespaced and require capabilities (which we drop) in the first place, so no practical change there either.
This allows to be compatible to the restricted pod security admission profile.
Fixes #
Prior art:
* https://github.com/kubernetes-sigs/cluster-api/pull/7831
**Checklist**:
**Release …
=> add explicit securityContexts to the controller

pkg/cloud/services/s3/s3.go, pkg/cloud/services/s3/s3_test.go
/kind bug
Fixes a problem introduced by merging https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4010
**Checklist**:
```release-note
Fix incorrect s3 bucket ARN formatting.
```
=> fix: malformed s3 arn due to incorrect string formatting

pkg/cloud/services/eks/securitygroup.go
/cleanup
In the logs, the security group does not show the cluster name, which makes it difficult to understand which cluster is being reconciled. It is currently shown as
`"Reconciling EKS security groups" cluster-name=0xc001a23e30`
Fixes #
**Checklist**:
```release-note
Added cluster name to security group reconciliation log, instead of reference
```
=> Show cluster name instead of address in reconcile message

Makefile, config/rbac/role.yaml, controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
/kind  bug
When backporting https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4011 RBAC permissions were not regenerated,and so the required permissions for `AWSManagedControlPlane` to access `AWSMachineTemplates` was omitted 
Fixes #
**Checklist**:
```release-note
fixes permissions for AWSManagedCluster to access AWSMachineTemplates
```
=> :bug: updates makefile to include controllers for codegen

pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/elb/loadbalancer_test.go
/kind bug
Automatically appends `/readyz` when user selects `HTTP` or `HTTPS` as their `healthCheckProtocol`. Presented as an alternative  solution to #4209 
Fixes #4183 
**Checklist**:
```release-note
Appends /readyz to HTTP and HTTPS health check for control plane loadbalancer
```
=> fix: automatically append /readyz to http and https health checks

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
/kind feature
In this commit, we include additional IAM permissions needed from the controller in order to be able to modify EC2 instance metadata attributes.
Fixes #
**Checklist**:
```release-note
- Updated IAM policy needed from CAPA controller. The latest controller version introduces operations on EC2 instance metadata and users must update their IAM resources accordingly to avoid getting permission errors after upgrading.
```
=> feat: Include controller IAM for instance metadata operations

api/v1beta2/awsmachinetemplate_webhook.go, api/v1beta2/awsmachinetemplate_webhook_test.go
**What this PR does / why we need it**: In https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4037 we introduced `InstanceMetadataOptions`, but we didn't deal with upgrading from `2.0.x` to `>= 2.1.0`.
In the `2.0.x` we didn't have `InstanceMetadataOptions`, so when upgrading to `2.1.0` or more, defaulting kicks in, but gets rejected. This is because of missing changes to `ValidateUpdate`, to detect this and allow defaulted changes. This PR fixes that.
Fixes #
@richardcase @Skarlso @Ankitasw - we should probably recommend using 2.1.1
**Checklist**:
```release-note …
```
=> 🐛 Allow the defaulting of InstanceMetadataOptions to go through for AWSMachineTemplates

config/manager/manager.yaml, controllers/awscluster_controller.go, controllers/awsmachine_controller.go, controlplane/eks/controllers/awsmanagedcontrolplane_controller.go, docs/book/src/topics/bring-your-own-aws-infrastructure.md, exp/controllers/awsmachinepool_controller.go, exp/controllers/awsmanagedmachinepool_controller.go, feature/feature.go, main.go, pkg/cloud/scope/cluster.go, pkg/cloud/scope/managedcontrolplane.go, pkg/cloud/scope/network.go, pkg/cloud/services/network/egress_only_gateways.go, pkg/cloud/services/network/subnets.go, pkg/cloud/services/network/subnets_test.go, pkg/cloud/services/network/vpc.go, pkg/cloud/services/network/vpc_test.go
/kind feature
This PR removed tagging from unmanaged network resources such that the unmanaged resource tagging is taken care by the users themselves.
Fixes #3948 
Fixes #3919 
Fixes #3692 
**Checklist**:
```release-note
If the **TagUnmanagedNetworkResources** feature flag is set to false then CAPA tagging of unmanaged network resources will be disabled.
```
=> Remove CAPA tagging from unmanaged network resources

api/v1beta2/awsmachinetemplate_webhook_test.go, api/v1beta2/types.go, controllers/awsmachine_controller_unit_test.go, docs/book/src/topics/instance-metadata.md
/kind feature
Fixes #4247
Set default httpPutResponseHopLimit as 2 when creating instances
Keep crd default value as 1, in case that customers want to set it as 1 for some machine deployment
**Checklist**:
```release-note
Set default httpPutResponseHopLimit to 2 in IMDSv2 enablement when creating instances
```
=> Set httpPutResponseHopLimit to 2 when creating instances

hack/ensure-kubectl.sh
/kind cleanup
Part of umbrella issues to migrate the kubernetes project away from use of GCP project google-containers: https://github.com/kubernetes/k8s.io/issues/1571 and https://github.com/kubernetes/k8s.io/issues/2396. 
Updates `hack/ensure-kubectl.sh` script to use the https://dl.k8s.io/ url to install kubectl from.
Fixes #
**Checklist**:
```release-note
```
=> Use dl.k8s.io instead of kubernetes-release bucket

test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/addons/csi/data/aws-ebs-csi-external.yaml
/kind support
Add two e2e for AlternativeGCStrategy feature
- [managed] [gc] should cleanup a cluster that has ELB/NLB load balancers using AlternativeGCStrategy
- [unmanaged] [gc] should cleanup a cluster that has ELB/NLB load balancers using AlternativeGCStrategy
They have exact same test steps with ` [managed] [gc] should cleanup a cluster that has ELB/NLB load balancers` and `[unmanaged] [gc] should cleanup a cluster that has ELB/NLB load balancers`, except that before creating workload cluster, `shared.ReconfigureDeployment` is executed to reconfigure capa deployment with `AlternativeGCStrategy` feature flag set to true and will recover capa after test is done
**Which issue(s) this PR fixes** *(optional, in `fixes …
=> E2E tests for AlternativeGCStrategy

pkg/cloud/services/ec2/launchtemplate.go
/kind bug
Eventually, AWS' ipv6 docs aren't quite sure and eksctl completely removed dabbling with the network interface in launch templates. We are going to follow suit.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2420#issuecomment-1542812102
**Checklist**:
```release-note
Remove setting `Ipv6Prefix: aws.String("auto")` for network interfaces when IPv6 is enabled.
```
=> fix: remove modification of networkinterface for ipv6

cmd/clusterawsadm/cloudformation/bootstrap/iam.go, cmd/clusterawsadm/cmd/bootstrap/iam/iam_doc.go
Currently clusterawsadm doesn't support execution of "clusterawsadm bootstrap iam print-policy", it needs "--document" flag to specify the policy documents we want to see.
This PR introduces the "clusterawsadm bootstrap iam print-policy" as an individual command to list all those policy documents at once.
Fixes #
**Checklist**:
```release-note
Update clusterawsadm to include a full list of policies when omitting `--document` parameter.
```
=> Feature: add default behaviour for clusterawsadm bootstrap iam print-policy

test/e2e/shared/template.go
We're trying to migrate the `periodic-cluster-api-provider-aws-e2e` job from Prow build cluster running on GKE to Prow build cluster running on EKS. As part of that, we added [a new job `periodic-cluster-api-provider-aws-e2e-eks-canary`](https://github.com/kubernetes/test-infra/blob/f5f92ef685cfad2108bc5e266313c0f9636e79a7/config/jobs/kubernetes-sigs/cluster-api-provider-aws/cluster-api-provider-aws-periodics.yaml#L43-L91). However, the job is consistently failing with:
```
capa-e2e: [It] [unmanaged] [functional] Workload cluster with EFS driver should pass dynamic provisioning test
```
After some investigation, we found out that `efs-claim` PVC is not getting provisioned and `efs-csi-controller` is …
=> e2e: add elasticfilesystem:TagResource action

api/v1beta2/awsmachinetemplate_webhook_test.go, api/v1beta2/types.go, config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml, controllers/awsmachine_controller_unit_test.go, docs/book/src/topics/instance-metadata.md, pkg/cloud/services/ec2/instances.go, test/e2e/suites/unmanaged/helpers_test.go, test/e2e/suites/unmanaged/unmanaged_functional_test.go
/kind bug
IMDSv2 enablement in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4037 is a breaking change. We need give customer time to migrate their applications.
This PR set IMDSv2 as optional as the default to not break existing customers. The instance will be the same instance metadata options as before after capa upgraded:
```
httpPutResponseHopLimit: 1
httpTokens: optional
```
Customer can still customize instance metadata option themselves by configuring in the awsmachinetemplate/instanceMetadataOptions.
Fixes #4275 
**Special notes for your …
=> Set IMDSv2 as optional

api/v1beta1/awscluster_conversion.go, api/v1beta1/awsmachine_conversion.go, api/v1beta1/zz_generated.conversion.go, api/v1beta2/awsmachine_types.go, api/v1beta2/types.go, config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml, pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go
/kind feature
Adds support for users to specify the placement group by name when running instances.
Fixes #
**Checklist**:
```release-note
Add support to specify PlacementGroup Name in instances
```
=> :sparkles: Add support to specify PlacementGroup Name in instances

bootstrap/eks/controllers/eksconfig_controller.go, bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
/kind bug 
Previously the userdata for the eks config did not resolve the data from the `ContentFrom` field. This PR borrows the [implementation in the kubeadm bootstrap provider in CAPI](https://github.com/kubernetes-sigs/cluster-api/blob/1954644752499f38b0c5cdc8534718c32bfcde93/bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go#L734) and ports it over here. We also add a test to see if we resolve the secret properly
Fixes #
**Checklist**:
```release-note
resolves ContentFrom for eksconfig …
```
=> fix: resolve secrets when generating eks userdata

bootstrap/eks/controllers/eksconfig_controller.go, bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
/kind bug
Fixes #
**Checklist**:
```release-note
resolves ContentFrom for eksconfig userdata
```
=> fix: resolve secrets when generating eks userdata (backport #4285)

cmd/clusterawsadm/api/bootstrap/v1alpha1/zz_generated.conversion.go, cmd/clusterawsadm/api/bootstrap/v1beta1/types.go, cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_allow_assume_role.yaml, cmd/clusterawsadm/cloudformation/bootstrap/template_test.go, docs/book/src/topics/multitenancy.md, docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md
/kind feature
Allows CAPA policy to have an AssumeRole policy which allows it to perform cross account assume roles used by the AwsClusterRoleIdentity
Fixes #4046 
**Checklist**:
```release-note
Adds option to enable sts:AssumeRole policy in CAPA allowing it to perform cross account role assumes.  (#4046)
```
=> 4046 - Add AssumeRole and update appropriate tests

pkg/cloud/services/iamauth/reconcile.go, test/e2e/suites/managed/cluster.go, test/e2e/suites/managed/eks_ipv6_test.go, test/e2e/suites/managed/upgrade_test.go
/kind bug
removes the node role arn lookup automatically being added on to the iamconfig. 
Fixes #4291 
**Checklist**:
```release-note
removes always adding nodes role to iamauth config for EKS clusters 
```
=> fix: remove set nodes role

templates/cluster-template.yaml, test/e2e/data/infrastructure-aws/withclusterclass/e2e_test_templates/cluster-template-nested-multitenancy-clusterclass.yaml, test/e2e/data/infrastructure-aws/withclusterclass/e2e_test_templates/cluster-template-self-hosted-clusterclass.yaml, test/e2e/data/infrastructure-aws/withclusterclass/e2e_test_templates/cluster-template-topology.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-efs-support.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-gpu.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-ignition.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-internal-elb.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-intree-cloud-provider.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-kcp-remediation.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-kcp-scale-in.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-limit-az.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-machine-pool.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-md-remediation.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-multi-az.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-nested-multitenancy.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-peered-remote.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-remote-management-cluster.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-simple-multitenancy.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-spot-instances.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-ssm.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-upgrade-to-external-cloud-provider.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-upgrade-to-main.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-upgrades.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template.yaml
/kind bug
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4299
**Checklist**:
```release-note
The quick start guide is generated using this template and needs to use external provider.
```
=> fix: the quickstart guide needs update for external cloud provider

Makefile
/kind support
When doing the v2.1.3 there was an error when building the release binaries. Specifically the `release-binary` task was failing with the following error:
```
error obtaining vcs status exit status 128
```
Fixes #
Thanks to @killianmuldoon  for the change in CAPI that we are using here.
**Checklist**:
```release-note
Fix issue with building release binaries.
```
=> fix: building release-binaries fails

api/v1beta1/awscluster_conversion.go, api/v1beta1/zz_generated.conversion.go, api/v1beta2/awscluster_types.go, api/v1beta2/awscluster_webhook.go, api/v1beta2/awscluster_webhook_test.go, api/v1beta2/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml, docs/book/src/topics/bring-your-own-aws-infrastructure.md, pkg/cloud/services/securitygroup/securitygroups.go, pkg/cloud/services/securitygroup/securitygroups_test.go
/kind feature
We would like to customize the ingress rules that are included in the security group created for the control plane Load Balancer. Currently, capa always adds an ingress rule to allow traffic towards the k8s api from everywhere (`0.0.0.0/0`). But we would like to have more control over this. We would like to only allow traffic coming from our VPNs.
With the changes in this PR, when no additional ingress rules are defined, we add the ingress rule to allow traffic from everywhere. That way we are backwards compatible. But when additional rules are defined, these will be used instead.
**Checklist**:
```release-note
Allow customization of ingress rules in control plane Load Balancer security …
```
=> Allow customization of ingress rules in control plane LB security group

pkg/cloud/services/eks/iam/iam.go
/kind bug
Avoid "failed to create OIDC provider: error creating provider: EntityAlreadyExists" and "EKSControlPlaneReconciliationFailed" errors when provider.Url do not contain https
Fixes #3972 
**Checklist**:
=> Fix EKSControlPlaneReconciliationFailed when OIDC already exists

bootstrap/eks/controllers/eksconfig_controller.go, bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go, bootstrap/eks/controllers/eksconfig_controller_test.go, pkg/logger/logger.go, test/e2e/shared/template.go
/kind backport
Backport of #4195 
Fixes #
**Checklist**:
```release-note
Reconcile EKSConfig correctly for MachinePool and other Owner kinds
```
=> [release-2.0] Reconcile EKSConfig correctly for MachinePool and other Owner kinds

pkg/cloud/services/ec2/instances.go
When IsExternallyManaged we want to make sure additionalSecurityGroups are passed on creation to satisfy user intent. This also prevents the default VPC SG from silently attached to the ec2 and so deviating even more from user intent.
/kind bug
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4361
**Checklist**:
```release-note
When IsExternallyManaged create instance request uses additionaSecurityGroups
```
=> Pass right SGs for IsExternallyManaged on creation

pkg/cloud/awserrors/errors.go, pkg/cloud/services/ec2/ami.go
/kind bug
when upgrading to v2.1.2 we encountered the following error:
```
- lastTransitionTime: "2023-06-14T11:25:42Z"
message: "failed to create AWSMachine instance: UnauthorizedOperation: You are
not authorized to perform this operation.\n\tstatus code: 403, request id: 8b50824a-16ab-40cf-b737-47cb80ad34e4"
reason: InstanceProvisionFailed
severity: Error
status: "False"
type: InstanceReady
```
the message doesn't really provide any hints on the cause. After some investigation we found the issue to be a missing `ec2:DescribeInstanceTypes` permission which was introduced here https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4054. However, new permissions should not be required by a new version of the …
=> Use default arch x86_64 for AMI lookup if `ec2:DescribeInstanceTypes` permission is missing

controllers/awsmachine_controller.go
The non existence of the bootstrap secret should not prevent an awsMachine from being deleted
Fixes #
This change in behaviour was most likely introduced during the ignition support introduction 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2271/files#diff-4f8240f4e7ff07dcfa9627342b62772c1fe6ae0943021abe53fbb966db88886e
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2271/files#diff-0b559bbd149f0e6d54d789235423f66fa8906fdc6ee9c99b9e85db912912011e
**Checklist**:
```release-note …
```
=> Do not return error if secret does not exist

pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/elb/loadbalancer_test.go
/kind bug 
when a user specified healthCheck to be HTTPS or HTTP they would see an error like this in the logs 
```
failed to configure health check for classic load balancer: &{<redacted object>}: ValidationError: HealthCheck HTTPS Target must specify a port followed by a path that begins with a slash. e.g. HTTP:80/ping/this/path 
```
This was because the comparison on line 1441 of this file was comparing the addresses of the ELBHealthCheck, rather than the object. That comparison always failed and so the value from line 1445 was always returned. 
Fixes #
**Special …
=> :bug: compare string value of protocol in health check instead of pointer

pkg/cloud/services/ec2/instances.go
Before this, attachSecurityGroupsToNetworkInterface was re-applying existing SGs not specified in user intent. It's up to the caller to choose the right list of SG ids as in https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/3ebf018bbfc5345fbd9d9598ea9392b2a349ed6c/controllers/awsmachine_security_groups.go#L57-L64 so then attachSecurityGroupsToNetworkInterface just applies what is given.
/kind bug
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4361
**Checklist**: …
=> Drop unwanted SGs when calling attachSecurityGroupsToNetworkInterface

exp/controllers/awsmachinepool_controller.go, exp/controllers/awsmachinepool_controller_test.go, pkg/cloud/services/autoscaling/autoscalinggroup.go
/kind cleanup
Leftover from #4194, uses constants instead of strings for 2 "NoASGFound" events, removes duplicated code in `GetASGByName` in the asg helpers.
Fixes #
Split from #4194
**Checklist**:
```release-note
NONE
```
=> Switch to constants for asg not found events, simplify asg lookup

exp/controllers/awsmachinepool_controller.go, exp/controllers/awsmachinepool_controller_test.go
/kind bug
Changes how the AWSMachinePool and ASG retrieved from AWS is compared, so that we copy the existing AWSMachinePool values, and compare only fields we manage. This fixes bugs around partially set fields (e.g , `MixedInstancesPolicy` is set with an instance distribution, but no mixed instance policy) where the AWS defaults do not match the zero-values of fields.
Fixes #4070
Split off from #4194
**Checklist**:
```release-note
Improve AWSMachinePool diff to default to existing values when comparing launch …
```
=> Improve AWSMachinePool diff to default to existing values when comparing launch templates

Dockerfile, Makefile
/kind support
We can customize golang version of golang image `public.ecr.aws/docker/library/golang` when building managers and binaries
We can even customize golang image as well.
The customization impacts:
`make docker-build`
`make e2e-image`
`make build-toolchain` (used by `make release-binaries`)
Usually we don't need to customize the golang version. Each release has it's default golang version.
CAPI (https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L26-L27) and CAPV(https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/Makefile#L25) have similar support. The benefit of the support:
1. sometimes I want to use different golang version to build manager or binaries in my testing.
2. …
=> Customize golang version

test/e2e/data/e2e_conf.yaml
/kind support
This PR bumps k8s version to v1.26.6, AMIs of which uses containerd v1.6.14, this would fix failing conformance tests
Fixes https://github.com/kubernetes/kubernetes/issues/119446
**Checklist**:
```release-note
Bump k8s version to v1.26.6 to fix conformance tests
```
=> [E2E] Bump k8s version to v1.26.6 to fix conformance tests

Makefile, hack/verify-container-images.sh
/kind support
To support https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4394 in release-2.0 branch, backport make verify-container-image functionality.
Fixes #4394 
**Checklist**:
```release-note
Support `make verify-container-image` to scan CVEs with trivy
```
=> Backport verify container images to release 2.0

.github/workflows/scan.yml
/kind support
This PR adds Trivy scanning job to all supported release branches. Same thing has been done for CAPI (https://github.com/kubernetes-sigs/cluster-api/pull/7874) and CAPV(https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1978)
Fixes #4394 
try run in my folked repo: https://github.com/wyike/cluster-api-provider-aws/actions/runs/5699290555/job/15448043792
It depends on https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4401 
**Checklist**:
```release-note
Setup Trivy …
```
=> Setup Trivy scanning for supported release branches

.github/workflows/pr-gh-workflow-approve.yaml
/kind feature
This implements a GHA workflow that will automatically approve actions to run when there is an `ok-to-test`.
This has been copied from upstream CAPI.
Fixes #
**Checklist**:
```release-note
NONE
```
=> chore: approve actions on ok-to-test

api/v1beta2/awscluster_webhook.go, api/v1beta2/awscluster_webhook_test.go, api/v1beta2/types.go, cmd/clusterawsadm/gc/gc.go, cmd/clusterawsadm/gc/gc_test.go, exp/api/v1beta2/types.go, pkg/cloud/services/gc/cleanup.go, pkg/cloud/services/gc/cleanup_test.go
/kind support
This PR adds validation for the GC config annotation. 
Fixes #
As a part of this work 2 constants `ExternalResourceGCAnnotation` and `ExternalResourceGCTasksAnnotation` were moved from `exp/api/v1beta2` to `api/v1beta2`.
**Checklist**:
```release-note
None
```
=> Add validation for GC tasks annotation

controllers/awsmachine_controller.go, controllers/awsmachine_controller_test.go, controllers/awsmachine_controller_unit_test.go
/kind bug
At the moment, if the user uses Ignition as a bootstrap configuration, the user face a breaking error loop that prevents them from using this option.
The change makes sure that after the machine is successfully created, the data secret content in the S3 bucket gets removed correctly.
Fixes #4489 
With the change made, we needed to make sure to not break the unit tests that are already in place - we needed to add the secrets to the clients that didn't have it previously.
**Checklist**:
```release-note …
```
=> Fix error loop for ignition

pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/elb/loadbalancer_test.go
This ensures that failure domains are correctly set when using an externally managed (BYO) NLB
/kind bug
When using a BYO NLB, control plane nodes are only created in a single AZ regardless of the subnet AZs specified. This is due to the availability zones not being set in the lb status field, which causes the failure domains to not be detected in the AWSCluster reconciliation.
Fixes #4448
**Checklist**:
```release-note
Availability zone status is correctly set when using BYO NLBs, fixing an issue where control …
```
=> Set availability zones in status.networkStatus.apiServerElb when using BYO NLB

docs/book/src/topics/reference/reference.md
Added a table of feature gates and their corresponding environment variables 
Fixes #4323 
**Checklist**:
```release-note
Table of feature gates and their corresponding environment variables
```
=> feat: add table describing supported feature gates and their default values

controllers/awsmachine_controller.go, controllers/awsmachine_controller_unit_test.go
* see kubernetes-sigs/cluster-api-provider-aws#4511
/kind bug
This PR gets AWSCluster AdditionalTags onto root volumes for the AWSMachines in the cluster. I believe this is the intended behavior: Set the additional tags on the cluster and have them show up on all resources for that cluster.
I believe it was a minor oversight that the current behavior isn't like this already.
Fixes #4511
None
**Checklist**:
```release-note
Fixed: Additional Tags specified on the AWSCluster will now propagate to root storage …
```
=> fix: propagate AdditionalTags from AWSCluster to storage volumes

pkg/cloud/services/eks/roles.go
/kind bug
Currently if `EnableIAM` is set to true and no role is specified for a node group the controller auto generates a role. However, the name formatting seems to be backwards from what it is intended to be, causing the role name to start with a `-`. What's surprising to me is that this doesn't seem to cause problems, other than that it looks weird. The name for the role that is currently generated looks like: `-nodegroup-iam-service-role_<cluster-name>-<nodegroup-name>`. This PR swaps the generated role name so it will be: `<cluster-name>-<nodegroup-name>_nodegroup-iam-service-role`. This is follows the same format as the name generated for Fargate.
**Checklist**:
**Release …
=> fix: don't generate nodegroup role name starting with hyphen

pkg/cloud/services/network/natgateways.go, pkg/cloud/services/securitygroup/securitygroups.go, pkg/cloud/services/securitygroup/securitygroups_test.go
/kind bug
When we first create the nat gateways, they go to the `Pending` state. At that point, they don't have a PublicIP just yet. So if we only save the nat gateway public IP to the `status` field right after creating the nat gateway, we won't have the public IP available, meaning we won't be able to save it to the status.
Now the logic is changed so we always save the NAT Gateways IPs to the status field.
I've tested this version in our management clusters, adding our custom ingress rules and it all worked fine.
There was a missmatch in how the ingress rules were modeled in CAPA and the SDK, making the controller to keep reconciliating the same AWSCluster because the …
=> Save Nat Gateways IPs to status on every reconciliation

config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml, exp/api/v1beta1/conversion.go, exp/api/v1beta1/zz_generated.conversion.go, exp/api/v1beta2/awsmachinepool_types.go, exp/api/v1beta2/awsmanagedmachinepool_types.go, exp/api/v1beta2/awsmanagedmachinepool_webhook.go, exp/api/v1beta2/awsmanagedmachinepool_webhook_test.go, exp/api/v1beta2/types.go, exp/api/v1beta2/zz_generated.deepcopy.go, pkg/cloud/scope/machinepool.go, pkg/cloud/scope/managednodegroup.go, pkg/cloud/scope/shared.go, pkg/cloud/scope/shared_test.go
/kind feature
Currently when specifying the availability zone(s) for a (managed) machine pool, all the subnets in the zone(s) will be used. By default CAPI creates both a public and a private subnet in each availability zone. So when a machine pool specifies an availability zone, both the public and private subnets for the zone are used for the machine pool. It seems as though the private subnet is preferred in the ASG, however, I haven't been able to find any documentation regarding which subnet an instance gets launched in when an ASG contains both a private and public subnet. This means it's nondeterministic in which subnet an instance of the ASG will be launched in.
To solve for this, a new optional parameter …
=> feat: allow for specifying subnet type for az

templates/cluster-template-flatcar.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-ignition.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/ignition/patches/control-plane-ignition.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/ignition/patches/worker-ignition.yaml
/kind bug
Ensure kubeadm runs after containerd to avoid a race condition between the two.
We intentionally add an `After=` directive and not a `Requires=` directive to avoid breaking things for distros which use Ignition and don't use containerd.
See https://github.com/kubernetes-sigs/image-builder/issues/939.
None
**Checklist**:
```release-note
Ensure kubeadm runs after containerd on Flatcar
```
=> flatcar: Run kubeadm after containerd

controllers/awsmachine_controller.go
/bug
**What this PR does / why we need it**: Fixes an issue with the value of the `sigs.k8s.io/cluster-api-provider-aws-last-applied-tags` annotation growing to an unbounded size, due to re-use of it's previous state. We only need to persist information about volumes currently attached, so recomputing and clearing the annotation value is sufficient.
Fixes #4530
**Checklist**:
```release-note
Fixed a bug with the `sigs.k8s.io/cluster-api-provider-aws-last-applied-tags` annotation that could cause excessive metadata values on AWSMachines. 
```
=> Fix cluster-api-provider-last-applied-tags-on-volumes to recalculate the value on each reconcile

controllers/awsmachine_controller.go
/kind bug
cherry-pick of #4531 
**Checklist**:
```release-note
Fixed a bug with the `sigs.k8s.io/cluster-api-provider-aws-last-applied-tags` annotation that could cause excessive metadata values on AWSMachines. 
```
=> [release-2.2] cherry-pick: Fix cluster-api-provider-last-applied-tags-on-volumes to recalculate the value on each reconcile

hack/tools/Makefile, hack/tools/go.mod, hack/tools/go.sum, hack/tools/tools.go
/kind bug
This change makes the versions of kpromo to consistently be v4.
Fixes #
**Checklist**:
```release-note
Make kpromo versioned consistent
```
=> fix: make kpromo version consistent

Makefile, docs/book/src/development/releasing.md
/kind bug
During the v2.2.4 release `make promote` images failed for 2 reasons:
- incorrect project name
- blank fork
This change fixes both of these problems.
Fixes #
**Checklist**:
```release-note
Fix issues with kpromo to do with project name and fork
```
=> fix: kpromo failed during release

pkg/cloud/services/ec2/bastion_test.go, pkg/cloud/services/network/natgateways_test.go, pkg/cloud/services/network/vpc_test.go, pkg/cloud/services/secretsmanager/secret_test.go, pkg/cloud/services/ssm/secret_test.go
/kind bug
Fixes #4546
Fixes #
**Checklist**:
```release-note
fix: remove unused context imports
```
=> fix: remove unused context imports

scripts/ci-e2e.sh
/kind bug
Fixes #
**Checklist**:
```release-note
NONE
```
=> e2e: Remove double install

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml, pkg/cloud/services/s3/s3.go, pkg/cloud/services/s3/s3_test.go
/kind feature
I noticed that the S3 bucket isn't tagged. Some companies use AWS tags for grouping resources, calculating costs, or to clean up accidental remainders of clusters that CAPI/CAPA couldn't delete after a misconfiguration. With this change, the bucket is tagged as belonging to the cluster.
I'm not entirely sure if there's a use case where people provide a shared S3 bucket. In the S3 service code, there's such a hint in a `TODO`. For that case, we would need to introduce `AWSCluster.spec.s3Bucket.additionalTags` where users can set `sigs.k8s.io/cluster-api-provider-aws/cluster/...=shared`. And the implementation should be changed to only upsert tags instead of overwriting them, given that multiple `AWSCluster` …
=> 🌱 Tag S3 bucket as owned by cluster

controllers/awsmachine_controller.go
/kind bug
```
E1009 14:38:14.462868   54510 logger.go:83] "unable to delete machine" err="failed to get raw userdata: failed to retrieve bootstrap data secret for AWSMachine openshift-cluster-api-guests/vpri-4ll2w-master-0: Secret \"vpri-4ll2w-master\" not found"
E1009 14:38:14.463556   54510 controller.go:324] "Reconciler error" err="failed to get raw userdata: failed to retrieve bootstrap data secret for AWSMachine openshift-cluster-api-guests/vpri-4ll2w-master-0: Secret \"vpri-4ll2w-master\" not found" controller="awsmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSMachine" AWSMachine="openshift-cluster-api-guests/vpri-4ll2w-master-0" namespace="openshift-cluster-api-guests" …
```
=> :bug: On deletion, should ignore if the secret cannot be found

scripts/ci-conformance.sh, scripts/ci-e2e-eks-gc.sh, scripts/ci-e2e-eks.sh, scripts/ci-e2e-gc.sh, scripts/ci-e2e.sh, test/e2e/data/e2e_conf.yaml
/kind support
This PR adds python3-requests package installation which is breaking right now in the pip installation in CI.
It also fixes the semantic version of latest aws infrastructure provider.
Fixes #4550
**Checklist**:
```release-note
NONE
```
=> [release-2.2] [E2E] Fix E2E pipeline failures

pkg/cloud/services/securitygroup/securitygroups.go, pkg/cloud/services/securitygroup/securitygroups_test.go
/kind cleanup
This is an improvement on the current logic that blindly sets tags on security groups. The cloud provider expects only a single load balancer to be tagged with `kubernetes.io/cluster/test = owned`. By default, we already tag the `lb` security group, we should ensure all the other security groups remain untagged.
Fixes #
**Checklist**:
```release-note
NONE
```
=> When tagging security groups, ensure cloud provider tag is only on lb

controllers/awscluster_controller.go, controllers/awscluster_controller_unit_test.go
/kind cleanup
This is a small improvement, to try to always delete as many resources as possible before returning. When using external cloud providers, or service load balancers, there can be cross dependencies that the current logic doesn't solve. For example, a service load balancer created by a provider can use the security group created by CAPA, although when we try to delete the security group first the deletion fails because of dependencies, and we block deletion.
Fixes #
**Checklist**:
```release-note
NONE …
```
=> Try to delete as many resources as possible, then requeue

api/v1beta2/network_types.go, config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml, pkg/cloud/services/securitygroup/securitygroups.go, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-internal-elb.yaml
/kind feature
Fixes #
**Checklist**:
```release-note
NONE
```
=> :seedling: Allow ESP protocol to be set in IngressRules

OWNERS_ALIASES, README.md
/kind feature
This PR makes the following changes:
- @cnmcavoy moves to reviewer
- @nrb moves to reviewer
- @faiq moves to reviewer
- @vincepri moves from emeritus to maintainer
- @shivi28 moves to emeritus reviewer
- @dthorsen moves to emeritus reviewer
- @pydctw moves to emeritus reviewer
- Updates the owner alias with changes in CAPI / SIG cluster lifecycle leads
> For anyone moving to emeritus, if you feel you want to move back to reviewer in th efuture feel free to reach out to any of the maintainers to discuss.
```release-note
Maintainer and reviewer changes.
```
=> [PROPOSAL] Reviewer and maintainer changes

controllers/awsmachine_controller.go, exp/controllers/awsmachinepool_controller.go, pkg/logger/logger.go
/kind cleanup
See https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md#what-method-to-use
Fixes #
**Checklist**:
```release-note
If you're using --verbosity (or `-v`) flags to gather more logs, the new guidelines show: warn at level 1, debug at level 4, and trace at level 5.
```
=> ⚠️ Log according to sig-instrumentation guidelines

controllers/awsmachine_controller.go, controllers/awsmachine_controller_unit_test.go
**What this PR does / why we need it**: Regression from main branch, backport of #4512 into release-2.2 failed and introduced errors and missed adding a unit test. See conversation on slack by @philjb : https://kubernetes.slack.com/archives/CD6U2V71N/p1697658532510839 
Fixes #4511 
**Checklist**:
```release-note
Fixed: Additional Tags specified on the AWSCluster will now propagate to root storage volumes.
```
=> Fix the backport of #4512 into release-2.2 branch

cmd/clusterawsadm/ami/helper.go, docs/book/src/topics/images/built-amis.md
/kind support
Recent image-builder has removed support on ubuntu1804  in recent releases: [here](https://github.com/kubernetes-sigs/image-builder/blob/main/images/capi/Makefile#L323).
CAPA in the meanwhile follows the same, starts to support ubuntu2204 ami and drop support on ubuntu1804 ami.  When listing amis with clusterawsadm, add ubuntu2204 filter to include ubuntu2204 to the list result.
In this PR, it also fixes a typo on a duplicate region `ap-northeast-2` on the doc 
Fixes #
build clusterawsadm and test locally:
``` …
```
=> Update CAPA supported AMI OS

pkg/cloud/services/eks/cluster.go, pkg/cloud/services/network/routetables.go
/kind bug
Fixes #4574 
**Checklist**:
```release-note
Fix issue with EKE e2e tests due to a issue when specifying which subnets to use.
```
=> fix: eks e2e test failing as subnet name was used

OWNERS, OWNERS_ALIASES, README.md
/kind support
This changes makes the following maintainer & reviewer changes:
- @fiunchinho moves to reviewer
- @Skarlso moves from maintainer to emeritus
@Skarlso - thank you for your contributions and dedication to CAPA, the project is better for it.
Fixes #
**Checklist**:
```release-note
@fiunchinho moves to reviewer and @Skarlso moves to emeritus maintainer
```
=> [PROPOSAL] move fiunchinho to reviewer

pkg/cloud/scope/machinepool.go, pkg/cloud/services/ec2/launchtemplate.go
/kind bug
When changing the machine pool's bootstrap config, e.g. `KubeadmConfig/{a => b}`, which is supported after CAPI's fix https://github.com/kubernetes-sigs/cluster-api/pull/8667, CAPA had a bug where it would continue even after the new bootstrap secret cannot be read, for instance because it doesn't exist yet as the bootstrap provider still needs a few seconds to make it ready. That could lead to a catastrophic misconfiguration where the launch template's user data is empty, typically leading to new instances not getting bootstrapped at all. Detailed problem description in [this comment](https://github.com/kubernetes-sigs/cluster-api/issues/8858#issuecomment-1737930898).
This provides the obvious fix. I couldn't …
=> Fix launch template reconciliation if bootstrap data secret cannot be read

pkg/cloud/services/s3/s3.go, pkg/cloud/services/s3/s3_test.go
Follow-up to #4518: also add `AWSCluster.spec.additionalTags` to S3 bucket.
/kind feature
All cloud resources should have the additional tags on them.
**Checklist**:
```release-note
Use `AdditionalTags` for S3 buckets
```
=> Use `AdditionalTags` for S3 buckets

controllers/awsmanagedcluster_controller.go
/kind bug
Users may specify that some AWS resources should not be managed by CAPA controllers, because they may be managed by a different mechanism. We expose the `cluster.x-k8s.io/managed-by: "<name-of-system>"` annotation, so that users can specify which resources should not be reconciled by capa controllers. [We use it for our `AWSCluster` controller](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/controllers/awscluster_controller.go#L385), but we don't use it for our `AWSManagedCluster` controller. I believe it should also use it.
Fixes # …
=> Filter out reconciling events on externally managed AWSManagedClusters

controllers/awsmachine_controller_unit_test.go, controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook_test.go, hack/tools/Makefile, pkg/cloud/interfaces.go, pkg/cloud/services/ec2/instances_test.go, pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/elb/loadbalancer_test.go, test/e2e/shared/defaults.go, test/e2e/suites/unmanaged/unmanaged_functional_test.go
/kind support
This PR bumps following deps manually:
Bump Golangci lint to v1.55.2
Fixes #
**Checklist**:
```release-note
Bump dependencies
```
=> Bump golangci-lint dependency

test/e2e/suites/unmanaged/unmanaged_functional_test.go
Fixes #
**Checklist**:
```release-note
NONE
```
=> :bug: e2e should delete the cluster before validating

test/e2e/data/e2e_eks_conf.yaml
/kind support
This PR updates CAPA version for release-2.2 in EKS e2e config, to fix failing CI
Fixes #
**Checklist**:
```release-note
Fix EKS E2E tests
```
=> [release-2.2] [E2E] Fix EKS tests

exp/controllers/awsmachinepool_controller.go, pkg/logger/logger.go
/kind bug
I found that not all of these logs were printed in production:
```
func (s *Service) ReconcileLaunchTemplate(
scope scope.LaunchTemplateScope,
ec2svc services.EC2Interface,
canUpdateLaunchTemplate func() (bool, error),
runPostLaunchTemplateUpdateOperation func() error,
) error {
// [...]
// <=== NOT PRINTED ===>
scope.Info("checking for existing launch template")
// [...]
if needsUpdate || tagsChanged || amiChanged || userDataHashChanged || userDataSecretKeyChanged || launchTemplateNeedsUserDataSecretKeyTag {
// <=== PRINTED ===>
scope.Info("creating new version for launch template", "existing", launchTemplate, "incoming", scope.GetLaunchTemplate(), "needsUpdate", needsUpdate, "tagsChanged", tagsChanged, …
```
=> Pass logger to machine pool scope to get verbosity right, fix copying logger in `With...` methods

exp/api/v1beta2/awsmachinepool_webhook.go, exp/api/v1beta2/awsmachinepool_webhook_test.go
/kind feature
Users can currently set both `SpotMarketOptions` and `MixedInstancesPolicy`, but this is not a valid configuration on AWS, resulting on this error
```
InvalidQueryParameter: Incompatible launch template: You cannot use a launch template that is set to request Spot Instances (InstanceMarketOptions) when you configure an Auto Scaling group with a mixed instances policy. Add a different launch template to the group and try again.
```
It's better to prevent this configuration early, so users get quick feedback on what's wrong with their clusters.
**Checklist**:
```release-note
Prevent users setting SpotMarketOptions and MixedInstancesPolicy at the same time
```
=> :sparkles: Prevent users setting values that are invalid configuration on AWS

exp/controllers/awsmachinepool_controller.go, exp/controllers/awsmachinepool_controller_test.go, pkg/cloud/scope/machinepool.go, pkg/cloud/services/autoscaling/autoscalinggroup.go, pkg/cloud/services/autoscaling/autoscalinggroup_test.go, pkg/cloud/services/eks/nodegroup.go
/kind bug
For machine pools that have externally managed replicas (for example by `cluster-autoscaler`) the cluster-api-provider-aws should not set the desired replicas otherwise it can cause a problem where the controller is trying to update an ASG with desired replicas that are out of bounds of min/max.
Example:
The machine pool is set to have `min:1`  instances and `max: 3` instances and it's currently running on 2 desired replicas. The user wants to update to new values `min: 5` and `max: 10`.  The update operation fails with an AWS API error 
```
E1122 16:24:14.026636       1 controller.go:324] "Reconciler error" err=<
unable to update ASG: failed to update ASG "tsa05-ndp01": ValidationError: Desired capacity:2 must be between the specified min …
```
=> :bug: Update ASG - do not set desired value for machinepool which have externally managed replicas

pkg/cloud/services/ec2/instances.go
/kind bug
This mitigates issues caused by falling back to tag-based searching for EC2 instances in case future AWS calls fail within `CreateInstance()`, such as attaching ENIs to security groups or tagging ENIs.
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/c9b9276eb1491e75d5073a1c7965722b1fec090e/controllers/awsmachine_controller.go#L421-L448
Related to #4629 
This PR focuses on mitigating the impact when the controller fails to tag ENIs after creating EC2 instances. Another PR to make the fallback tag-based searching more robust is in the works in #4630 
**Checklist**:
```release-note
Update AWSMachine providerID …
```
=> :bug: Update awsmachine providerID and instanceID immediately after ec2:RunInstances is called

exp/controllers/awsmachinepool_controller.go, exp/controllers/awsmachinepool_controller_test.go, pkg/cloud/services/autoscaling/autoscalinggroup.go, pkg/cloud/services/autoscaling/autoscalinggroup_test.go
/kind bug
[On this PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4660) we tried to fix #4655 by ignoring the "not found" error when describing instance refreshes resources on AWS. But the AWS API returns a `400` error with code `ValidationError` when trying to describe the instance refreshes for a non existing AutoScalingGroup. Since `ValidationError` sounds super generic, instead of ignoring that error, on this PR I'm moving the call to find the AutoScalingGroup before defining the function that will check if we can do an instance refresh. That way, if the AutoScalingGroup is nil, we know we can skip checking. Also, we still want to update the `LaunchTemplate` when the AutoScalingGroup does not …
=> :bug:  There is no need to check instance refresh if ASG is not found

pkg/cloud/services/s3/s3.go, pkg/cloud/services/s3/s3_test.go
/kind feature
Fixes #
**Checklist**:
```release-note
Enable transit encryption on S3 buckets
```
=> :sparkles: Enable transit encryption to S3 bucket

go.mod, go.sum, pkg/cloud/services/autoscaling/mock_autoscalingiface/autoscalingapi_mock.go, test/mocks/aws_ec2api_mock.go
Supersedes auto-generated PR https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4669 since `make generate` is needed.
Module bump
**Checklist**:
```release-note
NONE
```
=> 🌱 bump sigs.k8s.io/aws-iam-authenticator from 0.6.12 to 0.6.13

templates/cluster-template.yaml
The default cluster template uses the `external` cloud provider, but does not provide the necessary information to install the cloud provider.
Copies the structure of the
cluster-template-external-cloud-provider.yaml into the default template, with the folloiwng changes.
* The following version updates were made to keep up-to-date:
aws-cloud-controller-manager: v1.28.3
CSI driver:                   v1.25.0
CSI provisioner:              v3.6.2
CSI attacher:                 v4.4.2
CSI resizer:                  v1.9.2
CSI livenessprobe:            v2.11.0
CSI register:                 v2.9.2
* The CNI resource references were removed, since the Quickstart lets the user install their own CNI.
* Updated the contents of the …
=> 🐛: Use external CCM in default template

exp/controllers/awsmachinepool_controller.go, exp/controllers/awsmachinepool_controller_test.go, pkg/cloud/services/autoscaling/autoscalinggroup_test.go
Cherry-pick https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4662 (@fiunchinho)
The only conflict was a simulated error type in the unit test.
**Checklist**:
```release-note
Skip instance refresh attempt if ASG does not yet exist
```
=> 🐛 There is no need to check instance refresh if ASG is not found (cherry-pick to release-2.3)

controllers/awsmachine_controller.go, pkg/cloud/scope/machine.go
/kind bug
We have an issue that there is a gap between the CAPI Machine deletion and the AWSMachine deletion. In this timeframe the kube-apiserver to the to be deleted control plane is no longer possible, but the deregistering of the LB member will be performed only for AWSMachine deletions. This PR fixes the gap and also deregisteres the instance if the CAPI Machine is deleted.
Fixes #4697
**Checklist**:
```release-note
Resolved issue where deleted control planes were still registered in the kube-apiserver load …
```
=> 🐛 Fix deregistering of deleted CAPI Machines

pkg/cloud/services/gc/ec2.go, pkg/cloud/services/gc/loadbalancer.go
/kind feature
Log messages are currently unactionable because only an ID is given:
```
capa-controller-manager-6df7759674-hpchv manager 2023-12-21T10:17:16.005130350+01:00 	failed delete reconcile for gc service: deleting resources: deleting security group sg-084aa1bd14358af73: deleting security group: DependencyViolation: resource sg-084aa1bd14358af73 has a dependent object
```
At least the region is needed for humans to follow up. Else you'd have to loop through your AWS accounts and regions to find the ID, which is cumbersome.
**Checklist**:
```release-note
Log full ARN in GC error messages
```
=> ✨ Log full ARN in GC error messages

exp/controllers/awsmachinepool_controller.go
Wrap the underlying error when the AWSMachinePool reconciler fails to get the infra cluster
Fixes #
**Checklist**:
```release-note
Wrap the underlying error when the AWSMachinePool reconciler fails to get the infra provider cluster or control plane object
```
=> :bug: Wrap error when AWSMachinePool reconciler fails to get infra provider cluster

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml, controllers/awsmachine_controller.go, controllers/awsmachine_controller_unit_test.go, pkg/cloud/services/s3/s3.go, pkg/cloud/services/s3/s3_test.go
/kind cleanup
Currently, the S3 object store generates a large amount of log spam during reconciliation. Objects are stated to be deleting regardless of objects already being deleted.
Example:
```
I1129 02:23:28.008345       1 logger.go:67] "Deleting unneeded entry from AWS S3" secretPrefix=""
I1129 02:23:28.008394       1 logger.go:67] "Deleting object" controller="awsmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSMachine" AWSMachine="clusters-system/us-west-2-production-worker-us-west-2d-infra-vln7r-xzcsk" namespace="clusters-system" name="us-west-2-production-worker-us-west-2d-infra-vln7r-xzcsk" reconcileID="c10cc649-57ce-40f4-99bb-17d06590c2cf" machine="clusters-system/us-west-2-production-worker-us-west-2d-5lgbh-6cbb9999d5xlnxtcvd" …
```
=> :bug: cleanup: eliminate log spam when using S3 secrets

controllers/awscluster_controller.go, controlplane/eks/controllers/awsmanagedcontrolplane_controller.go, pkg/cloud/services/eks/config.go, pkg/cloud/services/eks/roles.go
/kind cleanup
Add contextual logging of control plane / cluster. Fix some error returns/logging. Found while trying EKS cluster creation.
**Checklist**:
```release-note
Fix some logging and error cases
```
=> 🌱 Fix some logging and error cases

api/v1beta1/awscluster_conversion.go, api/v1beta1/zz_generated.conversion.go, api/v1beta2/network_types.go, config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml, pkg/cloud/awserrors/errors.go, pkg/cloud/filter/ec2.go, pkg/cloud/services/securitygroup/securitygroups.go, pkg/cloud/services/securitygroup/securitygroups_test.go
/kind feature
We want to secure the VPC as much as possible.
Fixes #4675 
**Checklist**:
```release-note
Remove ingress and egress rules from vpc default security group
```
=> :sparkles: Remove ingress and egress rules from vpc default security group

controllers/awscluster_controller.go, controllers/awscluster_controller_test.go, controllers/awscluster_controller_unit_test.go
/kind feature
Once CAPA is done with deletion reconciliation, it removes its own finalizer. Other operators however may still have finalizers on the `AWSCluster` object and the object may remain until those external operators are done with deletion. CAPA should not unnecessarily keep reconciling the object.
**Checklist**:
```release-note
Skip AWSCluster deletion reconciliation once CAPA finalizer is gone
```
=> ✨ Skip AWSCluster deletion reconciliation once CAPA finalizer is gone

pkg/cloud/services/s3/s3.go, pkg/cloud/services/s3/s3_test.go
/kind bug
Currently the S3 bucket is always created in us-east-1, regardless of where the cluster is located. In addition, this PR always ensures that we add a policy to ensure transport encryption is enabled, even when using presigned URLs.
Fixes #
**Checklist**:
```release-note
When using Ignition, the S3 bucket was previously created in us-east-1 regardless of where the cluster was located, new S3 buckets will be created within the same region as the cluster.
```
=> :bug: S3 Bucket should be created in the same region, always add transport encryption policy

controlplane/rosa/controllers/rosacontrolplane_controller.go, pkg/cloud/scope/rosacontrolplane.go, pkg/rosa/client.go, pkg/rosa/clusters.go, pkg/rosa/idps.go, pkg/rosa/nodepools.go, pkg/rosa/oauth.go, pkg/rosa/users.go, pkg/rosa/util.go
/kind feature
This PR generates a kubeconfig secret for ROSA clusters according to CAPI [contract ](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/cluster)
Secret name | Field name | Content
-- | -- | --
\<cluster-name>-kubeconfig | value | base64 encoded kubeconfig
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4734
**Checklist**:
```release-note
Generate CAPI kubeconfig secret for ROSA clusters
```
=> ✨ ROSA: Generate CAPI kubeconfig secret

config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml, controllers/rosacluster_controller.go, controlplane/rosa/api/v1beta2/rosacontrolplane_types.go, controlplane/rosa/controllers/rosacontrolplane_controller.go, exp/controllers/rosamachinepool_controller.go
/kind feature
- Add 2 new fields to the ROSAControlePlane.status: `ConsoleURL` and `OIDCEndpointURL` status fields.
- Set `Status.FailureMessage` when cluster provisioning failed (unrecoverable state).
- Delay removing the finalizer from `ROSAControlPlane` CR until the cluster is fully deleted.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4515
**Checklist**:
```release-note
Reconcile ROSAControlePlane status
```
=> ✨ ROSA: Reconcile ROSAControlePlane status

hack/ensure-kubectl.sh, hack/utils.sh
/kind bug
Fixes #4719
This PR is a pre-requisite to fix the blocked CI of #4710. 
Essentially, the `--short` flag has been deprecated and removed from v1.29.
To keep backward compatibility, although the infra image has already `kubectl` baked in, the `--output=yaml` flag is used as a replacement.
**Checklist**:
```release-note
NONE
```
=> 🐛 Updating verify kubectl version script

config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml, controlplane/rosa/api/v1beta2/conditions_consts.go, controlplane/rosa/api/v1beta2/rosacontrolplane_types.go, controlplane/rosa/api/v1beta2/zz_generated.deepcopy.go, controlplane/rosa/controllers/rosacontrolplane_controller.go, pkg/rosa/versions.go
/kind feature
Validate and reconcile `.spec.version` to trigger an upgrade if version changes.
Fixes #
**Checklist**:
```release-note
Reconcile ROSAControlPlane version to trigger upgrades
```
=> ✨ ROSA: Reconcile ROSAControlPlane version

api/v1beta1/awsmachine_conversion.go, api/v1beta1/zz_generated.conversion.go, api/v1beta2/awsmachine_types.go, api/v1beta2/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml, controllers/awsmachine_controller_test.go, docs/book/src/topics/bring-your-own-aws-infrastructure.md, pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go
/kind feature
Adds fields to the AWSMachine and AWSMachineTemplate resources to allow VPC selection, as well as overriding the security groups chosen for various infrastructure roles.
Fixes #4540
**Checklist**:
```release-note
Added AWSMachine and AWSMachineTemplate fields to control vpc placement for individual instances
```
=> ✨ Add AWSMachine fields to control vpc placement for the instance

controllers/awscluster_controller_test.go, pkg/cloud/services/network/vpc.go, pkg/cloud/services/network/vpc_test.go
/kind bug
In case of a repeating storage error, for example
```
"Reconciler error" err="failed to reconcile network for AWSManagedControlPlane mynamespace/mycluster: failed to patch conditions: AWSManagedControlPlane.controlplane.cluster.x-k8s.io \"mycluster\" is invalid: spec.network.subnets[7]: Duplicate value: map[string]interface {}{\"id\":\"\"}" [...]
```
which was caused by something totally different, CAPA would create an indefinite number of VPCs (and potentially other resources depending how far reconciliation succeeds!), filling up the AWS account to its limits and requiring manual cleanup of the whole mess (the one case I had wasn't fun 😆).
This is terrifying but based on a very simple, horrible bug: VPC …
=> 🐛 Make VPC creation idempotent to avoid indefinite creation of new VPCs if storage of the ID fails

test/e2e/data/e2e_eks_conf.yaml
/kind bug
-->
Kubernetes v1.24 is entering into an extended support window that adds additional cost for EKS clusters. This PR moves to v1.29.1, the latest version of Kubernetes, in order to avoid that infrastructure cost.
Standard EKS support for this version ends March 23, 2026.
Fixes #4777 
**Checklist**:
```release-note
NONE
```
=> :bug: Use Kube v1.29.1 for EKS e2e tests

Makefile
When a $GOPATH contains a trailing slash, the current check for string equality between the repo root and the computed path does not pass, even though it should. Passing both sides of the check through `abspath` makes this check more robust.
Fixes #
**Checklist**:
```release-note
NONE
```
=> :sparkles:  Makefile: handle $GOPATH with a trailing slash

docs/book/src/topics/rosa/enabling.md
/kind bug
Enable the machinePool feature in order to be able to use ROSA machine pool feature
Fixes #
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4774
**Checklist**:
```release-note
None
```
=> 📖 Improve ROSA quickstart with MachinePool and troubleshooting guide

api/v1beta2/awscluster_types.go, api/v1beta2/awscluster_webhook.go, api/v1beta2/awscluster_webhook_test.go, api/v1beta2/conditions_consts.go, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml, config/rbac/role.yaml, controllers/awscluster_controller.go, controllers/awscluster_controller_test.go, controllers/awsmachine_controller.go, controllers/awsmachine_controller_test.go, controllers/awsmachine_controller_unit_test.go, controllers/suite_test.go, pkg/cloud/scope/machine.go, pkg/cloud/scope/machine_test.go, pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go, pkg/cloud/services/secretsmanager/secret_test.go, pkg/cloud/services/ssm/secret_test.go
/kind feature
Cluster API allows defining externally managed control plane for the given cluster, the current code-base doesn't consider this since it nevertheless performs the following actions:
- reconciliation of a Load Balancer, although already provisioned by the ControlPlane provider
- blocking the EC2 creation since it requires an ELB DNS name
Fixes #4437
**Checklist**:
```release-note
A new enum value, `disabled`, is added for the `AWSCluster.spec.controlPlaneLoadBalancer.loadBalancerType` field, which skips the reconciliation of the load balancer for the given cluster, useful for clusters which are consuming an externally …
```
=> ✨ Supporting externally managed Control Plane

config/crd/bases/OWNERS, controllers/OWNERS, controlplane/rosa/OWNERS, docs/book/src/topics/rosa/OWNERS, exp/api/v1beta2/OWNERS, exp/controllers/OWNERS, pkg/cloud/scope/OWNERS, pkg/rosa/OWNERS, templates/OWNERS
The folks working on building out ROSA functionality would like to be able to iterate without needing to pull in top-level approvers for ROSA-isolated changes.
```release-note
NONE
```
=> :sparkles: *: add OWNERS for ROSA

api/v1beta2/network_types.go, cmd/clusterawsadm/converters/cloudformation.go, controllers/awscluster_controller_test.go, pkg/cloud/converters/tags.go, pkg/cloud/services/autoscaling/autoscalinggroup.go, pkg/cloud/services/ec2/launchtemplate.go, pkg/cloud/services/eks/iam/iam.go, pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/network/natgateways.go, pkg/cloud/services/network/routetables.go, pkg/cloud/services/network/subnets.go
/kind feature
In https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4474, @vincepri re-introduced the managed-subnet functionality. This PR adds a test to ensure that we don't lose the functionality again by mistake.
This is a forward-port of the test which I had originally added in our CAPA fork (https://github.com/giantswarm/cluster-api-provider-aws/commit/407bd9806fd50e1c970aa75ae79acfa7728070cf). Back then, I found an issue where updated information wasn't written back to the scope because `func (s Subnets) Find[...] *SubnetSpec` returned a pointer to a copy. I left this change in here – let me know if it should be split out.
Adds a test for …
=> ✨ Add test for provider-managed infrastructure, fix writing latest status back into `ClusterScope`

controllers/awscluster_controller_test.go, pkg/cloud/services/network/vpc.go
/kind bug
Fixes #
**Checklist**:
```release-note
NONE
```
=> :bug: Delete VPC endpoints only if s3 bucket is enabled

pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/elb/loadbalancer_test.go
/kind bug
The logic introduced in #4733 removed the checks on attaching security groups to network load balancers. This is fine for newly created NLBs, but for ones created in older versions of CAPI, security groups _cannot_ be attached, and we should respect those settings still.
Fixes #4790 
**Checklist**:
```release-note
NONE
```
=> :bug: Don't reconcile security groups on NLBs from older versions of CAPA

cloudbuild.yaml, go.mod, hack/tools/go.mod
/kind bug
When doing a recent release of CAPA we encountered an issue with the build of the staging image:
```
/workspace/hack/tools/go.mod:5: unknown directive: toolchain
go: errors parsing go.mod:
```
([source](https://console.cloud.google.com/cloud-build/builds;region=global/1057f825-10b2-44d4-9049-b5381d6b9f16?project=k8s-staging-cluster-api-aws))
Fixes #
We'll need to update the cloud build config on **main** as well.
**Checklist**:
```release-note
Remove toolchain directive and updated build image
```
=> 🐛 fix: staging image build failed due to toolchain directive

cloudbuild.yaml
/kind bug
Cloudbuild is timing out when building staging images. This rollbacks the recent change to the cloud build configuration file.
The update should have been done separartely.
Fixes #
**Checklist**:
```release-note
NONE
```
=> 🐛 chore: rollback changes to cloudbuild file

Makefile, cloudbuild-nightly.yaml, cloudbuild.yaml, docs/triage-party/Dockerfile, go.mod, hack/ensure-go.sh, hack/tools/go.mod, netlify.toml
/kind bug
Changes from the failed releases:
- Including the toolchain directive
- Bumping the GCB image so that it has a newer Go version (that understands the toolchain directive)
- Changing the clusterawsadm build to be inline with CAPI
Relates #4812 
This re-adds some of the changes from #4803 (by @damdo ) with changes to GCB.
**Checklist**:
```release-note
Various changes to the releases process.
```
=> 🐛 [RELEASE-2.3] Changes to release process

Makefile, cloudbuild-nightly.yaml, cloudbuild.yaml, go.mod, hack/tools/go.mod
/kind bug
Changes from the failed releases:
- Including the `toolchain` directive
- Bumping the GCB image so that it has a newer Go version (that understands the `toolchain` directive)
- Changing the clusterawsadm build to be inline with CAPI
Relates #4812 
This will be done for realease-2,3 manually instead of via automatic cherry pick
**Checklist**:
- x ] squashed commits
```release-note
Various changes to the releases process.
```
=> 🐛 fix: changes to release process

Makefile
/kind support
This change will disable the dependency report when generating the release notes. This is a temporary measure whilst we update the branch to use go 1.21.
Relates #4812 
**Checklist**:
```release-note
Disable dependency report generation short term.
```
=> 🌱 chore: disable dependency report

Makefile
/kind support
This disable the dependency report in the release notes. This is a temporary measure after the move to go 1.21.
It will be re-enabled in a future release.
Relates #4812 
**Checklist**:
```release-note
Disable dependency report short term.
```
=> 🌱 chore: disable the dependency report short term

api/v1beta2/awscluster_webhook.go, api/v1beta2/awscluster_webhook_test.go
/kind cleanup
Fixes #
**Checklist**:
```release-note
NONE
```
=> 🌱 Making ControlPlane LoadBalancer immutable for disabled type

controllers/awsmachine_controller.go, controllers/awsmachine_controller_test.go, controllers/awsmachine_controller_unit_test.go, pkg/cloud/interfaces.go, pkg/cloud/scope/cluster.go, pkg/cloud/scope/machine.go, pkg/cloud/scope/machine_test.go, pkg/cloud/scope/managedcontrolplane.go, pkg/cloud/scope/shared.go, pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go, pkg/cloud/services/secretsmanager/secret_test.go, pkg/cloud/services/ssm/secret_test.go, test/mocks/capa_clusterscoper_mock.go
/kind cleanup
Fixes #
**Checklist**:
```release-note
NONE
```
=> 🌱 Expose Cluster Control Plane ref through cluster scope

go.mod, go.sum
/kind bug
Bump rosa dep to fix overflow on non-64bit architectures (i.e. ARM)
Fix #4835 
**Checklist**:
```release-note
fix: bump rosa deps to fix int overflow on non-64bit arch
```
=> 🐛 fix: bump rosa deps to fix int overflow on non-64bit arch

pkg/cloud/services/s3/s3.go, pkg/cloud/services/s3/s3_test.go
/kind bug
The following error is raised when creating a cluster in `us-east-1`:
```sh
E0229 16:32:03.857522 2077184 co[1]ntroller.go:329] "Reconciler error" err=<
failed to reconcile S3 Bucket for AWSCluster openshift-cluster-api-guests/mrb-capa-00-gr9m7: ensuring bucket exists: creating S3 bucket: InvalidLocationConstraint: The specified location-constraint is not valid
status code: 400, request id: 3QSJFBYM9H60N3D6, host id: 
> controller="awscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSCluster" AWSCluster="openshift-cluster-api-guests/mrb-capa-00-gr9m7" namespace="openshift-cluster-api-guests" name="mrb-capa-00-gr9m7" reconcileID="f6b8a66c-108b-4988-9047-0151511fb5bd" 
```
The location …
=> 🐛 fix: s3 bucket in us-east-1 should not set location constraint

exp/controllers/rosamachinepool_controller.go, pkg/cloud/scope/machine.go, pkg/cloud/scope/providerid.go, pkg/cloud/scope/providerid_test.go, pkg/cloud/scope/rosamachinepool.go, pkg/rosa/helpers.go, pkg/rosa/versions.go
/kind feature
`spec.ProviderIDList` is required to fulfill CAPI MachniePool contract so the CAPI controller can match then to Nodes and report readiness.
depends on https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4804
Fixes #
**Checklist**:
```release-note
Reconcile ROSAMachinePool.spec.ProviderIDList
```
=> ✨ ROSA: Reconcile ROSAMachinePool.spec.ProviderIDList

config/crd/bases/infrastructure.cluster.x-k8s.io_rosamachinepools.yaml, exp/api/v1beta2/rosamachinepool_types.go, exp/api/v1beta2/rosamachinepool_webhook.go, exp/api/v1beta2/zz_generated.deepcopy.go, exp/controllers/rosamachinepool_controller.go
/kind feature
Fixes #
**Checklist**:
```release-note
Add additionalSecurityGroups field to ROSAMachinePool
```
=> ✨ ROSA: Add additionalSecurityGroups field to ROSAMachinePool

api/v1beta2/awsmachinetemplate_webhook.go
fix typo from VSphere.
/kind bug
Fixes #
**Checklist**:
```release-note
Fix typo in awsmachinetemplate_webhook logs
```
=> :seedling: Update awsmachinetemplate_webhook.go, fix typo

config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml, controlplane/rosa/api/v1beta2/doc.go, controlplane/rosa/api/v1beta2/rosacontrolplane_types.go, controlplane/rosa/api/v1beta2/rosacontrolplane_webhook.go, controlplane/rosa/api/v1beta2/zz_generated.deepcopy.go, controlplane/rosa/api/v1beta2/zz_generated.defaults.go, controlplane/rosa/controllers/rosacontrolplane_controller.go, docs/book/src/crd/index.md, templates/cluster-template-rosa-machinepool.yaml, templates/cluster-template-rosa.yaml
/kind feature
Adding new API fields to ROSAControlPlane:
- AdditionalTags,
- EtcdEncryptionKMSArn
-  EndpointAccess
Fixes #
**Checklist**:
```release-note
Add new fields to ROSAControlPlane - additionalTags, etcdEncryption, endpointAccess
```
=> ✨Add new fields to ROSAControlPlane - additionalTags, etcdEncryption, endpointAccess

.github/dependabot.yml
/kind cleanup
Fixes #
**Checklist**:
```release-note
NONE
```
=> :seedling: Align dependabot config with upstream cluster-api

pkg/cloud/scope/cluster.go, pkg/cloud/scope/elb.go, pkg/cloud/services/elb/loadbalancer.go
/kind bug
Secondary control plane load balancer is created using same schema of primary, failing in some scenarios like primary is created as private (internal) and secondary external (internet-facing) - it will result in the external LB w/ private subnets.
**Checklist**:
```release-note
Fix discovered subnets for additional Load Balancers ("SecondaryControlPlaneLoadBalancer") when it is internet-facing.
```
=> 🐛 fix: additional control plane LBs must use correct schema/subnets

pkg/cloud/services/eks/nodegroup.go
Hello all,
/kind bug
When using a custom AMI with a launch template, node group upgrades get stuck with the following error message:
```
E0227 15:07:47.415572       1 controller.go:329] "Reconciler error" err=<
failed to reconcile machine pool for AWSManagedMachinePool dev/pocg1eks80-mmp-infra: failed to reconcile nodegroup version: failed to update EKS nodegroup: InvalidParameterException: Launch template details can't be null for Custom ami type node group
{
RespMetadata: {
StatusCode: 400,
RequestID: "e8b04ccf-56aa-4bab-b313-0f4b25137e5c"
},
Message_: "Launch template details can't be null for Custom ami type node group"
}
> controller="awsmanagedmachinepool" controllerGroup="infrastructure.cluster.x-k8s.io" …
```
=> :bug: fix upgrade of managed node groups using custom AMIs

config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml, controlplane/rosa/api/v1beta2/rosacontrolplane_types.go, controlplane/rosa/controllers/rosacontrolplane_controller.go, go.mod, go.sum
/kind feature
It allow long cluster name and domain prefix
Fixes #
**Checklist**:
- [ X] squashed commits
```release-note
NONE
```
=> ✨ ROSA: support long cluster name

config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml, controlplane/rosa/api/v1beta2/rosacontrolplane_types.go, controlplane/rosa/api/v1beta2/rosacontrolplane_webhook.go, controlplane/rosa/controllers/rosacontrolplane_controller.go, docs/book/src/crd/index.md
/kind feature
Add new field 'auditLogRoleARN' to ROSAControlPlane to support audit log forwarding to CloudWatch.
Fixes #
**Checklist**:
```release-note
Add new field 'auditLogRoleARN' to ROSAControlPlane
```
=> ✨ ROSA: Support audit log forwarding

config/crd/bases/infrastructure.cluster.x-k8s.io_rosamachinepools.yaml, exp/api/v1beta2/rosamachinepool_types.go, exp/controllers/rosamachinepool_controller.go, go.mod, go.sum
/kind feature
Fixes #
**Checklist**:
```release-note
NONE
```
=> ✨ Add nodeDrainGracePeriod for RosaMachinePool

config/crd/bases/infrastructure.cluster.x-k8s.io_rosamachinepools.yaml, docs/book/src/crd/index.md, exp/api/v1beta2/rosamachinepool_types.go, exp/api/v1beta2/rosamachinepool_webhook.go, exp/api/v1beta2/zz_generated.deepcopy.go, exp/controllers/rosamachinepool_controller.go, exp/controllers/rosamachinepool_controller_test.go
/kind feature
/kind api-change
- Add `additionalTags` API field to ROSAMachinePool
- use the correct type `metav1.Duration` for `NodeDrainGracePeriod` field
- fixed reconcileProviderIDList() listing terminated/stopped instances
Fixes #
**Checklist**:
```release-note
Add `additionalTags` API field to ROSAMachinePool
```
=> ✨ ROSA: Add additionalTags API field to ROSAMachinePool

config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml, controlplane/rosa/api/v1beta2/rosacontrolplane_types.go, controlplane/rosa/controllers/rosacontrolplane_controller.go
/kind feature
Fixes #
**Checklist**:
```release-note
add `ProvisionShardID` API field to ROSAControlPlane
```
=> ✨ ROSA: Add ProvisionShardID API field to ROSAControlPlane

controlplane/rosa/controllers/rosacontrolplane_controller.go
/kind bug
In [PR-4857](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4857)  the domainPrefix has been mistakenly removed. setting it back 
Fixes #
**Checklist**:
```release-note
None
```
=> 🐛 ROSA: Fix domainPrefix not being set

api/v1beta2/network_types.go, pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/elb/loadbalancer_test.go
/kind bug
This change intents to synchronize w/ CLB the health check attributes for
API LB, and use the correct health check path when using HTTP or HTTPS.
The following target group health check attributes for ELBv2
are setting based in the CLB configuration for all protocols:
- interval: current(30) want(10)
- timeout: current(10) want(5)
- health threshold count: current(5) want(5)
- unhealthy threshold count: current(2) want(3)
When using HTTP or HTTPS, the following attributes will be fixed:
- path: current("/") want("/readyz")
*'current' is the default values set by AWS, 'want' is the value set
in the CLB.
N/A
**Checklist**: …
=> 🐛 Allow overriding health check endpoint protocol

pkg/cloud/identity/identity.go, pkg/cloud/identity/identity_test.go, pkg/cloud/scope/session.go, pkg/cloud/scope/session_test.go
/kind bug
When creating  `aws.Config` without specifying a region the AWS SDK will by default call AWS commercial partition (known as just `aws`) .
If you wanna use a different AWS partition (https://docs.aws.amazon.com/whitepapers/latest/aws-fault-isolation-boundaries/partitions.html  and https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html )   like for example `aws-cn` and provide static access keys to the user that is in `aws-cn` partition then the controller fails with error since  AWS SDK tries to validate the access keys in `aws` commercial partition.
```
> controller="awscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSCluster" AWSCluster="org-giantswarm/galaxy" …
```
=> :bug: Create a `aws.Config` with region to be able to work different AWS partition (like gov cloud or china AWS partition)

main.go
/kind feature
Add flags on manager to configure leaseDuration, renewDeadline and RetryPeriod for leader election. Set defaults based on cluster-api. These flags can be useful when the cluster runs on a relatively slow etcd.
**Checklist**:
```release-note
add flags to manager for leaderElection timeouts
```
=> :sparkles: Add flags for leaderElection timeouts

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_allow_assume_role.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml, controllers/awsmachine_controller_test.go, pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go
When a VPC sets a DHCPOption's domain-name with a custom DNS name, it's being ignored. Now, with this PR, ensure that during instance creation, the controller checks the DHCPOptions and sets the proper PrivateDNSName.
Signed-off-by: Juan Manuel Parrilla Madrid <jparrill@redhat.com>
/kind bug
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1691
Fixes #[OCPBUGS-29391](https://issues.redhat.com/browse/OCPBUGS-29391)
**Checklist**:
```release-note
NONE
```
=> :bug: fix: Fix instance PrivateDNSName when domain-name is set in dhcpOpts

pkg/cloud/services/s3/s3.go, pkg/cloud/services/s3/s3_test.go
/kind bug
**What this PR does / why we need it**: 
The `s3.HeadObject` API call can return "NotFound" when either the bucket or the object does not exist (as opposed to the more descriptive `s3.ErrCodeNoSuchKey` or `s3.ErrCodeNoSuchBucket`).
This would cause the machine controller to loop indefinitely trying to delete an already deleted object but failing:
```
E0316 16:37:08.973942     366 awsmachine_controller.go:307] "unable to delete machine" err=<
deleting bootstrap data object: deleting S3 object: NotFound: Not Found
status code: 404, request id: 5Z101DW1KN380WTY, host id: tYlSi9K38lBkIsr2DNf/xFfgDuFaVfeUmpscXdljiMZC5iRxPIDuXSLwHJwdFnosYCfi7Bih25GaDpVAbSq4ZA==
>
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes …
=> :bug: fix: s3: fix bucket object not found

pkg/cloud/scope/managedcontrolplane.go, pkg/cloud/scope/sg.go, pkg/cloud/services/securitygroup/securitygroups.go, pkg/cloud/services/securitygroup/securitygroups_test.go
/kind bug
Makes sure that ingress rules from all load balancers are created.
Fixes #4865 
**Checklist**:
```release-note
Fixed a bug where ingress rules specified in the secondary load balancer were not applied to the security group.
```
=> :bug: fix: create ingress rules from all load balancers

pkg/cloud/services/network/routetables.go, pkg/cloud/services/network/routetables_test.go
/kind bug
This fix creates an error handler when the route table reconcile loop returns error when creating routes. It will prevent left the route table behind.
Currently this issue is triggered when an invalid route entry is added, creating a new stale table every new reconciliation, growing to hundreds in a few minutes. This is one example triggering the issue (a subset of Carrier Gateway support adding in #4901):
~~~sh
E0403 01:04:42.329759 1157154 awscluster_controller.go:327] "failed to reconcile network" err=<
failed to create route in route table "rtb-067f352c09371fe71": {
CarrierGatewayId: "cagw-0ac129c044b2cd1b6",
DestinationCidrBlock: "0.0.0.0/0"
}: MissingParameter: The request must contain exactly one of …
=> 🐛 fix/network/rtb: delete rtb handling err when failed to create routes

api/v1beta1/awscluster_conversion.go, api/v1beta1/awsmachine_conversion.go, api/v1beta1/zz_generated.conversion.go, api/v1beta2/awsmachine_types.go, api/v1beta2/types.go, config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml, pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go
/kind feature
Adds support for users to specify the partition number (`PlacementGroupPartition`) of a placement group, identified by `PlacementGroupName` while creating instances.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4870
**Checklist**:
```release-note
Add support to specify PlacementGroupPartition of placement group in instances.
```
=> :sparkles: Add support to specify PlacementGroupPartition of placement group

pkg/cloud/services/secretsmanager/secret_fetch_script.go
/kind bug
When the bootstrap script runs, first call to the SecretsManager can fail in our environment. This PR adds a retry logic to the bootstrap script, if the first request fails it will retry again 10 times with a 10 second timeout.
Fixes #
**Checklist**:
```release-note
Retry getting and deleting user data from SecretsManager in the bootstrap script in case of request failure.
```
=> 🐛Retry fetching user data from secretmanager if first request fails

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_allow_assume_role.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml, controllers/awsmachine_controller_test.go, pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go
This is a manual backport from https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4841
```release-note
Fix instance PrivateDNSName when domain-name is set in dhcpOpts
```
=> [release-2.4] 🐛 fix: Fix instance PrivateDNSName when domain-name is set in dhcpOpts

pkg/cloud/services/network/subnets.go, pkg/cloud/services/network/subnets_test.go
/kind bug
The subnet information from unmanaged subnets, like the Availability Zone name discovered when reconciling subnets, is not updated for additional subnets when the are failures to tag subnets for the preceding subnets.
For example, given subnetId1 and subnetId2, if the subnet tag failed when setting tags on subnetId1, the subnetId2 will not be discovered and attributes not be correctly set.
This change enforces subnet updates before trying to apply tags and does not skip the loop when checking existing subnets.
Additionally, a new option was added to the unit for reconcileSubnets(), allowing to ensure expected SubnetSpec attributes from Subnets{} post reconciliation.
References: …
=> 🐛 fix: update network subnets prio tag failures

go.mod, go.sum, pkg/cloud/services/eks/mock_eksiface/eksapi_mock.go, pkg/cloud/services/s3/mock_s3iface/s3api_mock.go, pkg/cloud/services/secretsmanager/mock_secretsmanageriface/secretsmanagerapi_mock.go, pkg/cloud/services/ssm/mock_ssmiface/ssmapi_mock.go, test/mocks/aws_ec2api_mock.go, test/mocks/aws_elbv2_mock.go
/kind cleanup
Requested change to reduce the size of #4906
Fixes #
**Checklist**:
```release-note
Bump aws-sdk-go to v1.51
```
=> 🌱 bump aws sdk version

pkg/cloud/services/network/routetables.go, pkg/cloud/services/network/routetables_test.go
/kind cleanup
The flow for route discover and creation is reviewed to provide flexibility of route entry inputs for routes discovered by each subnet.
This change is a subset of Wavelength zone (#4874 , #4901) feature which will introduce requirements when discovering gateways of public and private subnets.
The refact should not change the existing flow.
**Which issue(s) this PR fixes**  None
**Checklist**:
```release-note
NONE
```
=> 🌱 refactor route discover/creation flow

api/v1beta2/network_types.go, config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml, pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/elb/loadbalancer_test.go
/kind bug
**What this PR does / why we need it**: 
Using the LB's name as part of the Target Group's name has the potential of causing failures since both have a limit of 32 characters. For example, using rdossant-installer-04-wn9qs-int as the LB name, will result in the following error
```
time="2024-04-22T22:54:32Z" level=debug msg="\tfailed to create target group for load balancer: ValidationError: Target group name 'rdossant-installer-04-wn9qs-int-6443' cannot be longer than '32' characters"
```
Fixes #4947
**Checklist**:
```release-note
Revert a …
```
=> :bug: Fix Target Group's name exceeding 32 characters

Makefile
/kind support
Opening this as per discussion at: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4949#issuecomment-2072971287
This PR starts publishing the nightly artifacts to the k8s-staging-cluster-api-aws bucket, instead of to the artifacts.k8s-staging-cluster-api-aws.appspot.com.
The latter is the backing bucket of the google container registry and will go away eventually when we migrate from the container registry to the artifact registry. It was never meant to be used to store files that are not part of container images.
Please note that the new location has a retention of 60 days (as of now). But that should be okay for nightly manifests.
```release-note
NONE
```
=> 🌱 Publish nightly manifests to the new staging bucket

api/v1beta2/awscluster_webhook_test.go, controllers/awscluster_controller_test.go, controllers/awscluster_controller_unit_test.go, controllers/awsmachine_controller_test.go, controllers/awsmachine_controller_unit_test.go, controlplane/eks/controllers/awsmanagedcontrolplane_controller_test.go, exp/controlleridentitycreator/awscontrolleridentity_controller_test.go, exp/instancestate/awsinstancestate_controller_test.go, exp/instancestate/helpers_test.go, test/e2e/shared/aws.go, test/e2e/shared/suite.go, test/e2e/suites/managed/addon_helpers.go, test/e2e/suites/managed/control_plane_helpers.go, test/e2e/suites/managed/machine_deployment_helpers.go, test/e2e/suites/managed/machine_pool_helpers.go, test/e2e/suites/unmanaged/helpers_test.go, test/e2e/suites/unmanaged/unmanaged_functional_test.go
/kind cleanup
In Gomega, when Eventually().Should(<bool>) fails, the failure returns a 
```
[FAILED] Timed out after 1200.001s.
Expected
<bool>: false
to be true
```
Which takes a bit of time to then debug further.
There is a more immediate way to add some context to this, by adding a failure message to the should like so: `.Should(x, "message")`. This PR does this for all the current occurrences of this construct.
```release-note
test: add failure message to Eventually().Should(bool) everywhere
```
=> 🌱 test: add failure message to Eventually().Should(bool) everywhere

api/v1beta2/network_types.go, pkg/cloud/scope/shared.go, pkg/cloud/scope/shared_test.go
/kind feature
Not sure if this is a bug or a feature. I don't think it's intended for nodes to land on the subnets intended for CNI, but if it is then I can also change this PR to add another `AZSubnetType`.
**Checklist**:
```release-note
Exclude CNI subnets when creating EKS NodeGroup with private availability zone subnet type.
```
=> ✨ Filter CNI subnets when creating EKS NodeGroup

docs/book/src/SUMMARY_PREFIX.md, docs/book/src/topics/rosa/index.md, docs/book/src/topics/rosa/support.md
documentation
Fixes #
**Checklist**:
```release-note
None
```
=> 📖 ROSA: Add support.md to the doc

pkg/cloud/services/eks/cluster.go
/kind bug
EKS does not allow for both a VPC config update and a logging update in the same API call. If both of these changes are applied to the spec at once, then the AWSManagedControlPlane will fail to reconcile.
Addresses the restriction in the EKS API by separating logging and vpc config updates into two separate steps.
Fixes #3553
**Checklist**:
```release-note
Separate Control Plane logging and VPC Config updates to ensure both can be applied
```
=> 🐛 fix: separate control plane logging and vpc config updates

controlplane/rosa/controllers/rosacontrolplane_controller.go, exp/controllers/rosamachinepool_controller.go, pkg/utils/utils.go
/kind bug
Fix delete rosaControlPlane and rosaMachinePool
Fixes #4936
**Checklist**:
```release-note
None
```
=> 🐛 ROSA: Fix issue-4936 delete rosaMachinePool and rosaControlPlane

controlplane/rosa/controllers/rosacontrolplane_controller.go, go.mod
/kind bug
Fixes an issue when manually deleting the bootstrap-kubeconfig secret
Fixes #
**Checklist**:
```release-note
NONE
```
=> 🐛 ROSA: Generate unique username for BreakGlassCredential requests

config/crd/bases/infrastructure.cluster.x-k8s.io_rosamachinepools.yaml, exp/api/v1beta2/rosamachinepool_types.go
/kind bug
The PR change the machinePool.AutoRepair default value to true as the default value of nodePool.AutoRepair at the OCM API [here](https://api.openshift.com/#/default/get_api_clusters_mgmt_v1_clusters__cluster_id__node_pools) is true. 
Fixes #
**Checklist**:
- [X ] squashed commits
- [ X] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
```release-note
Changing the ROSAMachienPool AutoRepair default value to true. 
```
=> 🐛 ROSA: Fix autoRepair default value

pkg/cloud/services/securitygroup/securitygroups.go, pkg/cloud/services/securitygroup/securitygroups_test.go
/kind bug
Ingress rules for the CP load balancer need to be processed like rules for CP instances. When user only specifies a source security group role, the controller should assign a proper ID to the ingress rule so it's gets assigned properly.
Fixes #
**Checklist**:
```release-note
Apply the same set of rules for processing all custom ingress rules
```
=> 🐛Apply the same set of rules for processing all custom ingress rules

controllers/awscluster_controller_test.go, controllers/helpers_test.go, pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/elb/loadbalancer_test.go, test/helpers/matchers.go
Signed-off-by: Nolan Brubaker <nolan@nbrubaker.com>
/kind bug
If a load balancer is created but the calls to create a target group or
listener fails (for example, due to a rate limit), creating the group or
listener is never retried. This results in a load balancer that's
created, but there is nothing attached to it, making it useless.
This change reconciles the target groups and listeners as their own entities, so that even if they fail to create initially, we'll keep retrying.
Fixes #5002
**Checklist**: …
=> 🐛 Reconcile target groups and listeners as their own entities

exp/api/v1beta2/rosamachinepool_webhook.go, exp/controllers/rosamachinepool_controller.go, exp/controllers/rosamachinepool_controller_test.go
/kind bug
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4998 introduced new `UpdateConfig` field to ROSAMachinePool which is causing unnecessary update calls. related to https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4977
Fixes #
**Checklist**:
```release-note
NONE
```
=> 🐛 ROSA: fix ROSAMachinePool.Spec.UpdateConfig causing unnecessary update calls

pkg/cloud/services/elb/loadbalancer.go
/kind bug
Fixes an error where capa will create duplicate target groups and listeners.
Fixes #5015 
**Checklist**:
```release-note
Fixes target group and listeners creation for v2 Load Balancers.
```
=> 🐛 Fix creation of target groups and listeners in the reconcile loop

api/v1beta1/zz_generated.conversion.go, api/v1beta2/awscluster_webhook.go, api/v1beta2/awscluster_webhook_test.go, api/v1beta2/network_types.go, config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml, pkg/cloud/services/securitygroup/securitygroups.go, pkg/cloud/services/securitygroup/securitygroups_test.go
/kind feature
This PR will allow using nat gateway IPs as sources in ingress rules. In my setup, I need machines to be able to connect to the load balancer through a certain port and I would like the load balancer to only accept traffic for this port from my machines. From the load balancer point of view the connection is made from nat gateway IPs so the CAPA API has to have a setting for this.
Fixes #
**Checklist**:
```release-note
Add natgatewayips as source for ingress rules
```
=> ✨ Add natgatewayips as source for ingress rules

docs/book/src/topics/eks/prerequisites.md, docs/book/src/topics/iam-permissions.md
📖 Fixes typos in the eks and iam docs
None
None
**Checklist**:
```release-note
NONE
```
=> 📖 fix docs typos

exp/controllers/awsmachinepool_controller_test.go, pkg/cloud/services/ec2/launchtemplate.go
/kind bug
I was the author of those tests. They shared one envtest and namespace by mistake, leading to conflicts. After fixing this, luckily, only one new problem appeared which the conflicting tests previously couldn't catch: the reconciliation would return after setting `AWSMachinePool.status.launchTemplateVersion`, but can just continue (else we would have to call 3x `reconcileNormal` in the test to make it all happen). One test was checking for something it didn't even need (again: `AWSMachinePool.status.launchTemplateVersion`).
n/a
**Special notes for your …
=> 🐛 Fix subtests running in same environment and reconciliation bug which was not covered because of that

controllers/awscluster_controller_test.go, controlplane/eks/controllers/awsmanagedcontrolplane_controller_test.go, pkg/cloud/services/network/subnets.go, pkg/cloud/services/network/subnets_test.go
The "shared" value will be used for unmanaged subnets.
/kind bug
Tag managed subnets with "kubernetes.io/cluster/<clusterID>: owned" tag.
Fixes #5050
**Checklist**:
```release-note
Fix managed subnet tagging with "owned" value for "kubernetes.io/cluster/<clusterID>" tag.
```
=> 🐛 subnets: use "owned" k8s tag value for managed subnets.

pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go
/kind feature
ENIs and EBS Volumes that are created as part of instance creation are not being tagged with the tags that are applied to the instance. Since these resources are created as part of the AWS API call to create the instance itself, it follows that the same tags would be applied at creation time. AWS allows for restrictions against CreateTags as a standalone API call vs CreateTags as part of a call to the RunInstances API call. This change allows restrictions against standalone CreateTags calls against existing resources, while still allowing the creation of tags at on the resource.
**Checklist**:
```release-note
- EBS Volumes and ENIs are now tagged when …
```
=> ✨ Ensure Volumes and Network Interfaces are also tagged when created as part of instance creation

.goreleaser.yaml
This change only updates the binary naming template to match previous
releases. There is still an issue of building the same binary twice
under two different names.
/kind bug
Releases prior to implementing goreleaser used the `clusterawsadm-{{ .Os }}-{{ .Platform}}` format. See [v2.4.0](https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v2.4.0) as an example of this format.
This does _not_ address the issue of building the same binary twice. We still need to address whether we would like to use `clusterctl-aws` or `clusterawsadm` going forward. ~~I will create an issue to track this.~~ See #5056 for tackling the double binary problem.
**Which issue(s) this PR fixes** *(optional, in …
=> :bug: Update filenames for released binaries

docs/book/src/topics/eks/creating-a-cluster.md, pkg/cloud/services/eks/config.go, pkg/cloud/services/eks/config_test.go, test/e2e/shared/suite.go
/kind feature
**What this PR does / why we need it**: Cluster Autoscaler can not mount and consume the [Cluster API Kubeconfig](https://cluster-api-aws.sigs.k8s.io/topics/eks/creating-a-cluster.html?highlight=kubeconfig#cluster-api-capi-kubeconfig) because the secret contents are refreshed every ten minutes, and no API Machinery exists to reload a kubeconfig safely.
Initially, I attempted solve this in the Cluster Autoscaler: https://github.com/kubernetes/autoscaler/issues/4784 - [However meeting with SIG APIMachinery on Nov 1 2023](https://youtu.be/JVs79gb7qJE), the SIG cautioned against this approach and advised splitting the token out from the kubeconfig, [as there is existing machinery to reload a token file …
=> ✨ Add separate eks kubeconfig secret keys for the cluster-autoscaler

controllers/awsmachine_controller.go, pkg/cloud/services/elb/errors.go
/kind bug
The AWS docs [1] state that to register an instance with the Load Balancer target groups, the instance must be running. Currently, CAPA tries to register it while it's still pending, causing the following error:
```
0314 22:24:18.512176  701419 awsmachine_controller.go:605] "failed to reconcile LB attachment" err=<
[could not register machine to load balancer: could not register control plane instance "i-039bb22b1e8df7c99" with load balancer: failed to register instance with target group 'mrb-capa-67-d2pfx-int-22623': InvalidTarget: The following targets are not in a running state and cannot be registered: 'i-039bb22b1e8df7c99'
status code: 400, request id: 17514354-77ac-42b1-a882-489760563bbd, could not …
```
=> 🐛 awsmachine: only register machine to LB when it's running

docs/book/src/topics/eks/pod-networking.md, go.mod, pkg/cloud/services/awsnode/cni.go
/kind bug
Recently, AWS changed the way VPC CNI is installed from manifest apply to managing it via Helm (ref: https://github.com/aws/amazon-vpc-cni-k8s/issues/2763#issuecomment-1908510232). This makes `AWSManagedControlPlane.Spec.VpcCni.Disable` flag obsolete due to the `app.kubernetes.io/managed-by: Helm` condition in deleteCNI flow.
This PR removes that condition to make the flag functional.
Fixes # [4743](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4743)
For users replacing the default VPC CNI with their …
=> :bug: Remove Helm condition for AWS VPC CNI deletion

api/v1beta2/types.go, docs/book/src/topics/eks/pod-networking.md, pkg/cloud/services/awsnode/cni.go
/kind feature
Small change to prefix the label that prevents deletion of the VPC CNI to be prefixed with an CAPA prefix. This is just to ensure that we make it as specific to CAPA as possible.
Fixes #
This is a follow-up to #5009 . I thought about this after it merged.
@jas-nik - would love to get your thoughts on making the label name more specific to CAPA.
**Checklist**:
```release-note
Change prevenet deletion label to be specific to CAPA.
```
=> 🌱 chore: change name of prevent deletion label

.github/workflows/dependabot.yml, .github/workflows/pr-verify.yml
/kind bug
Since moving to the Kubernetes GitHub Enterprise account, our GitHub Actions jobs haven't been able to write their status to the API.
This results in the following error on all jobs that run within GitHub Actions:
```
Error: unable to create check run: POST https://api.github.com/repos/kubernetes-sigs/cluster-api-provider-aws/check-runs: 403 Resource not accessible by integration []
```
This is similar to the [permissions carried by upstream CAPI](https://github.com/kubernetes-sigs/cluster-api/blob/main/.github/workflows/pr-verify.yaml#L7-L8)
```release-note
NONE
```
=> Add permissions to the GitHub Actions token

templates/cluster-template-flatcar.yaml
Backport the changes from https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/37e781454699bc76186ac75e19325e3a9b1b065d to the Flatcar template.
Without this change, the Flatcar based cluster will not reach a fully provisioned state, as Calico or any other CNI cannot be deployed, as all the worker nodes are tainted with `uninitialized` label.
/kind bug
```release-note
Update Flatcar template to use external CCM.
```
=>  :bug: Use external CCM in Flatcar template

config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml, exp/api/v1beta1/conversion.go, exp/api/v1beta1/zz_generated.conversion.go, exp/api/v1beta2/awsmachinepool_webhook.go, exp/api/v1beta2/types.go, exp/api/v1beta2/zz_generated.deepcopy.go, pkg/cloud/services/ec2/launchtemplate.go
/kind feature
Adding non root volumes is already possible for the control-plane by [specifying them in the AWSMachineTemplate](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/63c66352579ef08bd365abd529e1924cde6f0d26/api/v1beta2/awsmachine_types.go#L143), but only the RootVolume can be specified for AWSMachinePools. This PR adds this feature for the machine pools as well.
**Checklist**:
```release-note
Add NonRootVolumes to AWSMachinePool launch template. 
```
=> ✨ Add non root volumes to AWSMachinePool

pkg/cloud/services/elb/loadbalancer.go
Secret regions don't yet support security groups for NLBs.
/kind bug
C2S/SC2S regions do not support security groups on Network load balancers.
Fixes #5029 
**Checklist**:
```release-note
Fix: do not attach security groups for Network Load Balancers in secret regions.
```
=> 🐛: elbv2: skip adding security groups to NLB in secret regions

controllers/awscluster_controller.go
/kind bug
The ready condition never gets set. This was likely just a minor oversight in the initial implementation. I noticed because we had a temporary failure where CAPA didn't remove the non-ready mark for the condition after having successfully reconciled the bucket later.
I left out amending any test since there seems to be no full reconciliation test for bucket-backed cluster creation.
**Checklist**:
```release-note
Mark `S3BucketCreated` condition ready after successful reconciliation
```
=> 🐛 Mark `S3BucketCreated` condition ready after successful reconciliation

test/e2e/data/e2e_conf.yaml
**What type of PR is this?**:
I observed some tests try to pull in AMIs that are not available according to this https://cluster-api-aws.sigs.k8s.io/topics/images/built-amis
it bumps them up to 1.27.0 and beyond.
Fixes #
**Checklist**:
```release-note
NONE
```
=> :bug: fix: bumps ci versions to more recent versions

controllers/awsmachine_controller.go, controllers/awsmachine_controller_unit_test.go, pkg/cloud/services/ec2/eip.go, pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go, pkg/cloud/services/interfaces.go, pkg/cloud/services/mock_services/ec2_interface_mock.go, pkg/cloud/services/network/eips.go
/kind bug
The instance creation flow is creating by default EIP to instances even if the BYO IP flow is set. BYO IPv4 creates and associates the EIP to instance after it is created, preventing paying for additional EIP (amazon-provided) when creating the instance when the BYO IPv4 Pool is defined to be used by the machine.
Furthermore, the fix provides additional checks to prevent duplicated EIP in the BYO IP reconciliation loop. The extra checks include running the EIP association many times, while the EIP is already associated, and failures in the log when running the EIP association prematurely - when the instance isn't ready, Eg ec2 in pending state. …
=> 🐛 ec2/byoip: fix EIP leak when creating machine

.github/workflows/build-ami.yml
/kind feature
This adds a GitHub workflow that can be invoked manually to run image-builder to build and publish a new CAPA AMI to the community owned CNCF account.
Relates #5131
Relates #4984
**Checklist**:
```release-note
New workflow to publish CAPA AMIs
```
=> ✨ chore: workflow to build and publish AMIs

.github/workflows/build-ami.yml
/kind cleanup
Change the AMI build workflow to run the matrix entries sequentially instead of all parallel. This should stop them getting cancelled due to exceeding resource limits.
Fail fast has also been set to false so that if one of the metrix jobs fails the others continue.
Fixes #
**Checklist**:
```release-note
NONE
```
=> 🌱 fix: run ami builds sequentially

.github/workflows/build-ami.yml
/kind bug
This removes rhel-8 from the image builder workflow as there are issues with the target currently with target in image-builder for AMIs.
Fixes #
This is only a temporary solution.
**Checklist**:
```release-note
NONE
```
=> 🌱 chore: remove rhel from image build workflow

.github/workflows/build-ami-varsfile.yml, .github/workflows/build-ami.yml
/kind feature
A new GitHub Actions workflow that can be used to build a AMI using a packer vars file passed in as a string. This is in addition to the existing workflow that doesn't allow much customization.
This also pins the version of image-builder we use when building. The version can be changed via inputs to the workflow.
Relates #5131
Relates #4984 
**Checklist**:
```release-note
New AMI building workflow that allows a packer vars file to be passed in.
```
=> 🌱 feat: build amis with vars file

templates/cluster-template-machinepool.yaml, templates/cluster-template.yaml
/kind support
Aligns this template with the others which already have the working permissions set.
**Checklist**:
```release-note
NONE
```
=> 🌱 Fix cloud-controller-manager ClusterRole's service account permissions in templates

pkg/cloud/services/eks/roles.go
/kind bug
The validating webhook https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/abe918cfe1038c714792860b23632e38c7e0438f/exp/api/v1beta2/awsfargateprofile_webhook.go#L83-L90 uses the Fargate profile's `spec.clusterName` in order to generate the role name.
This differs from the EKS role service which instead uses the `scope.KubernetesClusterName()`.
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/abe918cfe1038c714792860b23632e38c7e0438f/pkg/cloud/services/eks/roles.go#L304-L309
The problem comes from the scenario where the cluster resource is named one thing (i.e. `foo`) but was created in EKS using some prefixes (i.e. `default_foo-control-plane`). If this is the case, the CAPA …
=> 🐛 Standardize cluster name in Fargate role names to avoid errors on mismatch between Cluster CR and EKS cluster name

OWNERS, OWNERS_ALIASES
/kind cleanup
This updates the owners (and aliases) to reduce unecessary notifcations and review requests.
Fixes #
**Checklist**:
```release-note
NONE
```
=> 🌱 chore: update owners

templates/cluster-template-flatcar.yaml
/kind support
This moves, quotes and formats YAML to make the diff between the two templates close to zero. `ClusterRole/ebs-csi-node` and permissions for `ClusterRole/cloud-controller-manager` are added.
**Checklist**:
```release-note
NONE
```
=> 🌱 Align `cluster-template.yaml` and `cluster-template-flatcar.yaml`

README.md, cmd/clusterawsadm/ami/helper.go, cmd/clusterawsadm/cmd/ami/common/copy.go, cmd/clusterawsadm/cmd/ami/common/encryptedcopy.go, cmd/clusterawsadm/cmd/ami/list/list.go, controllers/awsmachine_controller_test.go, docs/book/src/SUMMARY_SUFFIX.md, docs/book/src/crd/index.md, docs/book/src/development/amis.md, docs/book/src/topics/images/amis.md, docs/book/src/topics/images/built-amis.md, pkg/cloud/services/ec2/ami.go, pkg/cloud/services/ec2/instances_test.go, pkg/cloud/services/userdata/bastion.go, test/e2e/data/e2e_conf.yaml, test/e2e/shared/defaults.go, test/e2e/suites/unmanaged/helpers_test.go, test/e2e/suites/unmanaged/unmanaged_CAPI_clusterclass_test.go, test/e2e/suites/unmanaged/unmanaged_CAPI_test.go, test/e2e/suites/unmanaged/unmanaged_functional_test.go
/kind bug
Updates to the project to start using the new CNCF owned AWS account for publishing AMIs. The code has had the old VMWare account removed and the new account ID added. Additionally the docs have been updated including clarifying that the public AMIs should only be used for non-production usage.
Relates #5131
Relates #4984 
Fixes #5161 
A new GitHub Actions workflow (see #5138 ) can be invoked to publish new images. Also #5169 will be done as a follow-up.
**Checklist**:
```release-note
A …
```
=> ✨refactor: update to use new community ami account

controllers/awscluster_controller.go, controllers/awscluster_controller_unit_test.go, controllers/helpers_test.go, pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/elb/loadbalancer_test.go
/kind bug
Using DNS name resolution as a way to check the load balancer is working can cause problems that are dependent on the host running CAPA. In some systems, the DNS resolution can fail with very large TTLs cached DNS responses, causing very long provisioning times.
Instead of DNS resolution, let's use the AWS API to check for the load balancer "active" state. Waiting for resolvable DNS names should be left for the clients to do.
Fixes #5032 
This is an alternative approach to …
=> 🐛: elbv2: wait for LB active state instead of resolving DNS name

pkg/eks/addons/types.go, pkg/eks/addons/types_test.go
/kind bug
Currently a configuration change of an AddOn is not reconciled by capa and needs manual fixing (e.g. in the AWS console), this PR fixes the behaviour. The PR also adds basic tests for the IsEqual function and its expected results.
Fixes #5086 
**Checklist**:
```release-note
Fix: Include AddOn configuration and conflict resolution for reconciliation
```
=> 🐛 fix(addons): add configuration to IsEqual cmp

pkg/cloud/tags/tags.go, pkg/cloud/tags/tags_test.go
/kind bug
Tags that start with `aws:` are considered internal AWS tags and can't be add or removed.
Fixes #5120
**Checklist**:
```release-note
Filter out AWS internal tags when reconciling AWS infra
```
=> 🐛 Filter out AWS internal tags when reconciling

config/crd/patches/webhook_in_awsclustercontrolleridentities.yaml, config/crd/patches/webhook_in_awsclusterroleidentities.yaml, config/crd/patches/webhook_in_awsclusters.yaml, config/crd/patches/webhook_in_awsclustertemplates.yaml, config/crd/patches/webhook_in_awsmachinepools.yaml, config/crd/patches/webhook_in_awsmachines.yaml, config/crd/patches/webhook_in_awsmachinetemplates.yaml, config/crd/patches/webhook_in_awsmanagedcontrolplanes.yaml, config/crd/patches/webhook_in_eksconfigs.yaml, config/crd/patches/webhook_in_eksconfigtemplates.yaml
Description shamelessly lifted from [the equivalent PR on Cluster API](https://github.com/kubernetes-sigs/cluster-api/pull/10972).
/kind bug
Starting with Kubernetes 1.31 it won't be possible anymore to continuously apply CRDs that are setting caBundle to an invalid value (in our case `Cg==`). The solution is to simply drop the caBundle field (it was never actually required by kube-apiserver).
For more details see: https://kubernetes.slack.com/archives/C0EG7JC6T/p1722441161968339
Fixes #5195 
There are other references in the …
=> :bug: Remove placeholder CA bundle

pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go
/kind bug
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4541 I introduced a change to allow subnets from other subnets to be returned from the AWS describe subnets query. However, the sorting is subtly bugged. `func(i, j int) bool {` is supposed to return true when i is _less_ than j, or should be ordered first. We want any subnets with the cluster VPC to be "less" than to sort the strings.
The existing implementation (which I wrote :disappointed: ) does not do that. `strings.Compare(*filtered[i].VpcId, clusterVPC)` returns `0` (string match) or `1` if the clusterVPC > VPCID, or `-1` if VPCID < clusterVIPC. The second comparison `strings.Compare(*filtered[j].VpcId, clusterVPC)` is the same. However, it …
=> 🐛 Fix subnet sorting with multiple vpcs when launching an instance

controllers/awscluster_controller_test.go, pkg/cloud/services/network/vpc.go, test/e2e/data/e2e_eks_conf.yaml, test/e2e/shared/suite.go, test/e2e/suites/managed/eks_test.go
/kind feature
Fixes #5192 
**Checklist**:
```release-note
NONE
```
=> ✨ feat: Remove owned VPCEs when deleting VPC.

docs/book/src/development/releasing.md
Update the release notes to add a reminder that the Prow jobs need to be updated for any new MAJOR.MINOR release.
Fixes #
**Checklist**:
```release-note
Release notes include reminder to update Prow jobs.
```
=> 📖 docs: update release notes with jobs

test/e2e/shared/aws.go, test/e2e/shared/suite.go
/kind feature
Small update to the e2e tests to the AWS account being used. This is to help in the future with any issues that may be associated with a specific AWS account.
Fixes #
**Checklist**:
```release-note
Log AWS account being used when the e2e tests run.
```
=> 🌱 test: log aws account being used

controlplane/rosa/api/v1beta2/rosacontrolplane_types.go, docs/book/src/topics/rosa/upgrades.md, pkg/rosa/versions.go
/kind bug
Fixes a few typos.
Fixes #
**Checklist**:
```release-note
Fixed a few typos.
```
=> :bug: Fixed a few typos.

exp/api/v1beta2/conditions_consts.go, exp/controllers/rosamachinepool_controller.go, pkg/cloud/scope/rosamachinepool.go
/kind bug
This PR is fixing a `RosaMchinePoolReady` typo.
Fixes #
Discovered issue while working on https://issues.redhat.com/browse/ACM-16063
**Checklist**:
```release-note
Fixed RosaMachinePool typo.
```
=> :bug: Fixed RosaMachinePool typo.

docs/book/src/topics/rosa/creating-a-cluster.md, pkg/rosa/client.go, pkg/rosa/client_test.go
/kind feature
This pull request implements support for OCM (aka api.openshift.com) authentication using service account credentials.
The previous authentication mechanism (known as offline tokens) will be deprecated in few months, therefore we need to implement the alternative way. The offline token autentication is still being supported with my changes, though a deprecation
warning will be printed in the CAPA manager logs.
Fixes #
**Checklist**:
```release-note
feat: enable support for service account …
```
=> :sparkles: ROSA: Support for OCM service account credentials

api/v1beta2/awscluster_webhook.go, api/v1beta2/awscluster_webhook_test.go
/kind bug
The PR fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/5247.
Adding a secondary load balancer to existing aws cluster.
**Checklist**:
```release-note
1. fixed adding a secondary load balancer to existing aws cluster
```
=> 🐛 fix(awscluster): update with secondary control plane load balancer

config/crd/bases/OWNERS, controllers/OWNERS, controlplane/rosa/OWNERS, docs/book/src/topics/rosa/OWNERS, exp/api/v1beta2/OWNERS, exp/controllers/OWNERS, pkg/cloud/scope/OWNERS, pkg/rosa/OWNERS, templates/OWNERS
Updating the ROSA project work owners.
Fixes #
**Checklist**:
```release-note
None
```
=> ✨ ROSA: Update ROSA OWNERS

test/e2e/shared/aws.go
Periodic tests seemed to get into a failure loop because an IAM user
with the same name already existed, which is not allowed. This then
failed the entire CloudFoundation stack. Depite the stack claiming to
have been rolled back, the next iteration would run into the same
problem.
This change includes IAM users in the list of resources we need to
specifically delete in the case of a CloudFoundation failure, just in
case they've leaked
The periodic tests at https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-aws#periodic-e2e-release-2-7 were failing roughly every other day between Nov 23, 2024 to Dec 6, 2024.
We'd seen failures prior to that, but …
=> :bug: Attempt to clean up CF IAM users

test/e2e/data/e2e_conf.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-remote-management-cluster.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/remote-management-cluster/kustomization.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/remote-management-cluster/patches/root-volume-size.yaml
/kind bug
The self hosted e2e was failing as the control plane node was encountering disk pressure. This caused CAPA to be evicted and the CAPA images on the original node where deleted to reclaim disk space. When CAPA moved back to the node the image couldn't be found.
Fixes #5252 
Tested this locally:
**Checklist**:
```release-note
Fix self hosted e2e test caused by disk pressure.
```
=> 🐛 fix: self hosted e2e test

controllers/awscluster_controller_test.go, pkg/cloud/services/network/natgateways.go
/kind bug
This fixes an issue that caused the provider to add a security group rule allowing all addresses (`0.0.0.0/0`) access to the workload cluster API Server, if a cluster was created on an unmanaged VPC. The rule would be added even if the user had provided a list of source address in `spec.controlPlaneLoadBalancer.ingressRules`.
The rule was being added so the kubelets could reach the API, but `0.0.0.0/0` was a fall back source if the NAT Gateway IPs were not (yet) known. Prior to this PR, In the case of unmanaged VPC, the NAT Gateways IPs were never retrieved so `getIngressRulesToAllowKubeletToAccessTheControlPlaneLB()` in [securitygroups.go](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pk …
=> 🐛 fix(securitygroups): Look up unmanaged NAT Gateway IPs, so provider doesn't add 0.0.0.0/0 SG rule

config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml, controlplane/rosa/api/v1beta2/rosacontrolplane_types.go, controlplane/rosa/controllers/rosacontrolplane_controller.go, docs/book/src/topics/rosa/upgrades.md
The PR add the ROSA HCP version channel group; stable, candidate and nightly
**Checklist**:
```release-note
Add ROSA-HCP version channel group
```
=> ✨ ROSA: Add version channel Group

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pr-verify.yml, hack/verify-pr-title.sh
/kind cleanup
Updates the PR title checker to be inline with upstream CAPI. Also, this will help with some PR failures with auth.
Fixes #
**Checklist**:
```release-note
Update PR verifier to be inline with upstream CAPI.
```
=> 🌱 chore: title verifier update

.devcontainer/capa-devbox/devcontainer.json, devbox.json, devbox.lock
/kind support
Adds devbox so that the project can be built and executed on any machine.
Adds devcontainer so that anyone on github can build and execute the project using codespaces.
```release-note
Add devbox and devcontainer configuration
```
=> ✨ Adding devbox and devcontainer configuration

exp/controlleridentitycreator/awscontrolleridentity_controller.go, exp/instancestate/awsinstancestate_controller.go
This fixes startup errors
```
"unable to create controller" err="controller with name awscluster already exists. Controller names must be unique to avoid multiple controllers reporting to the same metric" logger="setup" controller="AWSControllerIdentity"
```
which I believe come from using latest cluster-api or controller-runtime which I had for locally running E2E tests. Since this might hit us when bumping CAPI or other components, I thought we can already fix it now.
/kind bug
Fixes #
**Checklist**: …
=> 🐛 Use different names for controllers watching `AWSCluster` objects

pkg/cloud/services/network/subnets.go, pkg/cloud/services/network/subnets_test.go
/kind bug
Since 2.5.0 release, we can't tag subnets anymore by adding tags to the subnet spec in the `AWSCluster` CR. I believe the bug got introduced [on this PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4917/files#r1810976840), by overwriting the subnet tags defined in the spec by the tags from the AWS Subnet. This means that the existing tags on the AWS Subnet will always be applied, while the tags defined in the subnet spec will be ignored.
**Checklist**:
```release-note
Tags defined in subnet spec should be applied
```
=> 🐛: Tags defined in subnet spec should be applied

pkg/rosa/client.go, pkg/rosa/client_test.go
/kind support
Set the ROSA client user agent and version configuration. This is needed so that the CAPA provider can be correctly identified in ROSA logs.
Fixes #
**Checklist**:
```release-note
None
```
=> 🌱 ROSA: Add capa agent and version to ocm client config

test/e2e/data/e2e_conf.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/remote-management-cluster/kustomization.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/remote-management-cluster/patches/root-volume-size.yaml
The self hosted e2e was failing as the control plane node was encountering disk pressure. This caused CAPA to be evicted and the CAPA images on the original node where deleted to reclaim disk space. When CAPA moved back to the node the image couldn't be found.
Fixes #
**Checklist**:
```release-note
Change the self hosted e2e template to give more disk space
```
=> 🐛 [release-2.5] fix: self hosted e2e test caused by disk pressure.

pkg/cloud/services/eks/nodegroup.go
Added a check to ensure that the nodegroup version is not nil before dereferencing it. This prevents potential runtime panics due to nil pointer dereference.
/kind bug
This PR adds a nil pointer check for the nodegroup version in the `reconcileNodegroupVersion` function. This prevents potential runtime panics caused by dereferencing a nil pointer when the nodegroup version is not set.
Fixes #5018
This change is essential to ensure the stability of the `reconcileNodegroupVersion` function by preventing nil pointer dereference issues.
**Checklist**:
```release-note
Fix nil pointer dereference in reconcileNodegroupVersion by adding a …
```
=> 🐛 fix(nodegroup): add nil pointer check for nodegroup version

test/e2e/data/e2e_eks_conf.yaml, test/e2e/suites/managed/addon.go, test/e2e/suites/managed/aws_node_env.go, test/e2e/suites/managed/eks_test.go, test/e2e/suites/managed/helpers.go
/kind flake
make managed suite more robust to errors with Eventually()
Trying to address issues like the ones seen here: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/5211/pull-cluster-api-provider-aws-e2e-eks/1856371404925046784
```release-note
NONE
```
=> 🌱 test: e2e: make managed suite more robust to errors with Eventually()

docs/proposal/2025-01-07-aws-self-managed-feature-gates.md
This proposal should be approved before https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/5124 can be implemented.
**Checklist**:
```release-note
NONE
```
=> :book: Proposal for two new AWS self-managed cluster feature gates

controlplane/rosa/api/v1beta2/rosacontrolplane_types.go, controlplane/rosa/controllers/rosacontrolplane_controller.go, exp/controllers/rosamachinepool_controller.go, exp/controllers/rosamachinepool_controller_test.go
Follow up to https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5279
The PR add the ROSA HCP version channel group; stable, candidate and nightly for `RosaMachinePools`
/kind feature
Fixes #
**Checklist**:
```release-note
Add ROSA-HCP version channel group for Machine Pools
```
=> :sparkles: Add version channelGroup for Rosa Machine Pool

api/v1beta1/awscluster_conversion.go, api/v1beta1/awsmachine_conversion.go, api/v1beta1/zz_generated.conversion.go, api/v1beta2/awsmachine_types.go, api/v1beta2/types.go, config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml, pkg/cloud/services/ec2/instances.go, pkg/cloud/services/ec2/instances_test.go
/kind feature
This PR adds a new enum field to AWSMachineSpec called NetworkInterfaceType that configures the type of the first interface (also called primary interface) on the created instance. 
The two values are:
NetworkInterfaceTypeENI: The network interface will be ENI. Currently, AWS defaults to this type when not specified.
NetworkInterfaceTypeEFAWithENAInterface: This option sets up both ENA (for IP networking) and EFA interface for HPC connections.
Fixes #3035
**Checklist**:
```release-note
Add support for creating instances with elastic fabric adapter interface type.
```
=> :sparkles: Implement support for EFA interface type

docs/book/src/topics/rosa/creating-a-cluster.md
/kind bug
The PR fixes doc formatting.
Fixes #
**Checklist**:
```release-note
Fix ROSA doc formatting
```
=> 🐛 Fix ROSA doc formatting

controlplane/rosa/controllers/rosacontrolplane_controller.go, exp/controllers/rosamachinepool_controller.go, pkg/rosa/idps.go, pkg/rosa/versions.go
Fixing a bug where we called incorrect interface conversion unnecessarily. Change functions to work directly with `OCMClient` and don't convert to `ocm.Client`.
It was caused by my previous PR https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5214 
/kind bug
Fixes #
**Checklist**:
```release-note
NONE
```
=> :bug: Fix OCM client wrapper

pkg/cloud/services/network/secondarycidr.go, pkg/cloud/services/network/secondarycidr_test.go
/kind bug
Currently, cluster deletion is failing when using BYO AWS infra mode (https://cluster-api-aws.sigs.k8s.io/topics/bring-your-own-aws-infrastructure.html#tagging-aws-resources) with:
```
Events:
Type     Reason                           Age                       From            Message
----     ------                           ----                      ----            -------
Warning  FailedDisassociateSecondaryCidr  2m27s (x3471 over 3h21m)  aws-controller  (combined from similar events): Failed disassociating secondary CIDR "100.64.0.0/16" from VPC InvalidCidrBlock.InUse: The vpc vpc-021b2fd5f5a7df0bc currently has a subnet within CIDR block 100.64.0.0/16
status code: 400, request id: …
```
=> 🐛 Fix cluster deletion when using BYO AWS infra mode and Secondary CIDR

test/e2e/shared/aws.go, test/e2e/shared/aws_helpers.go, test/e2e/shared/common.go, test/e2e/shared/identity.go
/kind cleanup
If a test failed, the dumping code may not have AWS clients yet and then panicked. This shifts the attention to a large stack trace instead of the actual, previous failures.
Also some logging improvements: start sentences with uppercase, use newlines.
**Checklist**:
```release-note
NONE
```
=> 🌱 Avoid panicking in after-suite test code, improve logging

test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/base/cluster-template.yaml
/kind support
Update testing to use NLB for controlPlaneLoadBalancer, as ELBs don't work with k8s >= 1.30
```release-note
NONE
```
=> 🌱 Update testing to use NLB for controlPlaneLoadBalancer

pkg/cloud/services/eks/oidc_test.go, pkg/internal/testcert/testcert.go
/kind bug
The OIDC tests use `httpTest.NewTLSServer` and uses a hard coded certificate (see [go src](https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/net/http/internal/testcert/testcert.go)) and we rely on the hash of this certificate in the tests ([here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/eks/oidc_test.go#L67)) as part of gomock assertions. 
The certificate changes with every new go version and the image used by the Prow job has been changed (see [PR](https://github.com/kubernetes/test-infra/pull/34318)) and now uses Go v1.22.12, so the certificates no longer match and the test fails
This updates the oidc test to use our own hard coded certificate with …
=> 🐛 fix: oidc test failure

templates/cluster-template-flatcar.yaml, templates/cluster-template-machinepool.yaml, templates/cluster-template-multitenancy-clusterclass.yaml, templates/cluster-template-simple-clusterclass.yaml, templates/cluster-template.yaml
/kind feature
This PR changes the type of loadbalancer used for controlPlane to NLB (Network Load Balancer) in the templates for CAPA.
This change is necessary in supporting k8s >= 1.30 since the AWS Classic Load Balancer has been deprecated for a while, and starting from K8s 1.30, the cyphersuite required by go to interact with the Classic LB has been removed. See https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/5139 for more details and reasoning.
```release-note
templates: start explicitly using NLB (Network Load Balancer) + HTTPS checks for the Control Plane Load Balancer
```
=> :warning: templates: use NLB as Control Plane Load Balancer type

controlplane/rosa/controllers/rosacontrolplane_controller.go
cleanup
The current error messages don't accurately reflect the error.
return fmt.Sprintf("version %s is not supported", version), nil
return "", fmt.Errorf("failed to check if version is valid: %w", err)
Modified the error messages to indicate there's a problem with the combination of version and channelgroup. 
```release-note
```
=> 🌱 ROSA Modified rosacontrolplane_controller version error messages.

docs/book/src/topics/rosa/creating-a-cluster.md
/kind bug
This pull request adds another paragraph to ROSA installation guide, instructing our users to activate every newly created service account.
Fixes #
**Checklist**:
```release-note
```
=> :bug: ROSA: Add instructions to activate a newly created service account

config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml, controlplane/rosa/api/v1beta2/rosacontrolplane_types.go, docs/book/src/topics/rosa/creating-a-cluster.md, docs/book/src/topics/rosa/enabling.md, docs/book/src/topics/rosa/external-auth.md, docs/book/src/topics/rosa/support.md
The more explicit product name is ROSA HCP, see issue for more details
Fixes #5257
**Checklist**:
```release-note
NONE
```
=> :book: Clarify that the ROSA provider is currently for ROSA HCP clusters

bootstrap/eks/controllers/eksconfig_controller.go, controllers/awscluster_controller.go, controllers/awsmachine_controller.go, controllers/awsmachine_controller_unit_test.go, controlplane/eks/controllers/awsmanagedcontrolplane_controller.go, controlplane/eks/controllers/awsmanagedcontrolplane_controller_test.go, controlplane/rosa/controllers/rosacontrolplane_controller.go, exp/controllers/awsmanagedmachinepool_controller.go, exp/controllers/rosamachinepool_controller.go, exp/controllers/rosamachinepool_controller_test.go, util/paused/paused.go, util/paused/paused_test.go
/kind api-change
edit (@damdo):
To follow the recent updates in the CAPI Provider contract for InfraMachines: https://github.com/kubernetes-sigs/cluster-api/pull/11275 we should set the `Paused=true` condition on the resource's status to acknowledge we detected the addition of the `cluster.x-k8s.io/paused` annotation on a resource and paused its reconciliation to fulfill the user's request.
AWSManagedCluster is handled in a separate PR as there are API changes involved. See #5394
**Checklist**:
```release-note
Set Paused condition on reconciled resources status upon pausing reconciliation (CAPI provider contract change)
```
=> ✨ Set Paused condition on reconciled resources status upon reconciliation being paused

config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml, controlplane/eks/api/v1beta1/conversion.go, controlplane/eks/api/v1beta1/zz_generated.conversion.go, controlplane/eks/api/v1beta2/awsmanagedcontrolplane_types.go, controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook.go, controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook_test.go, pkg/cloud/scope/managedcontrolplane.go, pkg/cloud/services/eks/cluster.go, pkg/cloud/services/eks/cluster_test.go, test/e2e/data/e2e_eks_conf.yaml, test/e2e/data/eks/cluster-template-eks-control-plane-bare-eks.yaml
/kind feature
Add flag to support BootstrapSelfManagedAddons to provision Bare EKS cluster without default addons (coreDNS, kube-proxy, aws-vpc-cni)
https://docs.aws.amazon.com/eks/latest/userguide/create-cluster.html
>By default, EKS installs multiple networking add-ons during cluster creation. This includes the Amazon VPC CNI, CoreDNS, and kube-proxy.
>If you’d like to disable the installation of these default networking add-ons, use the parameter below. This may be used for alternate CNIs, such as Cilium. Review the [EKS API reference](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html) for more information.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes …
=> ✨ Support for BoostrapSelfManagedAddons flag for EKS cluster creation

config/rbac/role.yaml, controllers/awscluster_controller.go, controllers/awsmanagedcluster_controller.go, controllers/rosacluster_controller.go, controlplane/eks/controllers/awsmanagedcontrolplane_controller.go, exp/controllers/awsfargatepool_controller.go
/kind bug
While #5394 and #5383 added support for patching a cluster/status in the cluster.x-k8s.io API group, neither added the patch permission for the associated controllers.
This commit adds RBAC support for patching cluster/status
**Checklist**:
```release-note
NONE
```
=> 🐛 Allow controllers to patch clusters/status

controllers/disabled_controllers.go, controllers/disabled_controllers_unit_test.go, docs/proposal/20250314-optional-controllers.md, main.go
/kind feature
This PR introduces the ability to disable controllers within the controller manager binary. It is an alternative to #5284 using a dedicated argument instead of the existing feature gates.
It starts with AWSMachine and AWSCluster as `unmanaged`, since those are the two we're interested in at the moment.
Other controllers that can be optional, such as the EKS, ROSA, and MachinePool ones, are currently managed with feature flags. When they graduate, they should be controlled by the disabled controllers flag.
Fixes #
Locally, this prints the options …
=> :sparkles: Allow disabling controllers

config/rbac/role.yaml, controllers/awscluster_controller.go, controllers/awsmanagedcluster_controller.go, controllers/rosacluster_controller.go, controlplane/eks/controllers/awsmanagedcontrolplane_controller.go, exp/controllers/awsfargatepool_controller.go
/kind bug
When ensuring the paused condition for AWSCluster we where accidently
passing in the CAPI Cluster as the object instead of the AWSCluster.
This caused a delay in reconciliation as the wrong object was being
patched. It also meant we added additional permission that we didn't
need.
Fixes #5424 
The efs / classic elb e2e tests will still fail so i think it safe to merge with some e2e test failures.
**Checklist**:
```release-note
Fix delay in reconciliation caused by patching wrong object with new paused …
```
=> 🐛 fix: ensure patching correct object for paused

controllers/awscluster_controller.go, controllers/awscluster_controller_unit_test.go, main.go, test/e2e/data/e2e_conf.yaml, test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/efs-support/patches/efs-support.yaml, test/e2e/shared/aws_helpers.go, test/e2e/suites/unmanaged/helpers_test.go
The EFS e2e test was breaking for 2 reasons:
1. Running out if disk space on the control plane nodes. It only had 8Gb so this has been increased to 16gb 
2. The workload being deployed to test EFS was using centos with has been discontinued for a long time now. So changed to use Ubuntu
The classic ELB upgrade test was failing because on upgrade of CAPA, the CAPA controller manager was restarted. From the logs i could see that the AWSCluster was no being reconciled and thats because the "old" and "new" versions were the same basic ion the predicate logic in SetupWithManager. Changed SetupWithManager to be more consistent with other CAPI infra providers. Also it was failing because of the wait introduced …
=> 🐛 fix: efs & elb upgrade e2e tests

cloudbuild-nightly.yaml, cloudbuild.yaml
/kind support
cloudbuild: bump gcb image to get go 1.23
```release-note
NONE
```
=> 🌱 cloudbuild: bump gcb image to get go 1.23

test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/efs-support/patches/efs-support.yaml, test/e2e/suites/unmanaged/helpers_test.go
The EFS e2e test was breaking for 2 reasons:
1. Running out if disk space on the control plane nodes. It only had 8Gb so this has been increased to 16gb 2.The workload being deployed to test EFS was using centos with has been discontinued for a long time now. So changed to use Ubuntu
Note: This is a backport from main (#5418 specifically), but omits the ELB healthcheck test updates, as those are for v2.8+
```release-note
NONE
```
=> [release-2.7] :bug: fix: efs e2e test breaking

docs/book/src/development/releasing.md
While releasing v2.8.1, we ran into some issues with building the image due to mismatched Go versions in the Google Cloud Builder image and the hack/tool dependencies.
This documents what to do in that scenario.
Also adds the nightly image push jobs to prerequisites to check before starting the release, so that hopefully we can avoid skipping the .0 again.
**Checklist**:
```release-note
NONE
```
=> :book: Document latest release obstacles

exp/controllers/rosamachinepool_controller.go, exp/controllers/rosamachinepool_controller_test.go, templates/cluster-template-rosa-machinepool.yaml
/kind bug
Apply CAPI machinepool changes to ROSAMachinePool when ROSAMachinePool is not managed by (external) autoscaler.
Fixes #
**Checklist**:
```release-note
Apply CAPI machinepool changes to ROSAMachinePool
```
=> :bug: ROSA: Apply CAPI machinepool changes to ROSAMachinePool

devbox.json, scripts/devbox-init-hook.sh
For users using devbox directly on their machines, envsubstr is now installed in the isolated devbox environment. Thus not conflicting with the GNU system installation.
Fix the below clusterawsadm installation error when re-entering the devbox environment "ln: failed to create symbolic link '$INSTALL_DIR/clusterawsadm': File exists"
Fixes #5423
`-L` checks if symlink exists, `-e or -f` errors out because `clusterawsadm` does not exist initially when the devbox session is created.
**Checklist**:
```release-note …
```
=> 🌱 Fix envsubstr installation in Devbox

controllers/awsmachine_controller.go
/kind bug
If we don't wire the logger we don't get the default keys that are already in the logger.
**Checklist**:
```release-note
Wire logger into machine scope
```
=> :bug: Wire logger into machine scope

config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml, controlplane/rosa/api/v1beta2/rosacontrolplane_types.go, controlplane/rosa/controllers/rosacontrolplane_controller.go, controlplane/rosa/controllers/rosacontrolplane_controller_test.go, controlplane/rosa/controllers/suite_test.go, exp/controllers/rosamachinepool_controller_test.go
/kind bug
Based on the doc for CAPI control plane contract [here](https://cluster-api.sigs.k8s.io/developer/providers/contracts/control-plane#controlplane-version) the RosaControlPlane status must have version field present the current version.
Fixes #
**Checklist**:
```release-note
Add Version to ROSA Control Plane Status
```
=> :bug: Add Version to ROSA Control Plane Status

api/v1beta1/awscluster_conversion.go, api/v1beta1/zz_generated.conversion.go, api/v1beta2/awscluster_webhook.go, api/v1beta2/awscluster_webhook_test.go, api/v1beta2/network_types.go, api/v1beta2/zz_generated.deepcopy.go, config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml, pkg/cloud/scope/cluster.go, pkg/cloud/scope/managedcontrolplane.go, pkg/cloud/scope/sg.go, pkg/cloud/services/securitygroup/securitygroups.go
/kind feature
It was already possible to add rules for control plane nodes, but not for all nodes. Example use case: pod network is deployed on separate VPC/ENIs (e.g. via Cilium AWS ENI allocator) and therefore doesn't have the `node` security group which allows access to the kubelet API for metrics-server's scraping – that can now easily be allowed with custom rules.
**Checklist**:
```release-note
Support additional security group ingress rules for all nodes
```
=> ✨ Support additional security group ingress rules for all nodes

pkg/cloud/services/network/subnets.go, pkg/cloud/services/network/subnets_test.go
/kind bug
When trying to update a subnet tag that is already present on AWS to a different value, CAPA keeps reconciling the `AWCluster` forever, flapping between the different values of the tag. When reconciling the subnet tags this is what happens
* AWSCluster has subnets, let's say `subnet-1a2b3c` has the tag `customtag: 1`
* CAPA saves the tags to a local variable
* CAPA overwrites all the subnet fields with the info from AWS, including tags. Let's say that the subnet in AWS contained `customtag: 2` (different from the value in the `AWSCluster` CR)
* CAPA takes the tags that it saved earlier to a local variable and it applies them to the AWS subnet. Now on AWS the subnet has the tag `customtag: 1`
* At the end of the …
=> :bug: Don't overwrite subnet spec tags with AWS tags

pkg/cloud/services/ec2/launchtemplate.go, pkg/cloud/services/ec2/launchtemplate_test.go
/kind bug
When the spot instances options are changed, we want to update the launch template so that the changes take effect.
I've changed the unit tests for the `LaunchTemplateNeedsUpdate` function, because some cases were passing by pure chance. Basically these security groups are always added to the incoming `AWSLaunchTemplate`
```
{ID: aws.String("sg-111")},
{ID: aws.String("sg-222")},
```
So if the existing `AWSLaunchTemplate` that we use in the tests don't have these security groups, the function will always return true. Tests like the one testing changes to the `IamInstanceProfile` field were passing because of the different security groups, rather than the change on the …
=> :bug: Launchtemplate needs to be updated if spot options are changed

pkg/cloud/services/eks/addons.go, pkg/eks/addons/types.go, pkg/eks/addons/types_test.go
With latest v2.7.2 and [this PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5202), there is an infinite reconciliation loop for eks addons.
We have seen two problems:
1. It tries to compare _resolveConflicts_ despite the fact that it's not part of _describe-addon_ output
2. It fails to compare emptyString ("") (_desired_ when not set) with nil pointer (_describe-addon output_) on optional `Configuration` field
**Checklist**:
```release-note
Fix: Ignore conflict resolution and correctly compare configuration for AddOn reconciliation
```
=> 🐛 fix(addons): avoid infinite reconciliation loop

pkg/cloud/converters/tags.go
Skip adding reserved aws internal tags (that start with `aws:`) to resources as they are invalid and will cause instance creation errors:
```
I0409 03:42:59.545979       1 awsmachine_controller.go:732] "Creating EC2 instance"
E0409 03:43:01.676476       1 awsmachine_controller.go:535] "unable to create instance" err=<
failed to create AWSMachine instance: failed to create tags for resource "eni-05807e398e7f79df3": : failed to create tags for resource "eni-05807e398e7f79df3": map[MachineName:openshift-cluster-api/capimachineset-ct2tn Name:capimachineset-ct2tn aws:ec2:capacity-reservation-type:capacity-block kubernetes.io/cluster/huliu-aws49a-bwrxg:owned sigs.k8s.io/cluster-api-provider-aws/cluster/huliu-aws49a-bwrxg:owned …
```
=> 🐛 Skip adding reserved aws internal tags to resources as they are invalid

pkg/cloud/services/autoscaling/autoscalinggroup.go
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5497 introduced this bug (copy-paste mistake) which leads to permanent updates of the ASG like this:
```
capa_control… │ I0604 10:14:12.938231      13 awsmachinepool_controller.go:528] "asg diff detected" controller="awsmachinepool" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSMachinePool" AWSMachinePool="org-myorg/andreas245-mp-0" namespace="org-myorg" name="andreas245-mp-0" reconcileID="5480a2f8-f0b3-44c5-af31-0c74cbe7bce3" machinePool="org-myorg/andreas245-mp-0" cluster="org-myorg/andreas245" asgDiff=<
capa_control… │ 	  v1beta2.AWSMachinePoolSpec{
capa_control… │ 	  	ProviderID:        "arn:aws:autoscaling:eu-west-2:242036376510:autoScalingGroup:6e23"...,
capa_control… …
```
=> 🐛 Fix determined value for `MinSize` field of ASG

pkg/cloud/services/securitygroup/securitygroups.go
/kind bug
This PR fixes warning events produced by EmptyRoutesDefaultVPCSecurityGroup option when default rules are already removed.
Before:
```bash
$ kubectl get events -A --field-selector involvedObject.kind=AWSManagedControlPlane
NAMESPACE     LAST SEEN   TYPE      REASON                                      OBJECT                                        MESSAGE
flux-system   33m         Warning   FailedRevokeSecurityGroupIngressRules       awsmanagedcontrolplane/t00-use1-eks-test-cp   (combined from similar events): Failed to revoke security group ingress rules [protocol=-1/range=[-1--1]/description=] for SecurityGroup "sg-019d09a5f5fdf2671": InvalidPermission.NotFound: The specified rule does not exist in this …
```
=> :bug: fix(EmptyRoutesDefaultVPCSecurityGroup): empty rule should not produce a warning event

pkg/cloud/services/ec2/ami.go
/kind bug
When using a bastion and relying on looking up the default AMI it was failing as the Ubuntu AMI's published by Canonical had changed their description and they no longer included LTS so the CAPA lookup failed.
This change removes using LTS in the lookup. In the future we should probably have a more robust way to look up the AMIs.
Fixes #
**Checklist**:
```release-note
Fixed the default AMI lookup when using a bastion.
```
=> 🐛 fix: default bastion ami lookup

api/v1beta2/awsmachine_types.go, api/v1beta2/awsmachine_webhook.go, api/v1beta2/tags.go, cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go, cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml, controllers/awsmachine_controller.go, exp/api/v1beta1/conversion.go, exp/api/v1beta1/zz_generated.conversion.go, exp/api/v1beta2/awsmachinepool_types.go, exp/api/v1beta2/awsmachinepool_webhook.go, exp/api/v1beta2/zz_generated.deepcopy.go, exp/controllers/awsmachinepool_controller.go, exp/controllers/awsmachinepool_controller_test.go, exp/controllers/awsmanagedmachinepool_controller.go, pkg/cloud/scope/ignition.go, pkg/cloud/scope/launchtemplate.go, pkg/cloud/scope/machinepool.go, pkg/cloud/scope/managednodegroup.go, pkg/cloud/services/ec2/launchtemplate.go, pkg/cloud/services/ec2/launchtemplate_test.go, pkg/cloud/services/interfaces.go, pkg/cloud/services/mock_services/ec2_interface_mock.go, pkg/cloud/services/mock_services/objectstore_machine_interface_mock.go, pkg/cloud/services/mock_services/reconcile_interface_mock.go, pkg/cloud/services/s3/mock_s3iface/s3api_mock.go, pkg/cloud/services/s3/s3.go, pkg/cloud/services/s3/s3_test.go
Reopened from https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5172 because of branch issues.
EC2 user data is insecure and very limited in size (16 KB). Use the S3 bucket storage also for machine pools. The difference to `AWSMachine` is that the S3 objects must stay around because a new instance could be started by the ASG at any time, and user data with a valid token must exist. Both a lifecycle policy for regular deletion, and explicit S3 object deletion requests, are used for cleanup, so that normally, only 1-3 launch template versions' user data are stored in S3. Each launch template version relates to one S3 object.
/kind feature
Didn't find an existing issue. My …
=> ✨ Support storing Ignition user data in S3 bucket for `AWSMachinePool`

api/v1beta1/types.go, api/v1beta2/types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
/kind bug
With recent changes introduced to support AL2023 EKS lookup https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5517.
This PR fixes the missing CRD changes that prevent users from using the AL2023 feature. While PR #5517 added the AMI lookup logic for Amazon Linux 2023, it missed updating the CRD validation enums, causing validation errors when users try to specify `eksLookupType: "AmazonLinux2023"`.
This PR completes the AL2023 support by adding the missing CRD enum values. The original PR #5517 added the backend logic for AL2023 AMI lookup but forgot to update the CRD validation, making the feature unusable. This fix enables users to actually use the AL2023 feature that was intended to be …
=>  🐛 Fix missing CRD validation for Amazon Linux 2023 eksLookupType

pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/elb/loadbalancer_test.go
/kind feature
LoadBalancers take many minutes to become available after creation. We currently wait synchronously for a loadbalancer to become available immediately after creation. This increases total cluster installation time when creating multiple control plane loadbalancers as we don't create a loadbalancer until the previous one is fully initialised. It would be more time-efficient to create them all first, then wait for them to become available.
This PR splits loadbalancer creation into 2 phases:
* Get or create
* Reconcile
We ensure that we do the waiting in the reconcile phase after all getOrCreates have executes.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …
=> ✨Create multiple control plane loadbalancers concurrently

api/v1beta2/network_types.go, controllers/helpers_test.go, pkg/cloud/services/elb/loadbalancer.go, pkg/cloud/services/elb/loadbalancer_test.go
/kind bug
The kube-apiserver expects to terminate connections itself during graceful shutdown. As soon as kube-apiserver has received SIGTERM, its /readyz endpoint begins serving HTTP 500 responses. To allow time for load balancers to mark it unhealthy, it continues accepting new connections and serving requests on existing connections for a period of time (controlled by the --shutdown-delay-duration option). Once the shutdown delay has elapsed, it stops accepting new requests and drains in-flight requests before exiting.
By default, NLBs immediately terminate established connections when a target becomes unhealthy. This causes client-facing disruption for clients connected via NLB to a kube-apiserver instance that is …
=> 🐛 Enable NLB connection draining for graceful apiserver shutdown.

config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml, config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanetemplates.yaml, controlplane/eks/api/v1beta2/types.go, docs/book/src/topics/eks/addons.md, pkg/cloud/services/eks/addons.go
/kind feature
Added support for resolveConflicts.PRESERVE ([API Reference](https://docs.aws.amazon.com/eks/latest/APIReference/API_UpdateAddon.html)). This is helpful if users are migrating an existing cluster to Cluster API and do not have their existing Addon Configs specified, or if an out of band change is made to an Addon (eg. configMap change) and the user wants to preserve it.
The schema for conflictResolution had listed `none` as the default behavior. I updated the docs and code to reflect that. 
*
*Special notes for your reviewer**:
**Checklist**:
```release-note
NONE
```
=> :sparkles: Addons: Add functionality for resolveConflicts: PRESERVE

test/helpers/kubernetesversions/data/debian_injection_script.envsubst.sh.tpl
/kind bug
Per https://github.com/kubernetes/kubernetes/commit/3f07fc3acc9014f33fb9bbde12937b35e3f48c75,
the `--short` option on `kubectl version` has been removed for the 1.35 alpha,
which is being used by the conformance tests.
Calling this flag has caused nightly jobs to fail, because the nodes never proceed after getting an error about the missing argument. See this excerpt from a [failed job](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-provider-aws-e2e-conformance-with-k8s-ci-artifacts/1957415637013762048)'s [logs](https://storage.googleapis.com/kubernetes-ci-logs/logs/periodic-cluster-api-provider-aws-e2e-conformance-with-k8s-ci-artifacts/1957415637013762048/artifacts/clusters/bootstrap/i …
=> :bug: Remove deleted `--short` option for kubectl

api/v1beta2/awsmachine_types.go, api/v1beta2/awsmachine_webhook.go, api/v1beta2/awsmachine_webhook_test.go, api/v1beta2/types.go, config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
/kind bug
Adds webhook validation to block conflicting configuration where CapacityReservationPreference is set to 'CapacityReservationsOnly' while MarketType is 'Spot' (or SpotMarketOptions is set), as this combination is not supported by AWS.
Fixes [OCPBUGS-60943](https://issues.redhat.com/browse/OCPBUGS-60943)
**Checklist**:
```release-note
fix: disallow setting of `CapacityReservationPreference: CapacityReservationsOnly` when `MarketType: Spot` or `SpotMarketOptions` is set
```
=> 🐛 Add validation to prevent Spot instances with CapacityReservationsOnly preference

controlplane/eks/controllers/awsmanagedcontrolplane_controller_test.go, pkg/cloud/services/network/natgateways.go, pkg/cloud/services/network/natgateways_test.go
/kind feature
We noticed that CAPA creates too many NAT gateways. One per AZ would be enough, even if there are multiple subnets in an AZ. This creates unnecessary costs. This applies only to clusters with multiple subnets per AZ, such as clusters with multiple VPC CIDRs (in the same region, of course).
**Checklist**:
```release-note
Create only one nat gateway per AZ
```
=> :sparkles: Create only one nat gateway per AZ

exp/controllers/awsmachinepool_controller.go
/kind bug
We don't want to reconcile when the `Cluster` is paused.
**Checklist**:
```release-note
Return early when owner Cluster is paused.
```
=> :bug: Return early if Cluster is paused

api/v1beta2/awsmachine_webhook.go, exp/api/v1beta2/awsmachinepool_webhook.go
/kind bug
Follow-up fix for
- #5641
We default the version only if storage type is not "unencrypted".
But we default the storage type too if not set.
Fixes #
**Checklist**:
```release-note
NONE
```
=> 🐛 Fix ignition version defaulting to consider if the storageType gets defaulted itself

cmd/clusterawsadm/cloudformation/bootstrap/iam.go, cmd/clusterawsadm/cmd/bootstrap/iam/iam_doc.go
/kind bug
Previously, print-policy claimed to output all policies, but in fact it missed some policies, because it did not use the code as print-cloudformation-template. This change makes print-policy use the same code, making it consistent.
Also, print-policy would not output valid JSON, but rather multiple, concatenated JSON documents. It now outputs all policies as a valid JSON object, where the keys are policy names, and the values are the policies.
Before:
```shell
> clusterawsadm bootstrap iam print-policy
AWSIAMManagedPolicyControllers {
...
}
AWSIAMManagedPolicyControllersEKS {
...
}
AWSIAMManagedPolicyCloudProviderControlPlane {
...
}
```
After
```shell
{
"AWSIAMManagedPolicyCloudProviderControlPlane": {
...
}, …
```
=> :bug: Make print-policy consistent with print-cloudformation-template

api/v1beta2/awsmanagedclustertemplate_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedclustertemplates.yaml
/kind bug
Fix AWSManagedClusterTemplate short name. The current short name conflicts with CAPZ, making it impossible to install the latest CAPA version on the same management cluster as CAPZ.
Fixes #
**Checklist**:
```release-note
The short name for AWSManagedClusterTemplate has changed from amct to awsmct. If you have any automation that relies on the short name it will needf to be updated.
```
=> 🐛 Fix AWSManagedClusterTemplate short name

config/rbac/role.yaml, controllers/rosacluster_controller.go, controllers/rosacluster_controller_test.go, controllers/suite_test.go, controlplane/rosa/controllers/rosacontrolplane_controller.go, exp/controllers/rosamachinepool_controller.go, exp/utils/rosa_helper.go, exp/utils/rosa_helper_test.go, pkg/rosa/ocmclient.go, test/mocks/ocm_client_mock.go
/kind bug
CAPA does not automatically manage the default "workers" machinepool created by ROSAControlPlane
Fixes #
**Checklist**:
```release-note
Fix ROSA control plane manage default ROSA machine pool 
```
=> 🐛 ROSA: Fix RosaControlPlane sync default RosaMachinePool

docs/proposal/20250922-nodeadm-bootstrap.md
/kind design
this is a kep to outline a design for a new API type -- `nodeadmconfig`
Proposed fix for #5546 
Looking for appropriate people to put in reviewers!
**Checklist**:
```release-note
NONE
```
=> :book: KEP: adds nodedm proposal
