kubernetes-sigs/cluster-api-provider-aws

- cloud/aws/providerconfig/types.go
- cloud/aws/providerconfig/v1alpha1/types.go
- docs/proposal/machine-config.md
Instead of repeating the proposed types in a doc, this proposal includes code changes to represent the initial proposed type definitions.
The goal is to come to a basic consensus on an initial implementation and generate some discussion around the open issues. Like anything else, this is expected to evolve as we evolve the implementation.
> Machine Config Proposal

- Gopkg.lock
- cloud/aws/actuators/machine/actuator.go
- cloud/aws/actuators/machine/actuator_test.go
- cloud/aws/controllers/machine/controller.go
- cloud/aws/services/cluster/service.go
- cloud/aws/services/ec2/instances.go
- cloud/aws/services/ec2/service.go
~~This is missing a lot of stuff and clearly isn't working, but it should show you the general way I'm thinking about building out the components. This provides a tiny skeleton to grow and add other bones onto as we flesh out the initial implementation.
Thoughts? I'm looking for high level feedback, not details in particular since those are not so hard to change.
Signed-off-by: Chuck Ha <chuck@heptio.com>~~
EDIT: This is a basic implementation ready for code review. This likely doesn't work and likely has bugs and isn't tested but should provide a framework to pick up a little more momentum.
cc @detiber
> basic machine actuator and aws instance implmentation

- Gopkg.lock
- cloud/aws/services/ec2/instances.go
- cloud/aws/services/ec2/instances_test.go
- cloud/aws/services/ec2/service.go
- cloud/aws/services/ec2/vpc.go
- cloud/aws/services/ec2/vpc_test.go
> Adds tests with package cleanup

- Makefile
- README.md
> Adds dev push instructions

- README.md
- clusterctl/examples/aws/generate-yaml.sh
- clusterctl/examples/aws/provider-components.yaml.template
> Improve dev workflow

- Gopkg.lock
- cloud/aws/controllers/cluster/controller.go
- cloud/aws/controllers/machine/controller.go
- clusterctl/examples/aws/generate-yaml.sh
- clusterctl/examples/aws/machines.yaml.template
- clusterctl/examples/aws/provider-components.yaml.template
This uses a real aws client.
I'd like to move the creds to a generated secret, but this should be fine for now to get us started. I will open a ticket around this work.
> Aws client

- cloud/aws/services/ec2/gateways_test.go
> Add tests for internet gateways

- cloud/aws/providerconfig/v1alpha1/types.go
- cloud/aws/services/ec2/routetables.go
> Add code to describe/create/associate routing tables.

- README.md
- cmd/cluster-controller/Makefile
- cmd/machine-controller/Makefile
Added instructions on using Elastic Container Registry during development.
> Support pushing dev images to AWS ECR

- cloud/aws/actuators/machine/actuator.go
- cloud/aws/actuators/machine/actuator_test.go
Fixes a typo and a test going missing.
> machine actuator: Fix typo and restore tests

- cloud/aws/controllers/cluster/controller.go
This PR uses a real cluster client to actually save state
**Special notes for your reviewer**:p
```release-note
NONE
```
> Use real cluster client

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Adds a issue template to standardize our process.
None
None
```release-note
NONE
```
> Add bug/feature issue templates

- .gitignore
- README.md
Improve the README instructions for development work and add some example output.
None
None
```release-note
NONE
```
> Refresh README dev instructions

- SECURITY_CONTACTS
Part of walkthrough
Fixes #
```release-note
```
> Update Security Contacts

- Makefile
Don't overwrite an existing envfile.
Fixes #
```release-note
NONE
```
> do not overwrite existing envfile

- cloud/aws/actuators/cluster/actuator.go
- cloud/aws/actuators/cluster/actuator_test.go
- cloud/aws/services/ec2/network.go
- cloud/aws/services/ec2/tags.go
- cloud/aws/services/ec2/vpc.go
- cloud/aws/services/ec2/vpc_test.go
Tag created resource and try to find them based on said tag before attempting to recreate them.
Fixes #103
This is currently WIP
```release-note
```
> Tag created VPC

- cloud/aws/actuators/cluster/actuator_test.go
- cloud/aws/services/ec2/gateways.go
- cloud/aws/services/ec2/gateways_test.go
- cloud/aws/services/ec2/natgateways.go
- cloud/aws/services/ec2/natgateways_test.go
- cloud/aws/services/ec2/network.go
- cloud/aws/services/ec2/routetables.go
- cloud/aws/services/ec2/routetables_test.go
- cloud/aws/services/ec2/subnets.go
- cloud/aws/services/ec2/subnets_test.go
Tag additional tag-able resources https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-resources
Fixes #
```release-note
```
> Tag additional cluster resources

- Makefile
Wasn't working locally, not sure if it's an OS X vs. Linux thing.
Fixes #
```release-note
NONE
```
> Makefile: Fix sourcing of env file.

- cloud/aws/services/ec2/natgateways.go
- cloud/aws/services/ec2/natgateways_test.go
General NAT gateway logs improvements.
None
None
```release-note
NONE
```
> Improve NAT gateway logs

- Makefile
- cloud/aws/actuators/machine/actuator.go
- cloud/aws/actuators/machine/actuator_test.go
- cloud/aws/providerconfig/types.go
- cloud/aws/providerconfig/v1alpha1/types.go
- cloud/aws/services/ec2/ami.go
- cloud/aws/services/ec2/instances.go
- cloud/aws/services/ec2/instances_test.go
- cloud/aws/services/ec2/subnets.go
- clusterctl/examples/aws/machines.yaml.template
This PR starts the work of implementing the instances
Fixes #53 
```release-note
NONE
```
> create an instance

- README.md
Improve development experience.
Fixes #114
None
```release-note
NONE
```
> Update README with more development instructions

- cloud/aws/actuators/cluster/actuator_test.go
- cloud/aws/providerconfig/v1alpha1/types.go
- cloud/aws/services/ec2/securitygroups.go
Adds the security group dedicated for the bastion host.
Fixes #45 
```release-note
NONE
```
> Add security group for bastion host

- cloud/aws/actuators/machine/actuator.go
- cloud/aws/actuators/machine/actuator_test.go
- cloud/aws/providerconfig/v1alpha1/types.go
- cloud/aws/services/ec2/instances.go
- cloud/aws/services/ec2/instances_test.go
Alignment with other ec2 wrapper types elsewhere.
None
None
```release-note
NONE
```
> Add Instance and InstanceState to v1alpha1 types

- cloud/aws/actuators/machine/actuator_test.go
- cloud/aws/providerconfig/v1alpha1/types.go
- cloud/aws/services/ec2/instances.go
- cloud/aws/services/ec2/instances_test.go
This PR runs a `runInstance` method to the ec2 service which uses our own internal Instance type to run and describe instances.
None
None
```release-note
NONE
```
> Add runInstance method & refactor

- cloud/aws/providerconfig/v1alpha1/types.go
- cloud/aws/services/ec2/errors.go
- cloud/aws/services/ec2/filters.go
- cloud/aws/services/ec2/instances.go
- cloud/aws/services/ec2/natgateways.go
- cloud/aws/services/ec2/routetables.go
- cloud/aws/services/ec2/securitygroups.go
- cloud/aws/services/ec2/service.go
This PR applies few general minor improvements around the use of constants, repetition and some naming nitpick. It also fixes an issue where the error to delete a NAT gateway was being ignored and where the retry loop in the NAT gateway could panic in case the describe ec2 call returns no results.
None
None
```release-note
NONE
```
> Refactor use of consts and minor improvements

- images/ansible/ansible.cfg
- images/packer/packer.json
Removes the temp folder created by Ansible.
Fixes #142 
None
```release-note
NONE
```
> Fix ansible temp folder directory

- Gopkg.lock
- cloud/aws/actuators/machine/actuator.go
- cloud/aws/deployer/deployer.go
- cloud/aws/providerconfig/v1alpha1/types.go
- cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
- cloud/aws/services/certificates/certificates.go
- cloud/aws/services/ec2/instances.go
- cloud/aws/services/elb/loadbalancer.go
This PR adds some base code to generate certs and generate a kubectl in deployer.
Unfortunately this is breaking clusterctl because the ELB isn't returning a DNS name properly but I wanted to share this and iterate on it.
Fixes #24
```release-note
NONE
```
> Adds generated certificates

- cloud/aws/services/ec2/instances.go
Ran into some NPEs during bastion reconciliation
```release-note
NONE
```
> Cleanup some NPE

- cloud/aws/providerconfig/v1alpha1/types.go
- cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
- cloud/aws/services/ec2/instances.go
/assign @randomvariable 
/assign @chuckha
> Use string for IAMInstanceProfile

- cloud/aws/services/elb/loadbalancer.go
Properly sets the DNSName during a type conversion
Fixes #
```release-note
NONE
```
> Set the DNSName during type conversion

- cloud/aws/deployer/deployer.go
- cloud/aws/services/certificates/certificates.go
- cloud/aws/services/ec2/instances.go
- cloud/aws/services/ec2/instances_test.go
- clusterctl/examples/aws/machines.yaml.template
> Misc bugfixes

- clusterctl/examples/aws/machines.yaml.template
$$
Fixes #
```release-note
```
> Use t2.medium in template

- Makefile
- cloud/aws/actuators/machine/actuator.go
- cloud/aws/controllers/cluster/controller.go
- cloud/aws/controllers/cluster/options/options.go
- cloud/aws/controllers/machine/controller.go
- cloud/aws/controllers/machine/options/options.go
- cloud/aws/providerconfig/register.go
- cloud/aws/providerconfig/types.go
- cloud/aws/providerconfig/v1alpha1/register.go
- cloud/aws/providerconfig/v1alpha1/types.go
- cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
- cloud/aws/services/certificates/certificates.go
- cloud/aws/services/ec2/bastion.go
- cloud/aws/services/elb/tags.go
- cloud/aws/services/interfaces.go
- cloud/aws/services/wait/wait.go
- cmd/clusterawsadm/cmd/alpha/root.go
- cmd/clusterawsadm/cmd/root.go
- scripts/ci-test.sh
Appeases the various linters (go fmt, go vet, golint).
Enabled fmt and vet in CI, but not golint because there's no way to exclude rules.
Fixes #168 
```release-note
```
> Appease the linters

- docs/getting-started.md
Fix some sentences in the getting started guide.
None
None
```release-note
NONE
```
> More getting started fixes

- cloud/aws/services/ec2/instances.go
An immediate fix for an NPE exception issue when checking for the instance.
More clean up of pointers / non-pointers to follow.
Part of #173
```release-note
```
> services/ec2/instances: Fix a small NPE

- hack/cluster-api-dev-helper/cmd/testing.go
Adds controller restart and controller manifest apply commands.
```release-note
```
> Dev helper additions

- cloud/aws/actuators/cluster/actuator.go
- cloud/aws/services/ec2/instances.go
This should resolve the issue with missing certificates
I'm still testing this
/hold
/assign @chuckha
> Create certificates in cluster actuator instead of machine actuator

- cloud/aws/services/cloudformation/bootstrap.go
- cloud/aws/services/sts/identity.go
- cloud/aws/services/sts/service.go
- cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
Give permission for machine actuator to attach scoped roles to instances it creates.
Fixes #
```release-note
```
> cloudformation: Add iam::PassRole permission for machine actuator

- .gitignore
- Gopkg.lock
- cloud/aws/actuators/cluster/actuator.go
- cloud/aws/actuators/machine/actuator.go
- cloud/aws/controllers/machine/controller.go
- cloud/aws/deployer/deployer.go
- cloud/aws/services/ec2/bastion.go
- cloud/aws/services/ec2/errors.go
- cloud/aws/services/ec2/instances.go
- cloud/aws/services/ec2/instances_test.go
- cloud/aws/services/elb/loadbalancer.go
- cloud/aws/services/interfaces.go
- cloud/aws/services/mocks/ec2.go
- cloud/aws/services/mocks/elb.go
Current working branch for testing for release
Builds upon #196
> Misc fixes for release

- Gopkg.lock
- Gopkg.toml
This pins our version to the latest release of cluster-api just before the switchover to CRDs
Fixes #
```release-note
NONE
```
> Use the latest release of cluster-api

- cloud/aws/services/ec2/filters.go
- cloud/aws/services/ec2/instances.go
> Use existing machine by tag lookup

- cloud/aws/controllers/cluster/controller.go
- cloud/aws/controllers/cluster/options/options.go
- cloud/aws/controllers/machine/controller.go
- cloud/aws/controllers/machine/options/options.go
- cloud/aws/deployer/deployer.go
- cloud/aws/services/ec2/ami.go
- cloud/aws/services/wait/wait.go
- clusterctl/main.go
- cmd/cluster-controller/main.go
- cmd/clusterawsadm/client/client.go
- cmd/machine-controller/main.go
- hack/cluster-api-dev-helper/cmd/exec.go
- hack/cluster-api-dev-helper/cmd/minikube.go
- hack/cluster-api-dev-helper/cmd/root.go
- hack/cluster-api-dev-helper/cmd/testing.go
- hack/cluster-api-dev-helper/main.go
Normalize copy notice across all files
None
None
```release-note
NONE
```
> Normalize copy notice

- Makefile
Works with latest go versions with default path.
None
None
```release-note
NONE
```
> Use go env to gather GOPATH in makefile

- cloud/aws/actuators/cluster/actuator.go
- cloud/aws/actuators/machine/actuator.go
- cloud/aws/actuators/machine/security_groups.go
- cloud/aws/actuators/machine/tags.go
- cloud/aws/providerconfig/v1alpha1/types.go
- cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
- cloud/aws/services/ec2/instances.go
- cloud/aws/services/ec2/securitygroups.go
- cloud/aws/services/interfaces.go
- cloud/aws/services/mocks/ec2.go
This PR refactors the actuator/service instance security group handling as well as normalizing error handling and simplifying some of the codebase.
None
None
```release-note
NONE
```
> Refactor instance security group handling

- docs/getting-started.md
Fix minor markdown syntax error.
```release-note
NONE
```
> docs/getting-started: fix minor typo

- clusterctl/examples/aws/README.md
We're not OpenStack
Fixes #236 
```release-note
```
> examples: AWS, not OpenStack

- docs/getting-started.md
Fix minor typo.
```release-note
NONE
```
> docs: fix minor typo in "ssm put-parameter" command

- cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
- cmd/clusterawsadm/cmd/alpha/ec2/ec2.go
This PR improves UX for clusterawsadm so it's easier to understand and fix errors.
The following changes are introduced:
* glog is not used anymore, as it's maybe not a great solution for CLI. Instead we've resorted to handling errors with Cobra and fmt.Printf
* Improved error messages to improve understandability and add instructions how to obtain needed resources
* Exit codes are correctly handled
Fixes #191 
Known problems:
* Link for Machine ID instructions may be incorrect one. Is there documentation for that?
* fmt.Printf approach may not be an elegant …
> clusterawsadm: improve user experience

- config/cluster.yaml
- config/cluster_v1alpha1_cluster.yaml
- config/cluster_v1alpha1_machine.yaml
- config/machine.yaml
- config/manager.yaml
- config/rbac.yaml
This PR adds the CRD definitions to continue the building. These should be generated but for now they are not. This is a stop gap to keep development going.
```release-note
NONE
```
> adds basic CRD to get started

- pkg/cloud/aws/services/certificates/certificates.go
> Cleanup certificates package

- cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
Generates a Kubernetes secret from the user's environment.
This is part of revamping documentation and UX.
The move to CRDs adds a fair bit of complexity to the provider components
so, trying to remove it elsewhere.
There'll be documentation updates on using this command in a future PR.
Fixes #
```release-note
```
> clusterawsadm: Add command to generate AWS secret

- .bazelrc
- clusterctl/BUILD
- cmd/clusterawsadm/client/BUILD
- cmd/clusterawsadm/cmd/alpha/BUILD
- cmd/clusterawsadm/cmd/alpha/bootstrap/BUILD
- cmd/manager/BUILD
- pkg/apis/BUILD
- pkg/apis/awsprovider/BUILD
- pkg/apis/awsprovider/v1alpha1/BUILD
- pkg/cloud/aws/actuators/cluster/BUILD
- pkg/cloud/aws/actuators/machine/BUILD
- pkg/controller/BUILD
- scripts/ci-bazel-build.sh
- scripts/ci-bazel-test.sh
- scripts/ci-build.sh
- scripts/ci-test.sh
Swaps out our Prow makefile builds for their Bazel equivilents
Fixes #
```release-note
NONE
```
> Use Bazel for CI

- cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
Fix typo in the AWS credential template for session tokens
Fixes #
```release-note
NONE
```
> Fix aws credentials template for session-token

- Makefile
- scripts/check-install.sh
> Adding a check-install script to the Makefile

- hack/coalesce.py
- scripts/ci-bazel-test.sh
Makes our test results easier to read!
Fixes #
```release-note
NONE
```
> Coalesce test results

- docs/getting-started.md
Corrects link within Getting Started Guide.
Fixes #
N/A.
No image version changes and this is the sole change
N/A
> Correct link to CF templates.

- docs/getting-started.md
Corrects Table of Contents for #293 
N/A
N/A
N/A
> Fixup table of contents from last commit.

- Dockerfile
- cmd/clusterawsadm/cmd/root.go
- config/manager/manager.yaml
- pkg/cloud/aws/services/cloudformation/bootstrap.go
- clusterawsadm: consolidate controller roles/profiles, since there is only a single controller manager now
- clusterawsadm: fixup glog error
- aws provider controller manager: fixup argument error for the aws provider controller manager statefulset.
> misc post-crd fixes

- Gopkg.lock
- config/rbac/rbac_role.yaml
- config/rbac/rbac_role_binding.yaml
- pkg/apis/awsprovider/v1alpha1/BUILD
- pkg/apis/awsprovider/v1alpha1/register.go
- pkg/controller/add_cluster_controller.go
- pkg/controller/add_machine_controller.go
- marshall to json prior to embedding in runtime.RawExtension
- update manager RBAC to handle cluster/machine status subresources
/assign @ashish-amarnath 
/assign @vincepri 
/assign @randomvariable
> Fixes for status updates

- OWNERS_ALIASES
Fixes #
As discussed on Zoom call for 2018-10-22·
```release-note
```
> OWNERS_ALIASES: Add randomvariable (Naadir Jeewa) to maintainers list.

- Makefile
Fixes an issue with go generate that requires GOPATH to be set.
Fixes #
```release-note
NONE
```
> Fix issue if no gopath is set

- scripts/ci-aws-cred-test.sh
- scripts/ci-bazel-build.sh
Signed-off-by: Ruben Orduz <rubenoz@gmail.com>
Simple shell script which will be run periodically to test the aws credentials work for our purposes. 
Fixes #318 
Opted to use bash script (as opposed to Go script) for sake of quick turn-around.
> Adding test script to test ci credentials work for us

- Makefile
- build/cluster_api_binary.bzl
> Fix Bazel image building & Makefile GOPATH reference

- build/cluster_api_binary.bzl
- config/manager/manager.yaml
> Fix Bazel image name, remove cmd directive in yaml

- .gitignore
- BUILD.bazel
- Makefile
- build/cluster_api_binary_image.bzl
- cmd/clusterawsadm/BUILD
- cmd/clusterctl/BUILD
- cmd/manager/BUILD
- docs/development.md
- Update release image to use a version tag rather than latest
- Add a target for generating the release binaries
Fixes #321
> Improve release tooling

- docs/amis.md
- pkg/apis/awsprovider/v1alpha1/types.go
Fix typo.
```release-note
NONE
```
> *: fix "Kubernetes" typos

- pkg/apis/awsprovider/v1alpha1/types.go
Remove blank lines.
Does not break anything. Just nits :)
```release-note
NONE
```
> pkg/apis/awsprovider/v1alpha1: remove blank lines

- Makefile
- docs/development.md
Changes the two docker build targets in the Makefile from `build` to `run`. This
has the effect of Bazel making the resultant images available to Docker locally
as a side effect of the build.
Documentation is updated to specifically call out the necessity of Python 2.x
Fixes #361 
```release-note
```
> Makefile update for local Docker

- WORKSPACE
Bumps Go to 1.11.2 to match k/k
Matches https://github.com/kubernetes/kubernetes/pull/70665
```release-note
```
> Bump Go to 1.11.2

- docs/getting-started.md
More info on minikube and aws user in the getting started doc.
> [DOCS] More info on minikube and aws user in the getting started doc

- pkg/cloud/aws/services/userdata/controlplane.go
- pkg/cloud/aws/services/userdata/node.go
Fixes #367 
```release-note
```
> Prefer ec2 metdata hostname

- Makefile
Fixes #365 
```release-note
NONE
```
> Fix 'cmd/clusterctl/examples/aws/out/' make target

- cmd/manager/BUILD
- cmd/manager/main.go
Part of #330 
Fixes #
```release-note
```
> Use klog instead of zap logger in manager

- pkg/cloud/aws/actuators/cluster/BUILD.bazel
- pkg/cloud/aws/services/mocks/BUILD.bazel
- pkg/deployer/BUILD.bazel
- pkg/deployer/deployer_test.go
This PR is a follow-up from #355, moves the GetIP tests to the deployer package and removes the cluster actuator test file for #305.
Fixes #
```release-note
```
> Deployer GetIP tests

- Gopkg.lock
- pkg/deployer/deployer.go
This PR updates the Gopkg.lock as well as fixes an error message to be more accurate.
Fixes #
```release-note
NONE
```
> Minor cleanup

- Makefile
> Copy mocks on generate step

- pkg/cloud/aws/filter/BUILD.bazel
- pkg/cloud/aws/filter/ec2.go
- pkg/cloud/aws/filter/types.go
- pkg/cloud/aws/services/ec2/BUILD
- pkg/cloud/aws/services/ec2/account.go
- pkg/cloud/aws/services/ec2/bastion.go
- pkg/cloud/aws/services/ec2/eips.go
- pkg/cloud/aws/services/ec2/gateways.go
- pkg/cloud/aws/services/ec2/instances.go
- pkg/cloud/aws/services/ec2/natgateways.go
- pkg/cloud/aws/services/ec2/routetables.go
- pkg/cloud/aws/services/ec2/securitygroups.go
- pkg/cloud/aws/services/ec2/subnets.go
- pkg/cloud/aws/services/ec2/vpc.go
> Move filters into a package

- cmd/clusterawsadm/cmd/root.go
- cmd/clusterctl/examples/aws/generate-yaml.sh
- docs/getting-started.md
- pkg/cloud/aws/services/ec2/securitygroups.go
**What this PR does / why we need it**: Addresses the difficulties we ran into during our attempt to trial the project.
We noticed a few details that appear to have desynchronized from the current state of the project, but by far the biggest time sinks were around minikube and the SSH key (we didn't think to look at the logs until very late, sadly).
The minikube issue has been reported upstream here: https://github.com/kubernetes/minikube/issues/3284
> Update getting started guide

- pkg/cloud/aws/filter/ec2.go
- pkg/cloud/aws/services/ec2/subnets.go
> Fix ec2 subnet filter typo

- pkg/apis/awsprovider/v1alpha1/awsclusterproviderstatus_types.go
- pkg/cloud/aws/actuators/BUILD.bazel
- pkg/cloud/aws/actuators/cluster/actuator.go
- pkg/cloud/aws/actuators/machine_scope.go
- pkg/cloud/aws/actuators/scope.go
- pkg/cloud/aws/services/ec2/bastion.go
- pkg/cloud/aws/services/ec2/instances.go
- pkg/cloud/aws/services/interfaces.go
- pkg/cloud/aws/services/mocks/ec2interface.go
> Refactor bastion methods around scope and remove region from status

- pkg/cloud/aws/actuators/cluster/actuator_test.go
- pkg/cloud/aws/actuators/machine/actuator_test.go
This PR adds a test to make sure that the machine and cluster actuator satisfy the upstream interfaces.
Fixes #
```release-note
```
> Add actuator interface tests

- pkg/cloud/aws/actuators/scope.go
- pkg/cloud/aws/services/ec2/network.go
- pkg/cloud/aws/services/ec2/securitygroups.go
> Refactor security groups around Scope

- pkg/cloud/aws/services/ec2/gateways.go
- pkg/cloud/aws/services/ec2/gateways_test.go
- pkg/cloud/aws/services/ec2/natgateways.go
- pkg/cloud/aws/services/ec2/natgateways_test.go
- pkg/cloud/aws/services/ec2/network.go
> Refactor NAT & Internet gateways around Scope

- pkg/cloud/aws/services/ec2/network.go
- pkg/cloud/aws/services/ec2/subnets.go
- pkg/cloud/aws/services/ec2/subnets_test.go
> Refactor subnets around Scope

- pkg/cloud/aws/actuators/cluster/BUILD.bazel
- pkg/cloud/aws/actuators/cluster/actuator.go
- pkg/cloud/aws/actuators/machine/BUILD.bazel
- pkg/cloud/aws/services/ec2/network.go
- pkg/cloud/aws/services/ec2/vpc.go
- pkg/cloud/aws/services/ec2/vpc_test.go
- pkg/cloud/aws/services/interfaces.go
- pkg/cloud/aws/services/mocks/ec2interface.go
> Refactor VPC around Scope

- pkg/cloud/aws/actuators/cluster/actuator.go
- pkg/cloud/aws/actuators/machine/actuator.go
- pkg/cloud/aws/services/elb/loadbalancer.go
- pkg/cloud/aws/services/interfaces.go
- pkg/cloud/aws/services/mocks/elbinterface.go
- pkg/deployer/deployer.go
> Refactor elb package around Scope

- Makefile
- pkg/apis/awsprovider/v1alpha1/register.go
- pkg/cloud/aws/actuators/cluster/BUILD.bazel
- pkg/cloud/aws/actuators/machine/BUILD.bazel
- pkg/cloud/aws/actuators/machine/actuator.go
- pkg/cloud/aws/actuators/machine_scope.go
- pkg/cloud/aws/services/BUILD.bazel
- pkg/cloud/aws/services/ec2/BUILD
- pkg/cloud/aws/services/ec2/instances.go
- pkg/cloud/aws/services/ec2/instances_test.go
- pkg/cloud/aws/services/interfaces.go
- pkg/cloud/aws/services/mocks/BUILD.bazel
- pkg/cloud/aws/services/mocks/ec2interface.go
> Refactor instances around Scope/MachineScope

- config/crds/awsprovider_v1alpha1_awsclusterproviderconfig.yaml
- config/crds/awsprovider_v1alpha1_awsclusterproviderstatus.yaml
- pkg/cloud/aws/actuators/cluster/actuator.go
- pkg/cloud/aws/actuators/machine/actuator.go
- pkg/cloud/aws/services/mocks/BUILD.bazel
This PR fixes the initialization of the Deployer struct in the machine and cluster actuator.
Fixes #234 
```release-note
```
> Fix deployer initialization, update config files

- cmd/clusterctl/BUILD
- cmd/clusterctl/main.go
- cmd/manager/main.go
This is a temporary fix while the upstream deps are sorted out.
Fixes #
```release-note
```
> Fixup logs

- hack/lib/init.sh
- hack/verify-bazel.sh
This is ported from https://github.com/kubernetes/kubernetes/blob/master/hack/verify-bazel.sh
Fixes #376 
```release-note
```
> Add verify-bazel script for CI 

- Makefile
> Update Makefile for easier DX

- hack/verify-bazel.sh
> Exclude .git/build-* directory in verify bazel

- .gitignore
> Remove manager binary and add to gitignore

- Gopkg.lock
- cmd/manager/main.go
- pkg/cloud/aws/services/ec2/BUILD
- pkg/cloud/aws/services/ec2/bastion.go
- pkg/cloud/aws/services/ec2/eips.go
- pkg/cloud/aws/services/ec2/gateways.go
- pkg/cloud/aws/services/ec2/instances.go
- pkg/cloud/aws/services/ec2/natgateways.go
- pkg/cloud/aws/services/ec2/subnets.go
- pkg/cloud/aws/services/ec2/vpc.go
- pkg/record/BUILD
- pkg/record/recorder.go
Fixes #127 
```release-note
```
> Record basic events

- Makefile
Adds Makefile targets for development purposes. It uses [kind](https://github.com/kubernetes-sigs/kind) to create a bootstrap cluster.
```release-note
```
> Add kind targets to Makefile

- docs/clusterctl.md
- docs/getting-started.md
Explains why clusterctl and how it works.
Fixes #296
> Adds clusterctl documentation

- .gitignore
- pkg/cloud/aws/services/certificates/certificates.go
- pkg/cloud/aws/services/ec2/BUILD
- pkg/cloud/aws/services/ec2/instances.go
- pkg/cloud/aws/services/userdata/node.go
Fixes the error on node join where file and bootstrapToken are mutually exclusive.
/assign @chuckha
> Fixes node join for v1.13

- WORKSPACE
- test/e2e/e2e_suite_test.go
- test/e2e/metacluster_test.go
- test/e2e/util/kind/setup.go
Fixes an issue that came up using Bazel 0.20.0
```
ERROR: error loading package '': Encountered error while reading extension file 'container/container.bzl': no such package '@io_bazel_rules_docker//container': The native git_repository rule is deprecated. load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository") for a replacement.
Use --incompatible_remove_native_git_repository=false to temporarily continue using the native rule.
ERROR: error loading package '': Encountered error while reading extension file 'container/container.bzl': no such package '@io_bazel_rules_docker//container': The native git_repository rule is deprecated. load("@bazel_tools//tools/build_defs/repo:git.bzl", …
```
> Fixes bazel 0.20 deprecated git_repository native rule

- Makefile
- cmd/clusterctl/examples/aws/BUILD
- cmd/clusterctl/examples/aws/aws_manager_image_patch.yaml.template
- cmd/clusterctl/examples/aws/generate-yaml.sh
- config/manager/manager.yaml
> Fix manager container imagePullPolicy substitution

- cmd/clusterctl/examples/aws/cluster.yaml.template
- cmd/clusterctl/examples/aws/generate-yaml.sh
- cmd/clusterctl/examples/aws/machines.yaml.template
> Add ability to configure cluster name, remove generateName

- pkg/apis/awsprovider/v1alpha1/register.go
- pkg/cloud/aws/actuators/BUILD.bazel
- pkg/cloud/aws/actuators/machine_scope.go
- pkg/cloud/aws/actuators/scope.go
Fixes #430 
```release-note
```
> Fix cluster/machine status updates

- WORKSPACE
> Update Bazel to Go 1.11.4

- build/amis/packer/packer.json
Addresses [issues installing Ubuntu packages](https://www.packer.io/docs/other/debugging.html#issues-installing-ubuntu-packages)
```release-note
NONE
```
> Wait for cloud-init to complete

- pkg/cloud/aws/converters/BUILD.bazel
- pkg/cloud/aws/converters/tags.go
- pkg/cloud/aws/services/ec2/natgateways.go
- pkg/cloud/aws/services/ec2/natgateways_test.go
- pkg/cloud/aws/tags/tags.go
- pkg/cloud/aws/tags/types.go
This PR is part of #218. It makes sure that NAT gateways are always tagged appropriately.
Fixes #
```release-note
```
> Ensure tags on natgateways

- pkg/apis/awsprovider/v1alpha1/types.go
- pkg/apis/awsprovider/v1alpha1/zz_generated.deepcopy.go
- pkg/cloud/aws/services/ec2/securitygroups.go
This PR ensures that tags are always up-to-date on security groups.
Related to #218 
```release-note
```
> Ensure tags on security groups

- pkg/cloud/aws/services/ec2/routetables.go
This PR ensures routing table tags are always up-to-date.
Fixes #218 
```release-note
```
> Ensure tags on routing tables

- pkg/apis/awsprovider/v1alpha1/types.go
- pkg/apis/awsprovider/v1alpha1/zz_generated.deepcopy.go
- pkg/cloud/aws/services/ec2/subnets.go
- pkg/cloud/aws/services/ec2/subnets_test.go
This PR ensure subnet tags are kept up-to-date.
Related to #218
```release-note
```
> Ensure tags on subnets

- pkg/cloud/aws/services/ec2/ami.go
this pr adds an owner-id to the ami filter.
Fixes #486 
Additional cleanups can be added in a later commit
```release-note
NONE
```
> Include owner as an AMI filter

- pkg/apis/awsprovider/v1alpha1/BUILD
- pkg/apis/awsprovider/v1alpha1/types.go
- pkg/apis/awsprovider/v1alpha1/types_test.go
Implements equality for IngressRule struct.
Fixes #145
None
cc/ @vincepri @chuckha
> add equality for ingressrule

- Makefile
Fixes #476 
```release-note
```
> Replace glob with more strict directory matching in Makefile

- config/crds/awsprovider_v1alpha1_awsclusterproviderstatus.yaml
- pkg/cloud/aws/services/ec2/mock_ec2iface/ec2api.go
> Update autogenerated files

- Makefile
- cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
- docs/clusterctl.md
- docs/development.md
- docs/getting-started.md
This PR updates the getting started guide to use KIND as ephemeral bootstrapper.
Fixes #
NOTE: I removed the PowerShell part in the getting started guide given that we don't support Windows.
```release-note
```
> Update documentation to use KIND

- docs/getting-started.md
Small fix to allow one of the example commands to work.
Also updates the TOC
Fixes #
```release-note
```
> Small getting started fixup

- docs/README.md
- docs/accessing-instances.md
Fixes #188 
```release-note
```
> Add documentation on how to access cluster nodes

- docs/development.md
This PR updates and organizes the developer documentation to add more information for folks getting started.
Related to #490 
```release-note
NONE
```
> Update developer docs

- WORKSPACE
Fixes a TODO where we're pulling in a git commit
Fixes #
```release-note
```
> Bazel: Update dependencies for Bazel

- docs/getting-started.md
This updates the getting started guide with edits to more accurately reflect the state of the repository.
Fixes #490 
I made one potentially contentious change: I changed the ssh key to be named `default` on AWS since that's what we use as the default in the makefile.
I would be fine changing the makefile as well, but this seemed easier.
I ran through the `clusterctl` command to make sure it works, but have not started from a blank slate.
_Please confirm that if this PR changes any image versions, then that's the …
> Updates getting-started documentation

- WORKSPACE
Removes a repository that was added when testing different linting solutions, but wasn't used in the end.
Fixes #
```release-note
```
> Bazel: Removed unused repository

- cmd/manager/main.go
> Fix klog init in manager

- pkg/cloud/aws/actuators/machine/actuator.go
Fixes #529 
```release-note
```
> Fix control plane url in token creation

- Gopkg.lock
- cmd/clusterawsadm/cmd/alpha/bootstrap/BUILD
- cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
Fixes #494 
```release-note
```
> Use default credentials chain instead of environment variables

- cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
Signed-off-by: ishantanu <shantanud106@gmail.com>
This PR adds a new line while printing error
Fixes #511 
NA
```release-note
NONE
```
> Add new line while printing error

- pkg/cloud/aws/services/cloudformation/bootstrap.go
- pkg/cloud/aws/services/iam/types.go
Fixes #548 
Was missing a string processing statement on doing stack updates.
Also additionally adds pretty printing to the JSON IAM policy documents (which were used for comparison).
```release-note
```
> Fix CloudFormation stack updates

- docs/development.md
Small change in development docs linking to gitbook.
Fixes #125
```release-note
```
> Add gitbook link to dev docs

- build/amis/ansible/roles/common/defaults/main.yml
- build/amis/ansible/roles/common/tasks/debian.yml
- build/amis/packer/goss/goss.yaml
- build/amis/packer/goss/redhat-vars.yaml
- build/amis/packer/goss/ubuntu-vars.yaml
- build/amis/packer/packer.json
- docs/README.md
- docs/packer.md
Related to #205 
This PR does not solve #205. It fixes the problem that was discovered while working on #205.
```release-note
```
> Make sure ubuntu gets proper version of cloud-init

- hack/checkin_account.py
- hack/checkout_account.py
We are working on using Boskos for managing AWS credentials with 
Part of #272 
Why Python?
* Don't need to worry about proper GOPATH handling
* Prior art for Python scripts in `hack/`
I can rewrite this in Go if need be!
```release-note
NONE
```
> Python scripts for checking in/out Boskos AWS accounts

- Makefile
- cmd/clusterctl/examples/aws/generate-yaml.sh
Rev the manager image tag to prep release
> Rev manager image tag

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/aws/aws-sdk-go/aws/version.go
- vendor/golang.org/x/oauth2/README.md
- vendor/golang.org/x/oauth2/internal/token.go
- vendor/golang.org/x/oauth2/oauth2.go
- vendor/golang.org/x/oauth2/token.go
- vendor/k8s.io/klog/.travis.yml
- vendor/k8s.io/klog/CONTRIBUTING.md
- vendor/k8s.io/klog/OWNERS
- vendor/k8s.io/klog/README.md
- vendor/k8s.io/klog/code-of-conduct.md
- vendor/k8s.io/klog/klog.go
- vendor/sigs.k8s.io/cluster-api/Gopkg.lock
- vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/clusterdeployer.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/BUILD.bazel
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/controller.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/controller.go
Updates cluster-api and vendored dependencies.
Fixes #
```release-note
```
> Update cluster-api dep

- pkg/apis/awsprovider/v1alpha1/types.go
- pkg/cloud/aws/actuators/machine/BUILD.bazel
- pkg/cloud/aws/actuators/machine/actuator.go
- pkg/cloud/aws/actuators/machine_scope.go
This PR sets the NodeRef on Machine's Spec effectively linking each created Machine to a Kubernetes node.
Related to #214 
```release-note
```
> Set NodeRef to Machines

- pkg/apis/awsprovider/v1alpha1/types.go
- pkg/cloud/aws/actuators/machine/actuator.go
@chuckha  left some comments too late.
Fixes #
```release-note
```
> Followup to #579 comments

- pkg/cloud/aws/actuators/machine/actuator.go
> Fix return in isNodeJoin

- cmd/clusterctl/examples/aws/BUILD.bazel
This was a bit oversimplified and broke, so reverting here.
`make manifests-dev` should succeed after this.
Fixes #
```release-note
```
> bazel: Fixup to dev manifests

- Gopkg.lock
- pkg/cloud/aws/services/ec2/account.go
**What this PR does / why we need it**: This PR removes some unused code.
Fixes #
```release-note
NONE
```
> Remove dead code

- .golangci.yml
- pkg/cloud/aws/services/elb/loadbalancer.go
This PR enables the deadcode linter and removes some dead code
```release-note
NONE
```
> enable deadcode linter, cleanup

- docs/creating-multinode-controlplane-clusters.md
This PR finishes off the clean up tasks from #545.
Fixes #414 
```release-note
NONE
```
> Multi node control plane documentation

- README.md
Updates the meeting times to reflect reality.
> README: Update meeting times

- RELEASE.md
- docs/releasing.md
Minor cleanup
```release-note
NONE
```
> Release docs update

- docs/development.md
Development doc improvements:
* Add instructions to build container images with custom tags
* Add instructions to push to non GCR container registry
* Add troubleshooting section for commonly encountered errors.
Impreoves development doc.
Fixes #
```release-note
```
> Development doc improvements

- WORKSPACE
- build/cluster_api_binary_image.bzl
- cmd/clusterctl/examples/aws/provider-components-base.yaml
- cmd/manager/BUILD.bazel
- pkg/cloud/aws/services/ec2/mock_ec2iface/ec2api.go
- pkg/cloud/aws/services/elb/mock_elbiface/elbapi.go
- pkg/cloud/aws/services/mocks/ec2interface.go
- pkg/cloud/aws/services/mocks/elbinterface.go
This PR updates the Bazel's WORKSPACE file using tags and best practices, updates generated files and removes the custom Go image using the default gcr distroless docker image as specified here https://github.com/bazelbuild/rules_docker/tree/master/go.
Fixes #
```release-note
```
> Update Bazel WORKSPACE / use tags where appropriate

- pkg/cloud/aws/services/mocks/ec2interface.go
Following up from PR https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/644 updating the generated mocks
Fixes #
```release-note
```
> Update ec2interface mocks

- test/e2e/BUILD
- test/e2e/aws_test.go
Small fixes in `aws_test.go`.
```release-note
NONE
```
> small e2e fixes

- Makefile
- cmd/clusterctl/examples/aws/generate-yaml.sh
> Remove '-dev' references

- Makefile
- cmd/release/main.go
Adds some technical debt to the releaser
```release-note
None
```
> Release tool

- cmd/release/main.go
This PR cleans up the release tool to make it slightly more reusable in some ways and less reusable in others.
There will be some tricky part with regards to determining exactly what is in a release for each provider and how to build it. This may need an interface, but it's a bit early to define that right now
```release-note
NONE
```
> clean up release tool a tiny bit

- Makefile
- docs/development.md
Updates developer documentation to reflect changes in v0.1.1
> docs: Update developer documentation for v0.1.1

- docs/development.md
Also, small rewrites for clarity
Make explicit that you need new binaries in $PATH for `make manifests` to complete.
Partially addresses #674 
/cc @sfzylad 
```release-note
```
> docs: Add note on new binaries for DevX

- README.md
Add version compatibility information with Cluster API and Kubernetes.
Fixes #628
```release-note
NONE
```
/priority important-soon
/milestone v1alpha1
> Add version compatibility info to README

- docs/getting-started.md
Adds the minimum Go version and KIND version required to Getting Started Guide
Fixes #652
```release-note
NONE
```
> Specify minimum Go and KIND versions in Getting Started Guide

- test/e2e/BUILD
- test/integration/BUILD
Stops the e2e and integration tests from being cached.
Part of #272 
/milestone v1alpha1
```release-note
```
> test: Mark integration and e2e tests as external

- docs/getting-started.md
Fixes [reference](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/cmd/clusterctl/examples/aws/generate-yaml.sh) in getting started commands.
```release-note
NONE
```
> docs: Fix reference to renamed script

- pkg/cloud/aws/services/ec2/instances.go
Additional security groups are now applied via ec2.ModifyNetworkInterfaceAttribute rather than ec2.ModifyInstanceMetadata in order to support instances with multiple ENIs.
Fixes #638 
```release-note
Support adding security groups to instances with multiple network interfaces
```
> fix: apply security groups by ENI rather than instance

- docs/development.md
The doc explanation and the command to run are out of sync
Fixes #
```release-note
```
> Fix make target in doc

- hack/checkout_account.py
> Add error reason to output if fail to checkout an account from boskos

- pkg/cloud/aws/services/ec2/instances.go
This PR uses gzip library to compress user-data.
Fixes #705
```release-note
```
> GZIP user-data

- pkg/apis/awsprovider/v1alpha1/types.go
- pkg/cloud/aws/services/ec2/securitygroups.go
Allow Calico to talk IP-in-IP protocol
Fixes #554 
```release-note
```
> Make sure Calico can talk IP-in-IP

- Gopkg.lock
- Gopkg.toml
- vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
- vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/clusterdeployer.go
Fixes #415 
**Note**: This PR doesn't solve #415, so please do not close it.
```release-note
```
> Switch dep to use release-0.1 branch instead of version

- Makefile
Improves DevEx.
Ensures manifests are generated from the current state of the source, assuming `$GOPATH/bin` is in the `$PATH`
Fixes #674
```release-note
```
> Add clusterawsadm as make dependency to manifests make target.

- test/e2e/BUILD.bazel
This should fix the next error in the periodic job failure
Step 1 in #732
```release-note
NONE
```
> Add the HA machines configuration to bazel

- cmd/clusterctl/examples/aws/BUILD.bazel
This will fix the next error in the prow jobs.
Step forward for #732 
```release-note
NONE
```
> Fix the prow jobs

- Gopkg.lock
- Makefile
- pkg/cloud/aws/services/ec2/bastion.go
- vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
Fixes a NPE when trying to delete the bastion host. It also updates cluster-api to latest version.
Fixes #
```release-note
```
> Fix NPE on delete bastion host

- pkg/cloud/aws/actuators/machine_scope.go
- pkg/cloud/aws/actuators/scope.go
This PR minimizes the number of updates performed to only update when necessary.
There were only 2 re-reconciles for each machine object with this patch.
```release-note
NONE
```
> Reduce the number of re-reconciles

- cmd/clusterctl/examples/aws/BUILD.bazel
This PR adds machine-deployments to the release artifacts.
Fixes #754 
```release-note
NONE
```
> Add machine-deployment to release artifacts

- cmd/clusterctl/examples/aws/BUILD.bazel
This PR adds the remaining commit from master that fixes the release artifacts.
> Add machine-deployment to release artifacts (#755)

- pkg/cloud/aws/actuators/scope.go
> Simple cache for sessions

- WORKSPACE
> Update dep to 0.5.2

- pkg/cloud/aws/actuators/scope.go
* Make sure cluster reconciler set the api endpoints if it is not set
or changed.
Fixes #764 
```release-note
```
> Set cluster status api endpoints. (# 764)

- cmd/release/main.go
This PR makes publishing releases a little bit less scary. Or more depending on your perspective.
If you mess up a release or need to add some more commits to a branch before releasing this will force update the tag and force push the tag instead of making you do it by hand.
```release-note
NONE
```
> Few release tool improvements

- pkg/cloud/aws/services/ec2/securitygroups.go
Currently security groups reconciling works only for the creation of new subnets. For existing subnets case, `ResourceID` is not being set in buildParams which results in the aws api failure. Overall it leads to network reconciliation failure.
```
I0513 13:45:02.870613       1 securitygroups.go:48] [cluster-actuator]/cluster.k8s.io/v1alpha1/default/test-vichoudh "level"=2 "msg"="Reconciling security groups"  
E0513 13:45:03.507470       1 controller.go:134] Error reconciling cluster object test-vichoudh; failed to reconcile network for cluster "test-vichoudh": failed to ensure tags on security group "sg-02e51493b84d53085": failed to tag resource "" in cluster "test-vichoudh": InvalidParameterValue: Value ( null ) for parameter resourceId is invalid. Null/empty value for resourceId is …
```
> Fix security group reconcile

- docs/getting-started.md
> Add more troubleshooting tips

- pkg/cloud/aws/services/ec2/BUILD.bazel
- pkg/cloud/aws/services/ec2/securitygroups_test.go
This PR adds unit test for security group reconciliation logic
Fixes #
```release-note
None
```
> Add unit test for security group reconciliation logic

- docs/getting-started.md
Some slight clarification to the setup guide
Fixes #
```release-note
NONE
```
> Show where to get the cluster-api-provider-aws-exmaples.tar

- docs/upgrade-to-0.3.0.md
move the backtic where it belongs, and linkify the Kubernetes issue.
Fixes #
```release-note
NONE
```
> Fix errant formatting

- README.md
- docs/accessing-instances.md
- docs/clusterctl.md
- docs/getting-started.md
- docs/upgrade-to-0.3.0.md
move the backtic where it belongs, and linkify the Kubernetes issue.
Fixes #
```release-note
```
> Backport to release-0.3: Fix errant formatting (#802)

- README.md
Updates the README to list version compatibility information for v0.3
```release-note
NONE
```
> Update version compat docs for v0.3

- OWNERS_ALIASES
This PR adds @sethp-nr and @rudoi to project reviewers 🎉 
Fixes #
```release-note
```
> Promote sethp-nr and rudoi to reviewers

- WORKSPACE
Updates some bazel dependencies
```release-note
NONE
```
> Update some bazel dependencies

- pkg/cloud/aws/actuators/machine/actuator.go
- pkg/cloud/aws/services/ec2/instances.go
- pkg/cloud/aws/services/ec2/instances_test.go
- pkg/cloud/aws/services/interfaces.go
Removes and unused parameter
```release-note
NONE
```
> Remove unused parameter

- README.md
Fix broken link to kubernetes not command on README.md
Fixes #
Just simple document update
Just simple document update
```release-note
NONE
```
> updated link to kubernetes bot commands

- docs/getting-started.md
Improves documentation for users authentication with MFA
None
None
```release-note
NONE
```
> Add AWS_SESSION_TOKEN to the documentation

- pkg/cloud/aws/services/ec2/instances.go
Logs userdata size so we know how big the blobs are getting
Fixes #846 
]
```release-note
NONE
```
> Log userdata size

- Gopkg.lock
- vendor/sigs.k8s.io/cluster-api/Makefile
- vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml
- vendor/sigs.k8s.io/cluster-api/docs/developer/releasing.md
Update to cluster-api v0.1.4
```release-note
NONE
```
> Update to cluster-api v0.1.4

- README.md
- build/amis/packer/packer.json
- docs/amis.md
Updates README and AMI docs for Kubernetes v1.15 support
```release-note
NONE
```
> Update for Kubernetes v1.15

- config/rbac/rbac_role.yaml
- pkg/cloud/aws/actuators/cluster/actuator.go
This PR is a fix for #861 
Fixes #861
```release-note
```
> Add watch and list to secret rbac

- config/rbac/rbac_role.yaml
- pkg/cloud/aws/actuators/cluster/actuator.go
Backports #862 to the release-0.3 branch
```release-note
NONE
```
> Add watch and list to secret rbac (#862)

- pkg/cloud/aws/services/ec2/instances.go
Noticed this was missing while working on #863.
Adds docs and silences a `golint` warning.
Fixes #
```release-note
NONE
```
> doc: Add godoc for GetCoreSecurityGroups

- cmd/clusterctl/examples/aws/controlplane-machine.yaml.template
- cmd/clusterctl/examples/aws/controlplane-machines-ha.yaml.template
- cmd/clusterctl/examples/aws/machine-deployment.yaml.template
- cmd/clusterctl/examples/aws/machines.yaml.template
I often use the examples to create multiple clusters in one management cluster. This is a quality-of-life improvement so I don't have to rename machines and deployments to keep them from conflicting with each other.
```release-note
NONE
```
> Prefix templated nodes with cluster names

- pkg/cloud/aws/services/elb/BUILD.bazel
- pkg/cloud/aws/services/elb/loadbalancer.go
- pkg/cloud/aws/services/elb/loadbalancer_test.go
Fixes #874 
```release-note
```
> Fix ELB panic on deletion

- pkg/cloud/aws/services/ec2/securitygroups.go
- Previously we relied on the status object for deleting security
group ingress rules, instead query the aws sdk for the current
list of ingress rules and revoke all ingress rules prior to deletion.
```release-note
Cluster deletion now queries the security groups for the currently configured ingress rules rather than relying on the status.
```
> Don't rely on status for deleting security group ingress rules

- docs/releasing.md
Updates the manual releasing docs
```release-note
NONE
```
> Update Releasing docs

- cmd/manager/main.go
This is a backport of #900 
Fixes #
```release-note
Added --profiler-address flag to the manager, allowing you to enable the pprof http server.
```
> [0.3] Add optional pprof http server

- docs/getting-started.md
Document how to use an SSH key already in AWS to deploy a cluster.
> Document custom ssh key

- pkg/cloud/aws/actuators/machine/BUILD.bazel
- pkg/cloud/aws/actuators/machine/actuator.go
- pkg/cloud/aws/services/ec2/bastion.go
- pkg/cloud/aws/services/ec2/instances.go
Adds additional events for Machines
```release-note
Emit proper events for Machine creation/termination
```
> [0.3] Update events for Machines

- pkg/apis/awsprovider/v1alpha1/types.go
- pkg/cloud/aws/services/certificates/BUILD.bazel
- pkg/cloud/aws/services/certificates/certificates.go
- pkg/cloud/aws/services/ec2/gateways.go
- pkg/cloud/aws/services/ec2/natgateways.go
- pkg/cloud/aws/services/ec2/routetables.go
- pkg/cloud/aws/services/ec2/securitygroups.go
- pkg/cloud/aws/services/ec2/subnets.go
- pkg/cloud/aws/services/ec2/vpc.go
- pkg/cloud/aws/services/ec2/vpc_test.go
- Adds additional Cluster-related Events
Fixes #816 
```release-note
TODO
```
> Additional Cluster Events

- Makefile
A minor annoyance from the Makefile
Fixes #
```release-note
NONE
```
> Fix make create-cluster-ha

- Gopkg.lock
- Makefile
- README.md
- cmd/release/main.go
- docs/amis.md
- docs/releasing.md
- vendor/sigs.k8s.io/cluster-api/Makefile
- vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml
- vendor/sigs.k8s.io/cluster-api/docs/book/npm-shrinkwrap.json
- vendor/sigs.k8s.io/cluster-api/docs/book/package-lock.json
- vendor/sigs.k8s.io/cluster-api/netlify.toml
- vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/BUILD.bazel
- vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/cluster_controller.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/noderef/noderef_controller.go
Update cluster-api to v0.1.8
```release-note
NONE
```
> Update cluster-api to v0.1.8

- cmd/release/main.go
- docs/releasing.md
Updates releasing documentation and release tool for the image promotion process.
Fixes #795 
```release-note
NONE
```
> Update releasing documentation for image-promoter

- Makefile
This PR fixes an issue where a stale Bazel cache could cause the `hack/copy-mocks.sh` file to error out.
Fixes #
```release-note
```
> Clean bazel mocks before generating them

- pkg/cloud/aws/services/awserrors/errors.go
- pkg/cloud/aws/services/ec2/eips.go
- pkg/cloud/aws/services/ec2/gateways.go
- pkg/cloud/aws/services/ec2/natgateways.go
- pkg/cloud/aws/services/ec2/routetables.go
- pkg/cloud/aws/services/ec2/securitygroups.go
- pkg/cloud/aws/services/ec2/subnets.go
- pkg/cloud/aws/services/ec2/vpc.go
- pkg/cloud/aws/services/ec2/vpc_test.go
- pkg/cloud/aws/services/elb/loadbalancer.go
- pkg/cloud/aws/services/wait/BUILD.bazel
- pkg/cloud/aws/services/wait/wait.go
- Implements backoff and retry for AWS eventual consistency
Fixes #890
Fixes #851 
Fixes #836 
```release-note
TODO
```
> Implement backoff and retry for AWS eventual consistency

- pkg/cloud/aws/services/ec2/vpc.go
Query vpc before attempting to delete
Fixes #943 
```release-note
- Attempt to query VPC prior to deletion
```
> Query vpc before attempting to delete

- pkg/apis/infrastructure/v1alpha2/types.go
- pkg/cloud/services/ec2/BUILD.bazel
- pkg/cloud/services/ec2/gateways.go
- pkg/cloud/services/ec2/natgateways.go
- pkg/cloud/services/ec2/routetables.go
- pkg/cloud/services/ec2/securitygroups.go
- pkg/cloud/services/ec2/subnets.go
- pkg/cloud/services/ec2/vpc.go
- pkg/cloud/services/ec2/vpc_test.go
Signed-off-by: Andy Goldstein <goldsteina@vmware.com>
This ports #910 to master.
Fixes #
I had to do copy/paste by hand for each event, and I decided to move some of them to places that I thought made more sense. I chatted with @detiber about this and he's on board for now, although the long term plan is to move events into the controller code.
```release-note
NONE
```
> Port 0.3 event generation code to master

- pkg/cloud/services/ec2/bastion.go
- pkg/cloud/services/ec2/instances.go
This PR moves the logic from #839 into v1alpha2
Related to #913 
/assign @detiber @ncdc 
```release-note
Bring additional events from v1alpha1 into v1alpha2
```
> Port #839 forward

- pkg/cloud/awserrors/errors.go
- pkg/cloud/services/ec2/eips.go
- pkg/cloud/services/ec2/gateways.go
- pkg/cloud/services/ec2/natgateways.go
- pkg/cloud/services/ec2/routetables.go
- pkg/cloud/services/ec2/securitygroups.go
- pkg/cloud/services/ec2/subnets.go
- pkg/cloud/services/ec2/vpc.go
- pkg/cloud/services/ec2/vpc_test.go
- pkg/cloud/services/elb/loadbalancer.go
- pkg/cloud/services/wait/BUILD.bazel
- pkg/cloud/services/wait/wait.go
This PR forward ports #916 from v1a1 to v1a2
Related to #913 
```release-note
Adds retries to tag related calls to aws.
```
> Port #916 to v1alpha2

- docs/development.md
With move to gomod, the development documentation needs to be updated.
Change `make dep-ensure` to `make vendor`
```release-note
```
> update dev docs with move to gomod

- pkg/cloud/aws/services/elb/loadbalancer.go
Signed-off-by: John Harris <joharris@vmware.com>
**What this PR does / why we need it**: Backport #1001 to 0.3 branch
Fixes #1000 
N/A
```release-note
NONE
```
> Backport #1001 to 0.3 branch

- docs/getting-started.md
> docs: Make getting started requirements easier to understand

- pkg/cloud/services/ec2/instances.go
Ports changes from #1024 to master
```release-note
NONE
```
> Do not include input object in the error message

- Dockerfile
- WORKSPACE
> Update Go 1.12.9

- cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
- pkg/cloud/aws/services/cloudformation/bootstrap.go
Currently, `clusterawsadm` can create IAM policies for the stardard AWS regions. For AWS GovCloud and AWS China, the ARN needs to updated with a specific partition name. From the AWS documentation: 
```
AWS accounts are scoped to a single partition. You can get a partition by name. Valid partition names include:
"aws" - Public AWS partition
"aws-cn" - AWS China
"aws-us-gov" - AWS GovCloud
```
Fixes #959 
I'm not super familiar with Cobra, so let me know if there is a different convention I should use for setting the flag and retrieving it's value.
_Please …
> [0.3] --partition flag for clusterawsadm

- test/e2e/aws_test.go
Backports #1040 to release-0.3
```release-note
NONE
```
> Add missing partition argument to ReconcileBootstrapStack call

- api/v1alpha2/awscluster_types.go
- api/v1alpha2/awsmachine_types.go
- api/v1alpha2/awsmachinetemplate_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
Add capi categories so that we can do kubectl get cluster-api
Fixes #
```release-note
```
> add capi categories

- config/crd/kustomization.yaml
Fixes issue when generating components using kustomize
```release-note
NONE
```
> :bug: Remove empty patches key in config/crd/kustomization.yaml

- pkg/cloud/aws/actuators/machine/actuator.go
Fixes #1054 
```release-note
```
> [0.3] 🐛 Only allow controlplane machines to acquire lock

- examples/controlplane/controlplane.yaml
- examples/provider-components/kustomization.yaml
- examples/provider-components/manager_tolerations_patch.yaml
> ✨ Make example controlplane HA, add toleration to managers

- Makefile
- Rename `generate-kubebuilder-code` to `generate-deepcopy` to align with Cluster API
- Add `--bootstrap-flags="name=clusterapi"` to clusterctl targets to align with `make kind-reset`
- Remove TODO in `create-cluster-management`
Fixes #
```release-note
```
> :running: Cleanup Makefile targets

- Dockerfile
> :running: Allow to provide custom GOPROXY

- cmd/clusterawsadm/cmd/alpha/migrate/migrate.go
- controllers/suite_test.go
- pkg/cloud/converters/instance.go
- pkg/cloud/converters/tags.go
- pkg/cloud/filter/ec2.go
- pkg/cloud/scope/cluster.go
- pkg/cloud/services/ec2/ami_test.go
- pkg/cloud/services/ec2/bastion.go
- pkg/cloud/services/ec2/eips.go
- pkg/cloud/services/ec2/gateways.go
- pkg/cloud/services/ec2/gateways_test.go
- pkg/cloud/services/ec2/instances.go
- pkg/cloud/services/ec2/instances_test.go
- pkg/cloud/services/ec2/natgateways.go
- pkg/cloud/services/ec2/natgateways_test.go
- pkg/cloud/services/ec2/routetables.go
- pkg/cloud/services/ec2/routetables_test.go
- pkg/cloud/services/ec2/securitygroups.go
- pkg/cloud/services/ec2/securitygroups_test.go
- pkg/cloud/services/ec2/subnets.go
- pkg/cloud/services/ec2/subnets_test.go
- pkg/cloud/services/ec2/vpc.go
- pkg/cloud/services/ec2/vpc_test.go
- pkg/cloud/services/elb/loadbalancer.go
- pkg/cloud/services/elb/loadbalancer_test.go
- pkg/cloud/tags/tags.go
Trying to keep consistency in how the imports are named across the repository.
Fixes #
```release-note
```
> 🏃‍♂️ Name v1alpha2 imports

- .github/workflows/main.yml
- .gitignore
- Makefile
> :sparkles: Add tag to action, update Makefile

- main.go
Fixes #1074 
```release-note
```
> Make Manager SyncPeriod configurable via a flag

- controllers/awsmachine_controller.go
- controllers/awsmachine_controller_unit_test.go
This PR fixes an issue with listing machines using a machine label.
> 🐛 Fix bug with requeuing machines from AWSCluster requests

- examples/machinedeployment/machinedeployment.yaml
> 🐛 Adds kind and apiversion to example

- pkg/cloud/services/ec2/ami.go
- pkg/cloud/services/ec2/ami_test.go
This PR fixes an unlikely but long outstanding bug. We removed logging/erroring when an AMI has an invalid creation timestamp. This now properly handles the error.
Fixes #716
> 🐛 handle an unhandled error

- Makefile
- examples/generate.sh
> Use latest clusterawsadm for generate-example

- controllers/awscluster_controller.go
- controllers/awsmachine_controller.go
> 🏃Fix log names are too verbose

- README.md
- docs/amis.md
- Update latest AMI information
- Fix v1alpha2 compat matrix info
> :book: Update latest AMI information

- docs/development.md
Modify URL of Cluster API GitBook.
Fixes #
> :book: Fix broken link in docs/development.md

- .gitignore
- Makefile
- config/default/kustomization.yaml
- config/default/manager_pull_policy.yaml
- controllers/suite_test.go
- go.mod
- hack/ensure-kustomize.sh
- scripts/ci-e2e.sh
- test/e2e/aws_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/util/kind/setup.go
Updates the e2e suite for v1alpha2
TODO:
- ~~update makefile target to build manager image prior to running test~~
- ~~update makefile target to add argument for loading manager image prior to running test~~
- ~~update e2e script for prow to download required binaries for testing prior to running make target~~
- ~~spin up an actual cluster~~
> :running: E2E test updates

- docs/prerequisites.md
This allows a cleaner embedding in the Cluster API book
Fixes #
> :book: Improve prerequisites document to be embedded in book

- README.md
> 📖 Cleaning up readme.md

- examples/controlplane/controlplane.yaml
Fixes issue reported on Slack where it was noted that the IAM profile was changed accidentally as part of fixups to examples. This restores the correct IAM profile for machines forming the control plane.
> 🐛 Correct IAM profile for control plane

- examples/generate.sh
> 🏃Use released manifests for CAPI and CABPK in examples

- pkg/cloud/services/cloudformation/bootstrap.go
Signed-off-by: guohaowang <wangguohao.2009@gmail.com>
Fixes #1191
> :bug: Add permission to allow controllers to get tags

- controllers/awsmachine_controller.go
- docs/observability.md
Cleans up logging during deletes, and adds documentation on events.
Fixes #1139 
Just need to do a sanity check before removing [wip]
> ✨ Instance deletion logs

- pkg/cloud/services/ec2/instances.go
> 🐛 Use sshKeyName from awsCluster if not set in awsMachine

- pkg/cloud/services/wait/wait.go
- pkg/cloud/services/wait/wait_test.go
> ✨ Surface inner error from `WaitForWithRetryable`

- pkg/cloud/services/wait/wait.go
- pkg/cloud/services/wait/wait_test.go
Follow up pr for #1217 
Fixes #
> 🐛 WaitForWithRetryable should return latest error

- config/default/manager_image_patch.yaml
> Change the default image in manifests to target release-0.4

- test/e2e/aws_test.go
- test/e2e/e2e_suite_test.go
Additional e2e fixes, with these changes the e2e tests are running locally for me again.
> :running: Additional e2e test fixes

- test/e2e/e2e_suite_test.go
- Adds fetching of the controller logs to the teardown of the kind cluster when running e2e tests.
> :running: [e2e] retrieve controller logs when tearing down kind cluster

- test/e2e/e2e_suite_test.go
Fixes a build related issue with the e2e tests that doesn't appear to be caught by presubmit validation today.
> :running: [e2e] Fix verification issues with e2e test

- examples/controlplane/controlplane.yaml
- examples/controlplane/kustomizeversions.yaml
- examples/generate.sh
- examples/machinedeployment/kustomizeversions.yaml
- examples/machinedeployment/machinedeployment.yaml
- hack/ci/README.md
- hack/ci/e2e-conformance.sh
- hack/ensure-kind.sh
- scripts/ci-conformance.sh
>  ✨e2e-conformance.sh to be able to run e2e tests

- pkg/cloud/services/elb/loadbalancer.go
> 🐛 Control plane Internal ELBs now connect to private subnets instead of public subnets

- test/e2e/e2e_suite_test.go
Use credentials we create in the cloud formation template instead of the boskos provided credentials
> :running: [e2e] update credentials used for controller

- test/e2e/e2e_suite_test.go
Fixes issues with the access key generation for the e2e tests
> :running: [e2e] more e2e fixes

- test/e2e/e2e_suite_test.go
> :running: [e2e] Create access key after creating the prerequisites

- pkg/cloud/services/ec2/instances.go
Fixes inconsistency of where events are recorded.
Fixes #1274
> :bug: Record events only on AWSMachine

- .gitignore
- test/e2e/e2e_suite_test.go
Adds junit output to e2e tests
> :running: [e2e] add junit output for e2e tests

- test/e2e/aws_test.go
Existing E2E tests doesn't cover MachineDeployment, and scaling it. This PR covers the below:
1. MachineDeployment
2. scale up MachineDeployment
3. scale down MachineDeployment
4. scale again MachineDeployment
Verified that the added tests are running and succeeding in local run
> 🏃 Add MachineDeployment, scale up, down tests

- examples/cluster/cluster.yaml
- examples/cluster/kustomizeconfig.yaml
- examples/controlplane/controlplane.yaml
- examples/controlplane/kustomizeconfig.yaml
- examples/generate.sh
- examples/machinedeployment/machinedeployment.yaml
- examples/provider-components/kustomization.yaml
> :running: Update generate examples to v1alpha3

- hack/ci/e2e-conformance.sh
- hack/heartbeat_account.py
- scripts/ci-e2e.sh
Adds a boskos heartbeat script to the e2e tests to prevent the account from being reaped prior to tests finishing
> :running: [e2e] Add boskos heartbeat

- Makefile
- config/certmanager/certificate.yaml
- config/certmanager/kustomizeconfig.yaml
- config/crd/patches/cainjection_in_awsclusters.yaml
- config/crd/patches/cainjection_in_awsmachines.yaml
- config/crd/patches/cainjection_in_awsmachinetemplates.yaml
- config/default/kustomization.yaml
- config/default/webhookcainjection_patch.yaml
- examples/generate.sh
- go.sum
> Update cert manager / fix Makefile targets

- scripts/ci-e2e.sh
- test/e2e/e2e_suite_test.go
- output logs to $ARTIFACTS/logs instead of just $ARTIFACTS/
- avoid failures in AfterSuite if there are errors in BeforeSuite
> :running: [e2e] Additional e2e tweaks

- test/e2e/e2e_suite_test.go
Fixes the currently broken e2e suite
> :running: [e2e] Fix e2e suite

- examples/generate.sh
- examples/machinedeployment/machinedeployment.yaml
- hack/ci/e2e-conformance.sh
- scripts/ci-conformance.sh
- Use python script for envsubst
- Add / Delete keypair if not preset
- Avoid printing unnecessary stuff
- Support specifying a lookup org for images
- option for skipping creation of the AMI image
Fixes #
> ✨Fix up e2e conformance tests (master)

- scripts/ci-e2e.sh
- test/e2e/aws_test.go
- test/e2e/e2e_suite_test.go
- Improves the e2e suite logging handling
- Adds event logging for the e2e suite
> :running: [e2e] Improve logging and add event logging

- scripts/fetch_ext_bins.sh
> Update CI Kubebuilder / k8s 1.15.5

- docs/README.md
Remove broken link to Developer documentation in the docs/README.md file.
> 📖 docs/README.md: remove broken link

- hack/ci/e2e-conformance.sh
Let's collect some logs from AWS nodes, will be useful for debugging
Fixes #
> ✨Fetch logs from nodes

- examples/generate.sh
fixes the last part of the examples generate script
Fixes #
> point to the output dir in examples generate script

- hack/ci/e2e-conformance.sh
Cherry pick of #1338 on release-0.4.
#1338: Fetch logs from nodes
> :sparkles: Automated cherry pick of #1338: Fetch logs from nodes

- controllers/awsmachine_controller.go
- pkg/cloud/services/ec2/instances.go
> :bug: Validate AWSMachine updates last

- controllers/awsmachine_controller.go
Cherry pick of #1256 on release-0.4.
#1256: machine controller: improve EC2 state handling
> :bug: improve EC2 state handling, fix handling of terminated EC2 instances

- OWNERS
- OWNERS_ALIASES
Waiting for a few other folks to see if they want to step up.
/hold
> :running: Update project maintainers and reviewers

- test/e2e/aws_test.go
> :bug: Fix kubeadm types import

- Makefile
- hack/ci/e2e-conformance.sh
> 🏃Rename Makefile dev target to create-cluster

- pkg/cloud/services/elb/loadbalancer.go
cherry pick of #1341 from release-0.4 to master . 
#1341 check for subnet nil pointer when register instance to apiserver elb
> :sparkles: cherry pick of 1341 from release-0.4 to master

- examples/controlplane/controlplane.yaml
- examples/controlplane/kustomizeversions.yaml
- examples/machinedeployment/kustomizeversions.yaml
- examples/machinedeployment/machinedeployment.yaml
Related to https://github.com/kubernetes-sigs/cluster-api/issues/1849
> 🐛 Update KubeadmConfig(s) to v1alpha3

- Makefile
- hack/ensure-kind.sh
Related to https://github.com/kubernetes-sigs/cluster-api/issues/1796
> 🏃 Update to KIND v0.6.1

- examples/controlplane/controlplane.yaml
- examples/machinedeployment/machinedeployment.yaml
- go.sum
- test/e2e/aws_test.go
This has been tested and it works fine.
> :running: Use local_hostname in cloud-init config

- config/rbac/role.yaml
- controllers/awsmachine_controller.go
Adds RBAC support for getting bootstrap data from secret.
Followup to #1407
> :bug: Update RBAC to add getting, listing, and watching Secrets for bootstrap data

- pkg/cloud/services/elb/loadbalancer.go
Fix the ELB subnets filter
Fixes #1423
> 🐛Fix creation of Internet-facing ELB

- test/e2e/e2e_suite_test.go
Fixes #1428 
Signed-off-by: John Harris <joharris@vmware.com>
> :bug: Fix broken e2e test caused by #1426

- .dockerignore
- .gitignore
- README.md
- tilt-provider.json
Support Tilt for local development. Requires https://github.com/kubernetes-sigs/cluster-api/pull/1894.
Replaces #1422
Fixes #
> ✨ Support Tilt for local development

- pkg/cloud/services/ec2/routetables.go
- pkg/cloud/services/ec2/routetables_test.go
> :sparkles: Add support for updating outdated managed routes

- api/v1alpha2/types.go
- api/v1alpha2/zz_generated.conversion.go
- api/v1alpha2/zz_generated.deepcopy.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
- controllers/awsmachine_controller.go
- controllers/awsmachine_tags.go
- pkg/cloud/services/ec2/instances.go
- pkg/cloud/services/ec2/instances_test.go
Reconciles AWSCluster/AWSMachine-level tags down to EC2 instance root volumes. 
Fixes #1392 
/hold to let discussion close on the associated issue
Also, apologies, I did 0.4 first but I think it'll be an easy forward-port.
> ✨[0.4] feat: pass instance tags through to root volume

- test/e2e/aws_test.go
- test/e2e/conformance_test.go
* Improves the e2e test suite code for better readability
* Introduced testSetup struct
> :sparkles: Improves e2e test suite code

- .dockerignore
- .gitignore
- README.md
- tilt-provider.json
Add tilt support to 0.4.x.
Fixes #
> 🏃 [0.4] Add tilt support

- pkg/cloud/services/ec2/instances.go
- pkg/cloud/services/ec2/instances_test.go
> :bug: Fix NPE when instance doens't have a root volume

- README.md
this link is invalid。I flow ashish-amarnath's advice to delete it and instead it by slack.
> fix a 404 url

- go.mod
- go.sum
- test/e2e/go.mod
- test/e2e/go.sum
> 🏃[0.4] Rev CAPI and CABPK modules

- hack/ci/ci-bootstrap.yaml
conformance: don't send CI artifacts to release path
> [0.4] conformance: don't send CI artifacts to release path

- pkg/cloud/services/elb/loadbalancer.go
Currently the reconcile process does not consider the security groups when reconciling the load balancer. This was found when testing cluster upgrades for PR #1456 
Fixes #
> 🐛 Include security groups when reconciling load balancer

- test/e2e/aws_test.go
Added test which will create AwsMachineTemplate with valid subnet ID
and update MachineDeployment object by replacing the existing AwsMachineTemplate
name with the one created.
Test also verify that the Machines are created.
Executed test locally and it passed.
> 🏃Automate updating machineDeployment with new AwsMachineTemplate name

- test/e2e/e2e_suite_test.go
Don't fail e2e test if log streaming fails.
Fixes #1491
> 🏃 e2e: don't fail test if log streaming fails

- pkg/cloud/services/ec2/instances.go
If spec.Version is not set on Machine, the controller will crash with NPE
Fixes #1092
> 🐛Prevent NPE if Machine's spec.Version is not set by failing the AWSMachine

- test/e2e/aws_test.go
- test/e2e/conformance_test.go
Steps followed:
- Create 2 ControlPlane machines in different AZs
- Create a MachineDeployment in az2 and deploy nginx service
- Now, Delete the ControlPlane machine in az2
- Verify if the nginx service is still accessible. This proves
that the ControlPlane machine in az1 is still able to communicate
with the machines in az2
**Remarks**
_Please let me know if this approach really tests HA_
> :sparkles: Adds test case to verify High Availability

- .golangci.yml
- Makefile
- controllers/awsmachine_controller.go
- pkg/cloud/scope/machine.go
- Re-add missing return when reconciling failed machines
- Fix lint deadline location
- Correct secret comments in machine scope
Fixes #
> :running: Post encryption fixes

- docs/userdata-privacy.md
> :book: Update docs for correctness around userdata-privacy

- docs/userdata-privacy.md
> :book: Update userdata-privacy docs for 0.4

- .golangci.yml
- controllers/awsmachine_controller.go
This change enables `unparam` linter.
Fixes #1544
> 🏃cleanup: enable unparam linter

- README.md
- docs/amis.md
Updates the documented AMIs available for the latest versions built.
> :book: Update README for latest built AMIs

- .golangci.yml
- api/v1alpha2/awsmachine_conversion.go
- pkg/cloud/awserrors/errors.go
- pkg/cloud/services/ec2/instances.go
- pkg/cloud/services/elb/errors.go
- pkg/internal/hash/base36.go
This PR Fixes #1543 and re-enables gocritic linting.
> 🏃 cleanup: enable `gocritic` linter #1543

- docs/userdata-privacy.md
Adding some more troubleshooting information based on conversations with @sethp-nr
> :book: userdata-privacy: Additional troubleshooting info

- .golangci.yml
- api/v1alpha3/awscluster_webhook.go
- api/v1alpha3/awsclusterlist_webhook.go
- api/v1alpha3/awsmachine_webhook.go
- api/v1alpha3/awsmachinelist_webhook.go
- api/v1alpha3/awsmachinetemplatelist_webhook.go
Enables staticcheck linter and removes deprecated packages.  Follow best practices
Fixes #1540
> Enabled staticcheck and replace deprecated packages 🏃

- .golangci.yml
- pkg/cloud/services/ec2/eips.go
- pkg/cloud/services/ec2/routetables.go
- pkg/cloud/services/ec2/securitygroups.go
- pkg/cloud/services/ec2/subnets.go
This enables scopelint.  We need it so we can follow best practices with go and write cleaner code.
Fixes #1542
I am not sure which of the following labels to add. Other and Minor seemed like the most reasonable for this.  I am also open to enabling more linters and cleaning up code, but I also understand the value of having good-first-issues to bring in new contributors.  I kind of enjoy doing this as it makes me better at writing Go but I don't want to hog all the good-first-issues.
> 🏃 Enabled scopelint and fixed reported errors with suggestions

- .golangci.yml
- cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
- pkg/cloud/services/cloudformation/bootstrap.go
Enables stylecheck linter rule and fixes found violations.
Fixes #1538
> 🏃enable <stylecheck> linter rule and fix related issues

- Makefile
> [0.4] Remove build images during make release

- pkg/cloud/services/cloudformation/bootstrap.go
When secrets manager was added it did not account for the different arn values in AWS GOV regions.  This updates that to bring it in-line with similar approaches.
Went ahead with the PR instead of opening an issue, let me know if you'd rather have an issue.
> :bug: Need ARN values different in GOV regions.

- docs/roadmap.md
Adds a project roadmap
Fixes #1419
> :book: Add a project roadmap doc

- Makefile
- controllers/awscluster_controller.go
- controllers/awsmachine_controller.go
- controllers/helpers.go
- go.sum
Implements the pause mechanism.
Fixes #1603
Testing.
> controllers: Implement pause mechanism

- pkg/cloud/services/ec2/instances.go
Update failureDomain support to handle it being set on the Machine rather than AWSMachine
Fixes #1620
> :bug: Update failureDomain support to handle it being set on the Machine rather than AWSMachine

- README.md
- docs/amis.md
- docs/roadmap.md
Updates docs for v0.5.0
Updates available AMIs
> :book: v0.5.0 docs

- README.md
- docs/amis.md
Updates the latest listed v1.16 and v1.15 AMIs
> :book: Update latest v1.16 and v1.15 AMIs

- docs/accessing-instances.md
small typo, did not find other errors 
Fixes #
> 📖 typos: fixing typos

- controllers/awscluster_controller.go
Watch for unpaused Clusters in AWSCluster controller. This speeds up
cluster moves with clusterctl.
Fixes #1654
> :bug: Watch for unpaused Clusters in AWSCluster controller

- api/v1alpha2/awsmachine_conversion.go
- api/v1alpha2/awsmachine_conversion_test.go
- api/v1alpha2/zz_generated.conversion.go
- api/v1alpha3/awsmachine_types.go
- api/v1alpha3/zz_generated.deepcopy.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
- hack/tools/tools.go
- pkg/cloud/scope/machine.go
- pkg/cloud/services/ec2/instances.go
- test/e2e/conformance_test.go
Add flag option for uncompressed userdata.
Fixes #1639
> :warning: :bug:Add flag option for uncompressed userdata.

- main.go
Seed the random number generator, as (at least) controller-runtime uses
it to add jitter to shared informer resync periods.
Fixes #
> 🏃 Seed the random number generator

- hack/ci/e2e-conformance.sh
Updates to the conformance script to bring it in line with changes made to the GCP provider
> :running: Fixes for the conformance script

- hack/ci/e2e-conformance.sh
Fixes an issue with applying filters for retrieving the bastion host in e2e-conformance.sh
> :running: Fix filters in e2e-conformance.sh

- main.go
Signed-off-by: Yuvraj <yuvraj.yad001@gmail.com>
Fixes #1670
> Added version setup log

- hack/ci/e2e-conformance.sh
- Fix quote handling for ssh connection tunneled through Session Manager
- Make sure KUBECONFIG is not set prior to trying to fetch logs from kind cluster during cleanup
> :running: [ci-conformance] Additional conformance test fixes

- docs/accessing-instances.md
This PR updates the `docs/accessing-instances.md` file with the following changes:
- New `clusterctl` commands and workflows are included
- AWS CLI commands are updated to account for changes in tag names and values
- Instructions for using AWS SSM are added
Fixes #1638
> Update docs on accessing instances 📖

- README.md
- docs/amis.md
Updates AMI information for the latest Kubernetes releases
> :book: Update AMIs for latest Kubernetes versions

- Makefile
- hack/ci/e2e-conformance.sh
- scripts/ci-conformance.sh
- templates/kustomizeversions.yaml
- Update templates to better handle kustomize
- Add region command line arg to proxy command
- Fix handling of Kubernetes Version, CI Version, and using imageID in tests
> :running: [ci-conformance] Fix kustomize template to better handle envsubst

- pkg/cloud/services/ec2/bastion.go
Signed-off-by: Yuvraj <yuvraj.yad001@gmail.com>
Fixes #1678
> Do not rely on status to determine if we should delete a bastion that was previously created

- pkg/cloud/services/ec2/account.go
- pkg/cloud/services/ec2/ami.go
- pkg/cloud/services/ec2/bastion.go
- pkg/cloud/services/ec2/console.go
- pkg/cloud/services/ec2/eips.go
- pkg/cloud/services/ec2/gateways.go
- pkg/cloud/services/ec2/instances.go
- pkg/cloud/services/ec2/natgateways.go
- pkg/cloud/services/ec2/routetables.go
- pkg/cloud/services/ec2/subnets.go
- pkg/cloud/services/elb/loadbalancer.go
This PR adds events to AWS cloud service failures 
Fixes #
> add events for AWS cloud service failures

- api/v1alpha2/awsmachinetemplate_conversion_test.go
- go.mod
Removes some extraneous output from the tests.
Fixes #
> :running: Remove spews from tests

- controllers/awsmachine_controller.go
- pkg/cloud/services/elb/loadbalancer.go
Check to see if an instance is already registered with the apiserver ELB
before adding it.
Check to see if an instance is already deregistered from the apiserver
ELB before removing it.
Fixes #1751
> 🐛 Check before (de)registering with ELB

- pkg/cloud/services/ec2/vpc.go
- pkg/cloud/services/ec2/vpc_test.go
When creating/describing the VPC from AWS, we were creating a new
VPCSpec and then using that for the actual VPCSpec in the AWSCluster,
unintentionally wiping out a couple of newly-added fields to VPCSpec
that are user-intent and not information that comes from AWS. This is a
temporary band-aid that ensures we do not lose these fields during
reconciliation. Without this change, the controller sends a patch to set
AvailabilityZoneSelection and AvailabilityZoneUsageLimit to null, but
because of defaulting, the null patches are essentially
rejected/overwritten by the mutating webhook. The result is that the
AWSCluster is reconciled continuously, over and over. This change fixes
that issue. …
> 🐛 Preserve all VPCSpec fields

- pkg/cloud/services/ec2/bastion.go
- pkg/cloud/services/ec2/bastion_test.go
**What this PR does / why we need it**: Delete bastion regardless of VPC type
Fixes #1773
> 🐛 Delete bastion regardless of VPC type

- OWNERS_ALIASES
Removes this account from the reviewers list.
> Remove sethp-nr from reviewers list

- OWNERS
> Add Seth Pellegrino to emeritus reviewers

- OWNERS_ALIASES
Add @randomvariable as a maintainer
Fixes #
/hold
for 1 week lazy consensus
> ✨ Add randomvariable as a maintainer

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Syncs up the changes from https://github.com/kubernetes-sigs/cluster-api/pull/3131 to here
> 🌱 Opt for a more inclusive "other" category for our emoji 

- pkg/cloud/services/ec2/natgateways.go
Kicks off creating NAT gateways in parallel. Returns an error if any of the creates fail. 
Fixes #1792
> 🌱 Creates NAT GWs in parallel

- controllers/awscluster_controller.go
- controllers/awsmachine_controller.go
- go.mod
- pkg/cloud/metrics/metrics.go
- pkg/cloud/scope/cluster.go
Captures count and latency metrics for all AWS API requests, with per-region and per-controller labels.
Fixes #78
> ✨ controllers: Capture metrics for every AWS API request

- OWNERS
- OWNERS_ALIASES
Signed-off-by: Ashish Amarnath <ashisham@vmware.com>
I haven't recently been reviewing PRs.
Fixes #
> 🏃‍♂️ Move myself to emeritus reviewers

- api/v1alpha3/types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
Fix spot instance field validation, it should be a string
> 🐛Fix spot instance field validation

- test/e2e/data/e2e_conf.yaml
- test/e2e/kubetest/test.go
> Update e2e tests to latest Kubernetes release

- tilt-provider.json
Tell `tilt` to watch `/exp` for changes and rebuild.
> 🌱 Reload tilt on exp changes

- README.md
- docs/amis.md
> :book: Update AMIs for Kubernetes v1.16.15 and v1.19.1

- docs/releasing.md
A very small addition to the release docs to include the new managed template
Fixes #
> 📖 docs: added managed template to release docs

- pkg/cloud/services/ec2/instances.go
- pkg/cloud/services/ec2/instances_test.go
**What this PR does / why we need it**: Unexpected behavior when the AWSCluster.Spec.SSHKeyName is set to `""` and the AWSMachine.Spec.SSHKeyName is set to `nil` - results in the instance.KeyName being set to `""`, instead of being unset.
Fixes #1728
>  🐛 AWSMachine ssh key should defer to AWSCluster when nil

- Dockerfile
- Dockerfile.fastbuild
> Bump Golang version to 1.13.15

- Makefile
- scripts/ci-build.sh
> 🌱 Verify e2e code compiles as part of pull-cluster-api-provider-aws-build

- docs/eks.md
This PR fix the command in creating EKS cluster
Fixes #1959
> fix docs for creating a EKS cluster

- cloudbuild.yaml
> :seedling: Bump codebuild timeout for eks control plane

- README.md
- docs/amis.md
Fixes #1965 
/hold
Pending #1947
> Update AMIs for Kubernetes 1.19.2, 1.18.9, 1.17.12

- pkg/cloud/services/securitygroup/securitygroups.go
> :bug: Fix NPE when deleting security groups on cluster deletion

- docs/book/src/topics/eks.md
- docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md
Slight docs update for the 0.6.1 release
Fixes #1971
>  📖  docs: eks docs updated in preparation for 0.6.1 release

- exp/api/v1alpha3/types.go
Can use io2 volume type
Fixes #1984
> add io2 as valid ebs volume type

- config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
- exp/api/v1alpha3/types.go
> 🌱 Add comments for VersionNumber field in AWSLaunchTemplate

- templates/cluster-template-eks-managedmachinepool.yaml
Adds a flavor combining `AWSManagedControlPlane` with `AWSManagedMachinePools`.
> 🌱 Add AWSManagedMachinePool flavor

- docs/machinepools.md
- templates/cluster-template-machinepool.yaml
Documentation for getting started with AWSMachinePools
> 📖 AWSMachinePools docs and flavor

- api/v1alpha3/awscluster_webhook.go
- api/v1alpha3/awscluster_webhook_test.go
- api/v1alpha3/awsmachine_webhook.go
- api/v1alpha3/awsmachine_webhook_test.go
- api/v1alpha3/webhooks.go
> Validation around fields that are passed in as AWS API parameters 

- docs/book/src/topics/eks.md
- docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md
fixes a couple of typos in commands related to EKS
Fixes #
> :docs: fix typos in eks commands

- docs/adr/0000-template.md
- docs/adr/0001-use-adrs-for-decisions.md
Added a template for using ADRs to record decisions and also the first ADR
Fixes #
> 📖 docs: add ADR template and first ADR

- pkg/cloud/services/eks/config.go
> 🐛 fix ownerref group on kube secret and configmap

- docs/changing-credentials.md
This pull request updates the change-credentials.md documentation.
Fixes #2093
> :book: Update docs to use capa-system namespace

- docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md
Updated details on prerequisites page to be more in line with current approach:
- Removed assumption of bootstrap user
- Updated SSH instructions to be optional
Made some small styling tweaks
> 📖 Updated wording on prerequisites doc

- docs/book/src/topics/specify-management-iam-role.md
Includes an example of how to make use of the `controllers.cluster-api-provider-aws.sigs.k8s.io` role when specifying `AWS_CONTROLLER_IAM_ROLE`.
> 📖 add config example to docs specifying IAM role

- OWNERS
- OWNERS_ALIASES
Move ncdc to emeritus status ❤️ 
Fixes #
> 🌱 Move ncdc to emeritus status

- README.md
- docs/book/src/topics/userdata-privacy.md
- docs/book/src/topics/using-cluster-api-with-cross-account-role-assumption.md
Fix broken doc links. 
Fixes #2063
> :book: Fix some of the broken doc links. 

- bootstrap/eks/config/rbac/leader_election_role_binding.yaml
- config/rbac/leader_election_role_binding.yaml
- controlplane/eks/config/rbac/leader_election_role_binding.yaml
The service account used for leader election was incorrect and causing issues.
Fixes #2177
> 🌱 fix: updated service account for leader election

- bootstrap/eks/config/manager/manager.yaml
- bootstrap/eks/config/manager/manager_args_patch.yaml
- bootstrap/eks/config/webhook/manager_webhook_patch.yaml
- bootstrap/eks/main.go
- config/manager/manager.yaml
- config/manager/manager_auth_proxy_patch.yaml
- config/webhook/manager_webhook_patch.yaml
- controlplane/eks/config/manager/manager.yaml
- controlplane/eks/config/manager/manager_args_patch.yaml
- controlplane/eks/config/webhook/manager_webhook_patch.yaml
- controlplane/eks/main.go
- main.go
- test/e2e/data/e2e_conf.yaml
Align flags with upstream k8s 
Fixes #2123
> :warning: align flag names to upstream k8s

- cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
We also need to allow updating the ASG templates for cases like AMI change.
Fixes #
> 🐛Add UpdateAutoScalingGroup to controller IAM

- scripts/ci-e2e-eks.sh
A recent change has changed the python scripts for the e2e shell script.
Fixes #
> 🐛 fix: updated the eks e2e script with latest boskos changes

- go.mod
- go.sum
- test/e2e/data/e2e_conf.yaml
- test/e2e/data/e2e_eks_conf.yaml
Upgrades CAPI from 0.3.11 to 0.3.12.
Fixes #
> Upgrade to CAPI v0.3.12

- go.mod
- go.sum
- pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
- pkg/cloud/services/eks/mock_eksiface/eksapi_mock.go
Upgrade the SDK to the latest version.
> 🌱Upgrade AWS SDK version to 1.36.26

- Makefile
Skip the upgrade tests when running the EKS E2E tests.
Fixes #
> 🌱 skip EKS upgrade tests when running e2e

- cloudbuild.yaml
> Bump GCB Docker image for cloudbuild

- Dockerfile
- hack/boilerplate/boilerplate.Dockerfile.txt
This is also needed in order for Docker to use the mirrored image.
Fixes #
> Bump dockerfile-experimental version

- docs/book/src/development/releasing.md
- hack/tools/Makefile
>  📖 Minor update on release process doc

- api/v1alpha3/types.go
The comment for InstanceStateRunning should reflect the `running` state.
Fixes #
**Special notes for your reviewer**: I hope not!
**Checklist**:
```release-note
Corrected comment for the InstanceStateRunning doc string
```
> 🌱  Minor comment update

- README.md
- docs/amis.md
- test/e2e/data/e2e_conf.yaml
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2257
**Checklist**:
```release-note
New AMIs are published for v1.18.16, v1.19.8, and 1.20.4
```
> 🌱New AMIs for versions 1.20.4, 1.19.8, and 1.18.16

- pkg/cloud/services/ec2/instances.go
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2255
**Checklist**:
```release-note
NONE
```
A follow-up PR for https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2229.
> Replace awslog with logrWrapper

- docs/proposal/20200506-single-controller-multitenancy.md
Updates multitenancy proposal with:
1. Supporting both list and selector for `allowedNamespaces`
2. AWSClusterControllerPrincipal controller that creates AWSClusterControllerPrincipal instance if missing.
**Checklist**:
-->
```release-note
NONE
```
> Add AWSClusterControllerPrincipal controller to multitenancy proposal

- README.md
Fix AMI link reference
Fixes #
**Checklist**:
```release-note
```
> Update README with correct AMI link

- pkg/cloud/services/elb/loadbalancer.go
/kind bug
Adds ELB name as tag.
Fixes #2284 
-->
```release-note
NONE
```
> Add name tag to ELB

- OWNERS_ALIASES
/kind support
I would like to propose @sedefsavas as a maintainer of Cluster API Provider AWS.
```release-note
@sedefsavas  made a maintainer of Cluster API Provider AWS
```
> PROPOSAL: sedefsavas as maintainer

- docs/book/src/development/releasing.md
- templates/cluster-template-eks-managedmachinepool-gpu.yaml
/kind feature
Adds a new cluster template for an EKS cluster that is GPU accelerated and with the nvidia ds. This assumes #2264 will be merged.
Fixes #
**Checklist**:
```release-note
New cluster template for an GPU accelerated EKS cluster
```
> feat: add GPU EKS cluster template

- test/e2e/data/ci-artifacts-platform-kustomization-for-upgrade.yaml
- test/e2e/data/e2e_conf.yaml
- test/e2e/data/infrastructure-aws/cluster-template-upgrade-to-main.yaml
- test/e2e/shared/defaults.go
- test/e2e/shared/suite.go
- test/e2e/suites/unmanaged/unmanaged_test.go
This PR adds upgrade to Kubernetes main branch test.
It tests both KCP and MachineDeployment upgrade.
Fixes #
**Checklist**:
```release-note
Add upgrade to Kubernetes main test
```
> Add upgrade to main test

- CONTRIBUTING.md
Documenting all the places that need updating for maintainer status.
Fixes #
**Checklist**:
```release-note
NONE
```
> Add maintainer docs

- cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
/kind bug
To support adding additional security groups to ELB, allowed ApplySecurityGroupsToLoadBalancer action.
Fixes #2156
**Checklist**:
```release-note
NONE
```
> Add ApplySecurityGroupsToLoadBalancer action to controllers role

- cmd/clusterawsadm/api/bootstrap/v1alpha1/defaults.go
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/template_test.go
/kind bug
Fixes #2339 
**Checklist**:
- [] adds or updates e2e tests
```release-note
Fixes bug where custom bootstrap user name was not accepted.
```
> Allow custom bootstrapper user name

- OWNERS
- OWNERS_ALIASES
/kind cleanup
Move myself from the maintainers list to emeritus status. Since I no longer have time or credentials to contribute to the project.
```release-note
NONE
```
> Move myself to emeritus status

- docs/book/src/topics/machinepools.md
/documentation
Fixes some broken links within the machinepool book topic 
**Checklist**:
```release-note
Fixes broken links to templates in the machinepool book topic
```
> Fix machinepool template links

- controlplane/eks/api/v1alpha3/doc.go
- docs/book/Makefile
- docs/book/gen-crd-api-reference-docs/config.json
- docs/book/src/SUMMARY_SUFFIX.md
Adds the CRD documentation for EKS controlplane and exp
Fixes #
**Checklist**:
```release-note
NONE
```
> docs: Add EKS and experimental CRD documentation

- docs/book/theme/head.hbs
Adds site verification for access to Google Search tools. Book isn't getting indexed, want to find out why.
Once this is set up, I will share with the maintainers Google group.
Fixes #
**Checklist**:
```release-note
NONE
```
> Add Google site verification

- README.md
Replace the AMI list in the readme with a link to the book.
Fixes #
**Checklist**:
```release-note
NONE
```
> Replace AMI list in README with link to amis page in book.

- cloudbuild.yaml
This PR updates the cloudbuild to use an image with Go 1.16. For more context see https://github.com/kubernetes-sigs/cluster-api/issues/4383.
Fixes #
**Checklist**:
> 🏃‍♂️ Update cloudbuild to Go 1.16

- test/e2e/suites/unmanaged/unmanaged_test.go
Signed-off-by: Zhou Hao <zhouhao@fujitsu.com>
Fixes #
**Checklist**:
```release-note
NONE
```
> fix ineffectual assignment

- exp/controllers/awsmachinepool_controller.go
- pkg/cloud/scope/machinepool.go
- pkg/cloud/services/ec2/launchtemplate.go
- pkg/cloud/services/ec2/launchtemplate_test.go
- pkg/cloud/services/interfaces.go
- pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
/kind bug
Cherry pick of: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2394
Fixes #
**Checklist**:
```release-note
NONE
```
> Get LaunchTemplates by name

- pkg/cloud/services/ec2/launchtemplate.go
Should return error if DescribeLaunchTemplates() call fail.
Fixes #
**Checklist**:
```release-note
NONE
```
> Return error in DescribeLaunchTemplate()

- pkg/cloud/services/eks/roles.go
/kind bug
The max-length allowed for an IAMRole name is 64 chars. This PR adds a fix to limit the max-length for the default 'EKS nodegroup IAM Role' name to 64 chars.
Fixes #2378 
**Checklist**:
```release-note
NONE
```
> fix max-length for nodegroup IAM role

- pkg/cloud/scope/fargate.go
/kind feature
Add identity reference provider support for fargate controller
Fixes #
**Checklist**:
```release-note
NONE
```
> add identity ref support for fargate controller

- pkg/cloud/scope/fargate.go
/kind bug
Cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2403
Fixes #
**Checklist**:
```release-note
Add identity ref support for fargate controller
```
> cherry-pick add identity ref support for fargate controller

- pkg/cloud/services/eks/nodegroup.go
/kind bug
If a user edits the min/max size of a EKS node pool manually in the AWS console the controller will make sure that this is changed back to match the min/max size defined in AWSManagedMachinePool
Fixes #2318 
**Checklist**:
```release-note
EKS Nodepool min/max will be updated to match the AWSManagedMachinePool spec, overriding changes to min/max made via the AWS Console, CLI, or SDK.
```
> fix: managed machine pool correct min/max size

- cmd/clusterawsadm/cmd/bootstrap/iam/cloudformation.go
/kind bug
This PR contains the following changes:
- Aligns `clusterawsadm bootstrap iam delete-cloudformation-stack` and `clusterawsadm bootstrap iam create-cloudformation-stack` in a way they accept region parameter:
```
config < env < flag
```
- Removes call to `ShowStackResources` which always results in error.
- Delete incorrect alias from `delete-cloudformation-stack` command.
Fixes #2392
As suggested in #2392 we can further expand the config resolution to `~/.aws/credentials` for both methods, as it was unintentionally …
> :bug: Align region resolution in create/delete cloudformation stack commands

- Makefile
- docs/book/src/development/releasing.md
Switched published artifacts from `us.gcr.io/k8s-artifacts-prod` to `k8s.gcr.io`
Fixes #2258
**Checklist**:
```release-note
Switch to k8s.gcr.io registry
```
> Switch published artifacts to k8s.gcr.io

- docs/book/src/SUMMARY_PREFIX.md
- docs/book/src/SUMMARY_SUFFIX.md
- docs/book/src/development/development.md
- docs/book/src/development/tilt-setup.md
Divided the developer section as initial setup and tilt setup, and provided examples for CAPA managed clusters as well.
Also added a way to bring up local cluster without KinD for development.
Fixes #
**Checklist**:
```release-note
NONE
```
> Update developer section in the book

- Makefile
- docs/book/src/development/releasing.md
- hack/tools/Makefile
Forward port of: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2421
Fixes #
**Checklist**:
```release-note
NONE
```
> Minor makefile release fixes

- test/helpers/envtest.go
Cluster-api made some envtest methods internal (https://github.com/kubernetes-sigs/cluster-api/pull/4698), so we copy the ones we need here.
Fixes #
**Checklist**:
```release-note
NONE
```
> Copy envtest cleanup from core cluster-api repo

- README.md
- docs/book/src/development/tilt-setup.md
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2459
**Checklist**:
```release-note
NONE
```
> [docs] Minor introduction section improvements

- test/e2e/data/cni/calico.yaml
/kind other
Updates Calico version + yaml files in e2e tests. 
Fixes #2435 
**Checklist**:
```release-note
NONE
```
> Update calico in e2e tests

- .github/workflows/dependabot.yml
/kind cleanup
Should automate some of the dependabot steps for us. Total experiment.
Fixes #
**Checklist**:
```release-note
NONE
```
> Dependabot: Add workflow to automatically update generated code

- Makefile
- cloudbuild-nightly.yaml
Set up nightly build.
Follow up for:
https://github.com/kubernetes/test-infra/pull/22546
https://github.com/kubernetes/test-infra/pull/22560
Fixes #
**Checklist**:
```release-note
NONE
```
> Add file and make commands for nightly build

- .github/workflows/dependabot.yml
/kind cleanup
The dependabot action wasn't running on its PRs, so did some testing on my local fork to get it to work, which you can see here
https://github.com/randomvariable/cluster-api-provider-aws/pull/2/commits 
Fixes #
**Checklist**:
```release-note
NONE
```
/assign @richardcase
> Fix dependabot Github action

- metadata.yaml
/kind bug
Correctly state the infrastructure provider contract
**Checklist**:
```release-note
NONE
```
> Fix clusterctl metadata

- .github/workflows/dependabot.yml
/kind cleanup
Fixes #
Third time lucky.
**Checklist**:
```release-note
NONE
```
> dependabot: Update author of autocommit to pass CLA checks

- README.md
/kind cleanup
go-report is giving Fs whenever the runner fails, so removing it since it's not adding value.
Press F.
Fixes #
**Checklist**:
```release-note
NONE
```
> README: Remove go-report

- Makefile
- test/e2e/data/e2e_conf.yaml
- test/e2e/data/infrastructure-aws/cluster-template-kcp-scale-in.yaml
- test/e2e/data/infrastructure-aws/kcp-scale-in/kustomization.yaml
- test/e2e/data/infrastructure-aws/kcp-scale-in/patches/kcp-surge.yaml
- test/e2e/shared/defaults.go
- test/e2e/shared/resource.go
- test/e2e/shared/suite.go
- test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
- test/e2e/suites/unmanaged/unmanaged_test.go
Added KCP scale-in test to periodic CAPI e2e tests.
Fixes #
**Checklist**:
```release-note
NONE
```
> Add KCP scale-in test

- hack/ensure-kind.sh
Upgrade kind to v0.11.0 for less flakiness in e2e tests. 
the kind is already v0.11.1 in go.sum
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2413
**Checklist**:
```release-note
NONE
```
> upgrade to kind v0.11.0

- README.md
Corrects the version skew in the README.
Fixes #
**Checklist**:
```release-note
NONE
```
> README: Note that v1alpha3 (v0.6) supports Kubernetes v1.21

- pkg/cloud/services/network/eips.go
- pkg/cloud/services/network/natgateways_test.go
/kind feature
Tagging elastic IPs on creation. Earlier we were making a separate call after creation to tag the elastic IPs. 
Fixes #2207
**Checklist**:
```release-note
Tagging elastic IPs on creation
```
> Tagging elastic IPs on creation

- docs/book/src/development/releasing.md
Ref: #94319
```release-note
None
```
> master to main cleanup

- pkg/cloud/services/securitygroup/securitygroups.go
/kind bug
Backport of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2555
Fixes #
**Checklist**:
```release-note
Fix for only deleting Security Groups managed by CAPA controllers, not the overridden ones.
```
>  [Backport] Do not delete overridden security groups

- docs/book/src/topics/accessing-ec2-instances.md
- docs/book/src/topics/eks/addons.md
- docs/book/src/topics/eks/creating-a-cluster.md
- docs/book/src/topics/machinepools.md
- test/e2e/shared/cluster.go
- test/e2e/shared/temp.go
/kind bug
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2554
**Checklist**:
```release-note
None
```
> Modify clusterctl config to clusterctl generate

- Makefile
- go.mod
- go.sum
- test/e2e/data/kubetest/conformance.yaml
* Updates CAPI reference to account for change in image location
* Run the load balancer test here instead of the functional test
Fixes #
**Checklist**:
```release-note
NONE
```
> e2e: Pull in newer Cluster API for conformance fixes

- bootstrap/eks/controllers/eksconfig_controller.go
- bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
- bootstrap/eks/controllers/eksconfig_controller_test.go
Fixes #2595
Also pretty much re-wrote "Should reconcile an EKSConfig and update data Secret" as it didn't test what it said it did.
**Checklist**:
```release-note
NONE
```
> eksconfig reconciler tests: Remove race conditions

- Makefile
/kind bug
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2604
**Checklist**:
```release-note
NONE
```
> Makefile release fixes

- Makefile
Backport of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2605
Fixes #
**Checklist**:
```release-note
NONE
```
> [Backport] Makefile release fixes

- bootstrap/eks/config/manager/manager.yaml
/kind bug
The nodeaffinity definitions were incorrect, which caused  a validation failure on the manager deployments.
Fixes #2624 
**Checklist**:
```release-note
NONE
```
> fix: node affinity definitions incorrect

- Makefile
/kind bug
Fixes #
**Checklist**:
```release-note
NONE
```
> Release note creation should be based on 0.6 branch

- config/manager/manager.yaml
/kind feature
This PR adds log-level for artifacts logs of the E2E test runs which would be useful for development/debugging.
**Checklist**:
```release-note
Controller log level can be set using the CAPA_LOGLEVEL variable. Defaults to 0.
```
> Add log-level customization for artifact logs in E2E runs

- metadata.yaml
/kind cleanup
Fixes releases
**Checklist**:
```release-note
NONE
```
/priority important-soon
> metadata.yaml: Correct version

- docs/book/src/development/tilt-setup.md
I was following the documentation and encountered a broken link. The PR fixes the broken link.
**Checklist**:
```release-note
NONE
```
> fix broken link in docs

- docs/book/Makefile
- docs/book/gen-crd-api-reference-docs/config.json
- docs/book/src/SUMMARY_SUFFIX.md
Fixes #2680 
**Checklist**:
```release-note
NONE
```
> netlify: Attempt to resolve build speed issues

- exp/api/v1alpha4/awsfargateprofile_webhook.go
- pkg/cloud/services/eks/fargate.go
- pkg/cloud/services/eks/tags.go
/kind feature
This PR adds support to create and update fargate profile tags.
Currently the fargate profile spec is immutable. Validation should allow profile tags to be updated.
Fixes #2675 
**Checklist**:
```release-note
EKS: Add support to create and update tags for a Fargate Profile
```
> Fargate profile tags

- docs/book/src/topics/external-cloud-provider-with-ebs-csi-driver.md
/kind bug
Adding formatting in [doc](https://cluster-api-aws.sigs.k8s.io/topics/external-cloud-provider-with-ebs-csi-driver.html) 
Fixes #
**Checklist**:
```release-note
NONE
```
> fix: doc formatting

- docs/book/src/development/development.md
/kind bug
Fix the broken link in the doc
Fixes #
**Checklist**:
```release-note
NONE
```
> Fix the broken link in the doc

- bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
- bootstrap/eks/controllers/eksconfig_controller_test.go
- go.mod
- go.sum
/kind bug
The version bump of controller runtime brings gomega version update which breaks some existing tests, this PR is to fix those tests.
Fixes #
**Checklist**:
```release-note
NONE
```
> Fix the gomega errors in tests with the controller runtime version bump

- Dockerfile
- Makefile
- versions.mk
/kind cleanup
Use same golang version everywhere
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2736
This change will ensure that the same golang version has been used everywhere like building the binaries everywhere including binaries built in the dockerfile, outside.
**Checklist**:
```release-note
NONE
```
> Use same golang version everywhere

- docs/book/src/development/releasing.md
/kind cleanup
Related:
- Part of: https://github.com/kubernetes/community/issues/6036
- Followup to: https://github.com/kubernetes/test-infra/pull/23694
Follow the rename of wg-k8s-infra assets to sig-k8s-infra
n/a
```release-note
NONE
```
> docs: mv wg-k8s-infra sig-k8s-infra

- pkg/cloud/services/ec2/instances.go
- pkg/cloud/services/ec2/instances_test.go
/kind bug
Previously, PublicIP field in AWSMachine Spec didn't work. 
With the fix, when AWSMachine.Spec.PublicIP is set to true, an instance is launched in a public subnet with public IP.
If there is no matching public subnet, an instance fails to launch.
Fixes # https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2653
**Checklist**:
```release-note
When AWSMachine.Spec.PublicIP is set true, an instance is launched in a public subnet with public IP.
```
> Make PublicIP field in AWSMachine Spec work

- api/v1alpha4/awsmachine_types.go
- api/v1alpha4/awsmachine_webhook_test.go
- api/v1alpha4/awsmachinetemplate_webhook_test.go
- api/v1alpha4/sshkeyname_test.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
- exp/instancestate/awsinstancestate_controller_test.go
/kind bug
Validation added for empty InstanceType in AWSMachine and AWSMachineTemplate.
Fixes #2686
**Checklist**:
```release-note
Validation added for empty InstanceType in AWSMachine and AWSMachineTemplate.
```
> Validation added for empty instanceType in AWSMachine and AWSMachineTemplate

- Makefile
- docs/book/src/.gitignore
- docs/book/src/crd/index.md
Fixes #
Moving CRD doc generation into the repo to speed up Netlify builds.
**Checklist**:
```release-note
NONE
```
> Move generation of CRD docs to the repo to speed up Netlify

- config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
- exp/api/v1alpha3/conversion.go
- exp/api/v1alpha3/zz_generated.conversion.go
- exp/api/v1alpha4/awsmanagedmachinepool_types.go
- exp/api/v1alpha4/zz_generated.deepcopy.go
- exp/controllers/awsmanagedmachinepool_controller.go
- main.go
- pkg/cloud/scope/managednodegroup.go
- pkg/cloud/services/eks/roles.go
/kind feature
The node group role that is created per node group contains a list of default/pre-defined policies. This PR adds a property in AWSManagedMachinePool to allow attaching additional policies to this node group role.
Fixes #2750 
**Checklist**:
```release-note
EKS: Support role additional policies for AWSManagedMachinePool
```
> EKS: support role additional policies for AWSManagedMachinePool

- main.go
Controller runtime sets by default leader-election-resource-lock to ConfigMapsLeasesResourceLock so consumers can do smooth transitions.
This PR default our contorller to leases.
This mitigates overwhelming the apiserver in a large management cluster and avoid additional rbac.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2827
**Checklist**:
```release-note
Expose leader-election-resource-lock as a flag
```
> Default LeaderElectionResourceLock to leases

- api/v1alpha3/awscluster_types.go
- api/v1alpha3/types.go
- api/v1alpha4/awscluster_types.go
- api/v1beta1/awscluster_webhook.go
- api/v1beta1/awscluster_webhook_test.go
- api/v1beta1/defaults.go
- api/v1beta1/network_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
- pkg/cloud/services/elb/loadbalancer.go
/kind bug
Fixes #2801 
**Checklist**:
```release-note
Correct the casing of the ELB load balancer scheme from `Internet-facing` to `internet-facing`, allowing the ELB to be correctly continuously reconciled
```
/area api
/kind release-blocking
/milestone v1.0.0
> Fix for internet-facing ELB scheme

- docs/book/src/topics/machinepools.md
- templates/cluster-template-machinepool.yaml
/kind bug
Added AvailabilityZone variable in [cluster-template-machinepool.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/templates/cluster-template-machinepool.yaml#L97)
Fixes #2872 
**Checklist**:
```release-note
Added AvailabilityZone variable in machinepool template
```
> AvailabilityZone variable added in template

- pkg/cloud/services/eks/nodegroup.go
/kind bug
fix assignment to AddOrUpdateLabels in nil map of `UpdateLabelsPayload{}`
Fixes #2893
**Checklist**:
```release-note
Fix createLabelUpdate panic in nil map
```
> Fix createLabelUpdate panic in nil map

- docs/book/src/topics/consuming-existing-aws-infrastructure.md
Along with https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2383 fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2356
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2356
**Checklist**:
```release-note
Include docs for externally managed infrastructure.
```
> Add externally managed infrastructure docs

- clusterctl-settings.json
/kind feature
Updated clusterctl-settings next version to `v1.0.0`
Fixes #
**Checklist**:
```release-note
NONE
```
> Update clusterctl-settings next version

- bootstrap/eks/README.md
- bootstrap/eks/api/v1alpha3/condition_consts.go
- bootstrap/eks/api/v1alpha4/condition_consts.go
- bootstrap/eks/api/v1beta1/condition_consts.go
As now cluster-api repo has already renamed it's branch name to main, for clarity and ease the same change shpuld be reflected in few of the repo.
Fixes #2913 
**Checklist**:
```release-note
Update references to Cluster API main branch
```
> Branch name change from master to main

- hack/gen-test-flavors.sh
- test/e2e/data/infrastructure-aws/README.md
/kind cleanup
Just some small stuff found along the way.
```release-note
NONE
```
> Test flavors small improvements

- README.md
- docs/book/src/SUMMARY_PREFIX.md
- docs/book/src/crd/index.md
- docs/book/src/topics/images/amis.md
- docs/book/src/topics/images/built-amis.md
- docs/book/src/topics/images/custom-amis.md
- docs/book/src/topics/userdata-privacy.md
Add a page explaining how custom images can be built using image-builder.
Fixes #
**Checklist**:
```release-note
Added instructions on how to build and use custom images.
```
/triage accepted
/priority backlog
/milestone Backlog
> Add custom image generation to the book

- metadata.yaml
/kind bug
Fixes #
**Checklist**:
```release-note
NONE
```
> Add v1.1 release to metadata file

- test/e2e/data/e2e_conf.yaml
- test/e2e/data/infrastructure-aws/kustomize_sources/upgrades/kustomization.yaml
- test/e2e/data/infrastructure-aws/kustomize_sources/upgrades/machine-pool.yaml
- test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
Adds cluster upgrade and conformance spec based on CAPI cluster upgrade test framework.
Fixes #2935
**Checklist**:
```release-note
Adds cluster upgrade and conformance spec based on CAPI cluster upgrade test framework
```
> Add workload cluster upgrade and conformance spec

- docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md
The documentation assumes that the reader's AWS CLI is configured to use the output format of `json`. As that format is needed by commands that the output is piped to. This is not a safe assumption. This PR explicitly specifies the output format.
Fixes #2981 
**Checklist**:
```release-note
Updated documentation to specify JSON output for AWS CLI commands.
```
> docs: Update output format for ssh-key-pair generate

- docs/book/src/development/tilt-setup.md
Minor updates to the tile development doc to bring it in line with the
v0.7.0+ releases where EKS is enabled by default.
Also, added a section on using the debugger with tilt.
Fixes #
**Checklist**:
```release-note
Updated tilt development docs for v0.7.0+ and debugging.
```
> docs: updated tilt development documentation

- OWNERS_ALIASES
- test/e2e/suites/unmanaged/unmanaged_functional_test.go
Fixes #
**Checklist**:
```release-note
```
> Disable GPU test until it is fixed

- api/v1beta1/network_types.go
The field is optional due to omitempty tag but to have same convention everywhere added the optional tag.
Fixes #
**Checklist**:
```release-note
NONE
```
> Add optional tag to ELB name field

- exp/instancestate/awsinstancestate_controller.go
/kind bug
This PR fixes the SQS queue non existing errors from CAPA logs.
Fixes #2912 
**Checklist**:
```release-note
Fix recurring AWS.SimpleQueueService.NonExistentQueue error messages from CAPA logs
```
> Fix the AWS.SimpleQueueService.NonExistentQueue errors in CAPA logs

- exp/instancestate/awsinstancestate_controller.go
/kind cleanup
Fixes #
**Checklist**:
```release-note
NONE
```
> Remove unnecessary log from AWSInstanceState controller

- metadata.yaml
Fixes #
**Checklist**:
```release-note
NONE
```
> Update metadata file

- config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
- controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_types.go
- controlplane/eks/api/v1alpha4/awsmanagedcontrolplane_types.go
- controlplane/eks/api/v1beta1/awsmanagedcontrolplane_types.go
- docs/book/src/crd/index.md
fixes typos.
Fixes #
**Checklist**:
```release-note
NONE
> Fix typos in DisableVPCCNI description

- README.md
/kind cleanup
Fix broken link in the project readme and book introduction.
Fixes #
N/A
**Checklist**:
```release-note
NONE
```
> docs: fix broken link in docs

- controlplane/eks/api/v1alpha3/conversion.go
/kind bug
The `AWSManagedControlPlane` object conversion from `v1alpha3` to
`v1alpha4` were not considering new fields in status and spec. The bug
is covered by tests, but these are failing silently at the moment as
**Checklist**:
```release-note
Bugfix in  `AWSManagedControlPlane` object conversion from v1alpha3 to v1beta1. Some fields in Status and Spec were not being considered during conversion
```
> [backport 0.7] Fix AWSManagedControlPlane conversion

- OWNERS_ALIASES
This PR adds @pydctw  to CAPA reviewers.
@pydctw has been working on CAPA issues and actively reviewing PRs for a while now.
Fixes #
```release-note
Promote @pydctw to reviewers
```
> Promote pydctw to reviewers

- test/e2e/data/e2e_conf.yaml
- test/e2e/data/e2e_eks_conf.yaml
- test/e2e/shared/context.go
- test/e2e/shared/defaults.go
- test/e2e/shared/suite.go
- test/e2e/suites/unmanaged/unmanaged_CAPI_quick_test.go
- test/e2e/suites/unmanaged/unmanaged_CAPI_quick_test_cluster_class.go
- test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
- test/e2e/suites/unmanaged/unmanaged_functional_test.go
Enabled GPU e2e test again and fixed EC2 resource requests in e2e (EC2 resource quota calculations were wrong because instead of counting vCPU usage, instance number was being counted).
Fixes #
**Checklist**:
```release-note
```
> Enable GPU test

- docs/book/src/development/development.md
Fixed the inconsistency in path in developer guide.
Fixes #
**Checklist**:
```release-note
NONE
```
> docs: fix path inconsistency in developer guide

- OWNERS
- OWNERS_ALIASES
/kind cleanup
With regret, I will be stepping away from Cluster API and won't be around to review PRs, so need to take myself out of the loop.
Fixes #
**Checklist**:
```release-note
NONE
```
> OWNERS: Move randomvariable to emeritus

- README.md
Added the list contributor images to the readme.
Fixes #
**Checklist**:
```release-note
Add contributors to the README.
```
> docs: added contributors list to the README

- controllers/awscluster_controller.go
- controllers/awsmachine_controller.go
/kind cleanup
While reading the code, noticed that awsmachine and awscluster controllers use its own predicate functions for watching a Cluster that could be replaced with CAPI util functions. 
Note that we are already using them in [awsmanagedcontrolplane_controller.go](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/50af6ec5ce7a183b67d23a187e687c42fef24176/controlplane/eks/controllers/awsmanagedcontrolplane_controller.go#L94)
Continuously refactoring the code to make it cleaner and easy to read.
Fixes # …
> Replace predicate functions with CAPI util functions

- docs/book/src/topics/eks/creating-a-cluster.md
- docs/book/src/topics/specify-management-iam-role.md
The doc example is using `v1.17.3` as EKS version and it is outdated.
See the available EKS versions - https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
Also, fixed typos in the doc.
Fixes #
**Checklist**:
```release-note
NONE
```
> Update k8s version in EKS doc

- OWNERS
- README.md
/kind feature
Related issue containing the discussion for change https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3104
Fixes #3104
**Checklist**:
```release-note
Fix unknown fields of the OWNER field in light of the new parser tool located [here](https://github.com/dims/maintainers).
```
> Fixing the fields for the new OWNER audit tool

- README.md
Updates the office hours times and also adds current maintainers/reviewers to the readme.
Fixes #
**Checklist**:
```release-note
NONE
```
> docs: updated the README with the updated office hours times

- pkg/cloud/services/network/subnets.go
- pkg/cloud/services/network/subnets_test.go
/kind cleanup
`deleteSubnets` function calls `describeVpcSubnets` that makes multiple calls to AWS API although it only needs subnet IDs. 
Refactored the code to remove unnecessary calls, DescribeRouteTables and DescribeNatGatewaysPages, to AWS API during subnet deletion.
I also set up tests for deleteSubnets, which was missing. Plan to add more test cases as part of #3074.
Fixes #
**Checklist**:
```release-note
NONE
```
> Remove unnecessary calls to AWS API during subnet deletion

- docs/book/src/development/tilt-setup.md
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2890
**Checklist**:
```release-note
```
> Fix cluster-api tilt reference in the book

- test/e2e/shared/aws.go
/kind bug
**What this PR does / why we need it**:  Changes ECR lookup to match ECR created when error is found.
Fixes #3132 
**Checklist**:
```release-note
Fixes ECR describe when searching for previously created ECR so that names match.
```
> Fix e2e ECR creation/lookup

- pkg/cloud/tags/tags.go
- pkg/cloud/tags/tags_test.go
/area testing
This PR increases the unit tests coverage for package pkg/cloud/tags. The coverage of package has increased from 3.9% to 98%
Part of #2910 
**Checklist**:
```release-note
Add unit tests for package pkg/cloud/tags
```
> Add unit tests for package pkg/cloud/tags

- test/e2e/data/e2e_eks_conf.yaml
- test/e2e/suites/unmanaged/unmanaged_functional_test.go
/kind cleanup
Extracted independent changes from #2271 so they can be quickly merged.
```release-note
NONE
```
> test/e2e: fix typo and some formatting

- go.mod
- go.sum
- test/e2e/data/e2e_conf.yaml
- test/e2e/data/e2e_eks_conf.yaml
/kind api-change
This PR bumps CAPI version to v0.4.7 in CAPA release-0.7
Fixes #3141 
**Checklist**:
```release-note
Bump CAPI to v0.4.7 for CAPA v0.7
```
> Bump CAPI to v0.4.7

- Makefile
/kind cleanup
Changing the way the branch name is determined to be consistent with the
other release branches.
Fixes #
**Checklist**:
```release-note
NONE
```
> release: consistent branch name determination

- Makefile
/kind bug
Added branch variable in release-changelog
Fixes #3148 
**Checklist**:
```release-note
NONE
```
> Add branch variable in release-changelog

- Makefile
- api/v1alpha4/awscluster_conversion.go
- api/v1alpha4/awsclustertemplate_conversion.go
- api/v1beta1/conversion.go
- cmd/clusterawsadm/ami/helper_test.go
- hack/tools/Makefile
- hack/tools/tools.go
`/kind feature`
* Added conversion functions for `AWSClusterTemplateList`
* Added integration for `conversion-verifier` in CI with `verify-conversions` make target
* Added k8s boilerplate text to `cmd/clusterawsadm/ami/helper_test.go`
Fixes #3085, fixes #3127 
**Checklist**:
```release-note
Integrated `conversion-verifier` in CI
```
> Integrated `conversion-verifier` in CI

- pkg/cloud/services/network/routetables_test.go
/area testing
This PR increases the unit tests coverage for pkg/cloud/services/network/routetables package.
Part of https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2910
**Checklist**:
```release-note
Add unit tests for `pkg/cloud/services/network/routetables` package
```
> Added unit tests for pkg/cloud/services/network/routetables

- pkg/cloud/services/eks/fargate.go
- pkg/cloud/services/eks/nodegroup.go
- pkg/cloud/services/network/natgateways.go
/kind bug
This PR checks if a error is present already and then only makes use of the errors.Wrapf functionality else it returns a custom error. This should prevent unnecessary timeouts during implementation
Fixes #3179 
**Checklist**:
```release-note
None
```
> Use Wrapf for errors only when err is not nil

- pkg/cloud/services/network/gateways_test.go
/area testing
Added test cases in gateway.go file
Part of #2910 
**Checklist**:
```release-note
Test coverage for gateway.go updated to 72%
```
> Test cases added for gateway.go

- pkg/cloud/services/securitygroup/securitygroups.go
- pkg/cloud/services/securitygroup/securitygroups_test.go
/area testing
Added test cases for pkg/cloud/services/securitygroup 
Part of #2910 
**Checklist**:
```release-note
Added test cases for pkg/cloud/services/securitygroup and increased coverage to 78%
```
> Added test cases for pkg/cloud/services/securitygroup

- go.mod
- go.sum
- test/e2e/data/e2e_conf.yaml
- test/e2e/data/e2e_eks_conf.yaml
Fixes #
**Checklist**:
```release-note
Bump cluster-api to v1.1.1
```
/area release
> Bump CAPI to v1.1.1

- pkg/cloud/services/network/vpc_test.go
/area testing
This PR increases the unit tests coverage for pkg/cloud/services/network/vpc package.
Part of #2910 
**Checklist**:
```release-note
Add unit tests for `pkg/cloud/services/network/vpc` package
```
> Added unit test cases for pkg/cloud/services/network/vpc

- pkg/cloud/services/network/natgateways.go
- pkg/cloud/services/network/natgateways_test.go
/area testing
This PR increases the unit tests coverage for pkg/cloud/services/network/natgateway package.
Part of #2910 
**Checklist**:
```release-note
Add unit tests for `pkg/cloud/services/network/natgateway` package
```
> Added unit tests for pkg/cloud/services/network/natgateway package

- pkg/cloud/services/network/eips.go
- pkg/cloud/services/network/eips_test.go
/area testing
Added test cases for eips.go
Part of #2910 
**Checklist**:
```release-note
Added test cases for eips.go and increase coverage to 78%
```
> Test cases added for eips.go

- go.mod
- go.sum
- test/e2e/data/e2e_conf.yaml
- test/e2e/data/e2e_eks_conf.yaml
/area release
Fixes #
**Checklist**:
```release-note
Bump cluster-api to v1.1.2
```
> Bump CAPI to v1.1.2

- README.md
/kind feature
This PR adds a join slack badge in CAPA repo for k8s `cluster-api-aws` channel.
Now we can see <img src="https://img.shields.io/badge/join%20slack-%23cluster--api--aws-brightgreen"> badge in CAPA repository.
Fixes #
**Checklist**:
```release-note
Added a join slack badge in CAPA repo Readme.md
```
> Added a join slack badge in CAPA repo for k8s cluster-api-aws channel

- README.md
/area security
This PR adds OpenSSF best practices badge to the repository so that it will be easier to check if we are adhering to security standards and if not, then would be able to raise appropriate issues for the same.
Fixes #3062 
**Special notes to the reviewers**:
Please provide feedback on the info provided in OpenSSF related to our project [here](https://bestpractices.coreinfrastructure.org/en/projects/5688). I will make desired changes.
**Checklist**:
```release-note
Added OpenSSF best practices badge in README.md.
```
> Added OpenSSF best practices badge to README.md

- pkg/cloud/services/network/secondarycidr.go
- pkg/cloud/services/network/secondarycidr_test.go
/area testing
Added test case for secondarycidr.go file
Part of #2910 
**Checklist**:
```release-note
Test coverage for secondarycidr.go updated to 96%
```
> Test cases added for secondary cidr file

- pkg/cloud/services/ec2/ami_test.go
- pkg/cloud/services/ec2/helper_test.go
- pkg/cloud/services/ec2/launchtemplate.go
- pkg/cloud/services/ec2/launchtemplate_test.go
/area testing
This PR increases the unit tests coverage for launchtemplate.go file.
Part of #2910 
Kindly **add any missing scenario in the original issue #2910**. Decided to track all missing scenarios in future PR
**Checklist**:
```release-note
Added unit test cases for launchtemplate.go and increased coverage to 82%
```
> Added unit test cases for launchtemplate.go

- metadata.yaml
/kind cleanup
(no idea if this is the right type TBH)
Adds missing update to the repositories' manifest.yaml
```release-note
NONE
```
> update manifest to match latest release

- README.md
Updated Readme.md, added flatcar and some beautification
Fixes #
**Checklist**:
```release-note
NONE
```
> Readme updated with OS name and indentation

- docs/book/src/development/development.md
/kind cleanup
The install instructions link for kustomize in developer guide was showing 404 error.
See the slack conversation [here](https://kubernetes.slack.com/archives/CD6U2V71N/p1647691620238309)
```release-note
NONE
```
> update kustomize install instructions

- hack/tools/go.mod
- hack/tools/go.sum
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>
/kind feature
- Bump to golangci-lint v1.45.2
Fixes #
**Checklist**:
```
Bump to golangci-lint v1.45.2
```
> Bump to golangci-lint v1.45.2

- metadata.yaml
> Add v1.4 release to metadata.yaml

- test/e2e/shared/aws.go
Since validation of infrastructure creation was moved a scenario can occur where a VPC fails to get created and the test panics when an attempt to create dependent resources is made.
/kind bug
Fixes #3371 
**Checklist**:
> Move several functions under E2E CreateInfrastructure to panic

- controllers/awsmachine_controller.go
- controllers/awsmachine_controller_unit_test.go
git cherry-pick d15f9bcf27caa1f7157b0f7d17127a49b8dea261
git cherry-pick 823459d83416f6d3b063ac9496be4879141ed66d
Fixes #
**Checklist**:
> Backport #3400 to 1.4 branch

- test/e2e/data/e2e_conf.yaml
- test/e2e/data/infrastructure-aws/kustomize_sources/efs-support/aws-efs-csi-external.yaml
- test/e2e/data/infrastructure-aws/kustomize_sources/efs-support/csi-resource-set.yaml
- test/e2e/data/infrastructure-aws/kustomize_sources/efs-support/kustomization.yaml
- test/e2e/data/infrastructure-aws/kustomize_sources/efs-support/patches/efs-support.yaml
- test/e2e/shared/aws.go
- test/e2e/shared/defaults.go
- test/e2e/shared/template.go
- test/e2e/suites/unmanaged/helpers_test.go
- test/e2e/suites/unmanaged/unmanaged_functional_test.go
/kind feature
Adding an E2E test to install and verify EFS CSI driver in a CAPA managed cluster.
Fixes #3384 
**Checklist**:
> [E2E] EFS CSI driver support

- test/e2e/shared/aws.go
Change in timeout for functions and additional verbosity
/kind bug
Adds retry logic to GetSubnetByName function within CreateNatGateway.
Fixes #3469 
**Checklist**:
> [E2E] Add retry and timeout to GetSubnetByName in CreateNatGateway

- templates/cluster-template-multitenancy-clusterclass.yaml
- templates/cluster-template-simple-clusterclass.yaml
This PR publishes validated multi-tenancy and quick-start ClusterClass templates.
Fixes #
**Checklist**:
> Add ClusterClass templates

- test/e2e/suites/unmanaged/unmanaged_functional_test.go
/kind bug
Disable external infrastructure e2e test until RC can be determined for resource creation failures
Fixes #3498 
**Checklist**:
> [E2E] Disable external infrastructure test

- docs/book/src/SUMMARY_PREFIX.md
- docs/book/src/topics/full-multitenancy-implementation.md
Following a discussion in slack I'm adding a full example of the multi-tenancy implementation with EKS and cross account role
@sedefsavas better late than never ;) 
**Checklist**:
> first multitenancy example

- hack/gen-test-flavors.sh
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-csimigration-off.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-efs-support.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-external-cloud-provider.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-external-csi.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-external-infrastructure.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-gpu.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-ignition.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-internal-elb.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-kcp-remediation.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-kcp-scale-in.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-limit-az.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-machine-pool.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-md-remediation.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-multi-az.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-nested-multitenancy-clusterclass.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-nested-multitenancy.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-peered-remote.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-remote-management-cluster.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-simple-multitenancy.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-spot-instances.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-ssm.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-topology.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-upgrade-to-main.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-upgrades.yaml
- test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template.yaml
Publishing test templates in the repo will increase the visibility of what is being tested and what is missing for all the users; general users/new contributors are having hard time locating them in Prow. Also, there are lots of use cases covered in the e2e tests which might provide examples.
As a follow up to this, we also need to decide a set of auto-generated generic templates to publish.
Fixes #
**Checklist**:
> Publish e2e templates

- Makefile
- docs/book/src/development/e2e.md
- docs/book/src/topics/reference/jobs.md
/kind cleanup
Streamlining Ginkgo variables in Makefile to improve consistency with other providers and allowing easier usage in `test-infra`
Fixes #3390 
None
**Checklist**:
> Streamline Ginkgo variables

- Makefile
- hack/ensure-kind.sh
- hack/ensure-kubectl.sh
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>
/kind feature
- Make CAPA tooling work on arm64
Fixes #2930 
**Checklist**:
> Make CAPA tooling work on arm64

- docs/roadmap.md
This updates the roadmap docs to include a link to the issue documenting Windows Worker Node support to CAPA.
Fixes #
**Checklist**:
> Adding Roadmap Update for Windows Support

- docs/book/src/topics/full-multitenancy-implementation.md
Improve newcomer experience by fixing a few typos in the documentation
Fixes #3551
**Checklist**:
> update docs to improve new developer experience

- config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
- controlplane/eks/api/v1beta1/awsmanagedcontrolplane_types.go
- docs/book/src/topics/eks/pod-networking.md
- test/e2e/data/eks/cluster-template-eks-control-plane-only-withaddon.yaml
/kind bug
The json tag for vpcCni is uppercase. `VpcCni:`. This is a quick fix for that.
Fixes #
**Checklist**:
> Fix the json tag for VpcCni

- test/e2e/data/kubetest/conformance-fast.yaml
Forgot to make the change https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3586 for the fast conformance.
Fixes #
**Checklist**:
> Increase fast conformance test timeout

- scripts/ci-conformance.sh
- scripts/ci-e2e.sh
We identified in CAPO that with the latest kubekins-e2e image `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220720-b949db7485-master` the pip3 location `/usr/bin/pip3.7` does no longer exists.
```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.7'
```
[pull-cluster-api-provider-openstack-e2e-test/1550462495938842624](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1307/pull-cluster-api-provider-openstack-e2e-test/1550462495938842624)
In PR https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1307 we're changing this by setting a symlink. 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes …
> 🐛 Ensure that python and pip is installed for e2e and conformance tests

- exp/api/v1beta1/awsmanagedmachinepool_webhook.go
*What type of PR is this?**
/kind bug
Fixes #3435 
**Checklist**:
> feat: defaulting for update config

- docs/adr/0005-graduation of EventBridge.md
> Changed EventBridge ADR status to "Accepted"

- OWNERS_ALIASES
- README.md
This PR adds @Skarlso to CAPA reviewers.
@Skarlso has been actively contributing to CAPA for a while, working on the IPv6 support at the moment and willing to continue to contribute more with reviews. 
Fixes #
**Checklist**:
> Promote Skarlso to reviewer

- metadata.yaml
> Add 1.5 version to metadata file

- controllers/awsmachine_controller.go
/kind cleanup
Fixes #3454
**Checklist**:
> bugfix: Fix log level for a couple of message of log messages

- docs/book/src/development/releasing.md
> Update release steps

- test/e2e/data/e2e_conf.yaml
- test/e2e/data/infrastructure-aws/kustomize_sources/self-hosted-clusterclass/kustomization.yaml
- test/e2e/data/infrastructure-aws/kustomize_sources/self-hosted-clusterclass/limited-az-variable.yaml
- test/e2e/data/infrastructure-aws/kustomize_sources/self-hosted-clusterclass/self-hosted-variable.yaml
- test/e2e/data/infrastructure-aws/kustomize_sources/topology/clusterclass-quick-start.yaml
- test/e2e/shared/defaults.go
- test/e2e/suites/unmanaged/unmanaged_CAPI_clusterclass_test.go
/kind feature
Add self-hosted test based on ClusterClass
Part of #3346 
**Checklist**:
> Add self-hosted test based on ClusterClass

- test/e2e/suites/unmanaged/unmanaged_CAPI_clusterclass_test.go
/kind feature
Add Cluster Upgrade tests based on ClusterClass
Part of #3346 
**Checklist**:
> Add Cluster Upgrade tests based on ClusterClass

- pkg/internal/cidr/cidr_test.go
Fixing the cidr package a bit, the tests had a weird package/import which made no sense and since I was in the `SplitIntoSubnetsIPv4` code anyway trying to figure out what it does I wrote some unit tests for it.
/kind cleanup
Fixes #
**Checklist**:
> fixing package issues and adding SplitIntoSubnetsIPv4 unit tests

- docs/book/src/topics/multitenancy.md
> Fixing typo in documentation

- .gitattributes
for context in capz i did this too: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2417
> adding gitattributes for easier dev on windows os using wsl

- metadata.yaml
> Add v2.0 to metadata

- pkg/cloud/services/eks/identity_provider.go
Not sure why the interface func wasn't on this line when it was used a few lines below. updating for consistency.
/kind cleanup
Fixes #
**Checklist**:
> switch to using interface func for consistency

- OWNERS
- OWNERS_ALIASES
/kind cleanup
Backport the maintainer/reviewer updates.
Fixes #
**Checklist**:
> chore: Backport maintainer/reviewer updates to release-1.6

- OWNERS
- OWNERS_ALIASES
/kind cleanup
Backport the maintainer/reviewer updates.
Fixes #
**Checklist**:
> chore: Backport maintainer/reviewer updates to release-1.5

- docs/book/src/development/releasing.md
I recently released v1.5.1 with the help of @richardcase, @Skarlso, and @Ankitasw. We made some corrections to the the release process guide as we followed it, and this PR has those changes, plus some improvements to formatting, like additional headings, and dynamically-numbered markdown lists.
Fixes #
**Checklist**:
> docs: Refactor release process guide

- controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook.go
/kind bug
Safer nil pointer checking on a string pointer so we attempt to parse an empty string if nil
Fixes #3768
**Checklist**:
> More nil checks for Version

- docs/book/src/crd/index.md
Although we have been developing v1beta2 for a few months, the book CRD reference has not been updated as a result, most likely due to our Makefile targets making it look like the reference is already update to date. I'll look into that issue, but for now, here's an update to the reference. 
Fixes #
**Checklist**:
> docs: Update CRD reference with v1beta2 API

- test/e2e/shared/aws.go
/area testing
/kind flake
VPC creation ocassionally takes time, because of which the tests are flaky. This PR fixes that flake, by adding GetVPC retrying mechanism just before the statement where it was throwing nil pointer exception.
This PR also replaces the for loops for timeouts with `Eventually` blocks, such that we don't have such flakes in future.
Fixes #3884 
**Checklist**:
> [E2E] Fix AWS services creation flake in external infrastructure test

- api/v1beta2/tags.go
- controllers/awscluster_controller_test.go
- controllers/awsmachine_controller_test.go
- controllers/helpers_test.go
- docs/book/src/topics/accessing-ec2-instances.md
- docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md
- pkg/cloud/services/autoscaling/autoscalinggroup_test.go
- pkg/cloud/services/ec2/instances_test.go
- pkg/cloud/services/network/egress_only_gateways_test.go
- pkg/cloud/services/network/gateways_test.go
- pkg/cloud/services/network/natgateways_test.go
- pkg/cloud/services/network/routetables_test.go
- pkg/cloud/services/network/subnets_test.go
- pkg/cloud/services/network/vpc_test.go
- pkg/cloud/services/secretsmanager/secret_test.go
- pkg/cloud/services/securitygroup/securitygroups_test.go
- pkg/cloud/services/ssm/secret_test.go
- pkg/cloud/tags/tags_test.go
- test/e2e/shared/aws.go
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>
**What type of PR is this?** 
/kind bug
**What this PR does / why we need it**: This PR fixes what was missed in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3867 
**Which issue(s) this PR fixes**:  Fixes #
**Checklist**:
> drop /v2/ from api/tests/docs

- docs/book/src/development/conventions.md
Fixed as bulleted sections appear to be represented by code blocks.
https://cluster-api-aws.sigs.k8s.io/development/conventions.html#dont-expose-3rd-party-package-types
Fixes #
**Checklist**:
> docs: fix broken bullet points

- api/v1beta2/network_types.go
- config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
/kind bug
Fixes #
**Checklist**:
> Make the LoadBalancerType optional in the Status

- bootstrap/eks/controllers/eksconfig_controller.go
- config/rbac/role.yaml
- controllers/awscluster_controller.go
- controllers/awsmachine_controller.go
- controllers/awsmanagedcluster_controller.go
- controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
- exp/controlleridentitycreator/awscontrolleridentity_controller.go
- exp/controllers/awsfargatepool_controller.go
- exp/controllers/awsmachinepool_controller.go
- exp/controllers/awsmanagedmachinepool_controller.go
/area security
/kind cleanup
This PR cleans up some of the unused permissions from RBAC for the CAPA resources.
Fixes #2335 
**Checklist**:
> Scope down RBAC permissions for CAPA resources

- docs/book/src/topics/eks/ipv6-enabled-cluster.md
- pkg/cloud/services/network/vpc.go
- pkg/cloud/services/network/vpc_test.go
/kind bug
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3912
**Checklist**:
> Only enable IPv6 if it's already enabled in the config

- README.md
This PR updates README.md with instruction to install clusterawsadm via Homebrew.
Fixes #
**Checklist**:
> Update README.md instruction to install clusterawsadm via Homebrew

- go.mod
- go.sum
- pkg/cloud/services/ssm/mock_ssmiface/ssmapi_mock.go
- test/mocks/aws_ec2api_mock.go
/area release
This PR bumps aws-iam-authenticator from 0.5.10 to 0.6.1
Fixes #
**Checklist**:
> Bump aws-iam-authenticator from 0.5.10 to 0.6.1

- OWNERS
- OWNERS_ALIASES
- README.md
> Move sedefsavas to emeritus

- api/v1beta1/network_types_test.go
- api/v1beta1/tags_test.go
- api/v1beta2/awscluster_webhook_test.go
- api/v1beta2/awsclustercontrolleridentity_webhook_test.go
- api/v1beta2/awsclusterroleidentity_webhook_test.go
- api/v1beta2/awsclusterstaticidentity_webhook_test.go
- api/v1beta2/awsmachine_webhook_test.go
- api/v1beta2/network_types_test.go
- api/v1beta2/sshkeyname_test.go
- api/v1beta2/tags_test.go
- bootstrap/eks/controllers/eksconfig_controller_test.go
- cmd/clusterawsadm/cloudformation/bootstrap/template_test.go
- controllers/awscluster_controller_test.go
- controllers/awscluster_controller_unit_test.go
- controllers/awsmachine_controller_test.go
- controllers/awsmachine_controller_unit_test.go
- controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook_test.go
- exp/api/v1beta2/awsfargateprofile_webhook_test.go
- exp/api/v1beta2/awsmachinepool_webhook_test.go
- exp/api/v1beta2/awsmanagedmachinepool_webhook_test.go
- pkg/cloud/services/ec2/ami_test.go
- pkg/cloud/services/ec2/launchtemplate_test.go
- pkg/cloud/services/eks/cluster_test.go
- pkg/cloud/services/s3/s3_test.go
/kind cleanup
Makes all testcases naming convention to conform to camel case standard 
Part of https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3198
Covers all testcases that were remaining.
**Checklist**:
> refactor: Improved all testcases naming convention conformity to camel case standard

- config/default/kustomization.yaml
- config/default/metrics_service.yaml
- config/manager/manager.yaml
- pkg/cloud/logs/logs.go
/kind feature
This PR exposes the Metrics port of the CAPA main controller.
Fixes #3856
**Checklist**:
> Expose Metrics port

- pkg/cloud/services/network/egress_only_gateways.go
- pkg/cloud/services/network/egress_only_gateways_test.go
- pkg/cloud/services/network/gateways.go
/kind bug
Should not delete EIGWs for unmanaged VPCs.
Fixes #3986
**Checklist**:
> Ignore EIGW deletion in case of unmanaged VPC

- api/v1beta2/awsmanagedcluster_types.go
- controllers/awsmanagedcluster_controller.go
Fix run of `hack/verify-boilerplate.sh` (and `make verify` altogether). Two files had an invalid boilerplate header.
none
**Checklist**:
> Fix boilerplate

- Makefile
- docs/book/src/development/e2e.md
- docs/book/src/topics/reference/jobs.md
/area testing
This PR replaces use of E2E_FOCUS with GINKGO_FOCUS.
Fixes #
**Checklist**:
> Replace E2E_FOCUS with GINKGO_FOCUS in all jobs

- controllers/awscluster_controller.go
/kind bug
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2090/files had introduced defaulting of `AWSCluster` values for valid reasons. However, `.Default()` changes field values and therefore `clusterScope.Close()` would detect differences and send a patch to the Kubernetes API – in every request to the reconciler. Since other controllers may also listen to changes (such as these patch operations) on `AWSCluster` objects, this can lead to a ping-pong situation where the controller keeps getting triggered despite no semantic change is happening. By defaulting the object fields before creating the `clusterScope` helper, we can avoid detecting the defaulting as difference, resulting in no unnecessary …
> Move defaulting before creation of patch helper so that no differences will be detected unnecessarily

- test/e2e/shared/aws.go
/kind bug
Not so important, since this will just save a single loop in the eventually.
Fixes #
**Checklist**:
> Fix error condition on eventually

- cmd/clusterawsadm/cloudformation/service/service.go
- cmd/clusterawsadm/cmd/bootstrap/iam/cloudformation.go
- pkg/cloud/services/securitygroup/securitygroups.go
- test/e2e/shared/aws.go
/kind bug
Fixes #
**Checklist**:
> fix: cleanup AWS CloudFormation stack in Test environment

- test/e2e/shared/aws.go
- test/e2e/shared/defaults.go
- test/e2e/shared/resource.go
- test/e2e/suites/gc_unmanaged/gc_unmanaged_test.go
- test/e2e/suites/unmanaged/unmanaged_CAPI_clusterclass_test.go
- test/e2e/suites/unmanaged/unmanaged_CAPI_quick_clusterclass_test.go
- test/e2e/suites/unmanaged/unmanaged_CAPI_quick_test.go
- test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
- test/e2e/suites/unmanaged/unmanaged_functional_clusterclass_test.go
- test/e2e/suites/unmanaged/unmanaged_functional_test.go
This PR increases resource quota for EventBridge rules in E2E tests.
Fixes #
**Checklist**:
> [E2E] Fix service quotas for EventBridge rules

- api/v1beta2/awscluster_webhook.go
Signed-off-by: hejianpeng <hejianpeng2@huawei.com>
/kind bug
fix error validating message of AWSCluster.Spec.NetworkSpec.VPC.ID
Fixes #
**Checklist**:
> fix error validating message

- docs/book/book.toml
fix wrong git repository url
Fixes #
**Checklist**:
> docs: fix git-repository-url

- cmd/clusterawsadm/cloudformation/service/service.go
- test/e2e/shared/aws.go
- test/e2e/shared/suite.go
/kind bug
Fixes #
**Checklist**:
> chore(ref): add more robustness to cloudformation stack create in tests

- test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-gpu.yaml
- test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/gpu/gpu-operator-components.yaml
/kind cleanup
This removes usage of images from the old `k8s.gcr.io` registry. This is important to help reduce the costs and with the pending changes to that old registry
Fixes #
**Checklist**:
> chore: remove usage of images from k8s.gcr.io

- cmd/clusterawsadm/cloudformation/service/service.go
- cmd/clusterawsadm/cmd/bootstrap/iam/cloudformation.go
- test/e2e/shared/aws.go
/kind bug
Fixes #
**Checklist**:
```release-note
```
> chore(ref): always clean roles and resources on cf stack failure

- test/e2e/shared/aws.go
- test/e2e/shared/suite.go
/kind bug
Fixes #
**Checklist**:
```release-note
```
> chore(ref): add output of error for role deletion

- test/e2e/shared/aws.go
/kind bug
Fixes #
**Checklist**:
```release-note
```
> chore(ref): fix error checking in eventually

- cmd/clusterawsadm/api/bootstrap/v1beta1/defaults.go
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
- test/e2e/shared/aws.go
/kind bug
Fixes #
**Checklist**:
```release-note
```
> bug: order of deleting cloud formation resources matters and fix missing GroupName setting from Bootstrap user

- hack/tools/go.mod
- hack/tools/go.sum
/area release
This PR bumps github.com/a8m/envsubst from 1.3.0 to 1.4.2 in /hack/tools
Fixes #4062 
**Checklist**:
> Bump envsubst in /hack/tools

- OWNERS_ALIASES
- README.md
It's proposed that we make @luthermonson a reviewer of CAPA. Please indicate agreement by `lgtm`, comment or 👍 
This will be open for 1 week for consensue (and until after the next office hours call). With a view to merge 8th March 2023
Fixes #
**Checklist**:
```release-note
Add Luther as a reviewer
```
/cc @Ankitasw @Skarlso @dlipovetsky
> [PROPOSAL]  add luther as reviewer

- cmd/clusterawsadm/ami/copy.go
- cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
- controllers/awsmachine_controller_test.go
- pkg/cloud/services/ec2/ami.go
- pkg/cloud/services/ec2/ami_test.go
- pkg/cloud/services/ec2/instances.go
- pkg/cloud/services/ec2/instances_test.go
- pkg/cloud/services/ec2/launchtemplate.go
- pkg/cloud/services/ec2/launchtemplate_test.go
/kind feature 
This PR is a continuation of the work done in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3208
Fixes #3121
**Checklist**:
> ✨ support arm64 AMI lookup based on instance type

- bootstrap/eks/controllers/eksconfig_controller.go
- controllers/awscluster_controller.go
- controllers/awsmachine_controller.go
- controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
- exp/controlleridentitycreator/awscontrolleridentity_controller.go
- exp/controllers/awsfargatepool_controller.go
- exp/controllers/awsmachinepool_controller.go
- exp/controllers/awsmanagedmachinepool_controller.go
/kind cleanup
Fixes #3849 
**Checklist**:
```release-note
Use klog to log errors instead of panic in controllers
```
> Use klog to log errors instead of panic in controllers

- test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/addons/csi/data/aws-ebs-csi-external.yaml
/area testing
This PR fixes the ebs-csi-driver properties due which the MHC tests are failing in the CI.
Follow up of #4147 
**Checklist**:
```release-note
Fix failing MHC test affected due to ebs-csi-driver version update
```
> [E2E] Fix failing MHC test affected due to ebs-csi-driver version update

- api/v1beta1/awscluster_types.go
- api/v1beta2/awscluster_types.go
- api/v1beta2/network_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
/kind bug 
Validates data submitted to healthCheck protocol field 
Fixes #4182 
**Checklist**:
```release-note
Adds validation for healthCheckProtocol Field 
```
> fix: adds enum validations to healtcheckprotocol field

- pkg/annotations/annotations_test.go
/kind feature
add tests for annotations.go
Fixes #4230 
**Checklist**:
```release-note
NONE
```
> added tests for annotations.go

- pkg/internal/rate/reset_test.go
/kind feature
To test whether all token are being reset or not after use
Fixes #4233 
**Checklist**:
```release-note
NONE
```
> added reset_test.go

- docs/proposal/20230317-irsa-support-for-awscluster.md
/kind design
Add a proposal to add IRSA functionality to self-managed clusters.
For context please see...
Issue: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3560
WIP PR: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4094
Discussion Opened: https://github.com/kubernetes-sigs/cluster-api-provider-aws/discussions/4153
```release-note
Add proposal for enabling IRSA for self-managed clusters.
```
> add IRSA for self-managed clusters proposal

- controllers/awsmachine_controller.go
/kind bug
When instance is still pending after newly recreation, we should explicitly requeue to ensure next reconciliation can happen in short time and then aws machine can becomes Ready status in time.
Fixes #4293
Choose` ctrl.Result{RequeueAfter: DefaultReconcilerRequeue}` rather than `ctrl.Result{Requeue: shouldRequeue} `.  Because the latter uses default exponential backoff. It has higher reconciling frequency like additional 8 times in 5 seconds, before the instances becomes running (at the 5rd second). It will cause api …
> Requque when awsmachine is pending

- test/e2e/suites/managed/upgrade_test.go
This PR fixes kubernetes version for EKS upgrade tests.
Part of https://github.com/kubernetes-sigs/cluster-api/issues/8784
**Checklist**:
```release-note
Fix kubernetes version for EKS upgrade tests
```
> [release-1.5] [E2E] Fix kubernetes version for EKS upgrade tests

- test/e2e/data/e2e_conf.yaml
/area testing
/kind flake
This PR enables the EventBridge feature in E2E tests.
Fixes #4090 
**Checklist**:
```release-note
NONE
```
> [E2E] Enable EventBridge in the tests

- controllers/helpers_test.go
- pkg/cloud/services/network/subnets.go
- pkg/cloud/services/network/subnets_test.go
/kind bug
Check TagUmanagedNetworkResources feature gate before adding tags for LBs.
Fixes #4340 
**Checklist**:
```release-note
Check TagUmanagedNetworkResources feature gate before adding tags for Load Balancers to subnets.
```
> check TagUmanagedNetworkResources feature gate before tagging subnets for LBs

- Dockerfile
/kind support
Switch public.ecr.aws to avoid hitting rate limiting with Dockerhub.
Fixes #
**Checklist**:
```release-note
NONE
```
> Use public.ecr.aws for golang image

- test/e2e/data/shared/v1beta2_provider/metadata.yaml
/kind support
This PR updates the metadata.yaml for the new minor release v2.2.0
Fixes #
**Checklist**:
```release-note
Update metadata.yaml
```
> [release-2.2] Update metadata.yaml

- metadata.yaml
/kind bug
The root metadata.yaml was missing the 2.1 and 2.2 release series which was causing an issue with the recent 2.2.0 release.
Fixes #
**Checklist**:
```release-note
Added missing release series to metadata.
```
> chore: update metedata.yaml with the release series

- controllers/awsmachine_controller.go
- exp/controllers/awsmachinepool_controller.go
/kind feature
The missing error details bugged me when troubleshooting a networking issue. They should not be swallowed.
**Checklist**:
```release-note
Wrap error messages for failing to retrieve infra provider cluster
```
> Wrap error message for failing to retrieve infra provider cluster

- Dockerfile
- Makefile
(cherry picked from commit 4ff5e377c6253372c7eedb6f7fdedaca61b89c27)
default golang version: 1.19.5
/kind support
Fixes #4401
**Checklist**:
```release-note
Customize golang version when compiling our binaries and images 
```
> Customize golang version

- cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_allow_assume_role.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
/kind bug
We should add the IAM role `elasticloadbalancing:SetSubnets` to the cloudformation templates and `clusterawsadm` as we are using it during reconciliation (thanks to @seanschneeweiss for finding the lines in the code):
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/2d96288354dee44e60710048652267e2bf3e8c12/pkg/cloud/services/elb/loadbalancer.go#L113-L123
Otherwise the following error will occur:
```
failed to reconcile load balancer" err=<
failed to set subnets for apiserver load balancer '...-apiserver': AccessDenied: User: arn:aws:sts::xxx:assumed-role/... is not authorized to perform: elasticloadbalancing:SetSubnets on resource: arn:aws:elasticloadbalancing:... because no identity-based …
```
> Add elasticloadbalancing:SetSubnets to cloudformation

- config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
- exp/api/v1beta2/types.go
- exp/controllers/awsmachinepool_controller_test.go
- pkg/cloud/services/autoscaling/autoscalinggroup.go
- pkg/cloud/services/autoscaling/autoscalinggroup_test.go
/kind feature
This PR adds support for new instance allocation strategies: `lowest-price` on-demand strategy, `capacity-optimized-prioritized` and `price-capacity-optimized` spot strategies.
More info: https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-mixed-instances-groups.html#allocation-strategies
Fixes #4160 
**Checklist**:
```release-note
Added support for new instance allocation strategies: lowest-price on-demand strategy, capacity-optimized-prioritized and price-capacity-optimized spot …
```
> Add new on-demand and spot allocation strategies

- exp/api/v1beta2/types.go
- pkg/cloud/services/gc/cleanup.go
/kind feature
This PR allows to configure garbage collection and define what clean-up tasks to execute during cluster deprovisioning.
Fixes #3541
**Checklist**:
```release-note
Make garbage collection configurable
```
> Make garbage collection configurable

- pkg/cloud/services/gc/compose.go
/kind bug
To fix it we need to add a missing boilerplate to the `pkg/cloud/services/gc/compose.go` file.
Currently `make verify-boilerplate` returns an error:
```
Boilerplate header is wrong for: /Users/mfedosin/projects/cluster-api-provider-aws/pkg/cloud/services/gc/compose.go
make: *** [verify-boilerplate] Error 1
```
Fixes #
**Checklist**:
```release-note
None
```
> Add missing boilerplate

- pkg/cloud/services/gc/cleanup_test.go
/kind support
This PR adds missing tests for garbage collector configuration: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4466
Fixes #
**Checklist**:
```release-note
None
```
> Add GC configuration tests

- scripts/ci-conformance.sh
- scripts/ci-e2e-eks-gc.sh
- scripts/ci-e2e-eks.sh
- scripts/ci-e2e-gc.sh
- scripts/ci-e2e.sh
/kind bug
Fixes #
Same as https://github.com/kubernetes/cloud-provider-openstack/pull/2414
**Checklist**:
```release-note
NONE
```
> :bug: Fix "error: externally-managed-environment" CI

- pkg/cloud/services/elb/loadbalancer.go
- pkg/cloud/services/elb/loadbalancer_test.go
/kind bug
Fixes #
**Checklist**:
```release-note
NONE
```
> :bug: ELBv2 target groups should inherit tags

- pkg/cloud/services/s3/s3.go
/kind bug
Without sorting, the tag list is indeterminate and results in a flaky unit test and flaky result in applied tag order.
Fixes #
**Checklist**:
```release-note
fix: sorting the tags list to make it determined
```
> fix: sorting the tags list to make it determined

- test/e2e/suites/unmanaged/unmanaged_functional_test.go
Fixes #
**Checklist**:
```release-note
NONE
```
> :bug: Fix race condition between cluster delete, and check

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/pr-verify.yml
This commit adds a verifier action that will check the title of the pull request.
Fixes #4556 
**Checklist**:
```release-note
Added verifier for action for pull request
```
> 🌱 Add verifier action for pull requests

- metadata.yaml
/kind feature
Add the required metadata entry for the 2.3.x release series.
Fixes #
**Checklist**:
```release-note
Update metadata for the v2.3.0 release
```
> ✨chore: update metadata for 2.3.0 release

- .github/dependabot.yml
/kind cleanup
Lets group dependabot updates and ignore some updates.
Fixes #
**Checklist**:
```release-note
Dependabot configuration update to hroup updates,
```
> 🐛 chore: update dependabot to group updates

- .github/dependabot.yml
/kind cleanup
More tweaks to dependabot config to ignore more dependencies
Fixes #
**Checklist**:
```release-note
NONE
```
> 🌱 chore: change the ignore dependabot updates

- OWNERS
- OWNERS_ALIASES
N/A
I don't actively work on CAPA anymore (haven't really for the past year) and I have less time to look at PRs these days so I think it's time to move me to emeritus.
N/A
**Checklist**:
```release-note
NONE
```
> 🌱 Move AverageMarcus to emeritus status

- docs/book/book.toml
Adds a fixed-url redirect https://cluster-api-aws.sigs.k8s.io/agenda to use as a meeting invite.
Fixes #
**Checklist**:
```release-note
NONE
```
> :book: Add /agenda redirect to book

- metadata.yaml
/kind support
Updating the meteadata file for the 2.4.x release series.
Fixes #
**Checklist**:
```release-note
Update metadata for v2.4.x release series.
```
> 🌱 chore: add release 2.4.x to metadata

- docs/book/src/development/releasing.md
Adds a couple of notes for the changes in the release process. 
Fixes #
**Checklist**:
```release-note
NONE
```
> :book:  docs: adds some notes for the release process

- config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
- controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
- controlplane/rosa/controllers/rosacontrolplane_controller.go
/kind bug
Fixes #
**Checklist**:
```release-note
None
```
> 🐛 ROSA: fix auto scale and multi zone compute nodes

- go.mod
- go.sum
- pkg/cloud/services/eks/mock_eksiface/eksapi_mock.go
- pkg/cloud/services/s3/mock_s3iface/s3api_mock.go
- pkg/cloud/services/secretsmanager/mock_secretsmanageriface/secretsmanagerapi_mock.go
- pkg/cloud/services/ssm/mock_ssmiface/ssmapi_mock.go
- test/mocks/aws_ec2api_mock.go
- test/mocks/aws_elbv2_mock.go
/kind support
This is a manual backport of #4916 (thanks @stefanmcshane) as the automated cherry pick failed.
Fixes #
**Checklist**:
```release-note
Bump aws-sdk-go to v1.51
```
> 🌱 [backport] Bump AWS SDK

- Makefile
Signed-off-by: Nolan Brubaker <nolan@nbrubaker.com>
/kind bug
When generating release notes, the `release-note` tool would only look at the `main` branch. This was a problem when creating a release with a tag in a different branch, since the tags that the tool was comparing were not actually made against `main`.
This PR specifies the branch to reference when generating the release notes.
Fixes #4926
**Checklist**:
```release-note
NONE
```
**Testing**:
Testing locally, setting `GITHUB_TOKEN` prior to invocation in …
> :bug: Use release branch when generating changelog

- metadata.yaml
/kind support
Updates the metadata.yaml file for v2.5.x and API support.
**Checklist**:
```release-note
NONE
```
> :seedling: Update metadata for v2.5.x

- .github/dependabot.yml
/kind support
ROSA pkgs can introduce conflicts that needs to be resolved manually.
Fixes #
**Checklist**:
```release-note
NONE
```
> 🌱 Update dependabot config to ignore rosa/openshift pkgs

- docs/book/src/SUMMARY_SUFFIX.md
- docs/book/src/development/nightlies.md
📖 Add documentation for nightly builds
```release-note
NONE
```
> 📖 Add documentation for nightly builds

- pkg/cloud/services/network/subnets.go
/kind bug
A subnet without an ID is not valid and patching the cluster later will get rejected by the validating webhook.
**Checklist**:
```release-note
Add ID to secondary subnets
```
> 🐛 Add ID to secondary subnets

- pkg/cloud/services/ec2/instances.go
/kind bug
When `publicIP: true` the controller can panic due to nil pointer dereference in case the filtered subnets are not among the ones defined under `AWSCluster.Spec.NetworkSpec.Subnets`.
```release-note
fix: check for nil matching subnet when publicIP: true
```
/cc. @r4f4
> 🐛 fix: check for nil matching subnet when publicIP: true

- OWNERS_ALIASES
Fixes #
**Checklist**:
```release-note
NONE
```
> 🌱 Remove vincepri from cluster-api-aws-maintainers

- OWNERS
- OWNERS_ALIASES
- README.md
/kind cleanup
This change moves @AndiDog from reviewer to maintainer. There will be lazy concensus and this will merge after the CAPA office hours on Monday 22nd if there are no objections.
/cc @dlipovetsky @Ankitasw @nrb  
Fixes #
**Checklist**:
```release-note
Move AndiDog to maintainer status.
```
> 🌱 [PROPOSAL]: Move Andidog to maintainer

- metadata.yaml
/kind support
Update the metadata file for the v2.6.0 release
Fixes #
**Checklist**:
```release-note
Update the metadata file for v2.6.0
```
> 🌱chore: update metadata for v2.6.0

- .github/ISSUE_TEMPLATE/maintainer_change.yml
- .github/ISSUE_TEMPLATE/reviewer_change.yml
/kind support
Add issue templates for make reviewer and maintainer changes.
Fixes #
**Checklist**:
```release-note
Add issue templates for reviewer and maintainer changes
```
> 🌱 feat: add issue templates for reviewers/maintainer changes

- .github/workflows/dependabot.yml
- .github/workflows/release.yaml
- .golangci.yml
- Makefile
- docs/book/src/development/development.md
- docs/triage-party/Dockerfile
- docs/triage-party/go.mod
- hack/ensure-go.sh
- hack/tools/go.mod
- netlify.toml
/kind support
Updates to Go 1.22 in order to account for updated Go module toolchain behaviors.
**Checklist**:
```release-note
NONE
```
> :seedling: Update Go version to 1.22.6

- exp/controllers/rosamachinepool_controller.go
- exp/controllers/rosamachinepool_controller_test.go
/kind bug
Fixed machinePool spec.Taints diff detection:
- update unit test to cover all fields.
- log the spec diff when detected to make it easier to find what is causing update request.
Fixes #
**Checklist**:
```release-note
NONE
```
> 🐛 ROSA: Fix ROSAMchinePool spec.Taints diff detection

- .github/dependabot.yml
- go.mod
- go.sum
/kind cleanup
Dependabot's kind of noisy for OpenShift updates. Exclude patch versions, and also update non-k8s deps.
**Checklist**:
```release-note
NONE
```
> :seedling: Dependabot cleanup

- .github/workflows/build-ami.yml
/kind bug
The concurrency settings where causing matrix jobs to be cancelled. Removing for the time being.
Fixes #
**Checklist**:
```release-note
NONE
```
> 🌱 fix: concurrency settings where causing issues

- metadata.yaml
/kind support
Updates the metadata file in preparation for the 2.7.0 release.
Fixes #
**Checklist**:
```release-note
Update metadata file for v2.7.0 release.
```
> 🚀chore: update metadata for release 2.7.0

- docs/book/book.toml
This updates the links to include to the new 2025 meeting notes document. And a new Google doc has been created,
Fixes #
**Checklist**:
```release-note
Update links to new 2025 meeting notes doc
```
> 🌱 chore: add link to 2025 meeting notes

- docs/book/src/topics/reference/reference.md
Fixes #
**Checklist**:
```release-note
Fix typo on table of feature gates
```
> :book: Fix typo in table of feature gates in the docs

- go.mod
- go.sum
/kind bug
Fixes CVE-2024-45339, see https://groups.google.com/g/golang-announce/c/H-Q4ouHWyKs
```release-note
NONE
```
> :bug: Bump glog for recent fixes

- test/e2e/data/e2e_eks_conf.yaml
```
failed to get provider components for the “aws” provider: failed to get repository client for the InfrastructureProvider with name aws: error creating the local filesystem repository client: failed to get latest version: failed to find releases tagged with a valid semantic version number
```
**Checklist**:
```release-note
NONE
```
> 🌱 Fix test version string in order to use manifests from source files

- docs/book/src/topics/rosa/creating-a-cluster.md
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/5372
**Checklist**:
```release-note
```
> :book: Fix link to AWS ROSA documentation

- pkg/cloud/services/elb/loadbalancer.go
- pkg/cloud/services/network/subnets.go
/kind feature
Add support for public-only networking (i.e., managed-VPC without private subnets)
Fixes #5378
**Checklist**:
```release-note
NONE
```
> ✨Add support for public-only networking

- metadata.yaml
/kind support
Update the metadata file in preparation of the v2.8.0 release.
Fixes #
**Checklist**:
```release-note
Update metadata for release v2.8.x
```
> 🌱 chore: update metadata for v2.8.x release series

- .devcontainer/devcontainer.json
- devbox.json
- devbox.lock
- scripts/devbox-init-hook.sh
/kind support
Upgrade packages to latest versions
Add new packages: direnv, kustomize
Replace awscli with awscli2
Add init hook script for devbox to install arm8/envsubst 
Update package lock file with latest package versions
Verified dependencies for quickstart and dev guide
Moved most configuration to devbox (only docker-in-docker and essentials in devcontainer)
NONE
All tooling dependencies moved to devbox, except docker that should be started by devcontainer or pre-configured
**Checklist**:
Please add an icon to the title of …
> 🌱 Devbox update

- hack/boskos.py
/kind support
Right now, our custom boskos client does not retry checking out an account if there are no resources available.
Generally this is not a problem, but during busy periods our tests could fail simply because there were no available hosts at that exact moment.
The [go implementation](https://github.com/kubernetes-sigs/boskos) uses defaults of 3 tries with 10 seconds between, so that is replicated here.
**Checklist**:
```release-note
NONE
```
> :seedling: Retry boskos account checkouts

- .github/workflows/release.yaml
The calculation for the `PREVIOUS_TAG` value was a little confusing, document it for future use.
```release-note
NONE
```
> :seedling: Document how previous versions are found

- test/e2e/data/cni/calico.yaml
/kind support
The version of calico used in our e2e tests was 2 years old so this updates to the current latest version. This will help ensure that there are no issues with the latest version of calico.
Fixes #
**Checklist**:
```release-note
Bump calico used in e2e tests to newest version.
```
> 🌱 chore: bump calico for e2e tests

- main.go
/kind bug
Fixes #
**Checklist**:
```release-note
NONE
```
> :bug: Typo fixes

- controlplane/rosa/controllers/rosacontrolplane_controller.go
/kind bug
Fixes #
**Checklist**:
```release-note
Fix error message text in rosa control plane controller
```
> 🐛 Fix error message in rosa control plane controller

- pkg/cloud/services/ec2/launchtemplate.go
- pkg/cloud/services/ec2/launchtemplate_test.go
/kind bug
Follow up to https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5496
**Checklist**:
```release-note
Update launch template if PrivateDnsName changes
```
> :bug: Update launch template if PrivateDnsName changes

- test/e2e/shared/aws.go
- test/e2e/shared/context.go
- test/e2e/shared/suite.go
/kind bug
Fixes the failing unmanaged e2e tests.
Fixes #
**Checklist**:
```release-note
N/A
```
> 🐛  Fix session creation in e2e test suite

- docs/book/src/development/releasing.md
- templates/cluster-template-flatcar-machinepool.yaml
/kind support
A `MachinePool` based cluster template existed for most other variants, but not for Flatcar Linux.
For review, I suggest diff-ing against `cluster-template-flatcar.yaml`.
**Checklist**:
```release-note
Add machine pool template for Flatcar Linux
```
> 🌱 Add machine pool template for Flatcar Linux

- pkg/cloud/metricsv2/metrics.go
/kind bug
Fixes addition logic of getAttemptContextMiddleware relative to default "Retry" middleware of AWS SDK
Fixes #
NA
**Checklist**:
```release-note
Fix addition logic of getAttemptContextMiddleware
```
> 🐛  Fix addition logic of getAttemptContextMiddleware

- test/e2e/shared/common.go
/kind cleanup
Allows e2e tests to dump pod logs to further analyze issues which e.g. require to take a look at kube-apiserver logs like mentioned here: https://kubernetes.slack.com/archives/C8TSNPY4T/p1755619040487799
Fixes #
**Checklist**:
```release-note
NONE
```
> 🌱 e2e: create tarball as artifact with pod logs for debugging

- cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_allow_assume_role.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
/kind /bug
This action is needed by emptyRoutesDefaultVPCSecurityGroup to work.
Fixes #
**Checklist**:
```release-note
Add missing IAM permission `ec2:RevokeSecurityGroupEgress` for `emptyRoutesDefaultVPCSecurityGroup` option
```
> 🐛 Add missing IAM permission `ec2:RevokeSecurityGroupEgress` for `emptyRoutesDefaultVPCSecurityGroup` option
