kubernetes-sigs/cluster-api-provider-aws

scripts/ci-build.sh
scripts/ci-make.sh
scripts/ci-test.sh

ref #5
Signed-off-by: Chuck Ha <ha.chuck@gmail.com>

Adds ci scripts for presubmit checks

---

.gitignore
cloud/aws/actuators/machine/actuator.go
cloud/aws/actuators/machine/actuator_test.go
cloud/aws/services/ec2/instances.go
cloud/aws/services/ec2/instances_test.go

Connected to: #32 
Initial work on the machine actuator delete functionality.

machineactuator: Initial Delete implementation

---

cloud/aws/services/ec2/eips.go
cloud/aws/services/ec2/natgateways.go
cloud/aws/services/ec2/natgateways_test.go

Fixes #35 
Roughly, the approach will be for creation (after subnet reconciliation):
1. Loop over all subnets in provider config
2. Exit if all subnets are public
3. Loop over public subnets and ensure there is A NAT gateway managed by us in there.
4. Loop over routing tables and ensure one exists for each AZ corresponding to the NAT gateway
5. Loop over private subnets
a. Check the route table is the one we manage
b. If not, associate it

NAT Gateway reconciliation

---

cloud/aws/actuators/machine/actuator.go
cloud/aws/actuators/machine/actuator_test.go

Closes #33 
Initial implementation of the Machine Actuator Update method.
I think this is correct. I've made the assumption that the method is being passed the new `Machine` object and that we want to extract the new `Status` from that and pass that to the `updateStatus` method.
Basic testing of the happy path included.

machineactuator: Initial Update implementation

---

cloud/aws/actuators/machine/actuator.go
cloud/aws/actuators/machine/actuator_test.go

`InstanceIfExists` can also return `nil` if the call succeeded, but no instance has been found.
This allows to delete not yet started machines.

Fix NPE when deleting not yet created machine

---

cloud/aws/services/ec2/subnets.go
cloud/aws/services/ec2/subnets_test.go

`ModifySubnetAttributeInput` requires `SubnetId` to be set https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#ModifySubnetAttributeInput

Fix subnet create

---

Makefile

Using explicit generated binary path names is better than implying binaries in users' $PATH
Fixes #
```release-note
NONE
```

Refer to `deepcopy-gen` using explicit path names in Makefile

---

clusterctl/examples/aws/generate-yaml.sh

Allow the `generate-yaml.sh` script from the example to run from anywhere in your path. 
None
None
```release-note
NONE
```

Fix generate-yaml.sh example script so it can run from anywhere

---

cloud/aws/actuators/cluster/actuator.go
cloud/aws/actuators/cluster/actuator_test.go
cloud/aws/providerconfig/v1alpha1/types.go
cloud/aws/services/ec2/gateways.go
cloud/aws/services/ec2/natgateways.go
cloud/aws/services/ec2/network.go
cloud/aws/services/ec2/routetables.go
cloud/aws/services/ec2/subnets.go
cloud/aws/services/ec2/subnets_test.go
cloud/aws/services/ec2/vpc.go
clusterctl/examples/aws/provider-components.yaml.template

- Add much needed logs throughout the reconcile loop.
- Forces to store the state in the cluster actuator with defer.
- Fixes subnet discovery which caused the first iteration to fail.
- Actually reconcile routing tables.
- Complete cluster actuator tests.
- Fix NPE in route table association.
NONE
NONE
```release-note
NONE
```

Fix subnet discovery, reconcile route tables, add logs

---

clusterctl/examples/aws/provider-components.yaml.template
cmd/cluster-controller/Makefile
cmd/machine-controller/Makefile

Happy to extract those into separate PRs, but as they were tiny in bundled those changes.
**Fix example spec**
When running `clusterctl` two deployments will be created `clusterapi-apiserver` and `clusterapi-controllers`. Both have the label `api: clusterapi`, so add another label to the controllers to match only controller pods (the apiserver deployment has already the additional label `apiserver: true`)
**Allow to override dev image tags**
I found it a bit cumbersome to manually edit the tag when recreating the controllers, instead `export DEV_TAG` can now be used to modify the tag.
**Clarify example generation**
I tried to run `./clusterctl/examples/aws/generate-yaml.sh`, which failed as the script can only be executed inside `./clusterctl/examples/aws`

Example improvements

---

OWNERS_ALIASES

Add myself to cluster-api-aws-maintainers.
None
None
```release-note
NONE
```

Add vincepri to cluster-api-aws-maintainers

---

cloud/aws/actuators/cluster/actuator.go
cloud/aws/actuators/cluster/actuator_test.go
cloud/aws/actuators/cluster/interfaces.go
cloud/aws/controllers/cluster/controller.go
cloud/aws/providerconfig/v1alpha1/types.go
cloud/aws/services/ec2/ami.go
cloud/aws/services/ec2/instances.go
clusterctl/examples/aws/cluster.yaml.template

This PR adds the region parameter to the cluster configuration.
Fixes #144 
None
```release-note
The cluster configuration has a new required parameter, `region` which corresponds to the AWS region the cluster lives in.
```

Add region cluster configuration parameter

---

Gopkg.lock
cloud/aws/actuators/machine/actuator.go
cloud/aws/actuators/machine/actuator_test.go
cloud/aws/deployer/deployer.go
cloud/aws/providerconfig/v1alpha1/types.go
cloud/aws/services/ec2/instances.go
cloud/aws/services/ec2/instances_test.go

* Fetch the IP with the deployer (needs fixing)
* Apply a startup script to control plane nodes
This PR adds security groups to newly created nodes
It adds annotations to newly created nodes so clusterctl is happy. I expect these to change.
The deployer gets the IP of the node being created. This will also change 100% especially as we move into private subnet.
Related to  #31
```release-note
NONE …
```

Add security groups to new instances

---

cloud/aws/actuators/cluster/actuator.go
cloud/aws/actuators/cluster/actuator_test.go
cloud/aws/services/ec2/account.go
cloud/aws/services/ec2/bastion.go
cloud/aws/services/ec2/eips.go
cloud/aws/services/ec2/errors.go
cloud/aws/services/ec2/filters.go
cloud/aws/services/ec2/gateways.go
cloud/aws/services/ec2/natgateways.go
cloud/aws/services/ec2/natgateways_test.go
cloud/aws/services/ec2/network.go
cloud/aws/services/ec2/routetables.go
cloud/aws/services/ec2/securitygroups.go
cloud/aws/services/ec2/service.go
cloud/aws/services/ec2/subnets.go
cloud/aws/services/ec2/subnets_test.go
cloud/aws/services/ec2/tags.go
cloud/aws/services/ec2/vpc.go
cloud/aws/services/wait/wait.go

Tears down all VPC related resources, pretty much in the reverse order that it was created.
Supports #39, #41, #43, #56, #59, #61, #60, #62
For resources that take some time to delete, like NAT gateways, was originally going
to return a retryable error for the actuator to requeue. Unfortunately, the re queuing behaviour is not tunable, and is based on constant retries within a short interval up to a maximum of 10.
This PR therefore implements a waiter based on that within API Machinery, but with an
additional helper to handle errors given by the AWS SDK.
This also provides a …

VPC Teardown

---

Gopkg.lock
Gopkg.toml
Makefile
cloud/aws/services/cloudformation/bootstrap.go
cloud/aws/services/iam/types.go
clusterctl/examples/aws/bootstrap-cloudformation.yaml
clusterctl/examples/aws/machines.yaml.template
cmd/clusterawsadm/cmd/alpha/bootstrap.go
cmd/clusterawsadm/cmd/alpha/root.go
cmd/clusterawsadm/cmd/logutil.go
cmd/clusterawsadm/cmd/root.go
cmd/clusterawsadm/main.go

Adds a typed bootstrap CloudFormation template to set up IAM roles
and instance profiles that can be used by the Cluster API controllers
and the AWS Cloud Provider.
Also adds a `clusterawsadm` utility for want of a better name to
generate the YAML files and optionally apply it.
Commands are namespaced into `alpha`, as with `kubeadm` to not provide
a guarantee about its future availability.
This is part of improving user experience. Documentation updates to
follow in another PR.
Part of #120 
_Please confirm that if this PR changes any image versions, then …

Add CloudFormation template for bootstrap

---

Gopkg.lock
cloud/aws/services/ec2/bastion.go
cloud/aws/services/ec2/eips.go
cloud/aws/services/ec2/errors.go
cloud/aws/services/ec2/filters.go
cloud/aws/services/ec2/gateways.go
cloud/aws/services/ec2/gateways_test.go
cloud/aws/services/ec2/natgateways.go
cloud/aws/services/ec2/natgateways_test.go
cloud/aws/services/ec2/routetables.go
cloud/aws/services/ec2/routetables_test.go
cloud/aws/services/ec2/securitygroups.go
cloud/aws/services/ec2/subnets.go
cloud/aws/services/ec2/subnets_test.go
cloud/aws/services/ec2/tags.go
cloud/aws/services/ec2/vpc.go
cloud/aws/services/ec2/vpc_test.go
cloud/aws/services/elb/loadbalancer.go
cloud/aws/services/elb/tags.go

This PR adds a cluster-api-provider-aws specific tag to resources created and owned by cluster-api-provider-aws.
I plan on also reworking the way that we query objects based on tags and limit what operations we perform for owned vs shared objects.

Add cluster-api-provider-aws specific tag

---

.gitignore
Makefile
cmd/cluster-controller/Dockerfile.minikube
cmd/cluster-controller/Makefile
cmd/machine-controller/Dockerfile.minikube
cmd/machine-controller/Makefile
docs/development.md
hack/cluster-api-dev-helper/cmd/exec.go
hack/cluster-api-dev-helper/cmd/minikube.go
hack/cluster-api-dev-helper/cmd/root.go
hack/cluster-api-dev-helper/cmd/testing.go
hack/cluster-api-dev-helper/main.go

cluster-api-dev-helper encodes a few common development tasks
such as stand up and teardown within minikube, tailing logs etc...
minikube_build adds a faster development experience by utilising
the Docker endpoint in Minikube so images do not need to be pushed
to an external repository.
Signed-off-by: Naadir Jeewa <naadir@randomvariable.co.uk>
Fixes #
Some of this will be superseded by #136 
```release-note
NONE
```

Adds utilities to speed up dev process

---

cloud/aws/services/ec2/instances.go

**What this PR does / why we need it**: Adds more `glog` calls to the `services/ec2/instances` methods, improving debugability as we can more easily see where calls originated during errors.
Related to #173 
```release-note
None
```

services/ec2/instances: Add some more glogging to methods

---

cloud/aws/services/awserrors/errors.go
cloud/aws/services/cloudformation/bootstrap.go

Currently clusterawsadm returns an error if the stack already exists even if the update is successful, this change will only return an error if the update fails.
/assign @randomvariable 

[clusterawsadm] Do not return error if stack update successful

---

cloud/aws/services/elb/errors.go
clusterctl/examples/aws/machines.yaml.template

Since we don't have node join wired up yet, this comments out the node machine from the example.

Comment out node machine from example

---

cloud/aws/services/ec2/bastion.go

**What this PR does / why we need it**: Fixes bastion reconciliation after manually deleting in AWS console
Related to #165
**Special notes for your reviewer**: This fixes things so bastion lookup always happens via instance tags, fixing the reconciliation.
```release-note
NONE
```

bastion: Fix bastion code to always lookup via tags

---

clusterctl/main.go

`kubernetes-sigs/controller-runtime` uses `NullLogger`, so `log.Error` was being ignored.
https://github.com/kubernetes-sigs/controller-runtime/blob/ddf0390deebe496cb449b1b8540031da9236afa2/pkg/runtime/log/null.go#L27-L28
https://github.com/kubernetes-sigs/controller-runtime/blob/8d93cc75ed7086e85ec7de09332a3bfd8603a959/pkg/client/config/config.go#L91
This PR adds an additional error message, rather than proceeding to panic that's not helpful for debugging.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1059e58]
goroutine 1 [running]:
sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset.NewForConfig(0x0, …
```

clusterctl: fatal on empty kubeconfig

---

clusterctl/main.go

Previous line already calls `clusterActuator, _ := cluster.NewActuator(cluster.ActuatorParams{`. 
Remove `NewActuator` call that was never used.
```release-note
NONE
```

clusterctl: remove unused "NewActuator" call

---

clusterctl/main.go

clusterctl attempts to get a kube-client on startup instead of using a parameter.
We don't need a kube-client to get the cluster actuator going in the context of the CLI 
steps.
Part of #247
```release-note
```

clusterctl: Remove grabbing kubeconfig on start

---

pkg/cloud/aws/services/ec2/bastion.go
pkg/cloud/aws/services/ec2/filters.go
pkg/cloud/aws/services/ec2/vpc.go
pkg/cloud/aws/services/ec2/vpc_test.go

This should fix the reconcile in case the VPC doesn't exist anymore.
Fixes #
None
```release-note
NONE
```

Return a VPC only if it's available or pending

---

pkg/cloud/aws/services/ec2/account.go
pkg/cloud/aws/services/ec2/filters.go
pkg/cloud/aws/services/ec2/natgateways.go
pkg/cloud/aws/services/ec2/natgateways_test.go
pkg/cloud/aws/services/ec2/network.go
pkg/cloud/aws/services/ec2/routetables_test.go

This PR improves NAT gateway logs and the filtering when describing NAT gateways. Also makes sure to always return a sorted list of AZs.
Related to #241
None
```release-note
NONE
```

Improve NAT logging & filtering

---

hack/cluster-api-dev-helper/cmd/minikube.go
hack/cluster-api-dev-helper/cmd/testing.go

Converts all the dev hacks to work with our new shiny CRD version
Part of #247 
```release-note
```

cluster-api-dev-helper: Make compatible with CRDs

---

images/ansible/roles/common/tasks/debian.yml
images/ansible/roles/common/tasks/redhat.yml
images/ansible/roles/kubernetes/tasks/debian.yml
images/ansible/roles/kubernetes/tasks/redhat.yml
images/ansible/roles/providers/tasks/aws.yml

Installing packages in a loop is deprecated in Ansible 2.7.0 (possibly earlier) and will be removed in v2.11. This is the recommended method going forward.
```release-note
NONE
```

Fix looped package installation deprecation

---

Makefile
cmd/clusterawsadm/client/client.go
cmd/manager/main.go
pkg/apis/awsprovider/v1alpha1/register.go
pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/services/ec2/instances.go

This PR fixes a NPE in the machine actuator caused by the machine state to be empty on bootstrap. It also removes the state update, which is tracked in the follow-up issue #288.
Fixes #287 
```release-note
```

Fix NPE in machine actuator

---

pkg/apis/awsprovider/v1alpha1/register.go
pkg/cloud/aws/actuators/cluster/actuator.go
pkg/cloud/aws/actuators/cluster/actuator_test.go
pkg/cloud/aws/actuators/machine/actuator.go

Currently, updated status for cluster and machine don't get stored so the actuators work is not saved. This PR saves the status for both cluster and machine.
In this PR:
* add methods to encode ClusterProviderStatus and MachineProviderStatus
* add methods to store cluster and machine status
* store cluster and machine status in actuator function
Fixes # 288
```release-note
NONE
```

Cluster and machine actuator updates status

---

Makefile
cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
cmd/clusterctl/examples/aws/generate-yaml.sh
docs/getting-started.md
pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/services/ec2/instances.go
pkg/cloud/aws/services/ec2/instances_test.go

Fixes: #294 
- [clusterawsadm] enable sharedconfig usage 
- Update getting started guide for current workflow
- Update the default manager image for the `make manifests` target
- additional post-crd fixup to machine actuator

Fix up the getting started guide

---

pkg/cloud/aws/actuators/cluster/actuator.go
pkg/cloud/aws/actuators/cluster/actuator_test.go

Tries to get the cluster IP from several places instead
of failing after the first attempt.
This PR lets clusterctl end with exit code 0 as shown here:
```
...
I1025 18:00:24.754193   11903 clusterdeployer.go:175] Done provisioning cluster. You can now access your cluster with kubectl --kubeconfig kubeconfig
I1025 18:00:24.756865   11903 clusterdeployer.go:223] Cleaning up bootstrap cluster.
salazar:cluster-api-provider-aws cha$ $?
-bash: 0: command not found
```
This PR also refactors the actuator tests into test tables.
Fixes #313 
**Special notes for …

Cleans up clusterctl workflow

---

Makefile

Fixes #322
This PR removes the copy of bazel binaries into the GOPATH as this fails when GOPATH is not set:
```
INFO: Build completed successfully, 55 total actions
cp -f bazel-bin/cmd/clusterawsadm/*/clusterawsadm /bin/clusterawsadm
cp: /bin/clusterawsadm: Operation not permitted
make[1]: *** [clusterawsadm] Error 1
make: *** [manifests-dev] Error 2
```
Fixes #322
```release-note
NONE
```

Do not install binaries to gopath

---

scripts/check-install.sh

`scripts/check-install.sh` fails when GOPATH is not set.
Fixes #
```release-note
NONE
```

fix check-install for empty GOPATH

---

pkg/cloud/aws/services/ec2/filters.go
pkg/cloud/aws/services/ec2/subnets.go
pkg/cloud/aws/services/ec2/subnets_test.go

Adds a filter to the describe method making sure subnets are either pending or available
Related to #165 
```release-note
```

Add state filtering for subnets

---

BUILD.bazel

This makes gazelle prefer `BUILD.bazel` to `BUILD` which is good for case insensitive operating systems.
New files will be BUILD.bazel while older BUILD files will still be respected.
Fixes #343 
```release-note
NONE
```

fix gazelle parameters

---

WORKSPACE
cmd/clusterctl/examples/aws/BUILD
cmd/clusterctl/examples/aws/generate-yaml.sh

Some of the k8s images don't have `envsubst` on them. To fix this, pull in an external Golang envsubst program, and use it if it's available.
```release-note
NONE
```

Don't assume compilining machine has envsubst

---

scripts/ci-aws-cred-test.sh

Quick change to test script to set location of aws credentials which is set by `preset-aws-credential: true` in the prow job config.
/assign @detiber 
/assign @chuckha 
Signed-off-by: Ruben Orduz <rubenoz@gmail.com>

Configuring aws client with credentials file location

---

BUILD.bazel
Gopkg.lock
WORKSPACE
cmd/clusterawsadm/BUILD
cmd/clusterctl/BUILD
cmd/clusterctl/examples/aws/BUILD
config/BUILD
pkg/apis/awsprovider/v1alpha1/BUILD
pkg/apis/awsprovider/v1alpha1/register.go
pkg/cloud/aws/actuators/machine/BUILD
vendor/sigs.k8s.io/yaml/.gitignore
vendor/sigs.k8s.io/yaml/.travis.yml
vendor/sigs.k8s.io/yaml/BUILD.bazel
vendor/sigs.k8s.io/yaml/CONTRIBUTING.md
vendor/sigs.k8s.io/yaml/LICENSE
vendor/sigs.k8s.io/yaml/OWNERS
vendor/sigs.k8s.io/yaml/README.md
vendor/sigs.k8s.io/yaml/RELEASE.md
vendor/sigs.k8s.io/yaml/SECURITY_CONTACTS
vendor/sigs.k8s.io/yaml/code-of-conduct.md
vendor/sigs.k8s.io/yaml/fields.go
vendor/sigs.k8s.io/yaml/yaml.go
vendor/sigs.k8s.io/yaml/yaml_go110.go
vendor/sigs.k8s.io/yaml/yaml_go110_test.go
vendor/sigs.k8s.io/yaml/yaml_test.go

Since upstream has official forked ghodss/yaml under sigs.k8s.io, update to use the official fork.
Other changes are formatting changes that gazelle applied when `make dep-install` was run.

Update yaml to use official sigs.k8s.io fork

---

cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
pkg/cloud/aws/actuators/machine/BUILD
pkg/cloud/aws/services/cloudformation/bootstrap.go

* register generate-iam-policy-docs clusterawsadm command
* implement generate-iam-policy-docs command
Allow clusterawsadm to generate JSON representation of  PolicyDocument for all ManagedIAMPolicies 
Fixes #190 
```release-note
`clusterawsadm` can now generate JSON representation of  PolicyDocument for all ManagedIAMPolicies 
```

Add generate-iam-policy-docs command

---

pkg/cloud/aws/services/userdata/controlplane.go

This PR removes a flag that breaks the kubelet from starting. `--allocate-node-cidrs` is not a valid kubelet flag and this prevents the expected breaking loop of the kubelet when kubeadm is installed.
Fixes #
```release-note
NONE
```

Fix kubelet argumnets

---

cmd/clusterctl/examples/aws/machines.yaml.template

Previously the machines.yaml we were generating was missing TypeMeta information, which would cause issues with any external tooling (IDE plugins, kustomize, etc).

Update machines.yaml.template with TypeMeta

---

pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/services/userdata/node.go

* Fix kubeadm type to successfully join a node
This PR fixes the error when a node is joining:
```no kind "NodeConfiguration" is registered for version "kubeadm.k8s.io/v1alpha3" in scheme "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/scheme/scheme.go:31"```
Fixes #
```release-note
NONE
```

Do not bail early in Machine create

---

pkg/apis/awsprovider/v1alpha1/awsclusterproviderconfig_types.go

Just fixes a typo in json structtag (omitemptuy => omitempty)
Fixes #
```release-note
```

Fixed typo in cluster provider config

---

pkg/apis/awsprovider/v1alpha1/types.go
pkg/apis/awsprovider/v1alpha1/zz_generated.deepcopy.go
pkg/cloud/aws/services/ec2/securitygroups.go

This PR fixes an issue where the rules attached to a security group were recreated on every reconcile call. 
Fixes #
```release-note
```

Fix security group duplicate rule bug

---

pkg/cloud/aws/services/ec2/instances.go
pkg/cloud/aws/services/ec2/instances_test.go

Fix possible race condition between machine and cluster actuator

---

Makefile
pkg/cloud/aws/actuators/BUILD.bazel
pkg/cloud/aws/actuators/machine_scope.go
pkg/cloud/aws/actuators/scope.go

This PR fixes the status update error that happens when the actuator runs. It'll fetch the latest cluster object from the api and update the status.
Further investigation is needed for the other issues.
Related to #430
```release-note
```

Fix status update error on first run

---

build/amis/README.md
build/amis/ansible/roles/containerd/defaults/main.yml
build/amis/packer/packer.json
cmd/clusterctl/examples/aws/machines.yaml.template
docs/amis.md
pkg/cloud/aws/services/ec2/ami.go
pkg/cloud/aws/services/userdata/controlplane.go
pkg/cloud/aws/services/userdata/node.go

* Updates AMIs and related functions
* Updates kubeadm to use v1beta1 types
Fixes #412 
```release-note
Updates kubernetes cluster version to v1.13.0
```

v1.13 update

---

Makefile
cmd/clusterctl/examples/aws/generate-yaml.sh

Rev the manager image in preparation to cut a release.

Rev manager image

---

pkg/cloud/aws/actuators/cluster/actuator.go
pkg/cloud/aws/actuators/machine/actuator.go

This PR is related to the discussion in #390, it enables error printing using `%+v` directive when returning errors from the actuator methods.
```release-note
```

Enable stack trace error printing in actuators

---

.gitignore
pkg/cloud/aws/services/certificates/certificates.go
pkg/deployer/deployer.go

This PR removes the hard-coded cluster name when generating the kubeconfig for the target cluster
Fixes #455 
_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._ No
```release-note
NONE
```

fix kubeconfig to use correct cluster name

---

build/amis/ansible/roles/containerd/defaults/main.yml
build/amis/ansible/roles/containerd/tasks/main.yml

- installs latest containerd (1.2.1)
- deletes containerd tarball after installation
```release-note
NONE
```

Containerd 1.2.1

---

Gopkg.lock
Gopkg.toml
vendor/sigs.k8s.io/cluster-api/Dockerfile
vendor/sigs.k8s.io/cluster-api/Gopkg.lock
vendor/sigs.k8s.io/cluster-api/Makefile
vendor/sigs.k8s.io/cluster-api/WORKSPACE
vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
vendor/sigs.k8s.io/cluster-api/config/crds/cluster_v1alpha1_machinedeployment.yaml
vendor/sigs.k8s.io/cluster-api/config/default/kustomization.yaml
vendor/sigs.k8s.io/cluster-api/docs/book/appendices/keps/0003-cluster-api.md
vendor/sigs.k8s.io/cluster-api/hack/verify-bazel.sh
vendor/sigs.k8s.io/cluster-api/hack/verify_clientset.sh
vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/common/consts.go
vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/cluster_types.go
vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machineset_types.go
vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/controller.go
vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/controller.go
vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go
vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/rolling.go
vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/sync.go
vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/util/util.go
vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/controller.go
vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/machine.go

This PR keeps CAPA up to date with CAPI. It recently moved to depend on k8s 1.12.3 things and we want to eventually get to 1.13. This is just a step in that direction. Shoutout to @vincepri for doing the 1.12 migration work on CAPI
Related to #467 but only vaguely
I created a whole cluster with this commit.
```release-note
NONE
```

Bump cluster-api version

---

Makefile

Fixes #472
This PR installs built binaries into the GOPATH even in situations when the GOPATH is not set.
This basically reverts https://github.com/chuckha/cluster-api-provider-aws/commit/55e14bf240f69eb044ae617222d4777aac610e14 with the modification of working when GOPATH is unset.
```release-note
NONE
```

Installs binaries to gopath even if gopath is unset

---

Makefile

The generated kustomize patch now uses the correct dev image.
This PR makes `make examples-dev` work as expected.
```release-note
NONE
```

Fixes examples(-dev) makefile targets

---

envfile.example
pkg/cloud/aws/services/ec2/ami.go
pkg/cloud/aws/services/ec2/instances.go
pkg/cloud/aws/services/ec2/instances_test.go

This is a first pass at looking up AMIs instead of hardcoding
a big case statement basd on region.
Fixes #138
This PR looks up AMIs for control plane nodes instead of relying on hardcoded case statement.
This logic requires coordination with the build/ directory because it uses the name to look up the actual AMI. There may be improvements and we want to implement this logic with the bastion hosts (I think) as well.
The goal is to iterate from here, this may not be perfect but until we release new images with a different title, this will work. …

Lookup AMIs instead of hardcoding them.

---

cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go

Signed-off-by: Ruben Orduz <rdodev@vmware.com>
Currently `clusterawsadm alpha bootstrap  create-stack` is silent unless there's an error or completes successfully. This PR is minor UX message so they user knows actions are about to take place.
```release-note
On cluster boostrap creation the CLI will now let the user know it will attempt to create a bootstrap stack.
```

minor cli message

---

Makefile

In a fresh `cluster-api-provider-aws` checkout, the `release-binaries` make target would fail due to the `out` directory not existing yet.
This PR ensures that the directory exists before we attempt to use it, it also cleans it up in the `clean` target.
```release-note
NONE
```

Makefile: Ensure out directory exists for release-binaries target

---

Gopkg.lock
Gopkg.toml
vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/bootstrap/existing/BUILD.bazel
vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/bootstrap/existing/cluster.go
vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/bootstrap/kind/kind.go
vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/bootstrap/provisioner.go

This PR updates cluster-api upstream dependency to the latest master, which fixes an issue with kind bootstrapper returning kubeconfig path with a newline.
Fixes #
```release-note
```

Update cluster-api to latest master

---

cmd/clusterawsadm/cmd/alpha/bootstrap/BUILD
cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
pkg/cloud/aws/services/cloudformation/bootstrap.go
pkg/cloud/aws/services/iam/types.go

Fixes #422 
Permits ELB, as an Amazon-managed service, to create a role to access EC2 in the customer's account, which is needed to attach the control plane instances to a load balancer.
In order to test this, ELB will create a `AWSServiceRoleForElasticLoadBalancing` using these IAM permissions. If all ELBs are deleted, then this role can be deleted and then the account is reusable for testing this feature.
```release-note
clusterawsadm: IAM policies have been extended to allow AWS ELB to create the AWSServiceRoleForElasticLoadBalancing IAM …
```

Add permissions for ELB to create service linked roles

---

WORKSPACE

Update to go 1.11.5 to remain consistent with upstream/kubernetes projects.
We've already bumped the version of bazel go rules so this builds just fine
```release-note
NONE
```

Bump go version to 1.11.5

---

pkg/cloud/aws/actuators/machine/BUILD.bazel
pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/actuators/machine/actuator_test.go

Implements erroring on a machine update if the incoming configuration attempts to change immutable machine state.
Fixes #33 
Currently need to implement the Subnet checks.
```release-note
```

Machine Actuator: Implement immutable state checking for Update method

---

build/amis/ansible/roles/common/files/cloud.cfg
build/amis/ansible/roles/common/tasks/redhat.yml

Fixes #536 
```release-note
```

Reconfigure cloud-init to use ec2-user instead of centos on Amazon Linux

---

pkg/cloud/aws/services/cloudformation/bootstrap.go

Updates the controllers policy configured by clusterawsadm to support the changes made in #516 for Describing and Modifying LoadBalancerAttributes.
Fixes #546 
```release-note
NONE.
```

Update bootstrapper policy for loadbalancer attributes

---

Makefile

This makes the out taret a phony so make will always try to
run the script regardless if the directory is clean or not.
The script provides useful error messages that the user can
act upon.
This PR improves the UX for users getting started. This introduces errors and actions to fix the errors instead of silently ignoring a script and creating confusion for users.
Fixes #540 
```release-note
NONE
```

Improve user experience when generating manifests

---

pkg/cloud/aws/services/ec2/BUILD
pkg/cloud/aws/services/ec2/ami.go
pkg/cloud/aws/services/ec2/ami_test.go

DescribeImages does not guarantee an order so we order it in code by timestamp. The newest will alwyas be assumed the best.
This PR sorts the output of DescribeImages so we always get the newest AMI.
The strategy for testing is to override the AMI id in the Machine object.
Fixes #558 
```release-note
NONE
```

Sorts AMIs when they are returned

---

pkg/cloud/aws/services/certificates/BUILD
pkg/cloud/aws/services/certificates/certificates.go
pkg/cloud/aws/services/certificates/certificates_test.go

* Set MaxPathLen = 0 and MaxPathLenZero = true. Just setting MaxPathLenZero = true isn't sufficient
* Add unit tests to verify cert settings
Sets pathLenConstraint X509 constraint on generated CA certificates.
This prevents generating intermediate CA certs that can be used to generate certs for entities that will be trusted by virtue of having, say the cluster root ca, in their trust chain.
Fixes #557
```release-note
Generated ca certs for …
```

Set pathLenConstraint X509 constraint on CA certificates

---

config/rbac/rbac_role.yaml
pkg/apis/awsprovider/v1alpha1/register.go
pkg/cloud/aws/actuators/BUILD.bazel
pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/actuators/machine_scope.go

Adds support for retrieving the ProviderSpec from a MachineClass
Fixes #513
<!--  Write your release note:
```release-note
- cluster-api-provider-aws now supports using MachineClass
```

Add support for MachineClass

---

pkg/apis/awsprovider/v1alpha1/awsmachineproviderstatus_types.go
pkg/apis/awsprovider/v1alpha1/zz_generated.deepcopy.go
pkg/cloud/aws/actuators/machine/actuator.go

InstanceState is presently just a string. It ought to be the proper, previously created type
Fixes #
**Special notes for your reviewer**
```release-note
InstanceState in Machine Status is now properly an InstanceState type
```

Use InstanceState instead of String in Machine Status

---

cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go

Signed-off-by: ishantanu <shantanud106@gmail.com>
1. Fixes repeated error messages for clusterawsadm CLI.
2. Adds a validation for arguments passed to `clusterawsadm`'s `create-stack` command.
3. Skips printing `Usage:` when a genuine error occurs for `create-stack`. Only prints `Usage` details when invalid arguments are passed.
Fixes #550

Fix repeated error messages for clusterawsadm

---

pkg/apis/awsprovider/v1alpha1/awsclusterproviderconfig_types.go
pkg/cloud/aws/services/ec2/routetables.go
pkg/cloud/aws/services/ec2/subnets.go
pkg/cloud/aws/services/ec2/subnets_test.go
pkg/cloud/aws/tags/types.go

The subnet tracking code did not recognize our public subnets, because we've defaulted IP assignment off everywhere. Reading the docs seems to indicate that "public" or "private" subnets in AWS are an emergent property from how the traffic flows:
https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Scenario2.html
> The instances in the public subnet can send outbound traffic directly to the Internet, whereas the instances in the private subnet can't. Instead, the instances in the private subnet can access the Internet by using a network address translation (NAT) gateway that resides in the public subnet.
Which concurs with Stack Overflow:
https://stackoverflow.com/a/38691109
> A subnet is deemed to be a Public Subnet if it has a Route Table that …

More reliable public subnet detection

---

.bazelrc
build/stateful_set_patch.bzl
test/BUILD.bazel

Small fix to #580 to expand make variables in stateful_set_patch.bzl
Fixes #
```release-note
```

bazel: Expand make variables in stateful_set_patch

---

Gopkg.lock
cmd/clusterctl/examples/aws/generate-yaml.sh

Generated manifests, both dev and non-dev missing a yaml document break `---`
Fixes #588 
The Gopkg.lock file seemed to be missing online. This got generated after running a make command.
```release-note
```

fixes bug in generated manifests

---

Gopkg.lock
cmd/clusterctl/examples/aws/generate-yaml.sh

This reverts commit 1f4d4572099f9d471aa63e8c6184e901049ad859.
Because I had an outdated clusterawsadm. My fault.

Revert "fixes bug in generated manifests (#589)"

---

test/e2e/aws_test.go

This patch makes the AWS region used for e2e configurable via the environment variable `AWS_DEFAULT_REGION`, falling back to `AWS_REGION` if the former is not specified. If not specified, the region defaults to `us-east-1`.
NA
You're special, and gosh darnit, people like you.
```release-note
The AWS region used for e2e may now be configured with the environment variable AWS_DEFAULT_REGION, falling back to AWS_REGION if the former is not specified. The region defaults to "us-east-1".
```

Configurable region

---

scripts/ci-bazel-integration.sh

This patch creates separate scripts for running the e2e and integration tests. For now the e2e script simply execs the integration script in order to provide backward-compatibility with the [existing e2e Prow jobs](https://github.com/kubernetes/test-infra/pull/9974/files). Once those are updated, the e2e script will invoke the e2e tests instead.
Related to https://github.com/kubernetes/test-infra/pull/11459
NA
NA
NA

Separate e2e and integration scripts

---

.bazelrc

The current release tag for cluster-api-aws-controller is 0.0.4, not 0.1.0
Fixes #
```release-note
NONE
```

Fix tag for cluster-api-aws-controller

---

cmd/manager/main.go

Add cli flag to supply namespace for capa controller to watch for capi objects
This PR adds a CLI flag to restrict the namespace that capa controllers watch for capi objects to reconcile
Fixes #581
```release-note
```

Add cli flag to supply namespace for capa controller to watch for capi objects

---

docs/README.md
docs/reconcile-in-custom-namespace.md

https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/607
Fixes #581 
```release-note
```

Document the 'namespace' cli flag to capa controller

---

OWNERS
OWNERS_ALIASES

This PR adds @ashish-amarnath as a reviewer to the project. He's been a huge contributor to the project and regularly reviews code and provides feedback, features, tests and documentation. Really great to have you as an official reviewer!
```release-note
NONE
```
/assign @detiber @vincepri @randomvariable

Adds ashish-amarnath as a reviewer

---

.golangci.yml
WORKSPACE

This is a propagation of https://github.com/kubernetes-sigs/cluster-api/pull/699
Fixes #
```release-note
```

build: lock golangci-lint to a version instead of commit sha

---

WORKSPACE

Updates golangci-lint to the latest version, followup to https://github.com/kubernetes-sigs/cluster-api/pull/806
```release-note
NONE
```

Rev the version of golangci-lint used

---

pkg/cloud/aws/services/kubeadm/aws_defaults.go
pkg/cloud/aws/services/userdata/node.go

We observed that the user-data being created for nodes had illegal
indentation, and omitted the port from the api server address.
Previously, we observed user-data being generated that looks like:
```
permissions: '0640'
content: |
---
apiVersion: kubeadm.k8s.io/v1beta1
caCertPath: ""
discovery:
bootstrapToken:
```
Removing the leading spaces produced a cloud-config that seem 
```release-note
NONE
```

fix: repair node joins

---

pkg/cloud/aws/actuators/machine/actuator.go

Currently we do not set Machine.Spec.ProviderID on machines that we create, this resolves that.
Fixes #610
```release-note
The Machine Actuator now sets Machine.Spec.ProviderID
```

Set the ProviderID if unset

---

cmd/release/BUILD.bazel
cmd/release/main.go
docs/releasing.md

This PR adds a basic release tool to help us get started with automated releases. The idea is to run it to create a draft release that we edit and publish by hand when we're satisfied with the release notes.
Here is an example run:
```
salazar:cluster-api-provider-aws cha$ go run ./cmd/release/main.go -user chuckha -remote chuckha -version v1.2.6
tagging repository 🐲
pushing tag 🐲
drafting a release 🐲
uploading "cluster-api-provider-aws-examples.tar" 🐲
uploading "clusterawsadm-darwin-amd64" 🐲
uploading "clusterawsadm-linux-amd64" 🐲
uploading "clusterctl-darwin-amd64" 🐲
uploading "clusterctl-linux-amd64" 🐲
The next steps are:
- Write the release notes. It is a manual process
- push the container images
- …
```

Adds initial release automator

---

pkg/cloud/aws/services/cloudformation/bootstrap.go

Reconciling load balancers fails with an error stating that it needs 
`ec2:DescribeAccountAttributes`
Fixes #629 
```release-note
Added `ec2:DescribeAccountAttributes` to bootstrap user permissions.
action required: Run `clusterawsadm alpha bootstrap create-stack` to apply the new permissions
```

Add ec2:DescribeAccountAttributes to bootstrap user

---

pkg/cloud/aws/converters/instance.go

This PR fixes a panic that occurs on a new cluster creation for instances that don't have an associated instance profile.
Fixes #642
```release-note
```

Fix panic when IAM profile isn't available

---

Gopkg.lock
Gopkg.toml
vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/controller.go

Updates cluster-api dependency
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/815
Fixes #620
```release-note
NONE
```

Rev cluster-api dependency

---

Makefile

This PR is an effort to restructure the current Makefile in to provide better runtime for common targets, remove unused options and simplify cross-target dependencies.
- Remove FASTBUILD option in an effort to make most of the target fast instead of relying on on/off flags.
- Removes `dep status` and `dep-install` target which takes more time than just `dep ensure` in latest version of `dep`.
- Removes `generate` prereq from docker-push which isn't required or necessary.
- Reduces the amount of calls to `generate` and `gazelle` throughout the Makefile which increased the total time running a development build by several seconds.
- Adds `delete-cluster` development target.
**Which issue(s) this PR …

Restructure Makefile

---

cmd/clusterctl/examples/aws/provider-components-base.yaml
cmd/clusterctl/examples/aws/provider-components-base/stateful-set-credentials-patch.yaml
docs/reconcile-in-custom-namespace.md

Fixes an issue where the credentials couldn't be found after updating cluster-api to distroless.
Fixes #
```release-note
```

Fix AWS credentials mountpoint with distroless image

---

pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/services/ec2/instances.go
pkg/cloud/aws/services/ec2/instances_test.go
pkg/cloud/aws/services/interfaces.go

This PR fixes a bug where if the machine resource was deleted before the ec2 instance is created, the provider panics. The alternative to this is removing the finalizer by hand and then deleting them.
Fixes #
```release-note
Provider no longer panics when instance id is nil
```

fix: no longer panic when instance id is nil

---

pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/actuators/machine/actuator_test.go

This PR adds slightly more error logging when Machine reconciliation fails, with additional details when the failure is due to an attempt to change immutable fields such as SSH key name or IAM instance profile.
Issue discovered while troubleshooting for https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/635.
Sample log output:
```
E0312 15:24:59.803917       1 controller.go:214] Error updating machine rudeboy-machine-name: found attempt to change immutable state for machine rudeboy-machine-name: [(input instance profile "new" != existing "old") (input subnet ID "subnet-123" != existing "subnet-456")]
```
Edit: the above log output relies on https://github.com/kubernetes-sigs/cluster-api/pull/819 …

more verbose immutable machine state errors

---

.bazelrc
Makefile

This moves all the build variables into the make file so a release can happen entirely through make without having to modify bazel definitions
Aids in the next release
```release-note
NONE
```

Remove more bazel defaults

---

pkg/cloud/aws/services/kubeadm/aws_defaults.go

Adds a missing `--cloud-provider=aws` parameter for the controllermanager pod
Fixes #
```release-note
Adds an ExtraArg for the controllermanager pod for AWS cloud provider.
```

fix: add AWS ExtraArgs for ControllerManager

---

cmd/manager/main.go

Overrides the default resync interval (10h) to 10m
Related to: https://github.com/kubernetes-sigs/cluster-api/issues/748
```release-note
The resync interval for reconciling Machines and Clusters is now 10m instead of the Kubebuilder default of 10h
```

Update the resync interval to 10m instead of 10h

---

Makefile
hack/e2e.sh

Allows `make e2e` to work again

e2e: Fix-up for changes to release process

---

README.md
build/amis/README.md
build/amis/ansible/roles/containerd/defaults/main.yml
build/amis/packer/base-images-us-east-1.json
build/amis/packer/packer.json
cmd/clusterctl/examples/aws/addons.yaml
cmd/clusterctl/examples/aws/machines.yaml.template
docs/amis.md

- Update containerd to v1.2.5
- Update kubernetes-cni to v0.7.5
- Publish AMIs for Kubernetes v1.13.5 and v1.14.0
- Update machines template to use v1.13.5 by default
- Update Calico to v3.6.0

Update AMIs and Calico

---

cmd/release/main.go

Updates the release tool to use the same version number for binaries and images
Fixes #673 
```release-note
NONE
```

Sync binary and image versions with release tool

---

.gitignore
Gopkg.lock
pkg/cloud/aws/services/kubeadm/BUILD.bazel
pkg/cloud/aws/services/kubeadm/aws_defaults.go

Add roles to nodes
```
NAME                         STATUS   ROLES    AGE    VERSION
ip-10-0-0-113.ec2.internal   Ready    master   113m   v1.13.2
ip-10-0-0-138.ec2.internal   Ready    node     11m    v1.13.2
```
If we don't add this label, roles column becomes `<none>`
```
NAME                         STATUS   ROLES      AGE    VERSION
ip-10-0-0-138.ec2.internal   Ready    <none>     11m    v1.13.2
```

Add Roles for ControlPlane and Nodes

---

pkg/cloud/aws/actuators/machine/actuator.go

Fixes crash related to a nil dereference when cluster is not linked
Fixes #690 
```release-note
Return an error rather than crash if a cluster is not linked to a machine.
```

Avoid nil dereference when missing cluster

---

docs/releasing.md

Updates the docs for releasing cluster-api-provider-aws
```release-note
NONE
```

Update the releasing docs

---

hack/checkout_account.py

Currently the automated e2e tests are having issues related reusing the httplib connection: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cluster-api-provider-aws-bazel-e2e/1113802682641944577, this udpates checkout_account.py to not reuse connections.
```release-note
NONE
```

Update checkout_account.py to not reuse connections

---

pkg/apis/awsprovider/v1alpha1/types.go
pkg/cloud/aws/services/ec2/securitygroups.go

This change does two things:
1. Handles ingress rules that don't have a "port" notion. Counterintuitively, ICMP and ICMPv6 traffic _does_ have a "port" notion in AWS-land.
2. Fix a bug related to deleting ingress rules without a description, which AWS considers distinct from those with an empty description
These patches fix the crasher, but the story isn't yet fully told. We found ourselves in this situation after spinning up a Service of `Type: LoadBalancer`, which caused the cloud provider to helpfully add a rule to the nodes' security group for "all …

Fix: all traffic ingress rule triggers fatal nil dereference

---

pkg/cloud/aws/actuators/machine_scope.go
pkg/cloud/aws/services/ec2/instances.go
pkg/cloud/aws/services/kubeadm/BUILD.bazel
pkg/cloud/aws/services/kubeadm/aws_defaults.go
pkg/cloud/aws/services/kubeadm/aws_defaults_test.go

The pointers were not working as expected so the API is changing
to be more functional and leverage kubernetes' DeepCopy function.
This PR fixes a bug (bad pointer work) with regards to kubeadm defaults being set properly on the JoinConfiguration option.
This bug still exists in the neighboring functions but will be addressed in following PRs.
This adds tests to that function and makes the function more functional and easier to use.
Fixes #685 
```release-note
NONE
```

Fixes a bug and adds tests for kubeadm defaults

---

README.md
docs/amis.md

Update listed v1.14 AMIs to v1.14.1
```release-note
NONE
```

Update listed v1.14 AMIs to v1.14.1

---

pkg/cloud/aws/services/ec2/instances.go
pkg/cloud/aws/services/kubeadm/BUILD.bazel
pkg/cloud/aws/services/kubeadm/aws_defaults.go
pkg/cloud/aws/services/kubeadm/aws_defaults_test.go

Attempt at documenting the assumptions made in the kubeadm
defaults code.
This PR adds some tests and changes the API to the kubeadm defaults code.
Related to #685 
There is still one or two more PRS to come relating to this.
```release-note
NONE
```

Cleans up kubeadm default code and adds tests

---

cmd/clusterctl/examples/aws/generate-yaml.sh
cmd/clusterctl/examples/aws/machines-ha.yaml.template

We want to have an easy way to create highly available clusters. This PR introduces `machines-ha.yaml` file that is generated by `make manifests` command. It can be passed into `clusterctl` while new cluster is created.
Fixes #415 
```release-note
```

Ensure `make manifests` generates machines file for HA control plane too.

---

config/crds/awsprovider_v1alpha1_awsmachineproviderspec.yaml
pkg/apis/awsprovider/v1alpha1/awsmachineproviderconfig_types.go
pkg/cloud/aws/services/ec2/ami.go
pkg/cloud/aws/services/ec2/ami_test.go
pkg/cloud/aws/services/ec2/instances.go

Adds the ability to override the default Organization ID used for image lookups.
```release-note
- Users can now set machine.spec.providerSpec.imageLookupOrg to override the default Organization ID used for image lookups.
```

Add ability to override Organization ID for image lookups

---

config/crds/awsprovider_v1alpha1_awsclusterproviderstatus.yaml
config/crds/awsprovider_v1alpha1_awsmachineproviderspec.yaml
pkg/apis/awsprovider/v1alpha1/awsmachineproviderconfig_types.go
pkg/apis/awsprovider/v1alpha1/types.go
pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/actuators/machine/actuator_test.go
pkg/cloud/aws/converters/instance.go
pkg/cloud/aws/services/ec2/instances.go

This PR adds `rootDeviceSize` into the AWSMachineProviderSpec, allowing customization of the provisioned EC2 instance's root volume size.
```release-note
Add support for customizing instance root device size
```

feat: support customizing root device size

---

Gopkg.lock
pkg/cloud/aws/actuators/BUILD.bazel
pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/actuators/machine_scope.go
pkg/cloud/aws/actuators/scope.go
pkg/cloud/aws/services/ec2/BUILD.bazel
pkg/cloud/aws/services/ec2/instances.go
pkg/cloud/aws/services/ec2/instances_test.go

This fixes the errors we were seeing with Update conflicts.
The new logic will try to update; fetch a new version, set the most recent resource version and then try updating again.
Fixes #717
```release-note
NONE
```

Adds retry-on-conflict during updates

---

WORKSPACE

This PR adds a step to the WORKSPACE that ensures the version of bazel being run is a supported version of this project.
related to #730 
Periodics will now fail with this error until the kubekins version is updated (coming soon)
```release-note
NONE
```

Ensure bazel is the correct version

---

OWNERS_ALIASES
SECURITY_CONTACTS

Updates the OWNERS_ALIASES and SECURITY_CONTACTS for the repo to reflect current leadership and participation
~~Blocked on: https://github.com/kubernetes-sigs/cluster-api/pull/884~~
/hold
```release-note
NONE
```

Update OWNERS_ALIASES and SECURITY_CONTACTS

---

docs/creating-multinode-controlplane-clusters.md

[doc] Fix markdown formatting

---

cmd/release/main.go

This PR makes the logger in the release tool an explicit dependency. It's mostly for code hygiene and getting me back into this because I want to integrate this with the new sigs container image repositories.
Bonus: kick off a post submit job.
```release-note
None
```

extract fmt from release tool

---

WORKSPACE
test/e2e/util/kind/setup.go

* Bump kind version
* Remove docker load in favor of kind load for e2e cluster
We don't strictly need this PR but it's nice to have. This bumps the version of kind to 0.2.1 which will bump the bootstrap cluster to version 1.13.4.
```release-note
NONE
```

e2e testing improvement

---

pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/actuators/machine/actuator_test.go

This commit looks for empty RootDeviceSize in the spec and ignores it.
Otherwise, none of our control plane machines were updating with this
error:
```
E0418 23:07:48.250925       1 controller.go:214] Error updating machine "ns/controlplane-2": found attempt to change immutable state for machine "controlplane-2": ["Root volume size cannot be mutated from 8 to 0"]
```
Fixes #
```release-note
fixes issue updating machines with an unspecified …
```

fix: Don't try to update root size when it's unset

---

cmd/manager/BUILD.bazel
cmd/manager/main.go
pkg/cloud/aws/actuators/machine/actuator.go

This PR makes sure that NodeRef is set only in case the manager is running on the workload cluster.
Fixes #
```release-note
```

Scope nodeRef to workload cluster

---

docs/roleassumption.md

Documentation for creating a new cluster on a different AWS account than the one where the CAPA controller is running on by using cross account role assumption with KIAM. This is added as its a common use-case for a system to create a new cluster on behalf of another person/customer. 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` 
NONE
NONE
```release-note
NONE
```

Documentation for creating a new cluster on a different AWS account 

---

pkg/cloud/aws/actuators/BUILD.bazel
pkg/cloud/aws/actuators/machine_scope.go
pkg/cloud/aws/actuators/scope.go

* Uses patch for updating the cluster and machine specs
- patch does not cause a re-reconcile in the capi controller
* Uses update for updating the cluster and machine status
- update for status is ok since it does not update any of the metadata
no re-reconcile is necessary for the capi controller
apparently there is no issue, but creating a cluster was weird.
I believe this will be the first step to fixing the long-create times we were seeing.
```release-note
None
```

Fixes the infinite reconcile loop

---

test/e2e/BUILD.bazel

Fixes the recently introduced e2e test failure when building the test manifests
```release-note
NONE
```

Fix up //test/e2e:manifests

---

pkg/cloud/aws/actuators/machine/actuator.go

Fixes a misleading log message
```release-note
NONE
```

Fix log message

---

WORKSPACE

Updates tooling to use Go 1.12.5
```release-note
NONE
```

Update to Go 1.12.5

---

README.md
build/amis/README.md
build/amis/packer/packer.json
cmd/clusterctl/examples/aws/machine-deployment.yaml.template
cmd/clusterctl/examples/aws/machines-ha.yaml.template
cmd/clusterctl/examples/aws/machines.yaml.template
docs/amis.md

Update base image to k8s v1.13.6
```release-note
NONE
```

Update base image to k8s v1.13.6

---

pkg/cloud/aws/services/ec2/vpc.go
pkg/cloud/aws/services/ec2/vpc_test.go

This PR sets `EnableDnsHostnames` and `EnableDnsSupport` to `true` for managed VPCs.
Fixes #780 
```release-note
```

Set attributes for managed VPCs

---

pkg/cloud/aws/services/ec2/vpc.go
pkg/cloud/aws/services/ec2/vpc_test.go

This PR fixes #783 
```release-note
NONE
```

fixes vpc creation

---

pkg/cloud/aws/services/kubeadm/aws_defaults.go
pkg/cloud/aws/services/kubeadm/aws_defaults_test.go

This PR appends the `nodeRole` Node label when the `node-labels` Kubelet argument is supplied, rather than overriding it. 
Fixes #789 
Tested with worker node MachineDeployments.
```release-note
NONE
```

chore: append nodeRole label if additional labels provided

---

pkg/cloud/aws/services/kubeadm/BUILD.bazel
pkg/cloud/aws/services/kubeadm/aws_defaults.go
pkg/cloud/aws/services/kubeadm/aws_defaults_test.go

This PR allows taints from the machine object (from machine set, from machine deployment) to make their way into the kubeadm config so the nodes have the correct taints applied.
Fixes #793 
Tested by creating a cluster, deleting the default machine, applying this machine deployment:
```
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
name: sample-machinedeployment
labels:
cluster.k8s.io/cluster-name: test1
spec:
replicas: 2
selector:
matchLabels:
cluster.k8s.io/cluster-name: test1
set: node …
```

Copy taints to new machines

---

Gopkg.lock
pkg/tokens/BUILD.bazel
pkg/tokens/tokens.go

This PR Removes the retries around creating a secret. Instead of retrying for a long time we should just bail and let the cluster-api controller re-reconcile. These retries are not necessary and will only slow down imminent failure.
Another added benefit here is that errors on creating secrets don't get swallowed.
```release-note
NONE
```

Remove retries

---

docs/releasing.md

Signed-off-by: Amy Chen <hi@amycod.es>
Updates the documentation to instruct users to have a gpg key associated with their github profiles to enable the release script to work.
Related to: #795

add gpg key dependency to docs

---

README.md
build/amis/README.md
build/amis/ansible/roles/common/tasks/redhat.yml
build/amis/ansible/roles/containerd/defaults/main.yml
build/amis/ansible/roles/containerd/tasks/redhat.yml
build/amis/ansible/roles/kubernetes/tasks/redhat.yml
build/amis/packer/base-images-us-east-1.json
docs/amis.md

Previously the latest version of the images for v1.14.x was v1.14.1
```release-note
NONE
```

Build and update images for k8s v1.14.2

---

docs/getting-started.md

Installing `clusterctl` and/or `clusterawsadm` using `go get` causes the resulting binaries to not contain any version information, we should avoid telling users to install using this method as part of the getting started instructions. The development instructions already tell users how to build the binaries from master (correctly using bazel).
```release-note
NONE
```

Remove go get install instructions for binaries

---

README.md
docs/amis.md

Update AMI list for k8s v1.14.3
```release-note
NONE
```

Update for k8s v1.14.3

---

config/crds/awsprovider_v1alpha1_awsmachineproviderspec.yaml
pkg/apis/awsprovider/v1alpha1/awsmachineproviderconfig_types.go
pkg/apis/awsprovider/v1alpha1/types.go
pkg/apis/awsprovider/v1alpha1/zz_generated.deepcopy.go
pkg/cloud/aws/services/ec2/instances.go
pkg/cloud/aws/services/ec2/instances_test.go

This PR adds a new field to the Machine Spec called "availabilityZone". As expressed in the linked issue, users might prefer to specify an AZ to a SubnetID for simplicity. This PR is a simple implementation for that request which picks the first available private subnet within the AZ specified.
Fixes #799 
```release-note
```

Add availaibilityZone to Machine Spec

---

README.md
build/amis/packer/packer.json
cmd/clusterctl/examples/aws/machine-deployment.yaml.template
cmd/clusterctl/examples/aws/machines-ha.yaml.template
cmd/clusterctl/examples/aws/machines.yaml.template
docs/amis.md

- Build/Publish AMIs for k8s v1.13.7
- Set k8s v1.13.7 as default for templates
```release-note
NONE
```

Update for k8s v1.13.7

---

Gopkg.lock
vendor/sigs.k8s.io/cluster-api/Makefile
vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml

Updates cluster-api to v0.1.2
```release-note
Updates common cluster-api components to v0.1.2
```

Update cluster-api for v0.1.2

---

pkg/cloud/aws/services/cloudformation/bootstrap.go

try to fix #815 and #821, add new `ec2:ModifyVpcAttribute` and `ec2:DescribeVolumes` permissions.
this json copy from AWS web console.
When the first problem, the issue #815, is encountered. I tried to add  `ModifyVpcAttribute`， then error has been bypassed.
```json
{
"Version": "2012-10-17",
"Statement": [
{
"Action": [
"ec2:AllocateAddress",
"ec2:AssociateRouteTable",
"ec2:AttachInternetGateway",
"ec2:AuthorizeSecurityGroupIngress",
"ec2:CreateInternetGateway",
"ec2:CreateNatGateway",
"ec2:CreateRoute",
"ec2:CreateRouteTable",
"ec2:CreateSecurityGroup",
"ec2:CreateSubnet",
"ec2:CreateTags",
"ec2:CreateVpc",
"ec2:ModifyVpcAttribute",
"ec2:DeleteInternetGateway",
"ec2:DeleteNatGateway",
"ec2:DeleteRouteTable",
"ec2:DeleteSecurityGroup",
"ec2:DeleteSubnet",
"ec2:DeleteTags", …
```

Bugfix: add ModifyVpcAttribute and DescribeVolumes  permissions

---

pkg/cloud/aws/services/ec2/instances.go
pkg/cloud/aws/services/kubeadm/configs_test.go
pkg/cloud/aws/services/kubeadm/noderegistration.go
pkg/cloud/aws/services/kubeadm/noderegistration_test.go

This uses the provided Init/Join configurations' NodeRegistration as a base. If there is no provided NodeRegistration, this effectively functions the same as before, starting with a blank NodeRegistrationOptions and executing the funcOpts.
Fixes #822 
```release-note
Fixes bug where provided NodeRegistration is not honored
```

fix: use provided NodeRegistrationOptions as base

---

OWNERS_ALIASES

Not working on CAPA much at the moment, so am removing myself from the loop for now.

OWNERS_ALIASES: Remove randomvariable

---

pkg/cloud/aws/services/ec2/securitygroups.go

- Allows metrics-server to function
Fixes #825 
```release-note
NONE
```
I verified this with a 3 node (1 control plane, 2 workers) cluster with the metrics-server deployed on one of the worker nodes, and metrics appear to be fully functional afterwards:
```
> kubectl top node
NAME                         CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
ip-10-0-0-187.ec2.internal   52m          2%     779Mi           20%       
ip-10-0-0-206.ec2.internal   48m          2%     709Mi           18%       
ip-10-0-0-42.ec2.internal    193m         9%     1374Mi          35%     
```

Allow Nodes to talk to Kubelet API Port

---

pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/actuators/machine/actuator_test.go

Ignore deleted control plane machines when checking if a new machine should be a control plane node join or not.
Fixes #828
```release-note
Fix an issue where adding extra control plane machines could accidentally create new clusters instead of joining the existing cluster.
```

Ignore deleted control plane machines

---

pkg/cloud/aws/services/ec2/routetables.go
pkg/cloud/aws/services/ec2/subnets.go
pkg/cloud/aws/services/mocks/services_mock.go

Currently, when specifying a pre-provisioned VPC in the cluster provider spec, the provider controller scans each subnet in the VPC and labels it as `public` if it has a tag `sigs.k8s.io/cluster-api-provider-aws/role = public`, or if it's _explicitly_ associated with a route table that has an internet gateway route. 
The problem is that a subnet may be _implicitly_ associated with a "main" route table in the VPC, which can include an internet gateway route. The current logic ignores such implicit associations, which can leave users wondering why their subnet is not marked as public. 
This PR fixes that.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …

Add logic to handle implicit route table associations to main route table

---

WORKSPACE

Fix cross compilation issue with bazel 0.26+
```release-note
NONE
```

Fix cross compilation issue with bazel 0.26+

---

Gopkg.lock
vendor/sigs.k8s.io/cluster-api/Makefile
vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml
vendor/sigs.k8s.io/cluster-api/docs/developer/releasing.md

Backport of #858 to release-0.3
```release-note
NONE
```

Update to cluster-api v0.1.4

---

pkg/cloud/aws/actuators/machine/actuator.go

Make sure the machine actuator's Create() is using the cluster label
selector to list machines for the specific cluster; otherwise,
isNodeJoin might return false and incorrectly have an additional control
plane machine run `kubeadm init` instead of `kubeadm join`.
Fixes #869 
```release-note
Adding additional control plane machines when you have multiple clusters should now correctly join them to the control plane, instead of creating a …
```

[0.3] Use cluster label selector for machine list

---

WORKSPACE

Currently the docker-push target requires Bazel 0.25.0+, but the bazel minimum version check is set to 0.23.0+.
```release-note
NONE
```

Rev minimum version of Bazel to match requirements

---

OWNERS_ALIASES

This matches my entries for GitHub permissions in k/org.
Signed-off-by: Andy Goldstein <goldsteina@vmware.com>
Fixes #
```release-note
```

Match ncdc owner alias membership with k/org

---

pkg/cloud/aws/actuators/scope.go

This PR fixes an issue where the first reconciliation loop assigns APIEndpoints.Host to an empty string because the ELB might not be ready, and it'll start appending after that. The logic here changes to always have a single APIEndpoint and update if needed.
Fixes #880
```release-note
```

Avoid infinite APIEndpoints

---

README.md
build/amis/packer/packer.json
cmd/clusterctl/examples/aws/controlplane-machine.yaml.template
cmd/clusterctl/examples/aws/controlplane-machines-ha.yaml.template
cmd/clusterctl/examples/aws/machine-deployment.yaml.template
cmd/clusterctl/examples/aws/machines.yaml.template
docs/amis.md

- Add AMIs for Kubernetes v1.13.8 and v1.14.4
- Update manifests to default to Kubernetes v1.14.4
```release-note
- Update manifests to default to Kubernetes v1.14.4
```

Update Kubernetes Versions

---

README.md
build/amis/packer/packer.json
cmd/clusterctl/examples/aws/controlplane-machine.yaml.template
cmd/clusterctl/examples/aws/controlplane-machines-ha.yaml.template
cmd/clusterctl/examples/aws/machine-deployment.yaml.template
cmd/clusterctl/examples/aws/machines.yaml.template
docs/amis.md

- Add AMIs for Kubernetes v1.13.8 and v1.14.4
- Update manifests to default to Kubernetes v1.14.4
```release-note
- Update manifests to default to Kubernetes v1.14.4
```

Backport #897 to release-0.3

---

cmd/manager/main.go

Add an optional pprof http server for debugging goroutines, heap, etc.
Fixes #
```release-note
Added --profiler-address flag to the manager, allowing you to enable the pprof http server.
```

Add optional pprof http server

---

cmd/manager/main.go

Fixes #906 
`./manager -metrics-address="localhost:1233"`
I0717 09:23:53.474902   14910 listener.go:40] controller-runtime/metrics "level"=0 "msg"="metrics server is starting to listen"  "addr"="localhost:1233"
`./manager`
main.go:79] Failed to set up overall controller manager: error listening on :8080: listen tcp :8080: bind: address already in use
as before log, the output of CIL is expected.
Signed-off-by: guohaowang <wangguohao.2009@gmail.com>

feature: support set metric address

---

README.md
docs/amis.md

Add AMIs for Kubernetes v1.15.1
```release-note
NONE
```

Add AMIs for Kubernetes v1.15.1

---

pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/actuators/machine_scope.go

- Moves the update of LB attachments and providerID from Exists to Update
- Always set providerID if unset.
```release-note
- Moves the update of LB attachments and providerID from Exists to Update
- Always set providerID if unset.
```

Do not update LB attachments or providerID in Exists

---

PROJECT
cmd/manager/main.go
config/crds/infrastructure.cluster.x-k8s.io_awsclusterproviderspecs.yaml
config/crds/infrastructure.cluster.x-k8s.io_awsclusterproviderstatuses.yaml
config/crds/infrastructure.cluster.x-k8s.io_awsmachines.yaml
config/crds/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
config/crds/kustomization.yaml
config/rbac/role.yaml
config/samples/infrastructure_v1alpha2_awsmachine.yaml
config/samples/infrastructure_v1alpha2_awsmachinetemplate.yaml
config/samples/infrastructure_v1alpha2_machine.yaml
pkg/apis/awsprovider/v1alpha1/types.go
pkg/apis/infrastructure/v1alpha2/doc.go
pkg/apis/infrastructure/v1alpha2/register.go
pkg/apis/infrastructure/v1alpha2/types.go
pkg/controller/controller.go

Fixes #918 
```release-note
```

Switch apiGroup to cluster.x-k8s.io

---

pkg/cloud/aws/actuators/cluster/actuator.go
pkg/cloud/aws/actuators/machine_scope.go

Fixes #925 
Fixes #928
```release-note
```

[0.3] Add ownerRef to kubeconfig secret, fix NPE in MachineScope

---

pkg/cloud/aws/actuators/cluster/actuator.go

The control plane ready annotation should be removed when no control plane machines are ready, as is the case when all such machines are deleted.
Fixes #936
The cluster actuator is responsible for changing the annotation. It does that whenever the cluster controller reconciles the cluster. In theory, the annotation can be removed as soon as there are no ready control plane machines. But that may not immediately trigger a cluster reconciliation.
For now, the annotation is _eventually_ removed, namely when the cluster controller reconciles the cluster for the …

Cluster actuator: Remove the control plane ready annotation if no control plane machine is ready

---

Makefile

- Fix error with `make clean-bazel-mocks` when bazel-bin/pkg does not exist
```release-note
NONE
```

Fix error with `make clean-bazel-mocks` when bazel-bin/pkg does not exist

---

scripts/ci-bazel-integration.sh

Fixes bazel error when running the integration tests from prow
```release-note
NONE
```

Fix integration test error

---

pkg/cloud/aws/services/cloudformation/bootstrap.go

Fixes a missing IAM policy action for the CAPA controllers.
```release-note
- clusterawsadm now deploys the proper policy with permission for describing vpc attributes
```

[0.3] Update clusterawsadm bootstrap policy

---

pkg/cloud/services/cloudformation/bootstrap.go

E0802 03:18:33.901229       1 cluster_controller.go:166] Error reconciling cluster object manage-cluster; failed to reconcile network for cluster manage-cluster: failed to to set vpc attributes for vpc-0a42fc6644d299113: failed to describe vpc attribute: UnauthorizedOperation: You are not authorized to perform this operation.
status code: 403, request id: db498bbf-e4ed-45d2-9ab1-140e8f94c9be
Signed-off-by: guohaowang <wangguohao.2009@gmail.com>
#950 
```release-note
bugfix: add describe-vpc-attribute permissions
```

bugfix: add describe-vpc-attribute to permissions

---

test/e2e/BUILD.bazel

Increases the "size" of the e2e test in bazel, to avoid timeouts that we've been hitting in the periodics.
```release-note
NONE
```

increase size of bazel e2e test

---

cmd/clusterawsadm/client/BUILD.bazel
cmd/clusterawsadm/client/client.go
cmd/clusterawsadm/cmd/alpha/migrate/BUILD
cmd/clusterawsadm/cmd/alpha/migrate/migrate.go
pkg/apis/awsprovider/v1alpha1/doc.go
pkg/apis/awsprovider/v1alpha1/register.go
pkg/cloud/filter/BUILD.bazel
pkg/cloud/filter/ec2.go

This PR removes CRD generation from v1alpha1 types. We no longer need to generate CRDs from the v1alpha1 types but we will need to generate deep copy and other code. We keep the types around for the upgrade tool that will be built here.
This unblocks us from keeping this repo up-to-date with a controller-gen style config directory and a single `kustomize.yaml` file to generate all necessary CRDs.
Related to #968 
The deleted code in `clusterawsadm` is unused.
```release-note
NONE
```
/assign @ncdc …

Remove generation from v1alpha1 types

---

build/amis/ansible/roles/common/tasks/redhat.yml

The AMI build process doesn't recognize Amazon Linux properly.
Fixes #978 
`ansible_distribution_major_version` is `2`. I think you may have wanted `ansible_distribution_release` which is `NA` but I didn't see any reason why that was necessary. Can add it if there is.
```release-note
```

fix for AMI build to detect Amazon Linux

---

config/crds/infrastructure.cluster.x-k8s.io_awsclusters.yaml
config/crds/infrastructure.cluster.x-k8s.io_awsmachines.yaml
config/rbac/role.yaml
pkg/apis/infrastructure/v1alpha2/awscluster_types.go
pkg/apis/infrastructure/v1alpha2/awsmachine_types.go
pkg/apis/infrastructure/v1alpha2/types.go
pkg/cloud/scope/cluster.go
pkg/controller/controller.go

1. Update RBAC to allow working with AWSCluster objects
2. Enable the status endpoint
3. Some fields in the network status needed to be made optional based on their behaviors in AWS. There may be more out there but these are the ones that blocked me.
4. Another edition of everyone's favorite GVK patch hack
```release-note
RBAC/CRD manifest updates
```

fix: update rbac for working with Cluster objects, enable status endpoint

---

pkg/cloud/scope/machine.go

Signed-off-by: Andrew Rudoi <arudoi@newrelic.com>
Cluster wasn't being passed through NewMachineScope, causing an NPE later down the line. I was on the fence about adding the nil check here because I thought we didn't need a cluster to make Machines even in v1a2, but most of the other helpers return hard errors when there's no cluster object so I followed that pattern. 
```release-note
```

fix: pass cluster into machinescope return

---

pkg/cloud/services/elb/loadbalancer.go

Signed-off-by: John Harris <joharris@vmware.com>
When the healthcheck protocol is TCP the APIServer logs are
constantly spammed with Handshake EOF errors. This alters the
healthcheck target from `TCP:6443` to `SSL:6443`.
```
...
I0811 22:52:53.992577       1 log.go:172] http: TLS handshake error from 10.0.1.129:4224: EOF
I0811 22:52:54.630065       1 log.go:172] http: TLS handshake error from 10.0.1.203:16836: EOF
I0811 22:53:03.992780       1 log.go:172] http: TLS handshake error from 10.0.1.129:4240: EOF
...
```
Fixes #1000 
N/A …

Change APIServer healthcheck to SSL protocol

---

pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_test.go

Signed-off-by: Andrew Rudoi <arudoi@newrelic.com>
Decodes bootstrap data. The bootstrap provider sets the bootstrap data as a base64-encoded string, so we must decode it.
Also snuck in a small typo fix. 
```release-note
```

fix: base64 decode bootstrap data

---

pkg/cloud/aws/actuators/machine/actuator.go

Guard against missing instanceID on delete
```release-note
Guard against missing instanceID when deleting Machines
```

Guard against missing instanceID on delete

---

pkg/cloud/aws/services/ec2/instances.go

Previously, we observed a machine that was repeatedly failing to create
(we wanted an m5.large, but we were already at our quota for m5.larges)
would get a new copy of the node role appended to its labels every time
it tried.
I don't think it would've hurt anything and so this is a low-priority
(v1alpha1-only) item to be sure.
Fixes #
```release-note
fixes issue where node-labels would grow unbounded if a machine could not be created
```

fix: avoid duplicate nodeRole label in spec

---

pkg/cloud/aws/services/ec2/subnets.go
pkg/cloud/aws/services/ec2/subnets_test.go

Currently creating a Service with type=LoadBalancer will fail with the existing managed private subnets, this change will let the subnet be returned by the cloud provider integration query and allow the LoadBalancer to be created
Fixes #1008 
```release-note
Fixed bug where Service with type=LoadBalancer would fail on workload clusters.
```

[0.3]Update tags for managed subnets for Service type=LoadBalancer

---

pkg/cloud/aws/services/ec2/instances.go

It was pointed out in #1022 that the returned error message also includes the input instance in the error message, while this provides additional information about what the inputs going in were, it makes the returned error message more difficult to parse.
Fixes #1022
If we would like to still provide the given inputs as debug information, I would be happy to look at adding separate debug logging that contains that information.
Also, if this is deemed to be a good approach for handling this, I'm happy to open up a similar patch against master.
```release-note …
```

Do not include input object in the error message

---

pkg/cloud/aws/services/ec2/subnets.go
pkg/cloud/aws/services/ec2/subnets_test.go

when creating a service of type LoadBalancer, the controller manager searches for subnets tagged with `kubernetes.io/cluster/<name>`. If only the private subnet is tagged, only services with the annotation `service.beta.kubernetes.io/aws-load-balancer-internal: "true"` will work. The default service of type LoadBalancer provisions an internet-facing ELB that requires a public subnet.
Fixes #1008 
```release-note
```

apply tags to all subnets, not just private, to fix #1008

---

pkg/cloud/scope/machine.go
pkg/controller/awsmachine/awsmachine_controller.go

Sets `.Status.Ready` to true when instance is running.
Fixes #1032 
Is there anywhere in here we need to set it to false or is that too spicy?
```release-note
```

chore: set status.ready when machine is running

---

cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
pkg/cloud/services/cloudformation/bootstrap.go

Currently, `clusterawsadm` can create IAM policies for the stardard AWS regions. For AWS GovCloud and AWS China, the ARN needs to updated with a specific partition name. From the AWS documentation: 
```
AWS accounts are scoped to a single partition. You can get a partition by name. Valid partition names include:
"aws" - Public AWS partition
"aws-cn" - AWS China
"aws-us-gov" - AWS GovCloud
```
Fixes #959 
I'm not super familiar with Cobra, so let me know if there is a different convention I should use for setting the flag and retrieving it's value.
_Please …

--partition flag for clusterawsadm

---

BUILD.bazel
test/e2e/BUILD.bazel

In the [latest e2e test failure](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cluster-api-provider-aws-bazel-e2e/1163552170134474752) I noticed that bazel was referencing a location that no longer exists, so this updates the references to point to the correct location.
Fixes #
```release-note
```

Update manager image references

---

pkg/cloud/services/ec2/subnets.go
pkg/cloud/services/ec2/subnets_test.go

When creating a service of type LoadBalancer, the controller manager searches for subnets tagged with kubernetes.io/cluster/<name>. If no subnets with that tag are found, the ELB will not be provisioned. This was fixed in v0.3 branch but not yet on master.
Fixes #1008 
```release-note
Bugfix: Service of type LoadBalancer now provisions ELB
```

add tags for service of type LoadBalancer to create ELB

---

test/e2e/aws_test.go

I noticed the e2e were failing due to a [missing argument](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cluster-api-provider-aws-bazel-e2e/1163578343853920256#0:build-log.txt%3A217) that was recently introduced, so this adds that to the e2e tests.
Fixes #
```release-note
```

Add missing partition argument to ReconcileBootstrapStack call

---

hack/verify-bazel.sh

When looking at the one of the test failure outputs from #1042, I noticed that [`make verify` failure](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/1042/pull-cluster-api-provider-aws-verify/1163595080984956930#0:build-log.txt%3A58) wasn't returning much in the way of helpful output as to what caused it to fail.
Replicating this locally, I noticed that [`bazel run //:gazelle ...`](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/f1ae6d0021e95b6b2fab56da7210b1f3035e2fd8/hack/verify-bazel.sh#L23) would return with code 1 if it found anything, which in combination with `set -o errexit` would simply cause an early exit without the intended output.
These changes make it possible to …

Do not exit immediately if gazelle fix finds something; address shellcheck nit

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

This PR updates the PR template to match what we're doing in Cluster API.
Fixes #
```release-note
```

:running: Update PR template to match CAPI

---

controllers/awscluster_controller.go
controllers/awscluster_controller_test.go
controllers/awsmachine_controller.go

- Removes requeues for resources that we are watching
- Adds a watch for AWSClusters in the AWSMachine controller
Fixes #1037 
```release-note
NONE
```

:sparkles: Remove unnecessary requeues

---

controllers/awsmachine_controller.go
pkg/cloud/services/ec2/securitygroups.go
pkg/cloud/services/ec2/vpc.go

- fixes reconciliation when ssh key is not specified
- clean up some events
- add initial reconciliation logging for AWSMachine
```release-note
NONE
```

:bug: Fix reconciliation issue when not specifying an ssh key

---

examples/cluster/cluster.yaml
examples/generate.sh
examples/machinedeployment/kustomization.yaml
examples/machinedeployment/kustomizeconfig.yaml
examples/machinedeployment/machinedeployment.yaml

:sparkles: Add MachineDeployment example

---

pkg/cloud/scope/BUILD.bazel
pkg/cloud/scope/cluster.go
pkg/cloud/scope/machine.go
vendor/modules.txt

fix issue: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1019
Fixes #
```release-note
```

use cluster api patch helper to do the scope close

---

pkg/cloud/services/ec2/securitygroups.go

Cleans up some of the events generated related to security groups
```release-note
NONE
```

:bug: Clean up some of the security group events and logs

---

examples/provider-components/manager_tolerations_patch.yaml

This patch updates the manager toleration patch to account for an upstream change to the CAPI manager deployment (https://github.com/kubernetes-sigs/cluster-api/pull/1332).
Fixes #
```release-note
NONE
```

Update tolerations patch

---

examples/machinedeployment/machinedeployment.yaml

- Adds a unique label for the Machine Deployment example, otherwise MachineSets for additional MachineDeployments would also match the same label selector
```release-note
NONE
```

:bug: Add unique label for MachineDeployment example

---

controllers/awsmachine_controller.go
go.sum

When deleting an AWSMachine whose instance is already shutdown or already terminated, we should still remove the finalizer.

:bug: Improve handling of instance deletion

---

pkg/cloud/aws/services/ec2/eips.go
pkg/cloud/aws/services/ec2/gateways.go
pkg/cloud/aws/services/ec2/natgateways.go
pkg/cloud/aws/services/ec2/routetables.go
pkg/cloud/aws/services/ec2/securitygroups.go
pkg/cloud/aws/services/ec2/subnets.go
pkg/cloud/aws/services/ec2/vpc.go
pkg/cloud/aws/services/elb/loadbalancer.go
pkg/cloud/aws/services/wait/wait.go

[0.3] Backport: Refactor wait package to be capped to 10m and simplify

---

controllers/awsmachine_controller.go
pkg/cloud/scope/cluster.go
pkg/cloud/scope/machine.go

This PR adheres to the standard that the program should only use one context and `context.TODO()` everywhere a context is not available.

🏃 Context cleanups

---

.github/PULL_REQUEST_TEMPLATE.md

🏃 Remove release notes from PR template

---

.gitignore
api/v1alpha2/tags.go
api/v1alpha2/tags_test.go
controllers/awsmachine_controller.go
pkg/cloud/scope/cluster.go
pkg/cloud/scope/machine.go
pkg/cloud/services/ec2/bastion.go
pkg/cloud/services/ec2/eips.go
pkg/cloud/services/ec2/gateways.go
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_test.go
pkg/cloud/services/ec2/natgateways.go
pkg/cloud/services/ec2/routetables.go
pkg/cloud/services/ec2/securitygroups.go
pkg/cloud/services/ec2/subnets.go
pkg/cloud/services/ec2/vpc.go
pkg/cloud/services/elb/loadbalancer.go

Add support for applying custom tags to all AWS resources we manage. Every tag in AWSCluster.Spec.AdditionalTags is applied to all AWS resources we manage. For ec2 instances, we process tags in both AWSCluster and AWSMachine, with those in AWSMachine taking precedence if the same tag is present in both.
Fixes #1105 
/kind feature
/priority important-soon
/milestone v0.4.x

:sparkles: Add support for applying custom tags to all AWS resources we manage

---

api/v1alpha2/awsmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml

This PR is a small addition to the RootDeviceSize comment in AWSMachineSpec type to specify what measurement unit (GBs) are used by this field.
Fixes #1118

✨  Specified measurement unit for rootdevicesize comment

---

controllers/awsmachine_controller.go

Allows machines that were never created to be deleted.
When a machine is never created (in our case, because we were hitting a service quota), it can't be deleted & will block MachineDeployments from making progress.

:bug: remove finalizer when machine is absent

---

controllers/awscluster_controller.go

Currently the reconciler requeues when the apiserver DNS name is not set. If the DNS is set, the port of the first listener is grabbed. Turns out we were not actually grabbing the listeners...
So there's an `index out of range` panic :D

🐛fix: use clusterScope's port in APIEndpoint

---

pkg/cloud/aws/services/userdata/controlplane_init.go
pkg/cloud/aws/services/userdata/controlplane_join.go
pkg/cloud/aws/services/userdata/node.go

Removes the use of the custom kubeadm cloud init module

[v1alpha1] :sparkles: Remove use of cloud-init module

---

README.md

Fixes a typo in the compatibility matrix of the README

:book: Fix typo in readme

---

pkg/cloud/services/cloudformation/bootstrap.go
pkg/cloud/services/ec2/instances.go

Turns out, the destination in the copy builtin is first!
Fixes #1151

fix: use copy builtin correctly for security groups

---

api/v1alpha2/awscluster_types.go
api/v1alpha2/awsmachine_types.go
api/v1alpha2/zz_generated.conversion.go
api/v1alpha2/zz_generated.deepcopy.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
pkg/cloud/scope/cluster.go
pkg/cloud/scope/machine.go
pkg/cloud/services/ec2/securitygroups.go
pkg/cloud/services/ec2/securitygroups_test.go

Fixes a "leak" where the load balancer security groups' tags were being applied to other security groups because maps are secret pointers.
There's a test for the security group issue specifically, but I think I fixed/prevented some other odd behaviors around merging a Machine's tags into the cluster-level Scope.

🐛Fix a leak of AWS Tags from between Machine and Cluster resources

---

config/manager/manager.yaml

Signed-off-by: Andrew Sy Kim <kiman@vmware.com>
Adds toleration for well-known taints like node-role.kubernetes.io/master to released CAPA manager manifest.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/1486

add well-known tolerations to released CAPA manager manifest

---

pkg/cloud/services/ec2/subnets.go
pkg/cloud/services/ec2/subnets_test.go

Amazon requires [certain tags](https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html) on subnets for ALBs and other resources to be provisioned. This causes us to always set those tags. 
Fixes #1142

:sparkles: Apply elb-related tags to managed subnets

---

main.go

As discussed on [slack](https://kubernetes.slack.com/archives/CD6U2V71N/p1570024727095600), and seeing lots of user confusion, this PR increased the default concurrency for the reconcilers.

✨Increase AWSCluster and AWSMachine default concurrency

---

hack/ensure-kustomize.sh

Fixes the script used to download kustomize in CI, which has resulted in broken e2e test signal.

:running: Fix hack/ensure-kustomize.sh

---

dev.dockerfile
third_party/forked/README.md
third_party/forked/rerun-process-wrapper/LICENSE
third_party/forked/rerun-process-wrapper/README.md
third_party/forked/rerun-process-wrapper/restart.sh
third_party/forked/rerun-process-wrapper/start.sh

The third_party code is necessary for tilt's live_update feature
on a containerd-based kubernetes system
This docker file allows us to iterate quickly with tilt's live_update feature
/cc @noamran @ncdc

🏃 Add a development dockerfile

---

config/default/manager_webhook_patch.yaml
main.go

Add webhook port flag (default 8443)
Fixes #1120

✨ Add webhook port flag

---

api/v1alpha2/types.go

Add omitempty to RouteTableID. Without this, if you leave the field nil
and try to use a go client (client-go / controller-runtime) to create an
AWSCluster, it will fail with the error
spec.networkSpec.subnets.routeTableId in body must be of type string:
\"null\"
Fixes #1195

🐛 Add omitempty to RouteTableID

---

api/v1alpha3/groupversion_info.go

**What this PR does / why we need it**: Fix `GroupVersion` in `v1alpha3` (it was still saying `v1alpha2`).
Fixes #1211

🐛 Fix API version in v1alpha3

---

pkg/cloud/services/ec2/natgateways.go

To avoid a nil pointer dereference error, do not attempt to log the NAT
gateway ID when we get an error back from the AWS client.
Fixes #1209

🐛Do not attempt to log NAT gateway ID when creation fails

---

api/v1alpha3/awsmachinetemplate_webhook.go
api/v1alpha3/zz_generated.deepcopy.go
config/certmanager/certificate.yaml
config/crd/kustomization.yaml
config/default/kustomization.yaml
config/default/webhookcainjection_patch.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml
config/webhook/kustomizeconfig.yaml
config/webhook/manifests.yaml
config/webhook/service.yaml
examples/generate.sh
main.go

✨ Add validating webhook for AWSMachineTemplate

---

pkg/cloud/services/ec2/natgateways.go

To avoid a nil pointer dereference error, do not attempt to log the NAT
gateway ID when we get an error back from the AWS client.
Signed-off-by: Alexander Brand <alexbrand09@gmail.com>
(cherry picked from commit 34d21a0007802620fa74cd16594e6b78f2c7155c)
Fixes #1214

🐛 [0.4] Do not attempt to log NAT gateway ID when creation fails

---

pkg/cloud/services/ec2/ami.go

The added AMI is "ami-7dd85203":
Zone: eu-north-1
Name: xenial
Version: 16.04 LTS
Arch: amd64
Instance Type: hvm:ebs-ssd
Release: 20190913
AMI-ID: ami-7dd85203
AKI-ID: hvm
At the moment there is no default bastion AMI for the `eu-north-1` region.

:bug: add a default bastion AMI for the eu-north-1 (Stockholm) region

---

test/e2e/aws_test.go

Attempts to resolve the current e2e failures around timing out while waiting for the cluster infrastructure to be ready

:running: Tweak e2e timeout for waitForClusterInfrastructureReady

---

test/e2e/aws_test.go
test/e2e/e2e_suite_test.go

- Fix missing reference to `bootstrapv1`
- Increase timeout in waitForClusterInfrastructureReady

:running: Patch up e2e tests

---

api/v1alpha3/awsmachinetemplate_webhook.go
config/webhook/manifests.yaml

- Rename vawsmachinetemplate.kb.io to validating.awsmachine.infrastructure.x-k8s.io

:running: Update name of AWSMachineTemplate validating webhook

---

api/v1alpha3/awsmachinetemplate_webhook.go
config/webhook/manifests.yaml

Fixes the name for the AWSMachineTemplate validating webhook from `validation.awsmachine.infrastructure.x-k8s.io` to `validation.awsmachinetemplate.infrastructure.x-k8s.io`

:bug: Fix AWSMachineTemplate webhook name

---

go.mod
go.sum
pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go

Of interest to CAPA are the following:
* Support for M5n, M5dn, R5n, R5dn, A1.metal & G4 instances
* Updates to region and endpoint data
* Updates to the default retryer:
* Configurable retry behaviours
* Calculated jitter for delay
* Support for client-side metrics
* Support for assuming role via the Kubernetes service account token

:running: go.mod: Bump AWS SDK to v1.25.16

---

test/e2e/e2e_suite_test.go

- Updates the e2e test suite to fetch the controller logs when tearing down the kind cluster, this should help with troubleshooting failures.

:running: [e2e] Fetch controller logs when tearing down kind cluster

---

test/e2e/aws_test.go
test/e2e/e2e_suite_test.go

Fixes region mismatch between keypair creation and Cluster creation

:running: [e2e] Fix region handling for e2e tests

---

test/e2e/e2e_suite_test.go

Fixes a build related issue with the e2e tests that doesn't appear to be caught by presubmit validation today.

:running: [e2e] Fix verification issues with e2e test

---

Makefile

Similar to what we did in https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/188 we should be able to build a local image and use that in `kind`
Fixes #

✨ LOAD_IMAGE to allow injecting locally built image into kind

---

Makefile

Cherry pick of #1250 on release-0.4.
#1250: LOAD_IMAGE to allow injecting locally built image into kind

Automated cherry pick of #1250: LOAD_IMAGE to allow injecting locally built image into kind

---

main.go

Adds options that primarily allow the provider to be run using `go run .` for testing.

:sparkles: Allow webhook to be disabled and make leader election namespace configurable

---

examples/controlplane/controlplane.yaml
examples/controlplane/kustomizeversions.yaml
examples/generate.sh
examples/machinedeployment/kustomizeversions.yaml
examples/machinedeployment/machinedeployment.yaml
hack/ci/README.md
hack/ci/e2e-conformance.sh
hack/ensure-kind.sh
scripts/ci-conformance.sh

Cherry pick of #1254 on release-0.4.
#1254: e2e-conformance.sh to be able to run e2e tests

✨Automated cherry pick of #1254: e2e-conformance.sh to be able to run e2e tests

---

controllers/awsmachine_controller.go
controllers/awsmachine_controller_test.go
pkg/cloud/services/interfaces.go
pkg/cloud/services/mock_services/ec2_machine_interface_mock.go

The previous machine controller unit test only covered create. This covers delete as well. 
Fixes #1035 
I deleted the stubbed out ELB tests because I didn't think it was worth stubbing out that whole service for one test. Let me know if you disagree!

:running: unit tests for deleting machines

---

pkg/cloud/awserrors/errors.go
pkg/cloud/services/cloudformation/bootstrap.go
pkg/cloud/services/ec2/eips.go

Disassociate an Elastic IP if it is still associated, most commonly with an ELB
that is no longer visible in the API after deletion.
Fixes #1185 
**For release note**:
```
CloudFormation will need to be reapplied to allow Cluster API Provider AWS to disassociate IP addresses.
```

:bug: Disassociate Elastic IPs on deletion, if still associated

---

test/e2e/e2e_suite_test.go

Use credentials we create in the cloud formation template instead of the boskos provided credentials

:running: [e2e] update credentials used for controller

---

README.md
docs/amis.md

Updates the available AMI versions and AMI IDs for the latest Kubernetes versions.

:book: Update available AMI versions

---

test/e2e/e2e_suite_test.go

- Fixes the missing kindClient initialization that was missed in backporting

:running: [e2e] fix missing kindClient

---

test/e2e/e2e_suite_test.go

reinitialize the kindClient after deploying the cluster api components

:running: [e2e] reinitialize the kindClient after deploying the cluster api components

---

controllers/awsmachine_controller.go

Fixes a nil pointer dereference in Machine reconcileDelete

:bug: Fix Machine reconciliation of deletion

---

pkg/cloud/services/ec2/instances.go

Cherry pick of #1276 on release-0.4.
#1276: services: Record events only on AWSMachine

:bug: Record events only on AWSMachine

---

pkg/cloud/services/wait/wait.go

Revises the exponential backoff parameters such that the retries are not cancelled
after 20s.
These parameters are chosen so that the maximum retry time is 300s +/- 120s.
The wait method from API machinery continues to be employed, and is compared to the
[Full Jitter and Decorrelated Jitter approach using the AWS concurrent client sample simulation](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/) below.
These parameters compare well to the Full Jitter method, which is one of the recommended approaches. 
Fixes #1283

:bug: Revise wait backoff parameters

---

api/v1alpha3/awscluster_types.go
api/v1alpha3/awsmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml

Adds printer columns for AWSMachine and AWSCluster.
Example output:
```
[$] took 5s ➜ k get awsmachine
NAME                      CLUSTER    STATE     READY   INSTANCEID                    MACHINE
aws-test-controlplane-0   aws-test   running   true    aws:////i-06ef85a7726924b87   aws-test-controlplane-0
aws-test-worker-4bfdg     aws-test   running   true    aws:////i-07ade4576a2a4c226   aws-test-worker-cf6b4ff76-h7qlb
aws-test-worker-f62c4     aws-test   running   true    aws:////i-06e4de3f93f0f5c66   aws-test-worker-cf6b4ff76-vqrkb
aws-test-worker-n6zkx     aws-test   running   true    aws:////i-05e33c9b2dfe2c1b0   aws-test-worker-cf6b4ff76-v22h7
```
```
[$] took 5s ➜ k get awscluster
NAME       READY   VPC                     BASTION IP
aws-test …
```

:sparkles: Add printer columns

---

cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
go.mod
go.sum
pkg/cloud/services/cloudformation/bootstrap.go
pkg/cloud/services/iam/types.go

Removes a terrible hack to get round https://github.com/awslabs/goformation/issues/157 which has now been resolved.
Fixes #

:sparkles: Bump goformation to v3, and remove IAM hacks

---

docs/releasing.md

As a follow up to https://github.com/kubernetes-sigs/cluster-api/issues/1681 -  adding `make release-notes` to the release document

📖 Document how to generate release notes

---

test/e2e/aws_test.go

Fixes a type mismatch on comparison with the e2e test

:running: [e2e] fix machinedeployment scaling comparison

---

pkg/cloud/services/cloudformation/cloudformation.go
test/e2e/e2e_suite_test.go

On teardown of the e2e suite, delete the cloudformation stack

:running: [e2e] delete cloudformation stack on teardown

---

cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go

Cherry pick of #1299 on release-0.4.
#1299: We should propagate any errors during create-stack

Automated cherry pick of #1299: We should propagate any errors during create-stack

---

examples/provider-components/manager_tolerations_patch.yaml

cabpk is not a separate controller any more. fixes a new problem after i hastily merged https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1302
Fixes #

Drop cabpk from manager tolerations patch

---

main.go

🏃 Bump AWSMachine concurrency to 10, AWSCluster to 5

---

test/e2e/e2e_suite_test.go

Updates the e2e test to use upstream cert-manager, since we are removing it from capi

:running: [e2e] Update e2e test to use upstream cert-manager

---

Makefile

Fix this error
```bash
$ make create-cluster-management
unable to recognize "examples/_out/provider-components.yaml": no matches for kind "Certificate" in version "certmanager.k8s.io/v1alpha1"
unable to recognize "examples/_out/provider-components.yaml": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"
```
Fixes #

🐛 Wait for cert-manager in `make create-cluster-management`

---

test/e2e/aws_test.go

Forward ports MachineDeployment e2e tests to HEAD from the `release-0.4` branch.

:running: [e2e] Forward port MachineDeployment to HEAD

---

api/v1alpha3/awscluster_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_test.go

This PR adds a new field, `ImageLookupOrg`, to the `AWSClusterSpec` struct. The `ImageLookupOrg` field can be used to override the organization ID used when looking up AMIs for machines. Note that the `ImageLookupOrg` is only used when a machine does not specify an AMI ID.
With this change, the `ImageLookupOrg` can be set at the cluster-level or at the machine-level. The machine-level `ImageLookupOrg` takes precedence over the cluster-level `ImageLookupOrg`.
Fixes #1292

✨ AWSCluster: Allow setting ImageLookupOrg at the cluster level

---

examples/generate.sh
examples/machinedeployment/machinedeployment.yaml
hack/ci/e2e-conformance.sh
scripts/ci-conformance.sh

- Use python script for envsubst
- Add / Delete keypair if not preset
- Avoid printing unnecessary stuff
- Support specifying a lookup org for images
- option for skipping creation of the AMI image
Fixes #

✨Fix up e2e conformance tests (release 0.4)

---

test/e2e/aws_test.go

Fixes up usage of old naming for the ClusterLabelName

:running: [e2e] Update ClusterLabelName usage

---

test/e2e/aws_test.go

Fixes up the use of MachineDeployment in the e2e suite.

:running: [e2e] Fix up MachineDeployment for latest v1alpha3 changes

---

hack/ci/e2e-conformance.sh
scripts/ci-conformance.sh

Cherry pick of #1316 on release-0.4.
#1316: Better command line processing in e2e-conformance.sh

✨Automated cherry pick of #1316: Better command line processing in e2e-conformance.sh

---

hack/ci/e2e-conformance.sh
scripts/ci-conformance.sh

Allow stuff to be passed in as command line params
Also switch on the flag to use latest CI artifacts
Fixes #

✨Better command line processing in e2e-conformance.sh

---

hack/ci/e2e-conformance.sh

we need to switch to pod utils since bootstrap.py is deprecated. under pod utils the path is slightly different.
Fixes #

✨ Fix path to image-builder under pod utils

---

scripts/ci-conformance.sh

we should pass in "--use-ci-artifacts" only in the jobs we want to test against k/k CI master artifacts
Fixes #

✨ Allow passing in parameters to ci-conformance.sh

---

hack/ci/e2e-conformance.sh
scripts/ci-conformance.sh

- pass through params from CI through ci-conformance.sh to the
e2e-conformance.sh
- Add checks for mandatory AWS env vars
- Add more logs to what we are dumping already
Fixes #

✨Fine tune e2e-conformance and ci-conformance.sh

---

Makefile
examples/generate.sh

cert-manager components is required by the capa-controller-manager. The
user should create cert-manager components before creating capa
control-plane.
Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>
This PR creates `examples/_out/cert-manager.yaml` when running `make generate-examples`.
This PR improves the user experience for those using the `make generate-examples` command to understand how to deploy capa control plane.
Fixes #1233

🐛Add cert-manager to output of generate-examples

---

api/v1alpha2/types.go
api/v1alpha2/zz_generated.deepcopy.go
api/v1alpha3/types.go
api/v1alpha3/zz_generated.deepcopy.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
controllers/awsmachine_controller.go
pkg/cloud/scope/machine.go
pkg/cloud/services/ec2/instances.go

This PR is pretty similar to one merged in the GCP provider a few hours ago. 
It will add the ability to fish out the internal and external IPs
associated with an awsmachine resource and populate those values in
.status.addresses.
Happy to backport to release-0.4 after merge as well.
Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>

✨ Add addresses to machine status

---

examples/controlplane/controlplane.yaml
examples/controlplane/kustomizeversions.yaml
examples/machinedeployment/kustomizeversions.yaml
examples/machinedeployment/machinedeployment.yaml

Remove the ${IMAGE_ID} placeholder from the examples, as it's only used
for e2e conformance testing, and it's broken for example usage.
Use kustomize patches to handle the IMAGE_ID for e2e testing instead.
Fixes #1300

🐛 [0.4] Fix IMAGE_ID issue in examples

---

Makefile
examples/controlplane/controlplane.yaml
examples/controlplane/kustomizeversions.yaml
examples/machinedeployment/kustomizeversions.yaml
examples/machinedeployment/machinedeployment.yaml

Remove the ${IMAGE_ID} placeholder from the examples, as it's only used
for e2e conformance testing, and it's broken for example usage.
Use kustomize patches to handle the IMAGE_ID for e2e testing instead.
Cherry-pick of #1336 for `master`
Fixes #

🐛 Fix IMAGE_ID issue in examples

---

go.mod
pkg/cloud/services/elb/loadbalancer.go
pkg/cloud/services/elb/loadbalancer_test.go
pkg/internal/hash/base36.go

* Replaces "." in the ELB name with "-" making them compatible with the ELB API.
* Additionally, if the original, computed ELB name is more than 32 characters, then
use a truncated form of Blake2b to compute a consistent hash formatted ELB name.
Think this approach has a sufficiently low risk of collisions. "apiserver" suffix is
replaced with "k8s" to regain some entropy. Names arrive in the format of:
* `26o3cjil5at5qn27vukn5x09b3ql-k8s`
* `t8gnrbbifaaf5d0k4xmwui3xwvip-k8s`
etc...
Fixes #977 
Fixes #889

:sparkles: Support cluster names > 22 characters in length

---

controllers/awsmachine_controller.go
controllers/awsmachine_controller_test.go
pkg/cloud/scope/machine.go

Tweaks EC2 instance state handling in the following ways:
* Emit log event as well as publish event to resource for better traceability
* Ignore instance attributes for validation when the instance is terminated, or about to transition to terminated from "shutting-down".
* Don't error when EC2 instance is stopping or is stopped, as machine could be rebooted.
Fixes #1239 
Fixes #1238

:bug: Improve EC2 state handling, and set error for manually deleted EC2 instances

---

pkg/cloud/services/elb/loadbalancer.go

release:  v0.4.4
Check for subnet nil pointer when register instance to apiserver elb. 
This fix the case that if AWSCluster.Spec.NetworkSpec somehow loses subnetID information, machine controller will wait for cluster controller to finish reconcileNetwork before trying to attach control plane to ELB.  
fix: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1342

:bug: check for subnet nil pointer when register instance to apiserver elb

---

pkg/cloud/scope/cluster.go

Handles case most commonly seen during AWS role assumption where no credentials exist, role assumption has failed and an error needs to be bubbled up to the consumer.
Fixes #1343
Testing this is a little non-trivial due to needing to pass the recorder down into the AWS request handler. An attempt was made in #1349

:bug: Add NoCredentialProviders to list of authentication errors

---

cmd/versioninfo/versioninfo.go
hack/version.sh

Remove git branch from version info. This information is not really
relevant (a branch can have any name; what is important is the commit
and/or tag). It also breaks building the release versions of binaries.
Fixes #1362

🐛 Remove git branch from version info

---

pkg/cloud/services/elb/loadbalancer.go

AWSCluster controller now reconciles `AdditionalTags` against the API Server ELB.
Fixes #1376

✨reconcile apiserver elb tags

---

test/e2e/aws_test.go
test/e2e/conformance_test.go
test/e2e/e2e_suite_test.go

**What this PR does**:
* Adds flags to set the kubernetes version of workload clusters to test up on.
* Adds flags to set sonobuoy version to run conformance
**Why we need it**
Helps to run conformance/functional tests on latest kuberentes versions easily

:sparkles: Improves e2e tests by using version flags

---

cmd/versioninfo/versioninfo.go
hack/version.sh

Remove git branch from version info. This information is not really
relevant (a branch can have any name; what is important is the commit
and/or tag). It also breaks building the release versions of binaries
(see
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1362)
Signed-off-by: Andy Goldstein <goldsteina@vmware.com>
(cherry picked from commit f33b041e62fc489f4300ae23451558d46ac224cc)
Backport of #1366 to release-0.4

:running: [0.4] Remove git branch from version info

---

api/v1alpha3/awsmachine_webhook.go
api/v1alpha3/awsmachine_webhook_test.go
config/webhook/manifests.yaml
controllers/awsmachine_controller.go

✨ Add validation webhook for AWSMachine

---

Makefile
examples/machinedeployment/kustomizeconfig.yaml
examples/machinedeployment/machinedeployment.yaml

Instead of sleeping 10 seconds and hoping that cert-manager is ready,
use 'kubectl wait' to wait for the cert-manager webhook apiservice.
Also fix a conformance issue where the apiVersion of the MachineDeployment was wrong (v1a1 instead of v1a2).
Fixes #1383

🐛 make create-cluster: Improve cert-manager wait

---

Makefile
hack/ci/e2e-conformance.sh

Make conformance cluster names unique by default, so we have a better chance of being able to retrieve logs from the VMs (it's broken currently because there's already a keypair for `test1`, and because each run is _not_ generating a new keypair, it's unable to retrieve).
/hold

🏃 Make conformance cluster names unique by default

---

Makefile
hack/ci/e2e-conformance.sh

*What this PR does / why we need it**:
Make conformance cluster names unique by default, so we have a better chance of being able to retrieve logs from the VMs (it's broken currently because there's already a keypair for test1, and because each run is not generating a new keypair, it's unable to retrieve).
This is a manual backport of #1388 to release-0.4.
/hold

🏃 [0.4] Make conformance cluster names unique by default

---

examples/controlplane/kustomizeversions.yaml
examples/machinedeployment/kustomizeversions.yaml
hack/ci/e2e-conformance.sh

**Change 1**
When generating examples for the conformance tests, the
/tmp/kubeadm-bootstraph.sh preKubeadmCommand downloads gsutil if it does
not exist and adjusts $PATH accordingly. However, the script that
generates examples substitutes the values for environment variable
placeholders in the file, which means it will substitute whatever the
current value of $PATH is in your local environment.
Instead of trying to adjust $PATH, use a variable for gsutil to invoke
it.
**Change 2**
We've had an issue where we aren't always capturing the logs for the
control plane VMs, especially if the cluster fails to initialize;
instead, we've managed to capture just the bastion. This change removes
the code that filters out the first private IP address when …

🏃 [0.4] conformance: Fix gsutil usage, try capturing all VM logs

---

examples/controlplane/kustomizeversions.yaml
examples/machinedeployment/kustomizeversions.yaml
hack/ci/e2e-conformance.sh

**Change 1**
When generating examples for the conformance tests, the
/tmp/kubeadm-bootstraph.sh preKubeadmCommand downloads gsutil if it does
not exist and adjusts $PATH accordingly. However, the script that
generates examples substitutes the values for environment variable
placeholders in the file, which means it will substitute whatever the
current value of $PATH is in your local environment.
Instead of trying to adjust $PATH, use a variable for gsutil to invoke
it.
**Change 2**
We've had an issue where we aren't always capturing the logs for the
control plane VMs, especially if the cluster fails to initialize;
instead, we've managed to capture just the bastion. This change removes
the code that filters out the first private IP address when …

🏃 conformance: Fix gsutil usage, try capturing all VM logs

---

examples/controlplane/kustomizeversions.yaml
examples/machinedeployment/kustomizeversions.yaml

If CI_VERSION is a released version such as v1.16.3, we need to use a
different GCS bucket to download the artifacts.
This might f-i-x #1389
/cc @dims @vincepri 
/assign @dims @vincepri 
/milestone v0.4.x

🏃 [0.4] conformance: use the right bucket for released vs ci

---

examples/controlplane/kustomizeversions.yaml
examples/machinedeployment/kustomizeversions.yaml

Reverts kubernetes-sigs/cluster-api-provider-aws#1397

Revert "🏃 [0.4] conformance: use the right bucket for released vs ci"

---

Makefile

:running: Use variable to determine cluster name in create-cluster

---

pkg/cloud/scope/machine.go

With the bootstrap data moved to a secret, we were attempting to pass in a decoded string where the ec2 api expects the user data to be base64 encoded (client-go graciously decodes the contents of the secret).

:bug: Base64 the User Data retrieved from the bootstrap secret

---

Makefile

make create-cluster: use --decode for base64 decoding
The -D flag for base64 decoding is not available in *nix variants. Use
--decode instead, which is cross-platform compatible.
Fixes #1414 
/kind bug

🐛 make create-cluster: use --decode for base64 decoding

---

cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
docs/prerequisites.md
pkg/cloud/services/cloudformation/bootstrap.go

Convenience feature to allow users to specify extra policies to the control plane and node roles that `clusterawsadm` creates.
Fixes #1390 
Signed-off-by: John Harris <joharris@vmware.com>

:sparkles: Add support for extra AWS policies in clusterawsadm

---

.golangci.yml
main.go

:running: Exclude pprof lint warning in golangci-lint config

---

Makefile
test/e2e/aws_test.go
test/e2e/conformance_test.go
test/e2e/e2e_suite_test.go

Existing E2E tests, doesn't cover verification of dynamically provisioned Load Balancer deletion after cluster removal
This PR covers the 
1. Deploy a Load balancer service on infra cluster
2. Verify Load balancer provisioned
3. Verify Load balancer deleted on deleting the cluster
4. Deploy statefulset on infra cluster
5. Verify volumes are dynamically provisioned
6. Verify dynamically provisioned volumes retained on cluster deletion
Executed the tests locally and all the tests succeeded.

🏃 Verify LoadBalancer dyanamically provisioned on service creation and deleted after cluster deletion

---

Makefile
cmd/release/main.go
docs/releasing.md

test-infra has been updated to use GCB to build release version images,
so we no longer need to do it here in the repo.
Requires https://github.com/kubernetes/test-infra/pull/15624
Fixes #

🏃 Let GCB build release images

---

Makefile
test/e2e/aws_test.go
test/e2e/conformance_test.go

1. Adds Create/Delete multiple workload clusters test scenario
- clusters in different namespaces
- clusters within same namespace
2. Adds e2e tests for delete machine lifecycle
- delete a machine using kindclient
- wait for the MachineDeployment to be reconciled
3. Adds e2e tests for multi AZ deployment
- Deploy ControlPlane and MachineDeployment in new AZ
- Deploy ControlPlane and MachineDeployment in new AZ using subnet-id

:sparkles: Adds more e2e functional tests 

---

pkg/cloud/services/ec2/vpc.go

Fixes a typo.
Fixes #
Question for the team -- Is this the right process for fixing a typo?  I found it when working on an event related issue.  Wasn't sure if it was a good idea to include it in an unrelated PR or use a separate PR.

🐛 Fix typo in SuccessfulTagVPC event name

---

pkg/cloud/services/ec2/eips.go

also make related errors more consistent
Calls to EC2 for Elastic IP's didn't generate events if there were errors. This PR creates those events.
Fixes #1346 
Noticed some inconsistency around the related errors and made some very minor changes so they are consistent. Let me know if that's OK or if I should revert those changes.

🐛 Create events for Elastic IP allocate/disassociate/release

---

pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_test.go

This PR is a follow-up to #1444, removes the code getting and setting the RootVolumeSize, given that we don't ever allow to be mutated.

:warning: Remove check for root volume size

---

controllers/awsmachine_controller.go
pkg/cloud/services/ec2/instances.go

This PR is a forward-port of #1444, where we make sure to check that the root device size returned is not nil before using it.

:bug: Fix NPE when dealing with instance RootDeviceSize

---

examples/generate.sh
test/e2e/e2e_suite_test.go

This PR installs the CABPK and KCP components from Cluster API repository for the e2e tests.

:running: Install cabpk and kcp components in e2e tests

---

pkg/cloud/services/ec2/network.go
pkg/cloud/services/ec2/vpc.go

If a VPC cannot be created for an AWSCluster object (like when a VPC limit is reached), the controller will fail to delete the AWSCluster as certain AWS calls fail without a VPC id.
Fixes #1375

🐛 Fix deleting AWSCluster when VPC doesn't exist

---

pkg/cloud/services/ec2/network.go
pkg/cloud/services/ec2/vpc.go

If a VPC cannot be created for an AWSCluster object (like when a VPC limit is reached), the controller will fail to delete the AWSCluster as certain AWS calls fail without a VPC id.
Backport of #1453 to release-0.4

🐛 [0.4] Fix deleting AWSCluster when VPC doesn't exist

---

clusterctl-settings.json

This PR adds the clusterctl-settings.json so the AWs provider can be tested with clusterctl even if now there are no published releases for v1alpha3
XRef #https://github.com/kubernetes-sigs/cluster-api/pull/2027

✨ add clusterctl-settings.json

---

api/v1alpha3/types.go
pkg/cloud/services/ec2/securitygroups.go
pkg/cloud/services/ec2/securitygroups_test.go
pkg/cloud/services/elb/loadbalancer.go

Currently the ELB provisioned for the Kubernetes API server shares the security group with the control plane nodes. This leverages the existing LB security group that was created but never used. It also exposes the external port as set in `Clusters`'s `spec.clusterNetwork.apiServerPort`
Fixes #1452

⚠️ ELB uses separate security group

---

test/e2e/aws_test.go

added test which deletes a EC2 instance which was referenced in machine object of machine deployment.
After deletion, test verifies that the machine is in Failed state
This test improves the test coverage

🏃 automation to test deletion a EC2 instance which was referenced in machine object

---

pkg/cloud/awserrors/errors.go
pkg/cloud/services/ec2/instances_test.go

-  :bug: Fix when AWS return InvalidInstanceID.NotFound with statusCode 400
- Fixes  https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1411

:bug: Fix when AWS return InvalidInstanceID.NotFound with statusCode 400

---

pkg/cloud/awserrors/errors.go
pkg/cloud/services/ec2/instances_test.go

Backport to release 0.4 per request here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1480#issuecomment-573704288
/assign @ncdc

:bug: Backport: Fix when AWS return InvalidInstanceID.NotFound with statusCode 400

---

pkg/cloud/services/ec2/securitygroups.go
pkg/cloud/services/ec2/securitygroups_test.go

With the ELB  now using a separate security group, it makes sense to further lock down the ingress rules for the control plane security group and remove the 0.0.0.0/0 ingress CIDR rule. Inbound access to allowed on port 6443 for the 3 security groups:
* Control Plane
* Nodes
* API Server Load Balancer
Fixes #1478

⚠️ Update control plane security group rule to remove 0.0.0.0/0 ingress CIDR

---

pkg/cloud/services/ec2/instances.go

When a user specifies the `availabilityZone` or `failureDomain` in a `AWSMachine` and there are no available subnets to launch the EC2 instance, there are no events registered with the `AWSMachine`. This PR adds the event.
Part of #1425

🐛 Generate event when instance fails to launch because no subnets available in an availability zone

---

controllers/awscluster_controller.go
controllers/awsmachine_controller.go
controllers/awsmachine_controller_test.go
pkg/cloud/scope/cluster.go
pkg/cloud/scope/machine.go

If Cluster/AWSCluster resources are created and deleted relatively quickly (seconds up to a minute or so) the AWS resources in the VPC are orphaned as the AWSCluster is deleted without destroying the resources.
Fixes #1454

🐛 Persist AWSCluster/AWSMachine finalizers immediately to prevent orphaned AWS resources

---

test/e2e/e2e_suite_test.go

Makes sure bootstrapper and control plane components are deployed and logs are gathered for e2e tests.

:running: [e2e] Add waiting for deployment and watching logs for bootstrapper and control plane deployments

---

test/e2e/aws_test.go

Added automation to test creating a cluster when VPC limit was already reached.
This will verify cluster is in provisioning state till the VPC resources
were available and will provisioned during reconciliation after freeing
current VPCs
Executed the test locally and passed

🏃 Automate cluster creation when vpc limit was already hit

---

config/default/kustomization.yaml
config/default/manager_auth_proxy_patch.yaml

Enables auth proxy which is deployed as sidecar container in the CAPA manager pod. This is a follow up to https://github.com/kubernetes-sigs/cluster-api/pull/2035 to make sure we are consistent.

✨Adding an auth-proxy sidecar container

---

Makefile

Increases the e2e test timeout to resolve the timeout errors we are seeing in the periodic jobs.

:running: Increase e2e test timeout

---

config/default/kustomization.yaml

This PR adds clusterctl labels to all CAPA components generated when running `make release-manifests`. It removes the labels from selectors within the controller-manager deployment and services.
Ref https://github.com/kubernetes-sigs/cluster-api/issues/1989

✨Add clusterctl labels to CAPA components

---

OWNERS_ALIASES

Sync the cluster-api-maintainers alias with what is currently in
cluster-api.

🏃 Sync cluster-api-maintainers

---

test/e2e/aws_test.go

Added automation to test creating cluster with name more than 22 characters.
Verifies that Cluster provisioned and control plane initialized

🏃Add automation to test cluster creation with name length more than 22 characters

---

api/v1alpha3/tags_test.go
pkg/cloud/tags/tags.go
pkg/cloud/tags/tags_test.go

This PR fixes an issue where tags were being updated even there was no change in them. It happens when there are external tags on resources in addition to cluster managed tags.
Fixes #1499 
@ncdc @detiber @vincepri @randomvariable @rudoi

Fix to avoid updating tags when there is no change in them and add unit tests

---

api/v1alpha3/awsmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml

Make the field name consistent with the json tag name and other documentation.
related to kubernetes-sigs/cluster-api#2185

🏃 Update Machine FailureDomain field

---

hack/ci/e2e-conformance.sh

Change the URL we use for the latest Kubernetes CI artifacts because of
a race condition in the old URL that sporadically resulted in flakey
tests because the container images were sometimes missing when the tests
ran.
Fixes #

:running: Switch Kubernetes CI URL

---

hack/ci/e2e-conformance.sh

Change the URL we use for the latest Kubernetes CI artifacts because of
a race condition in the old URL that sporadically resulted in flakey
tests because the container images were sometimes missing when the tests
ran.
(cherry picked from commit de4ac76d9e3be6e6d289c402c7a23d0cbaf9cc12)
Fixes #

:running: [0.4] Switch Kubernetes CI URL

---

test/e2e/aws_test.go

Added automation to test cluster creation where cluster name
contains symbol '.'
Executed tests locally and tests succeeded.

🏃 Automate creating a cluster with name having period symbol

---

hack/heartbeat_account.py
scripts/ci-e2e-conformance.sh
scripts/ci-e2e.sh

Backports #1518 to the `release-0.4` branch

:running: Remove hardcoded 3h timeout from hack/heartbeat_account.py

---

pkg/cloud/services/elb/loadbalancer.go
pkg/cloud/services/elb/loadbalancer_test.go

Fix a nil pointer exception in getAPIServerClassicELBSpec if
AWSCluster.Spec.ControlPlaneLoadBalancer is not set.
Fixes #1520

:bug: Fix panic in getAPIServerClassicELBSpec

---

pkg/cloud/services/cloudformation/bootstrap.go

Adds the required tag permission for AWS Secrets Manager.
Tested via the `bootstrapper.cluster-api-provider-aws.sigs.k8s.io` user
Fixes #1523

:bug: cloudformation: Add tag permission for secretsmanager

---

controllers/awsmachine_controller.go

Re-add missing return when reconciling failed machines (accidentally removed).
Fixes #

:bug: Re-add missing return when reconciling failed machines

---

hack/ci/ci-bootstrap.yaml

Fixes the problem introduced by https://github.com/kubernetes/kubernetes/pull/87585 (no more .deb generated on CI)
Fixes https://github.com/kubernetes/kubernetes/issues/87961

🐛fix-failing-test

---

pkg/cloud/services/ec2/securitygroups.go

In my case, the GroupId came back nil from the create call, so
attempting to dereference it for the error message caused a panic.
I went ahead and fixed a few other instances of the same pattern in this
function, but I didn't look too far beyond.
Fixes #

:bug: panic in createSecurityGroup error reporting

---

api/v1alpha2/types.go
api/v1alpha3/types.go

Adds omitempty to some types that may be empty. Go will produce `null` otherwise.
Fixes #1554

✨add omitempty to networking types that may be empty

---

controllers/awsmachine_tags.go

Introduction of Secrets Manager brought in new EC2 instance state handling, widening the states in which instance tagging is created. However, EBS root volumes shouldn't be tagged when the instance is Pending.
Fixes #1564

🐛 tagging: skip non-existing root device when tagging

---

.golangci.yml
pkg/cloud/awserrors/errors.go

Enables gosimple linter rule and fixes violations.
Fixes #1539

🏃enable <gosimple> linter rule and fix violations

---

hack/ensure-kind.sh

Do not set xtrace in hack/ensure-kind.sh

:running: Do not set xtrace in hack/ensure-kind.sh

---

config/default/kustomization.yaml

This PR backports the clusterctl labels to v1alpha2 version of CAPA.
Ref https://github.com/kubernetes-sigs/cluster-api/pull/2112
Ref https://github.com/kubernetes-sigs/cluster-api/issues/1989
[Slack conversation for context](https://kubernetes.slack.com/archives/C8TSNPY4T/p1582129372253200)
/assign @fabriziopandini 
/assign @randomvariable

✨ Backport clusterctl labels to CAPA components

---

clusterctl-settings.json

This PR fixes clusterctl-settings.json after changes introduced by https://github.com/kubernetes-sigs/cluster-api/pull/2355
/assing @vincepri 
/assing @randomvariable

🐛 fix clusterctl-settings.json

---

examples/addons.yaml

Bumping Calico to 3.12. By the looks of things, the old manifest accidentally had the CRDs under apiextensions.k8s.io/v1, but they are decidedly not v1 CRDs, and don't install on 1.17.

:bug: Bump Calico version to 3.12 for Kubernetes 1.17 compatibility

---

examples/addons.yaml

Cherry pick of #1601 on release-0.4.
#1601: addons: Bump Calico version to 3.12 for 1.17 compatibility

:bug: Bump Calico version to 3.12 for Kubernetes 1.17 compatibility [backport]

---

pkg/cloud/services/cloudformation/bootstrap.go

Updates the node instance profile with the required policy to allow the use of AWS Session Manager for connecting with the instances created.
Fixes #1553

:warning: Update node instance profile to add support for Session Manager

---

config/manager/manager_auth_proxy_patch.yaml

Fixes an issue where leader election was no longer enabled for the controller manager
Fixes #1594 
/milestone v0.5.0-rc.0

:bug: Ensure that leader election is still enabled after applying auth proxy

---

controllers/awsmachine_controller.go
controllers/awsmachine_controller_test.go
go.mod
pkg/cloud/awserrors/errors.go
pkg/cloud/services/secretsmanager/secret.go
test/e2e/aws_test.go
test/e2e/e2e_suite_test.go

Fixes #1561
Updates state machine of secrets to handle intermittent failures by retrying creation of secrets, and making sure secrets are deleted prior to creation.

🐛 secrets manager: fix error handling when creating secrets (0.4 canonical)

---

controllers/awsmachine_controller.go
controllers/awsmachine_controller_test.go
pkg/cloud/awserrors/errors.go
pkg/cloud/services/secretsmanager/secret.go
test/e2e/aws_test.go

Cherry pick of #1563 on master.
#1563: secrets-manager: Fix error handling

:bug: secrets-manager: Fix error handling

---

api/v1alpha2/zz_generated.conversion.go
go.mod
go.sum
pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go

**What this PR does / why we need it**: Adds support for additional AWS region endpoints (AWS ISO regions) allowing for support in those areas without explicitly overriding the AWS endpoint URLs.
Based on discovery in slack thread https://kubernetes.slack.com/archives/CD6U2V71N/p1583175642128100?thread_ts=1583161863.102600&cid=CD6U2V71N

:sparkles: Bring AWS SDK in-line with Kubernetes master and add new regions

---

Makefile
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
examples/generate.sh

Adding  `preserveUnknownFields=false` to the release-0.4 branch to enable upgrading from v1alpha2 to v1alpha3. 
Also updating `examples/generate.sh` to use later CAPI and CABPK releases.

🏃 [0.4] Add preserveUnknownFields=false

---

Makefile
test/e2e/aws_test.go

Switch to using latest Calico manifests instead of hard-coding 3.12, as
Calico appears to only have a single versioned manifest available at a
time, and that will break us every time Calico releases a new version.
Fixes #1622

:bug: Use latest Calico manifests

---

pkg/cloud/services/ec2/securitygroups.go

This is backport of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1551 affecting also 0.4 release
Fixes #

:bug: panic in createSecurityGroup error reporting - backport to 0.4

---

Makefile

Updates the CAPI components used for conformance testing to released artifacts rather than using kustomize

:running: Update the CAPI components used for conformance testing

---

api/v1alpha2/awscluster_conversion.go
api/v1alpha2/awscluster_conversion_test.go
api/v1alpha2/awsmachine_conversion.go
api/v1alpha2/zz_generated.conversion.go
api/v1alpha3/awscluster_types.go
api/v1alpha3/awsmachine_types.go
api/v1alpha3/zz_generated.deepcopy.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
pkg/cloud/services/ec2/bastion.go
pkg/cloud/services/ec2/instances.go

**What this PR does / why we need it**: Allows instances to be provisioned with no SSH key pair specified. Organizations which have policies denying the use of SSH key pairs can now set the SSH key name value to "" to launch instances without a key pair set. A nil value still sets the default key pair name.
Fixes #1156

:warning: 1156 allow no key pair v1alpha3 2020

---

test/e2e/aws_test.go
test/e2e/go.mod

Fixes the e2e tests now that SSHKeyName is a pointer.

:running: Update e2e tests for SSHKeyName change to pointer

---

hack/ci/e2e-conformance.sh
templates/cluster-template.yaml

Normalizes machine type vars to have the AWS_ prefix for multi-provider compatibility when using ~/.cluster-api/clusterctl.yaml for configuration. In line with https://github.com/kubernetes-sigs/cluster-api/pull/2628
Fixes #1631

Normalize vars to have AWS_ prefix

---

README.md
docs/amis.md

Adds Kubernetes versions v1.17.4, v1.16.8, and v.1.15.11 to the supported versions and updates the latest available AMIs

:book: Update AMIs for latest k8s releases

---

Makefile

See this. https://github.com/kubernetes-sigs/cluster-api-provider-aws#compatibility-with-cluster-api-and-kubernetes-versions
And cluster-api v0.3.0 is released. https://github.com/kubernetes-sigs/cluster-api/releases/tag/v0.3.0
Fixes #

Fix v0.3.0-rc.3 to v0.3.0

---

pkg/cloud/services/ec2/ami.go

Currently image lookups are pretty strict about format, this loosens the image lookup filter while still retaining backward compatiblity for existing images produced.

:sparkles: Loosen the filter used for image lookups

---

controllers/awscluster_controller.go

Waits for DNS to resolve before setting the cluster as `Ready`
Fixes #1641

Ensure ELB is resolvable before marking as ready 🐛

---

main.go

Initialize the controller-runtime logger as soon as we're done parsing
flags, so we don't lose some of the setupLog output that is currently
going to nowhere.
Fixes #

🏃 Initialize CR logger earlier

---

test/e2e/e2e_suite_test.go

- Updates the CAPI version used for conformance and e2e tests

:running: Update cluster-api release used for e2e/conformance tests

---

controllers/awscluster_controller.go
controllers/awsmachine_controller.go
controllers/helpers.go

- Improve logging for predicate handling
- Improve logging for objectMapper functions
- Add triggering reconciliation on Cluster.Status.InfrastructureReady becoming available
Fixes #

:sparkles: Update predicate handling

---

Makefile

Increase the timeout when waiting for nodes from the workload cluster after cluster creation

:running: [ci conformance] increase timeout waiting for nodes

---

Makefile
hack/ci/e2e-conformance.sh

- Replaces tunneling through the bastion with aws Session Manager
- Increases the timeout waiting for `kubectl get nodes` to succeed against the workload cluster after creation to 15m

:running: More fixes for conformance test jobs

---

api/v1alpha3/awscluster_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml

Fixes seeing a bunch of log messages complaining that ready is a required field
```
[capa-controller-manager-79775956fb-sg76v manager] E0402 15:58:22.915432     267 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="AWSCluster.infrastructure.cluster.x-k8s.io \"test\" is invalid: status.ready: Required value"  "controller"="awscluster" "request"={"Namespace":"default","Name":"test"}
```

✨ Default cluster ready to false

---

hack/ci/e2e-conformance.sh

- Fixes ssh-to-node in e2e-conformance.sh to use the instanceID rather than private IP address when attempting to ssh to the node using Session Manager.

:running: [ci-conformance] Fix ssh-to-node to use instanceId rather than private IP address

---

README.md
docs/amis.md

- Adds AMI information for the k8s v1.18.1 release

:book: Add AMI for k8s v1.18.1

---

docs/existing-aws-infrastructure.md

This PR adds instructions for re-using existing AWS infrastructure. This includes information on configuring existing AWS resources as well as instructions for properly configuring CAPI manifests.
This PR adds a document explaining how users can use or consume existing AWS infrastructure with Cluster API, and updates the `docs/README.md` document with a link to the new document.
Fixes #1511

Add instructions for existing AWS infrastructure

---

docs/multi-az-control-plane.md

This PR provides information on configuring CAPA to use multiple availability zones (AZs) so that KubeadmControlPlane will distribute control plane nodes across multiple AZs (for a workload cluster). This PR also provides some caveats of this design.
Signed-off-by: Scott Lowe <lowes@vmware.com>
This PR documents the use of the `networkSpec` object to configure CAPA to create subnets across multiple AZs within a region. Once CAPA creates subnets in multiple AZs, then control plane nodes created by the KubeadmControlPlane object will automatically be distributed across multiple AZs.
Fixes #930

Add documentation for multi-AZ control plane 📖

---

docs/roadmap.md

Updating roadmap to account for delaying any breaking API changes in favor of adding additional features without breaking changes.

:book: Update roadmap for delayed v1alpha4

---

api/v1alpha3/awscluster_webhook.go
api/v1alpha3/awsmachine_webhook.go
api/v1alpha3/awsmachinetemplate_webhook.go
config/webhook/manifests.yaml

Else, kubectl diff refuses to run.
See also: https://github.com/kubernetes-sigs/cluster-api/pull/2868
Fixes #

fix: flag webhooks as side-effect free

---

pkg/cloud/services/ec2/bastion.go

This PR allows `describeBastionInstance` method to return instances also in stopping or stopped state, avoiding to create a new machine when users stop machines outside of Cluster API.
Fixes #1704 
/milestone v0.5.4
/assign @detiber @ashoksekar07

:bug: Include stopped bastion instances when describing

---

api/v1alpha3/types.go
controllers/awsmachine_controller.go
pkg/cloud/scope/machine.go
pkg/cloud/services/cloudformation/bootstrap.go
pkg/cloud/services/elb/errors.go
pkg/cloud/services/elb/loadbalancer.go

This PR makes CAPA remove control plane machine attached to ELB as soon as the machine is deleted or detected in some not running states, so the ELB immediately stops to forward requests without waiting for the health check timeouts
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1705
```release-note
⚠️ Action Required
The IAM policy for the controllers requires new permissions:
elasticloadbalancing:DeregisterInstancesFromLoadBalancer
```

🏃Reconcile ELB attached machines when a Machine is being deleted

---

pkg/cloud/services/elb/loadbalancer.go

This PR fixes an issue with the subnet loop when the ELB is created or reconciled, it allowed to attach more than one subnet to the ELB in the same Availability Zone.

:bug: ELB should now not register subnets in the same AZ more than once

---

api/v1alpha2/awscluster_conversion.go
api/v1alpha2/awsmachine_conversion.go
api/v1alpha2/zz_generated.conversion.go
api/v1alpha3/awscluster_types.go
api/v1alpha3/awsmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
go.sum
pkg/cloud/services/ec2/ami.go
pkg/cloud/services/ec2/ami_test.go
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_test.go

Allow the user to specify a custom format string for AMI lookup based on OS & Kubernetes version inside the AWSMachine and AWSCluster
Fixes #1644

✨ Customizable Image Lookup Format

---

api/v1alpha2/awsmachine_types.go
api/v1alpha2/types.go
api/v1alpha2/zz_generated.conversion.go
api/v1alpha2/zz_generated.deepcopy.go
api/v1alpha3/awsmachine_types.go
api/v1alpha3/types.go
api/v1alpha3/zz_generated.deepcopy.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
pkg/cloud/scope/machine.go
pkg/cloud/services/ec2/instances.go

[KEP-1664](https://github.com/kubernetes/enhancements/pull/1665) is proposing to deprecate and replace Node.Status.Address, so probably best to avoid
using those types. We have a copy of these types in CAPI, so this PR switches them over.
This doesn't really change the CRD API types other than changing the field
descriptions.
Fixes #

:running: Switch to using CAPI's MachineAddress instead of corev1.NodeAddress types

---

api/v1alpha2/zz_generated.conversion.go
api/v1alpha3/types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
controllers/awsmachine_controller.go
pkg/cloud/scope/machine.go
pkg/cloud/scope/machine_test.go
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_test.go

Closes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1693
This PR makes `providerID` of the machine more consistent with the node's `providerID`. See the attached issue for more details

✨Make machine's providerID consistent with node providerID

---

Makefile

Need to wait longer for cluster up time because of #1721 .
Witnessed an observed time of 547s, but also seen a failure on a 600s timeout, so setting at 700s here.
Fixes #

Bump cluster creation timeout for conformance in multi-AZ

---

pkg/cloud/services/ec2/bastion.go

Presently if you are using an unmanaged (bring your own) VPC, we do not create or reconcile a bastion host, but we do reconcile the security group for the bastion.Now  we could create a bastion host if it's enabled in the spec, regardless of managed or unmanaged VPC.
Fixes #1748

create a bastion host if it's enabled in the spec, regardless of managed or unmanaged VPC

---

pkg/cloud/services/elb/loadbalancer.go

When de-registering instances from an ELB, we ignore errors relating to "instance not found" or "loadbalancer not found". This avoids issues when the controller got interrupted **after** deleting the ELB but **before** deregistering the instances.
Also should handle the case where a controller is interrupted between the instance deregistration and the instance delete.
Fixes #1736

:bug: Ignore "not found" errors when deregistering ELB instances

---

controllers/awsmachine_controller.go

Extracting this fixup from #1783, this bug was preventing control plane machines from being deleted.
Fixes #

awsmachine_controller: Allow instances to be deleted if ELB is already gone

---

Makefile

Small fix to the release process so we don't end up publishing binaries that appear to be built from a non-tagged git tree.

:running: Makefile: Build clean binaries on release

---

test/e2e/aws_test.go
test/e2e/go.mod

The e2e tests have been failing for a while: https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-cluster-api-provider-aws#periodic-e2e-v1alpha3&width=20
They all seem to hit the 20 minute timeout while waiting for the cluster to reach `InfrastructureReady`. One of the recent changes that increased the time needed for an AWScluster to reach ready is the subnet defaulting logic #1721 
These changes restrict the number of AZs to provision infrastructure to 1. While testing locally, this made an improvement from 12 minutes down to 5 minutes. 
Note: We still have a test case that specifies subnets in multiple AZs and validates machines are created appropriately but there is now a gap in e2e testing the defaulting logic.

🐛 Restricts AZ limit to 1 in e2e tests

---

pkg/cloud/services/ec2/eips.go
pkg/cloud/services/ec2/natgateways.go
pkg/cloud/services/ec2/natgateways_test.go

Until the code is refactored in #1792 , this PR fixes the NAT gateway issue where creation fails because it assigned an EIP that is already bound to a different NAT gateway. The PR tries to keep the exact same workflow and steps but just batch creates the EIPs before creating the NAT gateways.
Changes/Additions:
Created a `createNatGateways` function that batch creates all the NAT gateways while keeping the createNatGateway function intact as much as possible
Changed `getOrAllocateAddress` to `getOrAllocateAddresses` to batch find/create all the EIPs before the NAT gateways are created
Fixes …

🐛 Fix issue with NAT gateway failing due to EIP already been assigned

---

pkg/cloud/services/ec2/securitygroups.go
test/e2e/aws_test.go

- Fixes security group failures when attempting to create a cluster that has a name starting with 'sg-'
Fixes #1725

🐛  Fixes cluster creation with names starting with 'sg-'

---

api/v1alpha3/awscluster_types.go
api/v1alpha3/awscluster_webhook.go
api/v1alpha3/awscluster_webhook_test.go
test/e2e/aws_test.go

- removed omit empty on the field so it still shows up when set to false
Fixes #1754

🌱 Allows configuring crossZoneLoadBalancing on controlPlaneLoadBalancer

---

go.sum
scripts/ci-e2e.sh
test/e2e_new/e2e_conf.yaml

Updates the ci script to handle new e2e tests. If environment variable `NEW_E2E_FLOW` is set through prow, it will follow the new flow. 
Removes go.mod from e2e-new as it's no longer needed.
New prow job PR: https://github.com/kubernetes/test-infra/pull/17590

🏃 Updates ci script to test using new e2e flow

---

.golangci.yml

With more linters comes longer linting time, I think?
Fixes #1795, maybe?

:seedling: Increase golangci timeout

---

.golangci.yml

Disables `gofumpt` linter. This linter has slightly stricter requirements than `gofmt` which could perhaps be useful, but `gofumpt` itself isn't compatible with `gopls` at this time.

:seedling: ci: disable gofumpt linter

---

cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go

Fixes a reported regression with the old deprecated commands. Default in new commands remains that the bootstrap user is not enabled.
Fixes #

clusterawsadm: Add bootstrap user back to deprecated alpha command

---

.gitignore
Makefile
test/e2e_new/conformance_test.go
test/e2e_new/data/e2e_conf.yaml
test/e2e_new/data/kubetest/kustomization/kustomizeversions.yaml
test/e2e_new/e2e_suite_test.go
test/e2e_new/kubetest/setup.go

Resolves a CI difference where _artifacts is not the same as the ARTIFACTS directory, by moving the logic from GNU Make to go

e2e: Fixups for conformance template generation

---

Makefile
test/e2e_new/aws_test.go
test/e2e_new/data/e2e_conf.yaml
test/e2e_new/data/infrastructure-aws/cluster-template-limit-az.yaml
test/e2e_new/data/infrastructure-aws/cluster-template-multi-az.yaml
test/e2e_new/e2e_suite_test.go

- Migrates remaining tests to use the clusterctl testing framework. 
- Removes parallel option for Ginkgo tests. Tests were competing for resources and hitting the 5 EIP resource limit
- Consolidate some test cases so fewer clusters are created.
In an effort to speed up the total time, some of the tests are combined so a new cluster isn't required per test: 
- Cluster name validations and provisioning extra AWS resources creates one cluster with the following tests:
- name with more than 22 characters
- name with '.'
- name that starts with 'sg-'
- Provisioning LoadBalancer dynamically and deleting on cluster deletion
- Provisioning volumes dynamically and retain on cluster deletion
- multiple workload clusters in different namespaces with machine …

🏃 Migrate rest of e2e tests to use clusterctl framework

---

pkg/cloud/scope/cluster.go
pkg/cloud/scope/machine.go

While creating a cluster, a conflict was briefly detected while updating the Ready condition on AWSCluster and AWSMachine. This PR adds the Ready condition to the list of conditions owned by the respective controllers. 
Slack discussion that led to this solution: https://kubernetes.slack.com/archives/C8TSNPY4T/p1595428905245100
cc: @ncdc @vincepri

🐛 Adds Ready condition to list of owned conditions for AWSMachine and AWSCluster

---

docs/prerequisites.md

Without this section header, the reader can assume that the SSH Key Pair header is under the **Without clusterawsadm** section and incorrectly setup the prerequisites. This explicit header makes sure that the two headings stand visually apart from each other.
N/A

📖 Update prerequisites.md to add IAM section header

---

pkg/cloud/filter/ec2.go
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_test.go

Currently the only way to specify a subnet to be used by a machine is by using the subnetID. It's restrictive as the user may not always have the subnet provisioned beforehand or have access to the subnetID. These changes allow the user to specify AWS filters to be used to select a subnet for a given machine template. 
It looks for subnet to use in the following order: 
- subnetID specified in template
- subnet filters specified in template (will add availability-zone filter if failureDomain is also specified)
- filter available private subnets by failureDomain if specified
- select first available private subnet
**If multiple subnets are returned by the filter parameters, the first one is used.** 
**Which issue(s) this PR fixes** *(optional, in …

✨  Use filters to select subnet for machines

---

test/e2e_new/kubetest/setup.go

(Follow-up to https://github.com/kubernetes/test-infra/pull/18290.)
[Now](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-build/1288265272272097280) that the `ci/latest` version marker again represents a cross build of `kubernetes/kubernetes@master`, we should stop using the `ci/k8s-master` generic version marker.
ref: https://github.com/kubernetes/test-infra/blob/master/docs/kubernetes-versions.md, https://github.com/kubernetes/sig-release/issues/850
Signed-off-by: Stephen Augustus <saugustus@vmware.com>
Fixes #

test/e2e_new: Use ci/latest version marker for retrieving cross builds

---

pkg/cloud/scope/machine.go

This PR fixes incorrect comments of `GetInstanceState` and `SetInstanceState` of MachineScope.
Fixes #

Fix MachineScope GetInstanceState/SetInstanceState comments

---

pkg/cloud/services/secretsmanager/secret_fetch_script.go

As per @oddbloke's suggestion, adding a #cloud-boothook line to the boothook script allows cloud-init v20.2 to correctly interpret the boothook.
Fixes #1839

:bug: Workaround for https://bugs.launchpad.net/cloud-init/+bug/1888822

---

api/v1alpha2/awscluster_conversion.go
api/v1alpha3/awscluster_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
pkg/cloud/services/ec2/bastion.go

T2 instance type is starting to be removed from Amazon DCs, so update
the default to the most universally available burstable micro instance,
with an exception for us-east-1.
Fixes #1830

✨ bastion: Make instance type selectable, with new defaults

---

.golangci.yml
api/v1alpha3/awsmachinetemplate_webhook.go
cmd/clusterawsadm/cloudformation/bootstrap/iam.go
cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
cmd/clusterawsadm/cmd/bootstrap/credentials/credentials.go
cmd/clusterawsadm/cmd/bootstrap/iam/iam_doc.go
cmd/clusterawsadm/configreader/configreader.go
cmd/clusterawsadm/credentials/credentials.go
controllers/awsmachine_controller.go
pkg/cloud/awserrors/errors.go
pkg/cloud/services/ec2/bastion.go
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_test.go
pkg/cloud/services/elb/errors.go
pkg/cloud/services/elb/loadbalancer.go
pkg/cloud/services/network/gateways.go
pkg/cloud/services/network/subnets_test.go
pkg/cloud/services/network/vpc.go
pkg/cloud/services/secretsmanager/helpers_test.go
pkg/cloud/services/wait/wait_test.go

- Use static errors or wrap them
- Remove redundant error wrapping from the awserrors package
Fixes #1800

🌱 Fix error handling for goerr113 linter

---

pkg/cloud/filter/ec2.go
pkg/cloud/services/network/account.go

Local zones don't currently work with CAPA. If a user has opted into the Local Zone feature, this change will skip that zone during reconciliation. Regions that need to be opted into like eu-south-1 will not be affected by these changes. 
Fixes #1799

🌱 Ignores local zones when fetching AZs

---

controllers/awscluster_controller.go
pkg/cloud/services/interfaces.go
pkg/cloud/services/network/gateways.go
pkg/cloud/services/network/natgateways.go
pkg/cloud/services/network/network.go
pkg/cloud/services/network/routetables.go
pkg/cloud/services/network/subnets.go
pkg/cloud/services/network/vpc.go
pkg/cloud/services/securitygroup/securitygroups.go
pkg/cloud/services/securitygroup/securitygroups_test.go
pkg/cloud/services/securitygroup/service.go

The reconciliation of security groups has been split out from the network service. This is to enable the EKS implementation to reconcile the network without the security groups.
Fixes #1857

✨ refactor: split security groups from network service

---

controllers/awsmachine_controller.go
controllers/awsmachine_controller_test.go
pkg/cloud/scope/cluster.go
pkg/cloud/scope/ec2.go
pkg/cloud/scope/elb.go
pkg/cloud/scope/machine.go
pkg/cloud/scope/machine_test.go
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_test.go
pkg/cloud/services/ec2/service.go
pkg/cloud/services/elb/service.go

**What this PR does / why we need it**: Refactors AWSMachine reconciliation to utilize the new scope interfaces. This will make onboarding the AWSManagedControlPlane stuff more simple.
Fixes #1852

🌱 refactor AWSMachine to use scope interfaces

---

Makefile
metadata.yaml

THis PR adds a metadata.yaml for clusterctl to enforce contracts.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1874

🌱Add metadata.yaml for defining contracts

---

api/v1alpha3/awsmachine_webhook.go
api/v1alpha3/awsmachine_webhook_test.go
go.mod
go.sum
pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
test/e2e/go.mod
test/e2e/go.sum

Signed-off-by: Fahri Yardımcı
#1886
This PR adds validation and tests for supporting io2 volume type in webhooks
Fixes #1886

✨  Add validation and tests for io2 volume type.

---

api/v1alpha2/awscluster_conversion.go
api/v1alpha3/awscluster_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
pkg/cloud/services/ec2/bastion.go

Allows us to specify a custom bastion AMI image. Useful for private partitions in AWS.
Fixes #1441

✨ Custom Bastion AMI

---

api/v1alpha3/awscluster_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml

This PR fixes Bastion struct AMI field comment.

 🌱Fix for Bastion struct field comment

---

config/manager/manager.yaml
config/manager/manager_auth_proxy_patch.yaml
config/webhook/manager_webhook_patch.yaml

The manager config has been updated so that you van enabled the EKS features flags by using envsubst. This is to provide the user with an easy way to enable the functionality.
**NOTE: the version of envsubst must be: https://github.com/a8m/envsubst as this allows defaults**
Fixes #

✨ feat: added ability to enable EKS via env vars

---

README.md
docs/README.md
docs/eks.md

Added initial basic docs for the EKS support in the provider. This will need to be expanded over time.
Fixes #1851

✨ docs: add eks documentation

---

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
go.mod
pkg/cloud/scope/clients.go
pkg/cloud/services/ec2/ami.go
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/service.go

This adds a lookup for the official EKS AMI.
Fixes #1778 
This is WIP until #1724 goes in. Will be using those types to determine if using the EKS AMI is appropriate. I'll also need some additional changes when #1810 goes in. 
Also still working on finding the right IAM updates. I'm having an obnoxiously difficult time getting a policy statement that is properly scoped. Wildcards are not appropriate at all for SSM Parameter Store.

✨ Look up official EKS AMI when appropriate

---

README.md
docs/amis.md

EOW 28/08/2020
Fixes #1892 
Fixes #1847

Update AMIs for latest Kubernetes patch releases

---

bootstrap/eks/config/rbac/role.yaml
bootstrap/eks/controllers/eksconfig_controller.go
bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
bootstrap/eks/main.go
controllers/awsmachine_controller.go
pkg/cloud/scope/machine.go
pkg/cloud/services/ec2/ami.go
pkg/cloud/services/ec2/instances.go

**What this PR does / why we need it**: Wires up AWSMachine controller to join AWSManagedControlPlanes. Also checks for EKSClusterName in the EKS bootstrap provider.
With this PR, I was able to fully join a MachineDeployment to the cluster.
Fixes #1897

chore: wire up EKS bootstrapper and AWSMachine controller for AWSManagedControlPlane

---

cloudbuild.yaml

builds have been failing of late. measured in a local cloudbuild run, and it takes about 28 minutes, so bump the timeout to 35 minutes.
Whilst I was here, I also bumped the docker build image.
Fixes #

:seedling: cloudbuild: Increase timeout, use newer Docker image

---

templates/cluster-template-managed.yaml

Added machine and EKS config to the managed template so that worker nodes are created when using the template
Fixes #1912

feat: added machines to managed template

---

docs/prerequisites.md

This PR adds information to the prerequisites documentation on changes in `clusterawsadm` in the 0.5.5 release around the creation of the bootstrap user and group.
Fixes #1898

Update prerequisites doc regarding bootstrap user 📖

---

cmd/clusterawsadm/cloudformation/bootstrap/iam.go

This PR fixes a minor mix up happens during printing IAM policies with clusterawsadm.
Fixes #1921

🐛Fix clusterawsadm policy mix up

---

go.mod
go.sum
pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
pkg/cloud/services/network/routetables.go
pkg/cloud/services/network/routetables_test.go

- Utilize the ability to create route tables with tags instead of tagging after creation. 
Fixes #1887 
Fixes #1895

🌱  Bumps aws-sdk. Creates tags during route table creation

---

api/v1alpha2/awsmachine_conversion.go
api/v1alpha2/zz_generated.conversion.go
api/v1alpha3/awsmachine_types.go
api/v1alpha3/awsmachinetemplate_webhook.go
api/v1alpha3/types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_test.go

This PR adds the ability to specify instance tenancy and makes possible running dedicated instances.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/dedicated-instance.html

✨Add ability to specify instance tenancy

---

pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_test.go

:seedling: instances: Sort tag keys so unit tests can succeed

---

pkg/cloud/services/network/subnets.go

To address a potential issue raised [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1721#discussion_r441821606)
Needed a way to short the rest of the reconciliation after default subnets is determined. I'm not super fond of this implementation where the `requeue` is bubbled up from the ec2 services so open to suggestions. Some other alternatives considered: 
- Patch the AWSCluster like how do for conditions. Calling patch on the spec outside of the controller felt wrong. Conditions was only modifying the status field. 
- Just return after determining the default subnets and continue. This may cause issues further down the line where subnets are expected to have been created. 
**Which issue(s) this PR fixes** *(optional, in …

✨ Persists changes early when using default subnets

---

bootstrap/eks/config/manager/kustomization.yaml
bootstrap/eks/config/manager/manager_manager_args_patch.yaml
bootstrap/eks/config/rbac/role.yaml
bootstrap/eks/controllers/eksconfig_controller.go
bootstrap/eks/main.go

* eks-bootstrap doesn't know about the CRD `machinepools.exp.cluster.x-k8s.io` and `User "system:serviceaccount:capa-eks-bootstrap-system:default" cannot list resource "machinepools" in API group "exp.cluster.x-k8s.io"`
* I want to be able to use `"EXP_MACHINE_POOL": "true"` like in the capi-controller-manager and capa-controller-manager
This needs to be merged so that awsmachinepools can connect to an eks controlplane
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1860

:bug: Add capi exp schema and fix manager args and rbac

---

Makefile

`make generate` was broken. `/bootstrap/eks/types` doesn't exist, so deleting that path.

:seedling: Makefile: Fix code generation for mocks and EKS bootstrap provider

---

pkg/cloud/services/network/subnets.go
pkg/cloud/services/network/subnets_test.go

**What this PR does / why we need it**: As a user, I may want to provide CAPA with a VPC that has no associated public subnets or internet gateways. It is unclear whether CAPA would support this today, even with an internal load balancing scheme for the apiserver.
Fixes #1696

✨ Unmanaged VPCs don't require public subnets

---

docs/changing-credentials.md

This PR adds documentation on how to update the AWS credentials used by CAPA after deployment of a management cluster.
Fixes #1946

📖 Add docs on updating AWS credentials used by CAPA

---

OWNERS_ALIASES
exp/OWNERS

I would like to propose @richardcase as a reviewer for Cluster API Provider AWS, and a maintainer of the exp directory containing the EKS control plane implementation.
/hold 
for consensus

PROPOSAL: @richardcase as reviewer

---

controllers/awscluster_controller.go
controllers/awsmachine_controller.go
pkg/cloud/scope/cluster.go
pkg/cloud/scope/machine.go
pkg/cloud/services/ec2/bastion.go
pkg/cloud/services/ec2/bastion_test.go
pkg/cloud/services/ec2/instances_test.go
pkg/cloud/services/elb/loadbalancer.go
pkg/cloud/services/elb/loadbalancer_test.go
pkg/cloud/services/network/network.go
pkg/cloud/services/securitygroup/securitygroups.go

Adding conditions for the reconcile delete workflow
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1867

🌱 Add conditions for the reconcile delete workflow

---

api/v1alpha3/awscluster_webhook.go
api/v1alpha3/awscluster_webhook_test.go
api/v1alpha3/defaults.go
api/v1alpha3/types.go
api/v1alpha3/validate.go
controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_webhook.go
controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_webhook_test.go
controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
docs/accessing-instances.md
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/securitygroup/securitygroups.go

The bastion was being reconciled before the security groups and this based the bastion reconciliation to fail. The reconciliation order has been updated.
Fixes #1956
Fixes #1958

🐛 fix: bastion reconcilation and connection error when using `eks` flavor

---

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
test/e2e/aws_test.go
test/e2e/data/e2e_conf.yaml
test/e2e/data/infrastructure-aws/cluster-template-spot-instances.yaml
test/e2e/e2e_suite_test.go

- adds a new test (and flavour) to exercise spot instances
- uses framework function to fetch machines from machine deployment
Fixes #1893

🌱 Adds e2e test for spot instances

---

controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_types.go
controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml

**What this PR does / why we need it**: When using the AWSManagedControlPlane, if you delete a Machine resource it does not gracefully cordon and drain the associated Node. The fix for this in CAPI is to have the managed control plane provider set the `externalManagedControlPlane: true` value in its status to signal to cluster-api that the control plane Nodes are not visible in the cluster.
Related to: https://github.com/kubernetes-sigs/cluster-api/issues/3631

🐛 Add externalManagedControlPlane Status to fix node drain under EKS

---

controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_types.go
controlplane/eks/api/v1alpha3/zz_generated.deepcopy.go
controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml

**What this PR does / why we need it**: The recently added `externalManagedControlPlane` in #1992 should have been optional, not required to be eligible for release in a minor version.

🐛 externalManagedControlPlane status field should have been optional

---

controllers/awscluster_controller.go
controllers/awsmachine_controller.go
controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
controlplane/eks/main.go
main.go
pkg/cloud/endpoints/endpoints.go
pkg/cloud/endpoints/endpoints_test.go
pkg/cloud/scope/cluster.go
pkg/cloud/scope/managedcontrolplane.go
pkg/cloud/scope/session.go
pkg/cloud/services/secretsmanager/cloudinit.go
pkg/cloud/services/secretsmanager/cloudinit_test.go
pkg/cloud/services/secretsmanager/secret_fetch_script.go

**What this PR does / why we need it**: Allows custom endpoints for aws services to be specified for the aws provider. Not only would this allow for local stack testing but would pave the road for Cluster API into AWS IC partitions which require FIPS named endpoints.
Fixes #1855

🌱 Support using custom endpoints for AWS services

---

cmd/clusterawsadm/api/bootstrap/v1alpha1/types.go

Noticed a very minor capitaliztion issue related to the bootstrap template for EKS.
Relates #1997

🌱 fix: incorrect capitalization for eks field

---

.dockerignore

.dockerignore: Add cmd package

---

exp/api/v1alpha3/types.go
pkg/cloud/services/autoscaling/autoscalinggroup.go
pkg/cloud/services/autoscaling/autoscalinggroup_test.go

**What this PR does / why we need it**: While testing the AWSMachinePools implementation, I noticed that if the optional field mixedInstancesPolicy is not set, the controller panics due to a nil pointer reference at line 58.

🐛 Fix AWSMachinePool panic when MixedInstancesPolicy is not set

---

pkg/cloud/services/eks/nodegroup.go

Nil pointer panic when creating the ScalingConfig for the CreateNodegroup call.

🐛 Fix AWSManagedMachinePool NPE with scalingConfig

---

docs/book/src/topics/eks.md

https://cluster-api-aws.sigs.k8s.io/topics/eks.html has a broken link to the prerequisites page.
It should actually point to https://cluster-api-aws.sigs.k8s.io/topics/using-clusterawsadm-to-fulfill-prerequisites.html .

📖 docs: fix a broken link to prerequisites

---

README.md

Adds a link to the rendered documentation site and moves the documentation section to the top of the repo readme rather than buried in the middle.

📖 Fix link to docs site and move to top of repo README

---

api/v1alpha3/types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml

Now that we have support for non-root volume, we should remove the 'root' keyword in description for Volume.
Fixes #

🌱 Fix volume description to remove 'root' since it's also used for non-root volume

---

exp/controllers/awsmachinepool_controller.go
exp/controllers/awsmachinepool_tags.go
pkg/cloud/scope/machinepool.go
pkg/cloud/services/autoscaling/autoscalinggroup.go
pkg/cloud/services/ec2/launchtemplate.go
pkg/cloud/services/interfaces.go
pkg/cloud/services/mock_services/autoscaling_interface_mock.go

**What this PR does / why we need it**: 
Currently, autoscaling groups, launch templates, and EC2 instances do not get the usual tags applied. This PR adds tagging with logic similar to that in the AWSMachine controller. We are running this code in our environment now, but it does still need tests written (We may get some time next week to work on that). I heard something about a tagging rework going on, so maybe this could benefit from that work. A better approach to this is definitely possible since it seemed when I started there was little code reuse around the tagging logic in the various controllers.

✨ Add tagging for AWSMachinePool resources

---

config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
exp/api/v1alpha3/awsmanagedmachinepool_types.go
pkg/cloud/services/eks/nodegroup.go

Addresses part of #1990, making it less cumbersome to set up remote access for AWSManagedMachinePool

🌱 Improve AWSManagedMachinePool remote access support

---

pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_test.go

Validates subnet's availability zone with failure domain when subnet id is passed
Fixes #1838

🌱 Validate subnet's az with failure domain when subnet id is passed

---

controllers/awscluster_controller.go
controllers/awsmachine_controller.go

[why we need it]
 awscluster/awsmachine controller's code has "SetupWithManager-WithEventFilter-predicate.Funcs-UpdateFunc" to prevent incremental status updates. that code is written by
oldMachine := e.ObjectOld.(*infrav1.AWSMachine).DeepCopy()
   newMachine := e.ObjectNew.(*infrav1.AWSMachine).DeepCopy()
oldMachine.Status = infrav1.AWSMachineStatus{}
   newMachine.Status = infrav1.AWSMachineStatus{}
But if status updates, so does resourceVersion in metadata. Therefore, even if the status is updated, the reconciler is called.
[What this PR does] 
even if the status is updated, the reconciler isn't called.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR …

🐛fix: add more condition for resource's status filtering

---

docs/amis.md
test/e2e/conformance_test.go
test/e2e/data/e2e_conf.yaml
test/e2e/e2e_suite_test.go

Due to https://github.com/kubernetes-sigs/image-builder/pull/406,
have had to rebuild Ubuntu AMIs.
Am also bumping e2e versions and fixing the conformance with ci artifacts job so we have signal.
Fixes https://github.com/kubernetes/kubernetes/issues/95730

:seedling: docs: Provide AMI IDs for rebuilt Ubuntu amis and fix e2e conformance with CI Artifacts jobs

---

pkg/cloud/services/ec2/ami.go

Updated the OS version of the bastion node. The current AMI's are Ubuntu 16.04 which is two years old and it has security vulnerabilities.
Fixes #

🌱 Updated Bastion node's AMI. Changed the OS version to Ubuntu 20.04 from Ubuntu 16.04

---

docs/book/src/topics/machinepools.md
docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md

A small update to the EKS docs to show home to enable the role creation for the managed machine pools
Fixes #

 📖 docs: eks docs update for managed machine pools

---

config/manager/manager.yaml
config/webhook/manager_webhook_patch.yaml
main.go

The `EXP_MACHINE_POOL` environment variable isn't being propagated to the the webhook manager and therefore the webhooks for AWSMachinePool aren't registsred
Fixes #2045

🐛fix: ensure env var enables AWSMachinePool webhooks

---

api/v1alpha2/awscluster_conversion.go
api/v1alpha2/awsmachine_conversion.go
api/v1alpha2/awsmachinetemplate_conversion.go
test/e2e/data/e2e_conf.yaml

This PR prevents overriding ControlPlaneLoadBalancer and Bastion changes.
It also avoids creating `CloudInit` during the conversion if it is empty, because if we create an empty `CloudInit` during conversion,
`out.EnableSecureSecretsManager = !in.InsecureSkipSecretsManager` sets a field that should not be there.
``
Fixes #2059

Fix roundtrip conversions between v1alpha2 and v1alpha3

---

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
cmd/clusterawsadm/cloudformation/bootstrap/managed_control_plane.go
cmd/clusterawsadm/cloudformation/bootstrap/template.go
pkg/cloud/services/eks/nodegroup.go

When creating the bootstrap stack the permissions required for managed machine pools (a.k.a EKS managed machine node groups) aren't added.
Fixes #2042

🐛 fix: add required iam permission for managed node groups

---

api/v1alpha3/awsmachine_webhook_test.go
api/v1alpha3/webhooks.go

Make the regex less restrictive to allows underscore etc. for ssh key file name
Fixes #2060

🐛Make the regex less restrictive to allow underscore etc. for ssh key file name

---

pkg/cloud/services/autoscaling/autoscalinggroup.go

Fallback to subnets associated with cluster if none are provided.
Related #2047
See also #2048 and #2050 as alternatives

🐛 Add fallback if subnets not provided on AWSMachinePool

---

api/v1alpha3/awsmachine_webhook.go
api/v1alpha3/awsmachine_webhook_test.go

This patch checks for the presence of the `spec.cloudInit.insecureSkipSecretsManager` before setting the default value for the `spec.cloudInit.secureSecretsBackend`.
Fixes #2064

🐛  Updates AWSMachine CloudInit defaulting logic

---

controllers/awscluster_controller.go

This PR adds defaulting to the AWSCluster controller to prevent deletion of CNI related security groups from the AWSClusters that are created before v0.5.5.
Starting from v0.5.5, CNI-related security groups are added to spec by defaulting and ReconcileSecurityGroups() uses networkSpec.cni to add CNI-related security groups. Controllers < v0.5.5, they were added by the ReconcileSecurityGroups(). CNI related security groups from AWSClusters (created before v0.5.5) that is not defaulted, were being deleted.
Fixes #2084

🐛 Add CNI defaulting to the controller

---

pkg/cloud/services/autoscaling/autoscalinggroup.go

Adds fallback logic to the update ASG function which was added to the create function in #2051

🐛 Fallback to cluster subnets on update ASG

---

Makefile

Fixes #
Won't necessarily prevent e2e failures if the manifest are broken, but gives some protection against bad kustomizations.

Makefile: Ensure manifests compile during verify

---

exp/controllers/awsmanagedmachinepool_controller.go
pkg/cloud/scope/managednodegroup.go
pkg/cloud/services/eks/nodegroup.go
pkg/cloud/services/eks/roles.go
pkg/cloud/services/eks/tags.go

Fixes incorrectly using the nodegroup name for tagging resources instead of cluster name.
Fixes potential nodegroup IAM role name collisions.

🐛 AWSManagedMachinePool: Fix cloud provider key usage and nodegroup IAM role name

---

api/v1alpha3/awsmachine_webhook.go
api/v1alpha3/awsmachine_webhook_test.go

Adds validation in webhook to validate that filter can not be there in additional security groups
Fixes #1723
Note to reviewer: Will have a separate PR(#2032) to refactor the error handling

🐛Validate that additional security groups can not have filters

---

docs/amis.md

This PR builds and updates the doc with latest versions: v1.17.14, v1.18.12, v1.19.4
Also built v1.17.3, v1.18.10, and v1.19.3.
`v1.18.11` gives error:  
```
centos-7: fatal: [default]: FAILED! => {"changed": false, "msg": "No package matching 'kubelet-1.18.11-0' found available, installed or updated", "rc": 126, "results": ["No package matching 'kubelet-1.18.11-0' found available, installed or updated"]}
```
Checked kubelet repo, only 1.18.11 rc is released.
Fixes #2039

🌱Build new AMIs

---

pkg/cloud/services/autoscaling/autoscalinggroup.go

Signed-off-by: Felipe Oliveira <fpo@felipeweb.dev>
fix `scope.Name` call to `scope.Name()`

✨ fix ASG event message

---

api/v1alpha3/awsmachinetemplate_webhook.go
api/v1alpha3/awsmachinetemplate_webhook_test.go

:bug: awsmachinetemplates: Allow cloudInit.secureSecretsBackend to be defaulted

---

test/e2e/data/e2e_conf.yaml

/hold
until https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2102 is merged.

🌱Upgrade e2e Kubernetes version to 1.19.4

---

go.mod
go.sum
test/e2e/data/e2e_conf.yaml

This PR bumps Cluster API dependency to v0.3.11.

🌱Bump CAPI version to v0.3.11

---

docs/adr/0003-separate-e2e-packages.md

Capture the decision about splitting the e2e tests into separate packages
Relates #1907

📖 docs: e2e test structure ADR

---

test/e2e/shared/cluster.go
test/e2e/shared/common.go

The e2e tests are failing due to the CAPI v0.3.11 upgrade: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2129
CAPI e2e framework no longer sets an environment variable for CNI resources: https://github.com/kubernetes-sigs/cluster-api/pull/3846
We need to use the new way of setting CNI data to the templates in e2e tests as well.
Fixes #
cc @randomvariable

 🐛Fix for CAPI 3.11 upgrade

---

docs/book/src/topics/consuming-existing-aws-infrastructure.md

Provide context as to where the `networkSpec` is to be updated inside the `kind: AWSManagedControlPlane`

:book: Update consuming-existing-aws-infrastructure.md to provide context to where networkSpec belongs

---

api/v1alpha2/awsmachine_conversion.go
api/v1alpha2/zz_generated.conversion.go
api/v1alpha3/awsmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
controllers/awsmachine_controller.go
pkg/cloud/scope/machine.go

set Interruptible as true when SpotMarketOptions for AWSMachine is non-nil
fixes issue 1899
**Which issue(s) this PR fixes** *
Fixes #1899

🌱 add Interruptible field to AWSMachine status

---

docs/adr/0002-eks-packaging.md

To capture the decition around the EKS packaging from the 2nd November 2020 office hours call around how we package the EKS functionality in the short term.
Relates to #2078

📖 docs: EKS packaging ADR

---

controllers/awsmachine_controller.go
pkg/cloud/scope/externalinfracluster.go
pkg/cloud/scope/machine.go
pkg/cloud/services/ec2/instances.go

This decouples the machine controller from the Infrastructure resource.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2125

Add externalInfraCluster

---

exp/api/v1alpha3/awsmachinepool_types.go

Marks `subnets` as an optional property on `AWSMachinePool`.
Fixes #
/assign @sedefsavas

🐛 Set Subnets as an optional property

---

cmd/clusterawsadm/api/bootstrap/v1alpha1/types.go
cmd/clusterawsadm/cmd/bootstrap/iam/iam_doc.go

Allow CLI to take a configuration file to print IAM policy documents.
Additionally, show that EKS is disabled by default in the configuration.
Fixes #

:sparkles: clusterawsadm: Allow CLI to take a configuration file to print IAM policy documents

---

cmd/clusterawsadm/credentials/credentials.go

When using clusterawsadm to encode credentials, allow the use of the shared configuration file to resolve them.
Fixes #

clusterawsadm: Enable use of shared configuration file

---

CONTRIBUTING.md

Fixed the display of the emoji codewords so they dont render as emojis and updated wording to indicate they should be used at the start of PR titles.

📖 fix emoji display on contributing guide

---

pkg/cloud/services/elb/loadbalancer.go
pkg/cloud/services/elb/loadbalancer_test.go

In clusters that uses existing VPCs, if there is an existing LB with matching name but with different scheme, LB returns error saying the load balancer scheme is different.
Fixes #2008

🐛 Error if a loadbalancer exist with the same name in the same region with a different scheme

---

pkg/cloud/services/elb/loadbalancer.go

For addressing the following
```
E1210 19:57:59.133730       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 350 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1f3db60, 0x39e1490)
/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1f3db60, 0x39e1490)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/elb.(*Service).describeClassicELB(0xc00120cfc0, …
```

loadbalancer: Fix NPE when comparing load balancers

---

docs/amis.md

Created AMIs and updated the doc for Kubernetes versions 1.19.5, 1.18.13, 1.17.15.
Fixes #2160

🌱 New AMIs for: Kubernetes version 1.19.5, 1.18.13, 1.17.15

---

controlplane/eks/config/manager/manager_args_patch.yaml
controlplane/eks/config/rbac/role.yaml
controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
controlplane/eks/main.go
pkg/cloud/services/eks/config.go
pkg/cloud/services/iamauth/reconcile.go

When investigating #2179  a number of issues have been discovered and this PR fixes them. When the control plane is deleted a check is made to see if there are any existing dependencies...if there are then the request is requeued until the dependencies no longer exist. 
This is required to enable the upgrade tests but it doesn't fix #2179 (but additional logging will help).
Fixes #2176

🌱 feat: control plane deletion checks

---

docs/amis.md

Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2174

New AMIs for Kubernetes versions 1.17.16, 1.18.14, 1.19.6, 1.20.1

---

cmd/clusterawsadm/cmd/ami/ami.go
cmd/clusterawsadm/cmd/ami/copy/copy.go
cmd/clusterawsadm/cmd/root.go
pkg/cloud/services/ec2/ami.go
pkg/cloud/services/ec2/ami_test.go
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/launchtemplate.go

This PR adds `clusterawsadm ami copy` command which can be used to copy a pre-existing AMI to user's AWS account.
Some examples:
```
clusterawsadm ami copy --kubernetes-version=v1.18.12 --os=ubuntu-20.04  --region=us-west-2
clusterawsadm ami copy --os centos-7 --kubernetes-version=1.19.4 --source-account=111111111111 --dry-run
```
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2041

✨Add copy AMI command to clusterawsadm

---

config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
exp/api/v1alpha3/types.go
exp/controllers/awsmachinepool_controller.go
pkg/cloud/services/ec2/launchtemplate.go
pkg/cloud/services/ec2/launchtemplate_test.go

This field isn't actually respected if set on an `AWSMachinePool`, and in particular a user cannot reference an existing launch template in an `AWSMachinePool`, as far as I can tell. The `ID` field and the `AWSLaunchTemplate` struct are sort of abused internally to hold the results of fetching a launch template based on `status.launchTemplateID` but we don't need to hold the ID.
Ideally this use case would work, but until it does, I think it best to remove this field.

🐛 AWSMachinePool: Remove unused ID field on launch template spec

---

api/v1alpha3/awscluster_webhook_test.go
api/v1alpha3/awsmachine_types.go
api/v1alpha3/awsmachine_webhook_test.go
api/v1alpha3/awsmachinetemplate_webhook_test.go
api/v1alpha3/suite_test.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
controllers/awscluster_controller_test.go
controllers/awsmachine_controller_unit_test.go
controllers/suite_test.go
controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_webhook_test.go
controlplane/eks/api/v1alpha3/suite_test.go
exp/controllers/awsmachinepool_controller_test.go
go.mod
test/helpers/envtest.go
test/helpers/external/cluster.go

Also includes fake CRDs for Cluster API clusters and machines
Creates a multi-package envtest helper, and converts controllers and webhook tests over from fake client to envtest*
Mirrors that of Cluster API where multiple controllers are in the same repo, so webhooks may need to modified so that they can run together.
`* The one exception is awsmachine_controller_test.go, which needs a major refactor to be able to use envtest, as it relies on sequential ordering of test statements. (https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2142)
Fixes #1999 
Fixes #2064

:bug: Fix OpenAPI defaulting for secrets backend and add OpenAPI testing

---

Makefile
controlplane/eks/config/manager/manager_args_patch.yaml
test/e2e/data/e2e_eks_conf.yaml
test/e2e/shared/aws.go
test/e2e/shared/suite.go
test/e2e/suites/managed/cluster.go
test/e2e/suites/managed/eks_test.go
test/e2e/suites/managed/upgrade_test.go

The EKS e2e tests have stopped working on connection to the remote cluster (with a connection timeout).
This is PR to enable investigation and testing of the failure.
Fixes #2179

🐛 test: investigate and fix eks e2e tests

---

cmd/clusterawsadm/cmd/ami/ami.go
cmd/clusterawsadm/cmd/ami/copy/copy.go
cmd/clusterawsadm/cmd/ami/copy/encryptedcopy.go

This PR is a follow up to `clusterawsadm ami copy` PR: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2112
`clusterawsadm ami encrypted-copy`, by taking K8s version, OS, region as parameters:
1- Copy and encrypt the requested AMIs snapshot to the user AWS account
2- Create and encrypt AMI using the copied snapshot
Encrypt using a non-default KmsKeyId specified using Key alias:
`clusterawsadm ami encrypted-copy --os centos-7 --kubernetes-version=v1.19.4 --kms-key-id=alias/ExampleAlias`
Fixes #https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2041

🌱 Add encrypted AMI copy

---

docs/amis.md

Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2205

🌱 New AMIs for Kubernetes versions 1.20.2, 1.19.6, 1.18.15, 1.17.17

---

go.sum
pkg/cloud/interfaces.go
pkg/cloud/scope/clients.go
pkg/cloud/scope/cluster.go
pkg/cloud/scope/externalinfracluster.go
pkg/cloud/scope/managedcontrolplane.go
pkg/cloud/scope/managednodegroup.go
pkg/cloud/scope/session.go
pkg/cloud/throttle/throttle.go
pkg/internal/rate/rate.go
pkg/internal/rate/reset.go

Rebase of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2033
Fixes #

✨ Add fine-grained service rate limiters

---

Makefile

As we now pull from a GCR mirror, mirrors are not supported directly
when using experimental build features, so pre-pull images from mirror
first.
Fixes #

Ensure mirrored OCI images are pulled before building Dockerfile

---

Dockerfile
Makefile

Was able to reproduce the cloudbuild environment locally and cause it to fail in the same way by editing the docker daemon configuration. These fixes should let the build complete.
Fixes #

Fixups to Docker build

---

hack/tools/Makefile

Fixes cloudbuild and CI for release-staging where gcc isn't installed.
Fixes #

Disable cgo for building kustomize without gcc

---

pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/launchtemplate.go

(This applies to both `AWSMachinePools` and `AWSMachines`)
Allows specifying AMI lookup details when using AWSManagedControlPlane (EKS), allowing the use of custom AMIs with EKS.
The logic takes the following steps:
1. If AMI ID is provided, use that
2. Check if any of the image lookup values are provided on the AWSMachinePool or AWSMachine (if any of these are empty then the AWSManagedControlPlane is checked), if found use those to search for an AMI
4. Lookup the AWS-provided AMIs based on the Kubernetes version
Fixes #2056

✨ Support custom AMI lookup with EKS

---

test/e2e/data/e2e_eks_conf.yaml

Locally built e2e images need to be preloaded into kind.
Fixes #

:bug: Ensure EKS controllers are preloaded in e2e

---

Makefile
cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
test/e2e/data/e2e_conf.yaml
test/e2e/data/infrastructure-aws/cluster-template-machine-pool.yaml
test/e2e/data/infrastructure-aws/cluster-template-mhc.yaml
test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
test/e2e/suites/unmanaged/unmanaged_test.go

Adding CAPI tests except KCP adoption.
MachinePool test will be uncommented once https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2137 is done.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2132

🌱Add CAPI E2E tests

---

controllers/awsmachine_controller.go
controllers/awsmachine_controller_test.go

Refactors some of the controller code around secrets backend handling. Early returns when we're not using it allowing insecureSkipSecrets to function in its entirety.
Fixes #

controllers: Add conditionals around fetching secret backend service

---

versions.mk

See https://blog.rust-lang.org/2021/01/04/mdbook-security-advisory.html for more details.
Thanks!

Update mdbook to 0.4.5 to fix CVE-2020-26297

---

controllers/awscluster_controller.go
controllers/awsmachine_controller.go
test/e2e/data/e2e_conf.yaml

* Makes EventBridge soft-error instead of failing an AWSCluster reconciliation.
* Standardises error logging in the unmanaged controllers
* Disables EventBridge for e2e tests at present, until we have aws-janitor configured.
Fixes #

:bug: Make EventBridge non-critical to cluster reconciliation

---

docs/book/src/SUMMARY.md
docs/book/src/development/development.md

For EKS Control Plane development
Documentation
Fixes #
Can't find an issue

📖 Added how to develop locally using Tilt for EKS Control Plane

---

.github/PULL_REQUEST_TEMPLATE.md

Signed-off-by: Richard Case <198425+richardcase@users.noreply.github.com>
An update to the PR template that includes the `release-note` code block. This will enable us to provide richer release notes.  Additionally, a checklist has also been added that will help the PR authors and reviewers.
the `release-notes` plugin will be anbled enabled via: https://github.com/kubernetes/test-infra/pull/20642
Fixes #

feat: updated PR template to include the release notes sand checklist

---

pkg/cloud/services/ec2/instances.go
pkg/cloud/services/eks/cluster.go
pkg/cloud/services/eks/cluster_test.go

**What this PR does / why we need it:**
Add missing security groups into node launch template.
Fixes #1985 
I will send another PR to solve #2231. It needs some refactor in Launch template stuff to be reusable between AWSMachinePool  and  AWSManagedMachinePool

🐛 Fix bastion  and AWSMachinePool connectivity

---

api/v1alpha3/awsmachine_types.go
api/v1alpha3/awsmachine_webhook.go
api/v1alpha3/awsmachine_webhook_test.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
controllers/awsmachine_security_groups.go
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_test.go
pkg/cloud/services/interfaces.go
pkg/cloud/services/mock_services/ec2_machine_interface_mock.go

This PR adds filters support for additional security groups and this change should not break any existing functionality. The current implementation only allows IDs. 
Related issue https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1723
```release-note
AWSMachine: Add filters support for additional security groups
```

✨ Add filters support for additional security groups

---

config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
controlplane/eks/api/v1alpha3/types.go
exp/api/v1alpha3/awsmanagedmachinepool_types.go
exp/api/v1alpha3/awsmanagedmachinepool_webhook.go
pkg/cloud/services/eks/nodegroup.go
pkg/cloud/services/eks/securitygroup.go

Restricts access to SSH for `AWSManagedMachinePool`s to specific security groups by default. Until now the default matches the AWS API defaults where if SSH access is enabled with some SSH key then access is allowed from any IP. Now the user must set `public: true`.
Fixes #1990 
**Checklist**:
```release-note
action required: New `AWSManagedMachinePool` resources with non-empty `remoteAccess` now require `remoteAccess.public: true` in order to allow public access to SSH on port 22
```

🌱 AWSManagedMachinePool: Make public access to SSH explicit

---

docs/adr/0004-fargate-pools.md

Documents a major decision around EKS Fargate support, whether they map to a `MachinePool`.
Part of #1786 (https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1786#issuecomment-777599215)
**Checklist**:
```release-note
New ADR to document the decision of how Fargate Profiles will be represented.
```

📖 Add AWSFargatePool ADR

---

pkg/cloud/logs/logs.go
pkg/cloud/scope/clients.go
pkg/cloud/services/autoscaling/service.go
pkg/cloud/services/ec2/service.go
pkg/cloud/services/eks/service.go
pkg/cloud/services/elb/service.go
pkg/cloud/services/iamauth/service.go
pkg/cloud/services/network/service.go
pkg/cloud/services/secretsmanager/service.go
pkg/cloud/services/securitygroup/service.go
pkg/cloud/services/ssm/service.go

Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2181
```release-note
Adds the ability to enable the AWS SDK debug logging. Use verbosity level of 9 to enable debugging and a verbosity level of 10 to include HTTP request bodies.
```

✨  Add a log debug log configuration to the AWS clients

---

config/manager/manager.yaml
config/manager/manager_auth_proxy_patch.yaml
config/webhook/manager_webhook_patch.yaml

/kind bug
The feature flags/args in `manager.yaml` are being overwritten by the patch args. I'm not sure why it would be necessary to patch the `manager` in the `auth_proxy` patch.
**Checklist**:
```release-note
NONE
```

🐛 Fix manager arg inconsistencies

---

.github/PULL_REQUEST_TEMPLATE.md

**What type of change is this**:
/kind cleanup
With the adoption of the `release-notes` Prow plugin and using the `release-notes` cli we need to have kinds associated with the PRS
**Checklist**:
```release-note
The PR template has been updated to include specifying the kind
```

Updated the PR template to include kind assignment

---

hack/ensure-kind.sh

`ensure-kind.sh` should compare semantic versions correctly, instead of checking for the exact number.
Otherwise it could fail even when the local kind version is `v0.10.0`, which is obviously greater than the minimum version `v0.6.1`.
So let's follow mostly the way how other ensure scripts are implemented:
read the kind version, run version sort with the minimum version, and compare it to the minimum version.
**Release note:**
```
NONE
```

🐛 hack: fix semver comparison in ensure-kind

---

docs/book/src/topics/eks/index.md
templates/cluster-template-eks-managedmachinepool-vpccni.yaml
templates/cluster-template-eks-managedmachinepool.yaml
templates/cluster-template-eks.yaml
test/e2e/data/eks/cluster-template-eks-control-plane-only-withaddon.yaml
test/e2e/data/eks/cluster-template-eks-control-plane-only.yaml
test/e2e/data/eks/cluster-template-eks-managedmachinepool.yaml
test/e2e/suites/managed/README.md

/kind cleanup
This removes the usage of AWSManagedCluster from the templates and docs to help with the deprecation in v1alpha4
Fixes #
**Checklist**:
```release-note
Removal of AWSManagedCluster from templates/docs to help with the future deprecation in v1alpha4
```

chore: remove usage of AWSManagedCluster from templates / docs

---

cmd/clusterawsadm/api/bootstrap/v1alpha1/defaults.go
cmd/clusterawsadm/api/bootstrap/v1alpha1/types.go
cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_node.go
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
cmd/clusterawsadm/cloudformation/bootstrap/managed_control_plane.go

Govcloud support was broken for CloudFormation since only there was hardcoded references to the AWS partition. A new global `partition` filed is added for referencing AWS managed policies.
Fixes #
**Checklist**:
- [x ] squashed commits
```release-note
Restore GovCloud and other AWS partition support for CloudFormation generation. If using EKS, you must provide the relevant value for `partition` in your clusterawsadm configuration file.
```

Fix Govcloud support for CloudFormation generation

---

config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
exp/api/v1alpha3/awsmachinepool_types.go
exp/api/v1alpha3/types.go
exp/controllers/awsmachinepool_controller.go
go.sum
pkg/cloud/services/autoscaling/autoscalinggroup.go
pkg/cloud/services/autoscaling/autoscalinggroup_test.go

/kind feature
Adds the ability to enable the new ASG capacity rebalance feature.
This only makes sense when there are Spot instances in the ASG (i.e. when `.spec.mixedInstancesPolicy.instancesDistribution.onDemandPercentageAboveBaseCapacity < 100`) but AWS still allows to enable capacity rebalance even when spot percentage is 0%. Some validation could be added, but I think if the AWS API accepts it we should just set it.
The new `.spec.capacityRebalance` field defaults to `false` and is set as optional for backwards compatibility.
**Checklist**:
```release-note
Add ability to toggle the new AWS Capacity Rebalance feature by setting a new `.spec.capacityRebalance` …
```

✨ Implement ASG capacity rebalance

---

test/e2e/suites/unmanaged/unmanaged_test.go

e2e multicluster test were failing because we disabled event-bridge feature.
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e-v1alpha3/1367465445199712256
Fixes #
```release-note
NONE
```

Fix e2e multi cluster test

---

api/v1alpha3/awscluster_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml

/kind cleanup
Added enum check for loadbalancer scheme.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2155
-->
```release-note
Add validation for loadbalancer scheme to allow only Internet-facing and internal values. 
```

Add enum validation for loadbalancer scheme

---

controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_types.go
controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_webhook.go
controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_webhook_test.go
controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
docs/book/src/SUMMARY.md
docs/book/src/topics/eks/pod-networking.md
pkg/cloud/scope/managedcontrolplane.go
pkg/cloud/services/awsnode/cni.go
pkg/cloud/services/awsnode/service.go

/kind feature
A new property called **disableVPCCNI** has been introduced that can be used to ensure that the Amazon VPC CNI is deleted as part of the **AWSManageControlPlane** reconciliation. This is useful in scenarios where a different CNI is used.
Fixes #2287 
**Checklist**:
```release-note
Ability to declaratively remove the Amazon VPC CNI when using an alternate CNI
```

feat: ability to delete amazon vpc cni

---

bootstrap/eks/main.go
controlplane/eks/main.go
main.go

/kind cleanup
Doing the same change with CAPI: https://github.com/kubernetes-sigs/cluster-api/pull/4257
> Set the UserAgent to "capa-controller".
> This string is used to identify actors within a Kubernetes system; for instance it appears in managedFields.
-->
```release-note
NONE
```

Set the UserAgent to "capa-controller"

---

docs/book/src/SUMMARY.md

/kind bug
There was a broken link to the book from the summary to the EKS pod networking page
Fixes #2300 
**Checklist**:
```release-note
NONE
```

fix: broken link to pod networking

---

docs/book/src/topics/consuming-existing-aws-infrastructure.md

Clarifying the requirements for existing subnets.
* Line 59 seemed to be no longer true after https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1721, when I didn't specify the subnets I saw:
```
E0317 17:08:36.026968       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile network for AWSCluster default/dkoshkin-aws: no subnets specified, you must specify the subnets when using an umanaged vpc"
```
* The list of Prerequisites sounds like there is a hard requirement on having public subnets or access to the Internet. Changed the wording a bit to let others know that it is possible to create a managed cluster with only private subnets. …

docs: clarify subnet requirements for existing-aws-infrastructure

---

api/v1alpha3/awscluster_webhook.go
api/v1alpha3/awscluster_webhook_test.go
api/v1alpha3/awsmachine_webhook.go
api/v1alpha3/awsmachine_webhook_test.go
api/v1alpha3/validate.go
api/v1alpha3/webhooks.go

/kind bug
Makes the AWSCluster & AWSMachine validation webhooks accept an empty string for `SSHKeyName`. That value is supported by the API.
Fixes #2306 
- The webhook test files have slightly different sets of SSHKeyName validation tests. The SSHKeyName field is common to both AWSCluster and AWSMachine, so I think there should be one set of tests for the field. I can do this in a follow-up PR. WDYT?
- The first two commits add tests; they are expected to fail. The third commit adds the fix.
- 
**Checklist**: …

:bug: Accept empty string SSHKeyName in AWSCluster & AWSMachine validation webhooks

---

api/v1alpha3/awscluster_webhook.go
api/v1alpha3/awscluster_webhook_test.go
api/v1alpha3/awsmachine_webhook.go
api/v1alpha3/awsmachine_webhook_test.go
api/v1alpha3/sshkeyname_test.go
api/v1alpha3/validate.go

/kind cleanup
- There were two, partially overlapping, sets of SSHKeyName field validation tests. Now there is one common set.  (I asked if this change was wanted, and [got a +1](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2308#issuecomment-803022348).)
- Validates SSHKeyName using the same convention (a receiver) used to validate other fields.
**Checklist**:
```release-note
NONE
```

refactor: Group SSH Key Name validation tests together

---

Makefile
hack/tools/Makefile
hack/tools/go.sum
scripts/ci-apidiff.sh
test/e2e/suites/unmanaged/unmanaged_CAPI_test.go

This PR adds apidiff script which is added to a job here: https://github.com/kubernetes/test-infra/pull/21451
Also adds PR-blocking tag to the CAPI's quick start test, it is added as PR-blocking presubmit job (https://github.com/kubernetes/test-infra/pull/21451)
**Checklist**:
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2130
```release-note
NONE
```

Add Apidiff script

---

cmd/clusterawsadm/cmd/ami/ami.go
cmd/clusterawsadm/cmd/ami/list/helper.go
cmd/clusterawsadm/cmd/ami/list/list.go
cmd/clusterawsadm/printers/printers.go
pkg/cloud/services/ec2/ami.go
pkg/cloud/services/ec2/instances_test.go

/kind feature
This PR adds a list command to clusterawsadm to list AMIs based on OS, region, and Kubernetes version.
`clusterawsadm ami list --kubernetes-version=v1.18.12 --os=ubuntu-20.04  --region=us-west-2
`
If none of the flags are used (`clusterawsadm ami list`), lists AMIs in all supported regions, OSes, and supported Kubernetes versions (N-2).
Example output:
```
$ clusterawsadm ami list --kubernetes-version=v1.19.3 -o json
{
"AMIs": [
{
"os": "centos-7",
"region": "ap-northeast-1",
"amiID": "ami-08cc1e47b38d69085",
"creationDate": "2020-11-14T21:33:51.000Z",
"kubernetesVersion": "v1.19.3",
"name": "capa-ami-centos-7-1.19.3-00-1605388645"
},
{
"os": "ubuntu-18.04",
"region": "ap-northeast-1",
"amiID": "ami-006d394ac4256d33f",
"creationDate": …
```

Add list AMIs command to clusterawsadm

---

api/v1alpha3/validate.go

There is no `sshKey` field.
/kind bug
/kind api-change
The current error refers to the `sshKey` field, which does not exist:
```
Error from server (AWSCluster.infrastructure.cluster.x-k8s.io "test" is invalid: sshKey: Invalid value: ...
```
This PR corrects the field name in the error:
```
Error from server (AWSCluster.infrastructure.cluster.x-k8s.io "test" is invalid: sshKeyName: Invalid value: ...
```
Fixes #
If the error string is considered part of the API, then this PR changes the API.
**Checklist**: …

:bug: Refer to `sshKeyName` field in error

---

Makefile
scripts/ci-test-coverage.sh

This PR adds test coverage script which will be called periodically by test-infra.
https://github.com/kubernetes/test-infra/pull/21801
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2144
**Checklist**:
```release-note
Add test coverage to test grid.
```

Test coverage

---

docs/book/src/SUMMARY_PREFIX.md
docs/book/src/topics/multitenancy.md
docs/proposal/20200506-single-controller-multitenancy.md

This PR adds multitenancy documentation to the book.
**Checklist**:
```release-note
NONE
```

[docs] Add multitenancy documentation

---

go.sum
hack/tools/go.sum
pkg/cloud/services/ec2/launchtemplate.go

/kind bug
When specifying an empty string for SSH key pair for a MachinePool, the following error is returned:
```
controllers/AWSMachinePool "msg"="unable to create AutoScalingGroup" "error"="failed to create autoscaling group: ValidationError: You must use a valid fully-formed launch template. Invalid value '' for keyPairNames. It should not be blank\n\tstatus code: 400
```
This PR fixes that by setting the SSH key name in the AWS launch template to nil pointer if an
explicit empty string is specified (semantic meaning of use no key as documented in code). …

fix: Properly handle empty string SSH key name in ASG launch template creation

---

docs/book/src/topics/machinepools.md
docs/book/src/topics/multitenancy.md
netlify.toml

/kind cleanup
Renames references to the default branch to main.
Part of #1782 
Corresponding test-infra PR kubernetes/test-infra#21832
**Checklist**:
```release-note
NONE
```
/hold
Cannot be merged before the branch is actually renamed.

Rename references to the default branch to main

---

config/rbac/role.yaml
controllers/awsmachine_controller.go
controlplane/eks/config/rbac/role.yaml
controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
docs/book/src/topics/multitenancy.md
exp/controllers/awsmachinepool_controller.go

eks controller requires namespace access to support StaticIdentities
defined in other namespaces
Fixes issue #2372
Signed-off-by: paulcarlton-ww <paul.carlton@weave.works>
/kind bug
Update rbac rules for for controller to allow access to namespaces so it can process identities in other namespaces.
Also add note to documentation about adding controller namespace to allowed namespaces
Fixes #2372
```release-note
Fix RBAC permission and update documentation for multi-tenancy
```

bug: add namespace access to eks-contoller rules

---

docs/book/src/topics/multitenancy.md

Fixes issue #2364
Signed-off-by: paulcarlton-ww <paul.carlton@weave.works>
/Fixes #2364
```release-note
Fix typo in documentation
```

book: fix typo identityidentity to staticidentity

---

controllers/suite_test.go
exp/controlleridentitycreator/suite_test.go
exp/controllers/suite_test.go

Prior to this change, TestMain deferred the `teardown` call. After running the tests, it called `os.Exit`, which exits immediately, ignoring any deferred functions. Therefore `teardown` was not called, and left testenv kube-apiserver and etcd processes running.
Demo of:
- old behavior: https://play.golang.org/p/LKynhlOi8K1
- new behavior: https://play.golang.org/p/Efu0Q-rQxvI
/kind cleanup
Make sure controller tests clean up after themselves.
```release-note
NONE
```

test: Ensure teardown runs

---

controlplane/eks/config/rbac/role.yaml
controlplane/eks/controllers/awsmanagedcontrolplane_controller.go

/kind bug
When using standard setup via `clusterctl init`
```
E0419 12:39:55.208006       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.9/tools/cache/reflector.go:105: Failed to list *v1alpha3.AWSClusterControllerIdentity: awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io is forbidden: User "system:serviceaccount:capa-eks-control-plane-system:capa-eks-control-plane-controller-manager" cannot list resource "awsclustercontrolleridentities" in API group "infrastructure.cluster.x-k8s.io" at the cluster scope
```
Meaning new `awsclustercontrolleridentities` is not in the ClusterRole RBAC
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close …

Issue 2358: Add required clustercontrolleridentities to eks rbac

---

pkg/cloud/services/ec2/launchtemplate.go

Cherry pick of #2362 on release-0.6.
#2362: fix: Properly handle empty string SSH key name in ASG

Automated cherry pick of #2362: fix: Properly handle empty string SSH key name in ASG

---

exp/controllers/awsmachinepool_controller.go
exp/controllers/awsmachinepool_controller_test.go
pkg/cloud/services/ec2/launchtemplate.go
pkg/cloud/services/ec2/launchtemplate_test.go
pkg/cloud/services/interfaces.go
pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
pkg/cloud/services/userdata/utils.go

**TODO:**
/kind bug
Previously, when the AWSMachinePool controller scaled an AutoScaling Group, and the configuration was the same, apart from the userdata, it would not update the Launch Template. The existing userdata would contain an expired bootstrap token, and new instances could not join the cluster.
Fixes #2321
**Checklist**:
```release-note
Fix: When the AWSMachinePool controller scales an AutoScaling Group, it updates the Launch Template with a valid bootstrap token.
```

:bug: AWSMachinePool: When userdata changes, create new LaunchTemplate version, but don't start Instance Refresh

---

exp/controllers/awsmachinepool_controller.go
pkg/cloud/scope/machinepool.go
pkg/cloud/services/ec2/launchtemplate.go
pkg/cloud/services/ec2/launchtemplate_test.go
pkg/cloud/services/interfaces.go
pkg/cloud/services/mock_services/ec2_machine_interface_mock.go

/kind bug
During AWSMachinePool reconcile we use LaunchTemplateID in the status to get launch template but we can get it by just name. Since status fields are not reliable (e.g., during `clusterctl move` the LaunchTemplateID gets wiped off, which results in error in this [issue](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2393).)
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2393
**Checklist**:
```release-note
Fix for reconciling LaunchTemplates after `clusterctl …
```

Get LaunchTemplates by name

---

api/v1alpha3/webhook_suite_test.go
api/v1alpha3/webhook_test.go
bootstrap/eks/api/v1alpha3/webhook_suite_test.go
bootstrap/eks/api/v1alpha3/webhook_test.go
bootstrap/eks/api/v1alpha4/eksconfig_webhook.go
bootstrap/eks/api/v1alpha4/eksconfigtemplate_webhook.go
bootstrap/eks/api/v1alpha4/zz_generated.deepcopy.go
bootstrap/eks/config/webhook/manifests.yaml
config/webhook/manifests.yaml
controlplane/eks/api/v1alpha3/webhook_suite_test.go
controlplane/eks/api/v1alpha3/webhook_test.go
controlplane/eks/main.go
exp/api/v1alpha3/webhook_suite_test.go
exp/api/v1alpha3/webhook_test.go
exp/api/v1alpha4/awsmanagecluster_webhook.go
test/helpers/envtest.go

This PR adds unit tests to make sure conversion webhooks are working correctly.
Similar to cluster-api PR: https://github.com/kubernetes-sigs/cluster-api/pull/4417
Fixes #
**Checklist**:
```release-note
NONE
```

Add v1alpha3 to v1alpha4 conversion unit tests

---

Makefile
go.mod
go.sum
test/e2e/data/e2e_conf.yaml
test/e2e/data/infrastructure-aws/cluster-template-nested-multitenancy.yaml
test/e2e/data/infrastructure-aws/cluster-template-simple-multitenancy.yaml
test/e2e/shared/aws.go
test/e2e/shared/common.go
test/e2e/shared/context.go
test/e2e/shared/defaults.go
test/e2e/shared/resource.go
test/e2e/shared/suite.go
test/e2e/shared/template.go
test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
test/e2e/suites/unmanaged/unmanaged_test.go

This PR allows to run e2e test in parallel: 
- Collects service quotas in the account: Internet gateway, NAT gateway, EC2, Classic LB, VPC, elastic IP
- Writes the quotas on a file
- Defines how much resources each test requires
- Each time a ginkgo node picks up a test, first checks if there are enough resources, if not waits; if there is, reduce the resource by the amount that test needs. 
- At the end of the test, release the resources by increasing the values at the doc.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2131 …

Add e2e parallelization

---

exp/controllers/awsmachinepool_controller.go
exp/controllers/awsmachinepool_controller_test.go
go.sum
hack/tools/go.sum
pkg/cloud/services/ec2/launchtemplate.go
pkg/cloud/services/ec2/launchtemplate_test.go
pkg/cloud/services/interfaces.go
pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
pkg/cloud/services/userdata/utils.go

/kind backport
/kind bug
Backports #2354
Previously, when the AWSMachinePool controller scaled an AutoScaling Group, and the configuration was the same, apart from the userdata, it would not update the Launch Template. The existing userdata would contain an expired bootstrap token, and new instances could not join the cluster.
Fixes #2321
**Checklist**:
```release-note
Fix: When the AWSMachinePool controller scales an AutoScaling Group, it updates the Launch Template with a valid bootstrap token.
```

:bug: AWSMachinePool: When userdata changes, create new LaunchTemplate version, but don't start Instance Refresh - backport to release-0.6

---

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
test/e2e/data/e2e_eks_conf.yaml

/kind bug
There is a missing permission for keypairs that stops the managed machine pool reconciling.
Fixes #2389 
**Checklist**:
```release-note
Controllers policy updated with missing key pairs permission, if you are using or plan to use AWSManagedMachinePool with an SSH key then you will need to update your controllers policy by running `clusterawsadm bootstrap iam create-cloudformation-stack` again. 
```

fix: missing iam permission for key pairs

---

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
test/e2e/data/e2e_eks_conf.yaml

/kind bug
There is a missing permission for keypairs that stops the managed machine pool reconciling.
Relates to #2389 
This is a cherry-pick to backport  #2404 to 0.6
**Checklist**:
```release-note
Controllers policy updated with missing key pairs permission, if you are using or plan to use AWSManagedMachinePool with an SSH key then you will need to update your controllers policy by running `clusterawsadm bootstrap iam create-cloudformation-stack` …
```

fix: missing iam permission for key pairs (backport)

---

pkg/cloud/services/eks/nodegroup.go

/kind bug
If a user edits the min/max size of a EKS node pool manually in the AWS console the controller will make sure that this is changed back to match the min/max size defined in AWSManagedMachinePool
Relates To #2318 
This is a cherry-pick to backport #2375 to 0.6
**Checklist**:
```release-note
EKS Nodepool min/max will be updated to match the AWSManagedMachinePool spec, overriding changes to min/max made via the AWS Console, CLI, or SDK.
```

fix: managed machine pool correct min/max size (backport)

---

pkg/cloud/awserrors/errors.go
pkg/cloud/services/ec2/launchtemplate_test.go

This function will return a `400` with an error like `InvalidLaunchTemplateName.NotFoundException: The specified launch template, with template name foo, does not exist.`
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/7eb58f53f56a96a13dc42f3df91f6903e6efe256/pkg/cloud/services/ec2/launchtemplate.go#L77
Added a new `LaunchTemplateNameNotFound` in the `IsInvalidNotFoundError()` function and updated the unit tests to reflect what the AWS API returns.
Fixes #2402
Also tested with a dev image …

fix: handle LaunchTemplateNameNotFound error

---

go.mod
go.sum

There is a bug fix in this version regarding conversion webhooks: https://github.com/kubernetes-sigs/cluster-api/pull/4638
```release-note
NONE
```

Update controller runtime to v0.9.0-beta.5

---

Makefile
docs/book/src/development/releasing.md
hack/tools/Makefile

`make release` was failing due to these minor errors. Just fixing v0.6 release for now until we do a v0.7 release and see if these issues exist there as well.
```release-note
NONE
```

Minor Makefile release fixes

---

api/v1alpha4/awscluster_webhook.go
api/v1alpha4/awscluster_webhook_test.go
api/v1alpha4/suite_test.go
controllers/awscluster_controller.go
pkg/cloud/scope/machine.go
pkg/cloud/services/ec2/instances.go

/kind feature
Add externally managed predicate. Clusters marked with `"cluster.x-k8s.io/managed-by"` annotation should be skipped from reconciliation.
https://github.com/kubernetes-sigs/cluster-api/pull/4135
https://github.com/kubernetes-sigs/cluster-api/pull/4135
Fixes #
**Checklist**:
```release-note
Add externally managed predicate. Clusters marked with `"cluster.x-k8s.io/managed-by"` annotation should be skipped from reconciliation.
```

Add externally managed predicate

---

main.go

After https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2121 webhooks are enable by default.
**Checklist**:
```release-note
Corrects wording on webhook server flag
```

Reword wrong webhook usage

---

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
cmd/clusterawsadm/cloudformation/bootstrap/template.go
cmd/clusterawsadm/cloudformation/bootstrap/template_test.go

/kind bug
This PR fixes the bug causing `extraStatements` section to be ignored for `clusterAPIControllers` when creating IAM role.
Fixes #2387
**Checklist**:
```release-note
Process extra statements for Cluster API Controllers
```

fix: Process extra statements for Cluster API Controllers

---

cmd/clusterawsadm/cmd/controller/controller.go
cmd/clusterawsadm/cmd/controller/credentials/common.go
cmd/clusterawsadm/cmd/controller/credentials/print.go
cmd/clusterawsadm/cmd/controller/credentials/update_credentials.go
cmd/clusterawsadm/cmd/controller/credentials/zero_credentials.go
cmd/clusterawsadm/cmd/controller/rollout/common.go
cmd/clusterawsadm/cmd/controller/rollout/rollout.go
cmd/clusterawsadm/cmd/root.go
cmd/clusterawsadm/cmd/util/util.go
cmd/clusterawsadm/controller/credentials/update_credentials.go
cmd/clusterawsadm/controller/credentials/zero_credentials.go
cmd/clusterawsadm/controller/helper.go
cmd/clusterawsadm/controller/rollout/rollout.go
cmd/clusterawsadm/credentials/credentials.go

Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2434
**Checklist**:
```release-note
Add controller related commands to clusterawsadm: zero/update/print bootstrap credentials and rollout controllers
```
/kind feature

Add new controller commands to clusterawsadm related to updating bootstrap credentials

---

api/v1alpha4/awsclustercontrolleridentity_webhook.go
api/v1alpha4/awsclustercontrolleridentity_webhook_test.go
api/v1alpha4/awsclusterroleidentity_webhook.go
api/v1alpha4/awsclusterstaticidentity_webhook.go
api/v1alpha4/awsclusterstaticidentity_webhook_test.go
api/v1alpha4/suite_test.go
config/webhook/manifests.yaml
main.go

This PR improves webhook validation checks for v1alpha4 types.
Fixes #2391
**Checklist**:
```release-note
* Validate label selector for AWS Identity CRDs
* Add AWSClusterStaticIdentity webhook with validation checks
```

Adding v1alpha4 webhook validation checks

---

config/webhook/manifests.yaml
exp/api/v1alpha4/awsfargateprofile_webhook.go

/kind cleanup
This typo cause the validate webhook of awsfargateprofile not called. 
Fixes #
**Checklist**:
```release-note
Fix typo in AWSFargateProfile validation webhook which cause the webhook not called.
```

fix typo in awsfargateprofile webhook

---

config/webhook/manifests.yaml
exp/api/v1alpha3/awsfargateprofile_webhook.go

backport awsfargateprofile validate webhook typo fix to release-0.6. 
Fixes #
**Checklist**:
Fix typo in AWSFargateProfile validation webhook which cause the webhook not called.
```release-note
Fix typo in AWSFargateProfile validation webhook which cause the webhook not called.
```

backport awsfargateprofile validate webhook typo fix to release-0.6

---

pkg/cloud/services/elb/loadbalancer.go
pkg/cloud/services/elb/loadbalancer_test.go

/kind bug 
This allows users with more than 20 LoadBalancers in their account to delete them in an airgapped environment 
Fixes #2497
**Checklist**:
```release-note
bug: fixes bug in elb.DescribeTags when the user has more than 20 load balancers in an account
```

fix: break down DescribeTags requests by 20 LoadBalancers at a time

---

pkg/cloud/services/elb/loadbalancer.go
pkg/cloud/services/elb/loadbalancer_test.go

/kind bug
Fixes #2497 backport 
**Checklist**:
```release-note
Fix for ELB deletion when there are more than 20 ELBs.
```

[backport] fix: break down DescribeTags requests by 20 LoadBalancers at a time

---

test/e2e/data/e2e_conf.yaml
test/e2e/data/e2e_eks_conf.yaml
test/e2e/data/eks/cluster-template-eks-control-plane-only-withaddon.yaml
test/e2e/data/eks/cluster-template-eks-control-plane-only.yaml
test/e2e/shared/common.go
test/e2e/shared/identity.go
test/e2e/shared/suite.go
test/e2e/suites/managed/eks_test.go

The EKS e2e tests are timing out and are getting stuck in the `WaitForClusterDeleted` in the test cleanup. Removed the EKS cluster deletion from the test and now relying on the Cluster deletion and the ownership chain.
Also,  changed templates used by the tests to use AWSClusterStaticIdentity
and added shared functions to create an instance of this CR and also the
associated secrets
Fixes #
**Checklist**:
```release-note
NONE
```

chore: rely on cluster deletion in eks e2e tests

---

cmd/clusterawsadm/cmd/resource/list/list.go
cmd/clusterawsadm/cmd/resource/resource.go
cmd/clusterawsadm/cmd/root.go
cmd/clusterawsadm/resource/list.go
cmd/clusterawsadm/resource/type.go

Usage:
clusterawsadm resource list [flags]
Eg: `clusterawsadm resource list --cluster-name=<cluster name> --region=<region>`
Output options: table(default), yaml, json
```
PARTITION   SERVICE                REGION       ACCOUNTID      RESOURCE                                 ARN
aws         ec2                    ap-south-1   832764931379   elastic-ip/eipalloc-0a4ef32fcffceaaf2    arn:aws:ec2:ap-south-1:832764931379:elastic-ip/eipalloc-0a4ef32fcffceaaf2
aws         ec2                    ap-south-1   832764931379   elastic-ip/eipalloc-04f393e86fd018583    arn:aws:ec2:ap-south-1:832764931379:elastic-ip/eipalloc-04f393e86fd018583
aws         ec2                    ap-south-1   832764931379   elastic-ip/eipalloc-0ef70b86d684b10a0 …
```

CLI command added to list aws resources created by CAPA

---

cmd/clusterawsadm/api/bootstrap/v1alpha1/defaults.go
cmd/clusterawsadm/api/bootstrap/v1alpha1/types.go
cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
cmd/clusterawsadm/cloudformation/bootstrap/template_test.go
docs/book/src/SUMMARY_PREFIX.md
docs/book/src/topics/eks/encryption.md
docs/book/src/topics/eks/index.md

/kind bug
If you are using encryption with EKS there are missing permission on the controllers policy to allow using the specified KMS key.
Added missing IAM permission required to use EKS encryption. The permissions are scoped to KMS keys that have an alias name with a prefix of cluster-api-provider-aws-*.
The prefix is configurable via clusterawsadm config file.
This is a backport of #2447 
Relates #2432 
**Checklist**:
```release-note …
```

fix: added missing kms permissions required for EKS encryption (backport)

---

cmd/clusterawsadm/api/bootstrap/v1alpha1/defaults.go
cmd/clusterawsadm/api/bootstrap/v1alpha1/types.go
cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
cmd/clusterawsadm/cloudformation/bootstrap/template_test.go
docs/book/src/SUMMARY_PREFIX.md
docs/book/src/topics/eks/encryption.md
docs/book/src/topics/eks/index.md

/kind bug
If you are using encryption with EKS there are missing permission on the controllers policy to allow using the specified KMS key.
Added missing IAM permission required to use EKS encryption. The permissions are scoped to KMS keys that have an alias name with a prefix of cluster-api-provider-aws-*.
The prefix is configurable via clusterawsadm config file.
Fixes #2432 
**Checklist**:
```release-note
Controllers policy updated with missing …
```

fix: added missing kms permissions required for EKS encryption

---

api/v1alpha3/awscluster_types.go
api/v1alpha4/awscluster_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml

/kind bug
We identified kubebuilder print column is still pointing to the old status field which was merged in PR https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1372. By changing `Status.APIEndpoints` to `Spec.ControlPlaneEndpoint` it should empty column in `kubectl get awscluster` for endpoints.
Fixes #
**Checklist**:
```release-note
Correct field being used for endpoint column on `kubectl get AWSCluster`
```

fix kubebuilder pointing to changed api-endpoint

---

exp/controllers/awsmachinepool_controller.go
pkg/cloud/services/ec2/launchtemplate.go
pkg/cloud/services/interfaces.go
pkg/cloud/services/mock_services/ec2_machine_interface_mock.go

/kind bug
Remove one old version before creating a new version.
Fixes #2368
I'm not sure what sort of unit test we want to see.
**Checklist**:
```release-note
AWSMachinePool controller removes one old LaunchTemplate version before creating a new version, preventing the number of versions from growing without bound, and reaching the maximum limit. 
```

:bug: AWSMachinePool: Prune old Launch Template versions

---

exp/controllers/awsmachinepool_controller.go
pkg/cloud/services/ec2/launchtemplate.go
pkg/cloud/services/interfaces.go
pkg/cloud/services/mock_services/ec2_machine_interface_mock.go

Remove one old version before creating a new version.
/kind bug
Backport of #2525. Remove one old version before creating a new version.
Fixes #2368
**Checklist**:
```release-note
AWSMachinePool controller removes one old LaunchTemplate version before creating a new version, preventing the number of versions from growing without bound, and reaching the maximum limit. 
```

[backport] :bug: AWSMachinePool: Prune old Launch Template versions

---

api/v1alpha4/awsclustercontrolleridentity_webhook.go
api/v1alpha4/awsclustercontrolleridentity_webhook_test.go
api/v1alpha4/awsclusterroleidentity_webhook.go
api/v1alpha4/awsclusterroleidentity_webhook_test.go
api/v1alpha4/awsclusterstaticidentity_webhook.go
api/v1alpha4/awsclusterstaticidentity_webhook_test.go
api/v1alpha4/defaults.go

/kind feature
Add `clusterctl.cluster.x-k8s.io/move-hierarchy` label to global identity resources like AWSClusterControllerIdentity, AWSClusterRoleIdentity, AWSClusterStaticIdentity.
Fixes #2415 
**Checklist**:
```release-note
Apply clusterctl.cluster.x-k8s.io/move-hierarchy label on the infrastructure cluster global identity CRDs. 
```

Added clusterctl move label to global identity resources

---

api/v1alpha4/awscluster_webhook.go
api/v1alpha4/awscluster_webhook_test.go
api/v1alpha4/types.go

When controlPlaneEndpoint is not set, it is defaulted to `Internet-facing` and validation webhook does not allow setting it to `Internet-facing` due to immutability. For better UX, this PR allows user to set the ELB scheme to the defaulted value when initially `scheme` is left empty. 
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2534
**Checklist**:
```release-note
NONE
```

Allow setting ELB scheme when previously not set

---

test/e2e/data/cni/calico.yaml
test/e2e/data/e2e_conf.yaml

Calico v3.13 was using apiextensions.k8s.io/v1beta1 and this makes v1.22 clusters to fail conformance tests
[The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition will no longer be served in v1.22.](https://kubernetes.io/docs/reference/using-api/deprecation-guide/)
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2419
```release-note
NONE
```

Update Calico version to 3.19

---

Makefile
go.mod
go.sum
test/e2e/data/e2e_conf.yaml
test/e2e/data/e2e_eks_conf.yaml
test/e2e/shared/resource.go

- Upgrades CAPI to v0.4.0 release
- Fixes an issue with coverage tests
```release-note
NONE
```

Upgrade to CAPI v0.4.0
